### ISSUE TITLE
Call to undefined function yajra\Pdo\oci_connect() 

### ISSUE THREAD

**Issue by jamieshepherd** [yajra/laravel-oci8#1]
Installed exactly as README recommends, received FatalErrorException (as follows):

Symfony \ Component \ Debug \ Exception \ FatalErrorException

Call to undefined function yajra\Pdo\oci_connect()

nginx/php5.5/oracle

**Comment by ali2535** [comment]
i have a problem , 
i dont know that the problem where is. 
 
FatalThrowableError in Oci8.php line 455:
Call to undefined function Yajra\Pdo\oci_connect()

this is additional information:

in Oci8.php line 455
at Oci8->connect('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.50.10)(PORT = 1521)) (CONNECT_DATA =(SERVICE_NAME = mipg)))', 'haft', 'haft', array(2, 2, 0, 'charset' => 'AL32UTF8'), 'AL32UTF8') in Oci8.php line 78

**Comment by mstaack** [comment]
@ali2535 it looks like your oci8 extension is still not loaded.
please check `php -m | grep oci8` this should show oci8  did you install oci8? it must be activated in php.ini for cli and! apache/nginx

**Comment by ali2535** [comment]
@mstaack :+1: 
thanks for your answer my friend . what is grep in windows? 
i install wampserver 3 and php7 . in remove ; from first of oci8_12c
why you say not loading?

**Comment by ali2535** [comment]
when i run this command no return anything. this is ok??

![capture](https://cloud.githubusercontent.com/assets/17930523/23153207/65a41034-f81c-11e6-85b9-87a6676c3e05.PNG)

**Comment by ali2535** [comment]
Where is problem in this connection string ? 

at Oci8->connect('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.50.10)(PORT = 1521)) (CONNECT_DATA =(SERVICE_NAME = haft)))', 'HAFT', 'HAFT', array(2, 2, 0, 'charset' => ''), '') in Oci8.php line 78

**Comment by yajra** [comment]
@ali2535 grep is a bash command so I think it will not work on windows. Just make sure that the proper `oci8*.dll` extension is enabled on your php.ini.

**Comment by ali2535** [comment]
@yajra : Thanks Yajra . 
i install oracle client 11g . and my db is oracle 11g.
and in php.ini file  extension=php_oci8_12c.dll
Not Problem?

**Comment by ali2535** [comment]
i write this code in controller

$d = DB::select('SELECT * FROM GIFT_INFO');
var_dump($d);

return this error : 
FatalThrowableError in Oci8.php line 455:
Call to undefined function Yajra\Pdo\oci_connect()

-------
i write this code : 
$c = oci_connect('haft', 'haft' , '192.168.50.12/MYDB');
		if($c){
			die('yes');
		}else{
			die('no');
		}


return this error:

FatalThrowableError in UserController.php line 72:
Call to undefined function App\Http\Controllers\oci_connect()

**Comment by mstaack** [comment]
@ali2535 sure thing.. have a look here: https://yajrabox.com/docs/laravel-oci8/master/oracle-eloquent

**Comment by ali2535** [comment]
@mstaack : Thank you so much

a question :  protected $binaries = ['content']  IS  protected $fillable = ['content'] ???????

**Comment by yajra** [comment]
@ali2535 you are only required to use `OracleEloquent` in cases where you have a `blob|binary` fields. If not, you can use the regular Eloquent/Model and should work like how MySQL does it.

`$binaries` is not `$fillable`. Binaries should be set to help us identify which columns are `blob|binary`.

**Comment by sonu1** [comment]
Hi,   How do we use service name instead of SID to connect to oracle database hosted on other server. Thanks. 
![image](https://user-images.githubusercontent.com/9291373/27113046-b53a6454-510e-11e7-9a5d-6ebfc7e351bc.png)

**Comment by mstaack** [comment]
@sonu1 use something like this in your config
```
            'driver'        => 'oracle',
            'tns'           => env('DATABASE_TNSNAME', 'oracle'),
            'service_name'  => env('DB_SERVICE_NAME', 'service-name'),
            'host'          => env('DB_HOST', '8.8.8.8'),
            'port'          => env('DB_PORT', '1521'),
            'username'      => env('DATABASE_USER', ''),
            'password'      => env('DATABASE_PASSWORD', ''),
            'database'      => env('DB_DATABASE', ''),
            'charset'       => env('DB_CHARSET', 'AL32UTF8'),
            'prefix'        => env('DB_PREFIX', ''),
            'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
            'options'       => [
                PDO::ATTR_PERSISTENT => true
            ],
```

**Comment by lytab** [comment]
FatalThrowableError in Oci8.php line 455:
Call to undefined function Yajra\Pdo\oci_connect()

**Comment by lytab** [comment]
help me

**Comment by mstaack** [comment]
@lytab look here https://github.com/yajra/laravel-oci8/issues/360
