### ISSUE TITLE
ErrorException in Oci8.php line 81: Laravel 5.1

### ISSUE THREAD

**Issue by dukejib** [yajra/laravel-oci8#100]
Getting this problem with my fresh Oracle Setup.

oci_connect(): OCIEnvNlsCreate() failed. There is something wrong with your system - please check that ORACLE_HOME and LD_LIBRARY_PATH are set and point to the right directories

ORACLE_HOME = /u01/app/oracle/product/11.2.0/xe
LD_LIBRARY_PATH = /home/duke/Apps/instantclient_12_1/

Webclient, sqladministrator & sqlplus works fine. Only route from laravel is creating issues.
I am on Ubuntu 15.10 x64

**Comment by yajra** [comment]
Are you using homestead? Maybe try my oracle version of it. https://github.com/yajra/homestead-oracle.

On the other hand, this is indeed a configuration/environment issue. Below is a script I created on my homestead oracle to fix the environments. Try to use some part of the script on your server.

```sh
if php -m | grep oci8; then
	echo 'oracle extension already installed!'
else
	echo autodetect | pecl install oci8
	echo 'extension=oci8.so' >> /etc/php5/fpm/php.ini
	echo 'extension=oci8.so' >> /etc/php5/cli/php.ini
fi

if cat /etc/php5/fpm/php-fpm.conf | grep ORACLE_HOME; then
	echo 'php-fpm oracle env path already set!'
else
	echo "env[ORACLE_HOME] = '/u01/app/oracle/product/11.2.0/xe'" >> /etc/php5/fpm/php-fpm.conf
	echo "env[LD_LIBRARY_PATH] = '/u01/app/oracle/product/11.2.0/xe/lib'" >> /etc/php5/fpm/php-fpm.conf
fi

if cat /home/vagrant/.bashrc | grep ORACLE_HOME; then
	echo 'oracle env path already set!'
else
	# fix Oracle ENV for root user - Needed for supervisord
	echo -e '\n#SET ORACLE ENV PATH' >> /home/vagrant/.bashrc
	echo 'ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe' >> /home/vagrant/.bashrc
	echo 'LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib' >> /home/vagrant/.bashrc
fi
```

**Comment by dukejib** [comment]
Thanks for the reply. 
I am not using homestead. i 've simple lamp setup like every other ubuntu.

both ORACLE_HOME & LD_LIBRARY_PATH are set in bash.bashrc, apache2.conf and are visible in php. (phpinfo()).

Only problem comes when i try to use it with laravel-oci8. it raises errors.

**Comment by dukejib** [comment]
Ok. I've managed to solve the problem.
It happens , if you utilize zip files of oracle instantclient (if you aren't using rpm's).
It's better to use PECl to install oci8. Rest always creates mess with systems.

Sorry for bothering for a problem, which wasn't related to Laravel-Oci8.
