### ISSUE TITLE
ORA-01722: invalid number

### ISSUE THREAD

**Issue by c0debreak** [yajra/laravel-oci8#103]
I get the error message "ORA-01722: invalid number" when insert data into the database,
I have a model with the name "Application", in my model, i custom column "FLD01" as the primary key and data type is varchar2.

this is the code in my controller :

$ data = ['FLD01' => 'app01'];
Application :: create ($ data);

and then I get an error:

Error Message: ORA-01722: invalid number
Position: 65
Statement: insert into GMS04001_0001 (FLD01) values (: autoparam0) returning FLD01 into: autoparam1
Bindings: []

anyone can help?

**Comment by yajra** [comment]
Since you are using a varchar primary key then you need to disable incrementing. On your model, set the property `public $incrementing = false;`

**Comment by c0debreak** [comment]
Thanks yajra :) now it's work fine for me

**Comment by yajra** [comment]
Welcome... Glad it worked! ^_^
