### ISSUE TITLE
ORA-01 861: literal does not match format string (when insert date format)

### ISSUE THREAD

**Issue by c0debreak** [yajra/laravel-oci8#104]
I get the error message "ORA-01 861: literal does not match format string" when insert date format,

This is my controller code:

$ data = ['FLD01' => $ request-> input ('code'), 'FLD02' => date ('Ym-d')];
DB :: setDateFormat ('DD-MON-YYYY');
Application :: create ($ data);

anyone can help?

**Comment by yajra** [comment]
`date ('Ym-d')`? Just use `Carbon::now()` and then `Application::create($data)`. No need to set the date format.

**Comment by c0debreak** [comment]
Thanks yajra, fixed,
Yajra, how to set table name dynamically on model?

**Comment by yajra** [comment]
"how to set table name dynamically on model?" Not sure on this one. Better ask on Laracasts or some forums.
