### ISSUE TITLE
Attributes (columns) returns lowercase

### ISSUE THREAD

**Issue by laurenceHR** [yajra/laravel-oci8#105]
The rows returned by the query has the attributes (columns) as lowercase, but in oracle is in uppercase, I need those on uppercase... what have I do?

**Comment by yajra** [comment]
Set the PDO option to return UPPER CASE via config file. See this example config as ref:
```php
'oracle'     => [
            'driver'   => 'oracle',
            'host'     => env('DB_HOST', 'localhost'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'port'     => env('DB_PORT', 1521),
            'prefix'   => env('DB_PREFIX', ''),
            'options' => [
                PDO::ATTR_CASE => PDO::CASE_UPPER,
            ]
        ],
```

However, please **NOTE** that the package is not fully tested when using upper case attributes.

**Comment by laurenceHR** [comment]
thanks a lot!!
I need uppercase, because my (frist) dev database was mysql and now I'm migrating to oracle

**Comment by egisberto** [comment]
Thanks mister @yajra !!! Works great.

**Comment by krytthew** [comment]
Thanks bro, you saved me
