### ISSUE TITLE
dropAutoIncrementObjects not called in VS Schema::table drop

### ISSUE THREAD

**Issue by FranPregernik** [yajra/laravel-oci8#106]
Hi,

when using the drop syntax:
```php
        Schema::table(
            PromotionType::TABLE,
            function (Blueprint $table) {
                // some 
                // other 
                // modifications like droping FK indexes etc.
                $table->drop();
            }
        );
```

The drop method call does not invoke the ```dropAutoIncrementObjects``` and this leaves the sequences hanging.

When calling via:

```php
        Schema::drop(PromotionType::TABLE);
```

They are removed.

What's you advice on this? Should I just use Schema::drop?

**Comment by yajra** [comment]
I suggest you use `Schema::drop` atm. And to be honest, I haven't used `$table->drop()` up to now. ^_^ 
But will try to check this on my free time as this should function as expected too.

Or if you can submit a PR to fix this then it's highly appreciated. Thanks!

**Comment by FranPregernik** [comment]
Thnx - I am switching to ```Schema::drop```. 

If you agree that it should be in $table->drop as well I will make an effort and do a PR when I find the time.

**Comment by yajra** [comment]
@FranPregernik, what I think is if it works on MySQL or other DB, then it should work on oracle too if possible. Thanks!

**Comment by rafael-renan-pacheco** [comment]
@FranPregernik 

#129 shall fix this, can you test it?

Thanks
