### ISSUE TITLE
Infinite loop when using query builder

### ISSUE THREAD

**Issue by pavlik1510** [yajra/laravel-oci8#108]
Hi,

first thanks for great job on that. I found out when i have a user which is not owner of shema and i have to use a prefix of another Table tan i get Infinite loop.

I used conection like that :   
      'oracle' => array(
            'driver'   => 'oracle',
            'database' => 'seerver',
            'username' => 'Username',
            'password' => 'password',
            'prefix'   => 'OTHER_SCHEMA.',
        ),

after prefix the application run in the loop. 
The fix was 
App::before(function($request) {
    DB::statement("ALTER SESSION SET CURRENT_SCHEMA = other_schema");
});

is there any solution on that?

Thank you.
Best Regards
Paul

**Comment by fabiothomaz** [comment]
Paul,

Try to use the 'schema' attribute in database config:

'oracle' => array(
'driver' => 'oracle',
'database' => 'seerver',
'username' => 'Username',
'password' => 'password',
'schema' => 'OTHER_SCHEMA',
),

**Comment by yajra** [comment]
@pavlik1510, @fabiothomaz suggestions should do the trick for you. Thanks!
