### ISSUE TITLE
Call to undefined function yajra\Pdo\oci_connect()

### ISSUE THREAD

**Issue by rogerburgos** [yajra/laravel-oci8#109]
Hi, i have this problem,

FatalErrorException in Oci8.php line 81:
Call to undefined function yajra\Pdo\oci_connect()

I put the project in a Windows Server 2008, can you help me? Thanks.

**Comment by yajra** [comment]
This is an environment issue. Please make sure you have `oci8` extension loaded on your `php.ini`.

**Comment by yajra** [comment]
Loading the proper `oci8` extension should fix the issue. Thanks!
