### ISSUE TITLE
oci_bind_by_name(): ORA-01036: illegal variable name/number

### ISSUE THREAD

**Issue by jyerdonspls** [yajra/laravel-oci8#110]
Hello,

[FYI, running in a Laravel 5.1 app]

I just installed the latest version of the framework (~3.0) and have had success thus far. Having an issue running a DB::statement though; ends up throwing the error "oci_bind_by_name(): ORA-01036: illegal variable name/number".

The debug chain is pasted below. I've seen that a very similar error occurred in Dec 2014; wanted to check with you to see if this error still exists in a different form.  Thanks!

1. in Connection.php line 651
2. at Connection->runQueryCallback('create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = ?)', array('7'), object(Closure)) in Connection.php line 611
3. at Connection->run('create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = ?)', array('7'), object(Closure)) in Connection.php line 391
4. at Connection->statement('create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = ?)', array('7'))
5. at call_user_func_array(array(object(Oci8Connection), 'statement'), array('create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = ?)', array('7'))) in DatabaseManager.php line 296
6. at DatabaseManager->__call('statement', array('create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = ?)', array('7'))) in Facade.php line 219
7. at DatabaseManager->statement('create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = ?)', array('7')) in Facade.php line 219
8. at Facade::__callStatic('statement', array('create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = ?)', array('7'))) in STable.php line 76
9. at DB::statement('create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = ?)', array('7')) in STable.php line 76

**Comment by yajra** [comment]
@jyerdonspls, I think binding of variables on this type of query is not allowed by oracle. Tried executing it on SQL Developer and this is the error I got:

```sql
create table TEMP_9 as (select distinct email from users where id > :id);
-----
SQL Error: ORA-01027: bind variables not allowed for data definition operations
01027. 00000 -  "bind variables not allowed for data definition operations"
*Cause:    An attempt was made to use a bind variable in a SQL data definition
           operation.
*Action:   Such bind variables are not allowed.
```

In this regard, you have to passed directly the value instead of binding it on array.

```php
$id = 7;
DB::statement("create table TEMP_9 as (select distinct email_id from email_keywords where keyword_id = $id)");
```

**Comment by yajra** [comment]
Passing the value directly in query should fix the issue. Binding is not allowed on this type of query. Thanks!
