### ISSUE TITLE
Sequence trigger with "before update"

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [yajra/laravel-oci8#112]
Hi there!

Why does the sequence trigger have a "before update" statement, instead of just a "before insert"?

The trigger body has only the following code:

```plsql
if inserting and :new.id is null then
    select table_id_seq.nextval into :new.id from dual;
end if;
```

So the `before insert or update` could be just `before insert`, right?

Best regards,
Rafael Pacheco.

**Comment by yajra** [comment]
Hmm good point. The snippet I used was fetch from my previous project and it has a different task when updating. Will remove the unnecessary inserting sql. Thanks for reporting..

```php
return $this->connection->statement("
            create trigger $triggerName
            before insert on {$table}
            for each row
                begin
            if :new.{$column} is null then
                select {$sequenceName}.nextval into :new.{$column} from dual;
            end if;
            end;");
```
