### ISSUE TITLE
Lowercase yarya in Quick Installation in readme.md

### ISSUE THREAD

**Issue by whit0313** [yajra/laravel-oci8#115]
Hi Yarya, it looks like you've still got `$ composer require yajra/laravel-oci8:~4.0` in the Quick Installation [Laravel 5.1 & Up] section of readme.md.

Should that be `$ composer require Yajra/laravel-oci8:~4.0` (with an uppercase Y)?

**Comment by yajra** [comment]
hi @whit0313, `4.0` is not yet released and still on development. You might need to add this on your composer.json to be able to download 4.0 dev branch.
```json
  "minimum-stability": "dev",
  "prefer-stable": true
```
`composer require yajra/laravel-oci8:~4.0` is correct.

**Comment by whit0313** [comment]
Oh - okay, my mistake. :-)
