### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by tristanrollet** [yajra/laravel-oci8#116]
Hello,
I'm trying to save a date in a column, but I encounter an error every time:
ORA-01 861: literal does not match format string (when insert date format).

I've tried everything I could think of:
- Carbon::now()
- to_date('d-m-y')
- '01-01-2015'
- '2015-01-01'

Could you please help ?

**Comment by rafael-renan-pacheco** [comment]
Did you try [this](https://github.com/yajra/laravel-oci8/wiki/Date-Formatting)?

**Comment by tristanrollet** [comment]
I did. The problem was a default date field which was formatted as a string, and with my locale it just didn't work.
