### ISSUE TITLE
Call to undefined function yajra\Pdo\oci_connect()

### ISSUE THREAD

**Issue by phpMick** [yajra/laravel-oci8#118]
Is this because I need to install oci8?

**Comment by rafael-renan-pacheco** [comment]
yes :+1:

**Comment by phpMick** [comment]
Just trying to do that.

Should I have a vendor/yajra/Pdo directory?

**Comment by rafael-renan-pacheco** [comment]
No.

1º: Make sure you have php_oci8.dll in your php\ext dir. If not, download it.
2º: Enable extension=php_oci8.dll in your php\php.ini file, and restart apache.
3°: Those are Windows/XAMPP instructions. If you are using another OS, the solution is most like the same.

This will handle the oci_connect() method and you shall not receive this error again.

**Comment by phpMick** [comment]
It was a Centos box, I have it working now. (Almost, it error out at  OCI_SUCCESS_WITH_INFO:the account will expire soon.)

**Comment by rafael-renan-pacheco** [comment]
:+1:

**Comment by phpMick** [comment]
If anyone else has this:
http://www.oracle.com/technetwork/articles/dsl/technote-php-instant-12c-2088811.html
I followed this but specified a different version pecl install oci8-2.0.10.
Thanks

**Comment by phpMick** [comment]
Any idea what I an doing wrong here?

$rows = DB::select("select * from something.table");

OCI-Lob::load(): OCI_INVALID_HANDLE (SQL: select * from something.table)

**Comment by rafael-renan-pacheco** [comment]
Now you are entering Google realm.

In a quick search, I found [this](http://stackoverflow.com/questions/16540226/how-to-update-a-lob-with-php-in-oracle-oci-invalid-handle).

Looks like OCI_INVALID_HANDLE is a warning fired when the statement does not find a row, usually caused by a wrong ID. If this something.table is empty, this may be the issue.

**Comment by phpMick** [comment]
Thanks, much appreciated. I did a 'select sysdate from dual' and I get a date.

I guess there is something wrong with that table.

:-)

**Comment by cartbeforehorse** [comment]
Is there a LOB, CLOB or ROWID in that table by any chance?
