### ISSUE TITLE
problem with Arabic language

### ISSUE THREAD

**Issue by yasserodb** [yajra/laravel-oci8#120]
Hello Arjay ,thanks for your support ,I had the same problem with Arabic language  characterset set of database level is  AR8MSWIN1256 and characterset of php level is utf8 
Note that the same settings worked with Arabic language  with pure PHP .

setting of pure php that worked correctly :+1: 
<?php

$tns = "
    (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.6)(PORT = 1521))
        (CONNECT_DATA =
            (SERVER = DEDICATED)
            (SERVICE_NAME = xe )
        )
    )
";

$pdo_string = 'oci:dbname='.$tns.';charset=utf8';

try {
    $dbh = new PDO($pdo_string, 'username', 'password' );
} catch (PDOException $e) {
    echo "Failed to obtain database handle: " . $e->getMessage();
    exit;
}

$query = "SELECT * FROM personnel";

$stmt = $dbh->prepare($query);

if ($stmt->execute()) {
    echo "<h4>$query</h4>";
    echo "<pre>";
    while ($row = $stmt->fetch()) {
        print_r($row);
    }
    echo "</pre>";
}

setting of laravel that not worked correctly :-1: 
config/database.php
'oracle' => [
            'driver' => 'oracle',
            'host' => '192.168.1.6',
            'port' => '1521',
            'database' => 'XE',
            'username' => 'username',
            'password' => 'password',
            'charset' => 'utf8',
            'prefix' => '',
        ]

app/http/route

Route::get('connection', function()
{
    return $users = DB::connection('oracle')->table('personnel')->select('*')->get();
});

please could you solve my problem

**Comment by yajra** [comment]
@yasserodb, where you able to make a successful connection? Also, it seems like you are using a service name instead on SID. Try using service_name too.
 
```php
config/database.php
'oracle' => [
'driver' => 'oracle',
'host' => '192.168.1.6',
'port' => '1521',
'database' => '',
'service_name'=>'xe',
'username' => 'username',
'password' => 'password',
'charset' => 'utf8',
'prefix' => '',
]
```

**Comment by yasserodb** [comment]
thanks for your response , 
yes , I already connected successfully , then i tried service_name as you mentioned , and still not working,

**Comment by yasserodb** [comment]
the problem not in the connection , but in the displaying of Arabic language

**Comment by yajra** [comment]
Where you able to do suggestions on #39 ? 
>From @mansouralex 
>Hi @yasserodb try to set your php charset to AL32UTF8. And as I remember you need to install the Arabic related libraries while installing the oracle database.

**Comment by yajra** [comment]
Language settings are mostly on database level and oci8 can't do much magic about it. Better check with your DBA for any possible settings/installation/setup needed for the database.

**Comment by yasserodb** [comment]
then what is your comment about that it worked on pure php code (without Laravel)

**Comment by yajra** [comment]
Not really sure on this but maybe because you are using `pdo_oci` instead of `oci8`? I don't have any Arabic oracle resource to tests but as per my readings, setting `charset=AL32UTF8` should help you with it. Otherwise, there might be some missing components that are not yet implemented in the package.

**Comment by yajra** [comment]
An alternative (https://github.com/jfelder/Laravel-OracleDB) package is also available that uses `pdo_oci`. You can also give it a shot as it may work for your case?

**Comment by yasserodb** [comment]
thank you very much you are kind :+1:

**Comment by yasserodb** [comment]
@mansouralex 
what is the characterset you set in the database level

**Comment by mansouralex** [comment]
Umm, I don't remember what the DBA set it at that time. But as I remember it's not just the characterset there is Arabic language related libraries should be installed while the DBA installing the DB.

**Comment by yasserodb** [comment]
thanks all it already had been solved by typing this code for testing

    $rows = DB::table('personnel')->select('name_ar')->get();
$column_vals = [];
foreach($rows as $row) {
  $column_vals[]=$row->name_ar;
  
}
 print_r($column_vals);

//first one code return encrypted arabic string 

thanks @yajra  , thanks @mansouralex

**Comment by yajra** [comment]
Glad you sorted this out! :+1:
