### ISSUE TITLE
->nocache() to ->cache($value)

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [yajra/laravel-oci8#121]
Hi there!

For version 4.0, what do you think about nocache for sequences be the default option when creating sequences?

If the user does want to cache, it can be achieved by using ->cache(some_value). This way the user can explicity set the cache size, if needed.

The auto_increments in MySQL does not cache the ID, so Oracle with nocache as default would make this project more "equal" as MySQL, for example.

**Comment by yajra** [comment]
Not sure about this one. Is there any benefit when disabling the cache? Let's research first on the pros and cons. I think caching is there by default for some reasons.

**Comment by rafael-renan-pacheco** [comment]
Hi there!

It depends on how heavily a sequence is used to fill some id. The problem is, if you do have a table that requires lots of inserts per second, which will require lots of sequence.nextval, cache 20 won't help that much. You need to change the cache to a higher value. So, in this situation, you may want to have control of the cache size, using something like `->cache(1000)`.

For tables that does not receive tons of inserts per second, cache 20 won't make that much difference.

In a little research [here](http://stackoverflow.com/questions/24298868/sequence-cache-and-performance) and [here](https://technology.amis.nl/2006/09/22/how-does-the-sequence-cache-affect-performance/), they benchmark for lots of inserts, with a cache different from 20.

[Here](https://asktom.oracle.com/pls/asktom/f?p=100:11:::::P11_QUESTION_ID:2985886242221) they have a long discussion, and always talking about "heavy usage", which makes that default cache of 20 kind useless.

After reading this articles, cache 20 as default is fine, but an option to set the cache size other than 20 becomes visibly necessary =)

**Comment by yajra** [comment]
Thanks for taking time to research. I guess we would be sticking to what we have now and setting cache is already available in the package. ^_^ Thanks!
