### ISSUE TITLE
Call to undefined function Yajra\Oci8\config_path()

### ISSUE THREAD

**Issue by jrosczyk** [yajra/laravel-oci8#123]
Any ideas? Getting this error:                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Call to undefined function Yajra\Oci8\config_path()      
                                                
$ php artisan migrate
PHP Fatal error:  Call to undefined function Yajra\Oci8\config_path() in /lumen/vendor/yajra/laravel-oci8/src/Oci8/Oci8ServiceProvider.php on line 34

**Comment by yajra** [comment]
Oh, I think `config_path` is not available on Lumen. Will check this later and will try to add a fix asap. Thanks for reporting.

**Comment by yajra** [comment]
It's confirmed that config_path is not available on Lumen. Added some helper to fix it on v4.0.2.

**Comment by jrosczyk** [comment]
That solved the config_path issue in Lumen... but now getting this message when trying to connect to db via a migration:
```
  [Yajra\Pdo\Oci8\Exceptions\Oci8Exception]  
```
