### ISSUE TITLE
oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by amrigo** [yajra/laravel-oci8#125]
Hi 

I just install PHP7-FPM with OCI8 enabled ORACLE_HOME and TNS enviroment correctly set ican seeit into phpinfo();

I create the credentials into config/database.php and .env as well .

For a second try i do create a pure PHP script and it connect .

I just get  the ORA-12154 message still. 

The error message points to vendor/yajra/laravel-pdo-via-oci8/src/yajra/Pdo/Oci8.php

There is a way i can specify that i do not want to use laravel-pdo-via-oci8 ? maybe using only laravel-oci8 the connection works.

**Comment by amrigo** [comment]
The error message shows // Attempt a connection
		if (isset($options[PDO::ATTR_PERSISTENT]) && $options[PDO::ATTR_PERSISTENT])
		{
			$this->_dbh = oci_pconnect($username, $password, $dsn, $charset);
		}
		else
		{
			$this->_dbh = oci_connect($username, $password, $dsn, $charset);
		}

**Comment by yajra** [comment]
@amrigo, what version are you using? `yajra/Pdo/Oci8.php` indicates that you are using version 3.0 or below. Laravel-OCI8 seems to be a bit buggy on PHP7 and I made some fixes on it on v4.0. Is it possible for you to use version 4 instead?

Anyways, can you please paste the full error stack? It would help a lot. Thanks!

**Comment by amrigo** [comment]
Hi! How can i see the version ? i do a composer update and read composer.json wich indicates version 3.0.  Wich is the best way to update to version 4.0 ? i do have to write 4.0 for yajra on composer.json file ?

**Comment by amrigo** [comment]
ErrorException (E_WARNING)
oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified

/vendor/yajra/laravel-pdo-via-oci8/src/yajra/Pdo/Oci8.php
		
		// Attempt a connection
		if (isset($options[PDO::ATTR_PERSISTENT]) && $options[PDO::ATTR_PERSISTENT])
		{
			$this->_dbh = oci_pconnect($username, $password, $dsn, $charset);
		} else {
			$this->_dbh = oci_connect($username, $password, $dsn, $charset);
		}

**Comment by amrigo** [comment]
Also i did not have PDO_Oracle enabled only oci8

**Comment by amrigo** [comment]
65. ErrorException
…/­vendor/­yajra/­laravel-pdo-via-oci8/­src/­yajra/­Pdo/­Oci8.php81

64. Illuminate\Foundation\Bootstrap\HandleExceptions handleError
<#unknown>0

63. oci_connect
…/­vendor/­yajra/­laravel-pdo-via-oci8/­src/­yajra/­Pdo/­Oci8.php81

62. yajra\Pdo\Oci8 __construct
…/­vendor/­yajra/­laravel-oci8/­src/­Oci8/­Connectors/­OracleConnector.php191

61. yajra\Oci8\Connectors\OracleConnector createConnection
…/­vendor/­yajra/­laravel-oci8/­src/­Oci8/­Connectors/­OracleConnector.php38

60. yajra\Oci8\Connectors\OracleConnector connect
…/­vendor/­yajra/­laravel-oci8/­src/­Oci8/­Oci8ServiceProvider.php40

59. yajra\Oci8\Oci8ServiceProvider yajra\Oci8\{closure}
<#unknown>0

58. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­DatabaseManager.php172

57. Illuminate\Database\DatabaseManager makeConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­DatabaseManager.php67

56. Illuminate\Database\DatabaseManager connection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php3284

55. Illuminate\Database\Eloquent\Model resolveConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php3250

54. Illuminate\Database\Eloquent\Model getConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1930

53. Illuminate\Database\Eloquent\Model newBaseQueryBuilder
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1873

52. Illuminate\Database\Eloquent\Model newQueryWithoutScopes
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1847

51. Illuminate\Database\Eloquent\Model newQuery
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php3495

50. Illuminate\Database\Eloquent\Model __call
…/­domain/­Informativos/­Repositories/­InformativoEloquentRepository.php23

49. Domain\Informativos\Repositories\InformativoEloquentRepository listar
…/­app/­Http/­Controllers/­HomeController.php16

48. Crono\Http\Controllers\HomeController index
<#unknown>0

47. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Controller.php256

46. Illuminate\Routing\Controller callAction
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php164

45. Illuminate\Routing\ControllerDispatcher call
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php112

44. Illuminate\Routing\ControllerDispatcher Illuminate\Routing\{closure}
<#unknown>0

43. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php139

42. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
<#unknown>0

41. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php102

40. Illuminate\Pipeline\Pipeline then
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php114

39. Illuminate\Routing\ControllerDispatcher callWithinStack
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php67

38. Illuminate\Routing\ControllerDispatcher dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Route.php203

37. Illuminate\Routing\Route runWithCustomDispatcher
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Route.php134

36. Illuminate\Routing\Route run
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php708

35. Illuminate\Routing\Router Illuminate\Routing\{closure}
<#unknown>0

34. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php139

33. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
<#unknown>0

32. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php102

31. Illuminate\Pipeline\Pipeline then
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php710

30. Illuminate\Routing\Router runRouteWithinStack
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php673

29. Illuminate\Routing\Router dispatchToRoute
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php635

28. Illuminate\Routing\Router dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Kernel.php236

27. Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
<#unknown>0

26. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php139

25. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­barryvdh/­laravel-debugbar/­src/­Middleware/­Debugbar.php49

24. Barryvdh\Debugbar\Middleware\Debugbar handle
<#unknown>0

23. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124

22. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Middleware/­VerifyCsrfToken.php50

21. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken handle
<#unknown>0

20. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124

19. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­View/­Middleware/­ShareErrorsFromSession.php49

18. Illuminate\View\Middleware\ShareErrorsFromSession handle
<#unknown>0

17. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124

16. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Session/­Middleware/­StartSession.php62

15. Illuminate\Session\Middleware\StartSession handle
<#unknown>0

14. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124

13. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Middleware/­AddQueuedCookiesToResponse.php37

12. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse handle
<#unknown>0

11. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124

10. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Middleware/­EncryptCookies.php59

9. Illuminate\Cookie\Middleware\EncryptCookies handle
<#unknown>0

8. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124

7. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Middleware/­CheckForMaintenanceMode.php44

6. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
<#unknown>0

5. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124

4. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
<#unknown>0

3. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php102

2. Illuminate\Pipeline\Pipeline then
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Kernel.php122

1. Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Kernel.php87

0. Illuminate\Foundation\Http\Kernel handle
…/­public/­index.php53

**Comment by amrigo** [comment]
Hi Yajra ! i try this command  : composer update vendor/yajra/laravel-oci8
> php artisan clear-compiled
Package "vendor/yajra/laravel-oci8" listed for update is not installed. Ignoring.

Wich command line can i use to update Yajra libray to version 4 ?

**Comment by amrigo** [comment]
I try this command :

 # composer require yajra/laravel-oci8:~4.0

./composer.json has been updated

> php artisan clear-compiled

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yajra/laravel-pdo-via-oci8 == 0.15.0.0 -> satisfiable by yajra/laravel-pdo-via-oci8[0.15.0].
    - yajra/laravel-oci8 v4.0.0 requires yajra/laravel-pdo-via-oci8 1.* -> satisfiable by yajra/laravel-pdo-via-oci8[v1.0.0].
    - yajra/laravel-oci8 v4.0.1 requires yajra/laravel-pdo-via-oci8 1.* -> satisfiable by yajra/laravel-pdo-via-oci8[v1.0.0].
    - yajra/laravel-oci8 v4.0.2 requires yajra/laravel-pdo-via-oci8 1.* -> satisfiable by yajra/laravel-pdo-via-oci8[v1.0.0].
    - yajra/laravel-oci8 v4.0.3 requires yajra/laravel-pdo-via-oci8 1.* -> satisfiable by yajra/laravel-pdo-via-oci8[v1.0.0].
    - yajra/laravel-oci8 v4.1.0 requires yajra/laravel-pdo-via-oci8 1.* -> satisfiable by yajra/laravel-pdo-via-oci8[v1.0.0].
    - Conclusion: don't install yajra/laravel-pdo-via-oci8 v1.0.0
    - Installation request for yajra/laravel-oci8 ~4.0 -> satisfiable by yajra/laravel-oci8[v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.1.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by amrigo** [comment]
I so write 4.0 into composer.json yajra line, do a composer update and now i have the right version running "composer show" i can see the new version : 
 yajra/laravel-oci8                    v4.1.0  Oracle DB driver for Laravel 4|5 via OCI8
  yajra/laravel-pdo-via-oci8            v1.0.0  PDO userspace driver proxying calls to PHP OCI8 driver

The error message changes to : Fatal error: Class 'yajra\Oci8\Oci8ServiceProvider' not found

**Comment by amrigo** [comment]
I check config/app.php i see i do have this line on the providers section: yajra\Oci8\Oci8ServiceProvider::class,

**Comment by amrigo** [comment]
Hi after change into config/app.php to Yajra\Oci8\Oci8ServiceProvider::class, the error message now is ORA-12541: TNS:no listener

**Comment by amrigo** [comment]
If i do specify into config/database.php a TNS the error message is : TNS:could not resolve the connect identifier specified

**Comment by amrigo** [comment]
The full stack error 
64. Yajra\Pdo\Oci8\Exceptions\Oci8Exception
…/­vendor/­yajra/­laravel-pdo-via-oci8/­src/­Pdo/­Oci8.php454
63. Yajra\Pdo\Oci8 connect
…/­vendor/­yajra/­laravel-pdo-via-oci8/­src/­Pdo/­Oci8.php66
62. Yajra\Pdo\Oci8 __construct
…/­vendor/­yajra/­laravel-oci8/­src/­Oci8/­Connectors/­OracleConnector.php188
61. Yajra\Oci8\Connectors\OracleConnector createConnection
…/­vendor/­yajra/­laravel-oci8/­src/­Oci8/­Connectors/­OracleConnector.php35
60. Yajra\Oci8\Connectors\OracleConnector connect
…/­vendor/­yajra/­laravel-oci8/­src/­Oci8/­Oci8ServiceProvider.php42
59. Yajra\Oci8\Oci8ServiceProvider Yajra\Oci8\{closure}
<#unknown>0
58. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­DatabaseManager.php172
57. Illuminate\Database\DatabaseManager makeConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­DatabaseManager.php67
56. Illuminate\Database\DatabaseManager connection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php3284
55. Illuminate\Database\Eloquent\Model resolveConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php3250
54. Illuminate\Database\Eloquent\Model getConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1930
53. Illuminate\Database\Eloquent\Model newBaseQueryBuilder
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1873
52. Illuminate\Database\Eloquent\Model newQueryWithoutScopes
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1847
51. Illuminate\Database\Eloquent\Model newQuery
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php3495
50. Illuminate\Database\Eloquent\Model __call
…/­domain/­Informativos/­Repositories/­InformativoEloquentRepository.php23
49. Domain\Informativos\Repositories\InformativoEloquentRepository listar
…/­app/­Http/­Controllers/­HomeController.php16
48. Crono\Http\Controllers\HomeController index
<#unknown>0
47. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Controller.php256
46. Illuminate\Routing\Controller callAction
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php164
45. Illuminate\Routing\ControllerDispatcher call
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php112
44. Illuminate\Routing\ControllerDispatcher Illuminate\Routing\{closure}
<#unknown>0
43. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php139
42. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
<#unknown>0
41. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php102
40. Illuminate\Pipeline\Pipeline then
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php114
39. Illuminate\Routing\ControllerDispatcher callWithinStack
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php67
38. Illuminate\Routing\ControllerDispatcher dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Route.php203
37. Illuminate\Routing\Route runWithCustomDispatcher
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Route.php134
36. Illuminate\Routing\Route run
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php708
35. Illuminate\Routing\Router Illuminate\Routing\{closure}
<#unknown>0
34. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php139
33. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
<#unknown>0
32. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php102
31. Illuminate\Pipeline\Pipeline then
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php710
30. Illuminate\Routing\Router runRouteWithinStack
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php673
29. Illuminate\Routing\Router dispatchToRoute
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php635
28. Illuminate\Routing\Router dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Kernel.php236
27. Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
<#unknown>0
26. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php139
25. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­barryvdh/­laravel-debugbar/­src/­Middleware/­Debugbar.php49
24. Barryvdh\Debugbar\Middleware\Debugbar handle
<#unknown>0
23. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124
22. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Middleware/­VerifyCsrfToken.php50
21. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken handle
<#unknown>0
20. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124
19. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­View/­Middleware/­ShareErrorsFromSession.php49
18. Illuminate\View\Middleware\ShareErrorsFromSession handle
<#unknown>0
17. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124
16. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Session/­Middleware/­StartSession.php62
15. Illuminate\Session\Middleware\StartSession handle
<#unknown>0
14. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124
13. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Middleware/­AddQueuedCookiesToResponse.php37
12. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse handle
<#unknown>0
11. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124
10. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Middleware/­EncryptCookies.php59
9. Illuminate\Cookie\Middleware\EncryptCookies handle
<#unknown>0
8. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124
7. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Middleware/­CheckForMaintenanceMode.php44
6. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
<#unknown>0
5. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php124
4. Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
<#unknown>0
3. call_user_func
…/­vendor/­laravel/­framework/­src/­Illuminate/­Pipeline/­Pipeline.php102
2. Illuminate\Pipeline\Pipeline then
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Kernel.php122
1. Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Http/­Kernel.php87
0. Illuminate\Foundation\Http\Kernel handle
…/­public/­index.php53

**Comment by yajra** [comment]
@amrigo , sorry for late response as I am on a long weekend holidays. 

Anyways, try using `service_name`? See this [issue](https://github.com/yajra/laravel-oci8/issues/111) for ref:

**Comment by amrigo** [comment]
@yajra Thank you a lot, for this library and for the solution!
Now i am running php7-fpm with nginx AND connecting to Oracle, my config/app.php now has this working configuration:
 'production' => [
            'driver'    => 'oracle',
            'SID'       => env('DB_SID', 'mysid'),
            'SERVICE_NAME' => 'myservicename',
            'host'      => env('DB_HOST', 'myhost'),
            'port'      => '1111',
            'database'  => '',
            'username'  => env('DB_USERNAME', 'myusername'),
            'password'  => env('DB_PASSWORD', 'mypassword'),
            'tns' => '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=111.111.111.111)(PORT=1111)))(CONNECT_DATA=(SID=mysid)(SERVICE_NAME=myservicename)))',
            'charset' => 'AL32UTF8',
            'prefix' => '',
        ],
best regards!

**Comment by salmanbaig** [comment]
Same worked for me too.
Thanks
