### ISSUE TITLE
ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by ehsanphp** [yajra/laravel-oci8#126]
I am having this issue with our production server. In my local environment, I can connect to Oracle database just like that. But, in production environment it shows "oci_connect(): ORA-12541: TNS:no listener"

FYI: I am using "yajra/laravel-oci8": "dev-master"

**Comment by yajra** [comment]
@ehsanphp, can you tnsping the database from your production server?

**Comment by ChaosPower** [comment]
@ehsanphp you still having issues with this?

**Comment by ChaosPower** [comment]
Closing inactive issue please reopen if you still getting this.
