### ISSUE TITLE
yajra\Oci8\Oci8ServiceProvider not found

### ISSUE THREAD

**Issue by sciracioglu** [yajra/laravel-oci8#130]
hi,
i use this version on laravel 5.2 
"yajra/laravel-oci8": "~4.0",
my provider is
Yajra\Oci8\Oci8ServiceProvider::class,

but i get 
FatalErrorException in ProviderRepository.php line 145: Class 'yajra\Oci8\Oci8ServiceProvider' not found

composer dump-autoload nothing changed.
where is the problem.
thanks.

**Comment by yajra** [comment]
I think you upgraded from v3 to v4 and the was already compiled? Try using `php artisan clear-compiled`.

**Comment by sciracioglu** [comment]
thanks but already


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'yajra\Oci8\Oci8ServiceProvider' not found
error is here

**Comment by sciracioglu** [comment]
upgrade from 
"yajra/laravel-oci8": "~2.0", to
"yajra/laravel-oci8": "~4.0",

**Comment by yajra** [comment]
I see. You may have to remove the vendor directory then reinstall all the packages.

**Comment by ChaosPower** [comment]
I encountered this as well but from a different package.

Usually is caused by config/app.php file.

Try commenting yajra\Oci8\Oci8ServiceProvider. Please notice that namespaces are case sensitive.

try changing to Yajra\Oci8\Oci8ServiceProvider.

**Comment by apit** [comment]
@ChaosPower that was my case, too. i think this issue could be closed

**Comment by yajra** [comment]
@ChaosPower solution will do fix the issue. Thanks!

**Comment by carsonevans** [comment]
I ran into an order of operations issue when trying to create a new install of Laravel 5.2 with this dependency. In order to use it you need to have the config/app.php provider entry, but to install it you need to comment out the entry or artisan clear-compiled won't work. So, commenting out the providers entry, doing a composer install or composer require to get the libraries downloaded, and then uncommenting the providers entry fixed it.

**Comment by divyad** [comment]
I am getting this same issue.
Laravel version is 5.2
yajra/laravel-oci8:"5.2.*"

Tried both solutions but didn't work.

Getting error: 
local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Yajra\Oci8\Oci8ServiceProvider' not found' in ProviderRepository.php:146

Please suggest
Thanks
