### ISSUE TITLE
[Yajra\Pdo\Oci8\Exceptions\Oci8Exception]  After update to version 4.*

### ISSUE THREAD

**Issue by allanfreitas** [yajra/laravel-oci8#133]
I'm getting this error after update to version 4.*,

any one can help?

```php
 [Yajra\Pdo\Oci8\Exceptions\Oci8Exception]
  Error Code    : 904
  Error Message : ORA-00904: "password": invalid identifier
  Position      : 59
  Statement     : insert into portal.usuarios (cod_obreiro, email, username, "password", ativo, updated_at, created_at) values (:p0, :p1, :p2, :p3,
   :p4, :p5, :p6) returning id into :p7
  Bindings      : [2,USER@EMAIL.com,myuser,$2y$10$b2Ktzrxnlbyxcn30z8uF7.ysOVwIDJTMYQmL06UJv32g2g1GDB6WK,1,2016-01-08 17:0
  8:38,2016-01-08 17:08:38,0]
```

**Comment by rafael-renan-pacheco** [comment]
Password was added in the Oracle reserved words list in version 4+, so it will be wrapped with double quotes from now on.

This means you have to change you password column to "password", same name, but double quoted.

For example, if I export my users table, I get this:
```sql
create table USER
(
  id             NUMBER(10) not null,
  name           VARCHAR2(30) not null,
  email          VARCHAR2(255) not null,
  "password"     VARCHAR2(60) not null,
  remember_token VARCHAR2(100),
  created_at     TIMESTAMP(6) not null,
  updated_at     TIMESTAMP(6) not null
)
```

$user->password or $user['password'] will work just fine, you don't have to wrap them. Laravel-oci8 does the wrap job when generating sql statements.

**Comment by allanfreitas** [comment]
Nice to know. Thanks for The explanation. But the clock was ticking for delivery, so i've changed the column name to `passwd` and already deployed :)
