### ISSUE TITLE
[LARAVEL5] When running migrations, I get "Call to undefined function Yajra\Pdo\oci_connect()"

### ISSUE THREAD

**Issue by vitroz** [yajra/laravel-oci8#135]
Hi All,
I am trying to migrate my database from mysql to Oracle, but when i try to run php artisan migrate, it simply wont run properly. I have tested the connection, and it is working fine. When i access the aplication, it tries to look for the tables, etc.
I have the oci installed, under composer and on providers on app.php

Does anyone have any idea on what's causing this?

on /storage/logs:
[2016-01-12 15:01:47] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function Yajra\Pdo\oci_connect()' in /home/programacao/projetos/gestor-codemed/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php:449
Stack trace:
#0 {main}

**Comment by rafael-renan-pacheco** [comment]
https://github.com/yajra/laravel-oci8/wiki/Requirements

**Comment by vitroz** [comment]
Im using: php 5.6.4
the OCI8Extension is enabled.
composer 1.0-dev

**Comment by mstaack** [comment]
what does 'php -m | grep oci8' give you?
make sure extensions is listed in your php.ini

**Comment by vitroz** [comment]
@mstaack Nothing happens, Max
Is there something missing then?

**Comment by mstaack** [comment]
you need to enable this extension into your php config
see here: https://github.com/yajra/homestead-oracle/blob/master/scripts/install-oci8.sh#L5
depends on your running nginx or apache
`echo 'extension=oci8.so' >> /etc/php5/cli/php.ini`  is for the console as an example

**Comment by vitroz** [comment]
@mstaack I already have those lines on my php.ini 

    ; Default timeout for socket based streams (seconds)
    ; http://php.net/default-socket-timeout
    default_socket_timeout = 60

    extension=oci8.so

Does it means its already enabled? Im using apache

**Comment by mstaack** [comment]
did you add  this line in the  `/etc/php5/apache2/php.ini` file?
did you restart apache?

**Comment by vitroz** [comment]
@mstaack Got it solved, thank you so much!
The only thing I did was add the lines to the php.ini on etc/php5/cli folder.
I didn't know there was two php.ini files. the extension was only enabled on the php.ini on apache folder.

Moderator may mark this issue as solved.

**Comment by rafael-renan-pacheco** [comment]
@yajra, may I suggest you add in the readme some common problems and solutions, like this undefined  oci_connect() error? This is a very common issue around here.

**Comment by yajra** [comment]
@rafael-renan-pacheco will try to add your suggestion. Thanks!

**Comment by ali2535** [comment]
hi yajra . i have a bigggggggggggggg problem in connect laravel to oracle  .

i dont know that the problem where is.

FatalThrowableError in Oci8.php line 455:
Call to undefined function Yajra\Pdo\oci_connect()

this is additional information:

in Oci8.php line 455
at Oci8->connect('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.50.10)(PORT = 1521)) (CONNECT_DATA =(SERVICE_NAME = mipg)))', 'haft', 'haft', array(2, 2, 0, 'charset' => 'AL32UTF8'), 'AL32UTF8') in Oci8.php line 78

**Comment by mstaack** [comment]
@ali2535 please one isse only1

**Comment by karlkyn** [comment]
I get "Call to undefined function Yajra\Pdo\oci_connect()" when running **php artisan migrate:generate**.
i'm using oracle 11g XE edition on ubuntu 16.04. oci extension is well configured (cli and apache2). requests to the database works well. the only issue is migration command

**Comment by mstaack** [comment]
@karlkyn you are missing oci8 extension on php console...  php -m should show oci8...its a well known problem ;) so search yourself smart..

**Comment by karlkyn** [comment]
can the connection to an oracle database an even request to a schema in that database work without oci8 well configured? in my case it works well. But php artisan migrate:generate doesn't
