### ISSUE TITLE
What version of Oracle and/or OCI8 is required on the server?

### ISSUE THREAD

**Issue by whit0313** [yajra/laravel-oci8#137]
Hi @yajra 

Can you tell me please what version of Oracle and/or OCI8 I will need on the server, to be able to use `yajra/laravel-oci8`?

The server at my workplace has Oracle 11.2.0.2.0 and OCI8 2.0.8. Do you know whether this is recent enough? Or do I need to ask them to update it?

Thanks,
    Brendan.

**Comment by yajra** [comment]
Hi @whit0313,

If you are using PHP 5 then OCI8 2.0.10 is the latest stable version. For PHP 7, use OCI8 2.1.0 (https://pecl.php.net/package/oci8)

For instantclient, you can use v11.2 to match your Oracle server. But using 12.x will also work in case you want it. Personally, I am using v11.2 instantclient and PHP 7 + OCI8 2.1.0.

Regards,

Arjay

**Comment by whit0313** [comment]
I might see if the server guys will update OCI8 to 2.0.10 ... otherwise I'll just leave 2.0.8 and hopefully it will still work (it's only two patches).

Thanks!
