### ISSUE TITLE
'rn' value in response

### ISSUE THREAD

**Issue by AdamWillden** [yajra/laravel-oci8#14]
Hi @yajra but what is this `rn` value? I'm getting it returned in one of my responses. Searched google for `laravel "rn"` and found myself at #12 .

I'm running a simple command in a controller method:

``` php
return SiteDevice::find($device_guid);
```

Getting the response:

``` json
{
    rn: "1",
    device_guid: "296946177",
    site_id: "4531",
    device_id: "10",
    device_num: "1",
    device_tag: "SYSTEM",
    description: "System Info"
}
```

**Comment by karunkshrestha** [comment]
Is there an option to exclude 'rn' from the result? I am having to do a post clean up to remove the 'rn' attribute from the result.
`
foreach ($rows as $key => $row) {
  $data[] = array_except((array)$row,'rn');
}
`

This is just to improve performance when dealing with  large datasets.
