### ISSUE TITLE
Remove PDO type hint on Oci8Connection

### ISSUE THREAD

**Issue by yajra** [yajra/laravel-oci8#143]
From @sasanet,
> Hello yajra, i had already suggest a fix some times ago. I want to suggest another fix on Oci8Connection class.
The constructor of this class have a type PDO for the first argument, but in laravel framework this param may be of tyoe PDO or Closure. It's possible to remove type hint?
This happen when i modify 'Illuminate\Database\Connectors\ConnectionFactory' to support oracle driver, you will see or try in 'createConnection' method.

>Thanks

**Comment by yajra** [comment]
@sasanet, I am not aware that a Closure can be used for pdo argument. If that's the case then I agree to remove the type hint. Can you please submit a PR to fix it? Thanks!

**Comment by sasanet** [comment]
https://github.com/laravel/framework/commit/f7062509d7e43e3d15d74db102008cf63ed90f89.

thanks

**Comment by mstaack** [comment]
https://github.com/yajra/laravel-oci8/pull/145
