### ISSUE TITLE
Query insert from model dont fired on query.illuminate

### ISSUE THREAD

**Issue by ptsilva** [yajra/laravel-oci8#144]
When listen the `illuminate.query`, querys inserts dont fire.

```
    public function handle($query, $bindings)
    {
       // inserts not fired
    }
```

Something wrong?

**Comment by ChaosPower** [comment]
@ptsilva can give us the code snippet? Are you trying to save a model or do insert query directly from the query builder?

**Comment by ptsilva** [comment]
@ChaosPower, from model.
For example:

```
$post = Post::fill($request->all());
$post->save();
```

This don't fire the ```illuminate.query``` on model

**Comment by ptsilva** [comment]
The Builder inserts works on event.

**Comment by yajra** [comment]
@ptsilva what version of Laravel are you using? For 5.2, I think you should the object `Illuminate\Database\Events\QueryExecuted` now instead of the event name `illuminate.query`. 

See upgrade docs https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0.
