### ISSUE TITLE
Function whereDay(Builder $query, $where) missing in OracleGrammar.php

### ISSUE THREAD

**Issue by peyobr** [yajra/laravel-oci8#146]
Hi Arjay,
it seems like whereDay(Builder $query, $where) has'nt been extended in your OracleGrammar.php

Or am i missing something? :D

This is my simple scope query clause:

    public function scopeWhereBirthday($query, $birthday)
    {
        return $query->whereDay('data_nascita', '=', $birthday->day)->whereMonth('data_nascita', '=', $birthday->month);
    }

This is my output:

[Yajra\Pdo\Oci8\Exceptions\Oci8Exception]                                                                                 
  Error Code    : 904                                                                                                       
  Error Message : ORA-00904: "MONTH": invalid identifier                                                                    
  Position      : 79                                                                                                        
  Statement     : select count(*) as aggregate from TB_PERSONA where day(data_nascita) = :p0 and month(data_nascita) = :p1  
  Bindings      : [29,29,1,1]       

Thank you.

**Comment by peyobr** [comment]
Mhhhhhhhhhh


It seems that in Oracle 12.c the right way now is:

...EXTRACT(month FROM data_nascita)...

**Comment by rafael-renan-pacheco** [comment]
Yes, extract exists for a long time, and indeed this grammar is missing from this lib.

You can see the default grammar in:

vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php

```php
public function whereDate($column, $operator, $value, $boolean = 'and')
{
    return $this->addDateBasedWhere('Date', $column, $operator, $value, $boolean);
}
```

and some others, while the OracleBuilder.php does not extend this :(

**Comment by yajra** [comment]
@peyobr, what version are you using? Date based queries where already implemented on v4.x.

**Comment by yajra** [comment]
This [commit](https://github.com/yajra/laravel-oci8/commit/30936ce4ab759e306b732d4ee29e18ed3128e2a4 ) added the date based queries. Is it not working properly?

**Comment by rafael-renan-pacheco** [comment]
Whops, I did not found it was implemented already.

Just tested a simple `App\Model::whereMonth('created_at', '=', 2)->get();` and it worked just fine.

:sweat_smile:

**Comment by peyobr** [comment]
I'm using: "yajra/laravel-oci8": "~2.0"

I really must upgrade to: : "yajra/laravel-oci8": "~4.0"

Sorry, thank you!!!
