### ISSUE TITLE
Config parameter "database" has no effect

### ISSUE THREAD

**Issue by Marius2805** [yajra/laravel-oci8#147]
Hey,
lets say you have the following configuration:
```
'oracle' => array(
     [...]
    'database' => 'COOL_APPLICATION',
    'username' => 'COOL_APPLICATION_APP',
    'password' =>  'secret',
     [...]
)
```
I would assume then, that COOL_APPLICATION_APP ist the access/authentication user and tables are stored in COOL_APPLICATION.
Tables should be accessed by default in the configured database.
This seems to work with other databases like Postgres or MySQL but not with Oracle.

Is my assumption right, that this is the usecase for the DATABASE config parameter?
If yes, then I will try to make a pull request.

Thanks!

**Comment by yajra** [comment]
Hi,

The database parameter for Oracle is equivalent to the `SID` of Oracle database like `xe` for instance.

Regards!
