### ISSUE TITLE
Wrong user ID when inserting task in Intermediate Task List tutorial in laravel

### ISSUE THREAD

**Issue by jmchanchong** [yajra/laravel-oci8#150]
I have a user who have a id of 1 in the table USERS.
When I log in with this user, in my view, {{ Auth::user()->id }} is 1.

But when I add the task, the user_id is 4294967297. 

When I try with MYSQL, the id is OK. 

Is there a bug or I have forgotten something ?

**Comment by yajra** [comment]
I just tested the final output code of the tutorial at [github](https://github.com/laravel/quickstart-intermediate) and everything is working fine. Please double check your code. Thanks!
