### ISSUE TITLE
disable foreign key constraints

### ISSUE THREAD

**Issue by mshs013** [yajra/laravel-oci8#151]
How to disable all foreign key in oracle? like `DB::statement('SET FOREIGN_KEY_CHECKS = 0');` Please help.

**Comment by yajra** [comment]
The correct syntax to [enable/disable oracle constraint](http://www.dba-oracle.com/t_enabling_disabling_constraints.htm) is:
```sql
alter table
   table_name
ENABLE constraint
   constraint_name;

alter table
   table_name
DISABLE constraint
   constraint_name;
```

You can use statement to execute it just like on your example.

**Comment by mshs013** [comment]
Is there any option to enable/disable all constraint on a single command. I want to use this on `db:seeder`

**Comment by yajra** [comment]
The same link above have suggestion on how to disable the constraints but you will need a procedure for it.
