### ISSUE TITLE
No connection with laravel 

### ISSUE THREAD

**Issue by javaoui** [yajra/laravel-oci8#159]
hello everybody  
have you idea to laravel oracle cause i installe https://github.com/yajra/laravel-oci8/wiki  
but i cant how to do  
thanks for helping please 

InvalidArgumentException in DatabaseManager.php line 238:
Database [toto] not configured.

**Comment by yajra** [comment]
Where you able to register the package service provider `Yajra\Oci8\Oci8ServiceProvider::class`? See installation wiki for details. https://github.com/yajra/laravel-oci8/wiki/Installation

**Comment by yajra** [comment]
Registering the provider should fix your issue. Thanks!
