### ISSUE TITLE
Datatype NVARCHAR2 support?

### ISSUE THREAD

**Issue by pawel-damasiewicz** [yajra/laravel-oci8#162]
Does this package provide api for Laravel migrations to create column with datatype NVARCHAR2?

**Comment by yajra** [comment]
@pawel-damasiewicz unfortunately, nvarchar2 is not yet supported by the package. But we are open to PR if you can do it. Will label this for enhancement. Thanks!

**Comment by yajra** [comment]
@pawel-damasiewicz thanks for PR. Merged and released on both version 5.1.1 and 5.2.5 💯
