### ISSUE TITLE
where() no found by char values come with spaces (completed to full lenght)

### ISSUE THREAD

**Issue by gustperz** [yajra/laravel-oci8#165]
I'm working on a bd oracle of only consult, and absolutely all the columns in the tables are char type, queries do not found, because the parameters that step will not have the spaces placed oracle at the end.
therefore relationships do not work

these are my models

```
use Yajra\Oci8\Eloquent\OracleEloquent as Model;

class Empleado extends Model
{

    protected $connection = 'oracle';
    protected $table = 'empleados';
    protected $primaryKey = 'codigo';
    public $incrementing = false;
    public $timestamps = false;

    protected $visible = ['codigo', 'apellido1', 'apellido2', 'nombres', 'estado'];

    public function contratos()
    {
        return $this->hasMany(Contrato::class, 'id_terc', 'codigo');
    }
}
```
```
use Yajra\Oci8\Eloquent\OracleEloquent as Model;

class Contrato extends Model
{
    
    protected $connection = 'oracle';
    protected $table = 'contratos';
    protected $primaryKey = 'codigo';
    public $incrementing = false;
    public $timestamps = false;

    protected $visible = [
        'codigo',
        'salario',
        'fecha_ingreso'
    ];
}
```

`Empleado::all()` this found and return data, sql generated `select * from terceros;`
`Empleado::find('1003266086')` not return data, sql generated `select * from (select * from terceros where terceros.codigo = '1003266086') where rownum = 1;`
and to go for with Empleado::all()
`$empleado->contratos` generared `select * from contratos where contratos.id_terc = '1003266086   ' and contratos.id_terc is not null;` but does not return anything because the fk column in the table contratos is char (15),  while in the table empleados is char(13)

How I can fix this?, because when you run the statements directly with oci8 functions these work

sorry for my english I speak spanish

**Comment by yajra** [comment]
Given your table structure where char is used as keys, I think you have to override the default Laravel model function like `find` and add some space padding on the value before searching. As you described, contratos is char(15) and empleados is char(13) which basically does not match.
