### ISSUE TITLE
ORA-01722: Invalid Number.

### ISSUE THREAD

**Issue by yuki104** [yajra/laravel-oci8#166]
Error occurs when that contains the alphabet in EMPLOYEE_NO.

Environment

<pre>
PHP 5.4.45
Laravel 5.0.33
yajra/laravel-oci8 2.4.5
Oracle 11g Release 11.1.0.7.0 
</pre>

Schema

<pre>
CREATE TABLE "EXAMPLE"."TEMPORARY" 
(
  "EMPLOYEE_NO" VARCHAR2(10) NOT NULL ENABLE, 
  "DEDUCTION_CODE" VARCHAR2(1) NOT NULL ENABLE, 
  "PAYROLL_DEDUCTION" NUMBER(10,0) NOT NULL ENABLE, 
  "BONUS_DEDUCTION" NUMBER(10,0) NOT NULL ENABLE, 
  "CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
  CONSTRAINT "TEMPORARY_PK" PRIMARY KEY ("EMPLOYEE_NO", "CREATED_AT")
)
</pre>

Source Code

<pre>
$temporary = new Temporary();
$temporary->employee_no = 'A00001';
$temporary->deduction_code = '0';
$temporary->payroll_deduction = 30000;
$temporary->bonus_deduction = 100000;
$temporary->created_at = '2016-4-28 16:00:00';
$temporary->save();
</pre>

Error Log

<pre>
[2016-04-28 13:49:55] local.ERROR: exception 'yajra\Pdo\Oci8\Exceptions\Oci8Exception' with message 'Error Code    : 1722
Error Message : ORA-01722: Invalid Number.
Position      : 189
Statement     : insert into temporary (employee_no, deduction_code, payroll_deduction, bonus_deduction, created_at) values (:autoparam0, :autoparam1, :autoparam2, :autoparam3, :autoparam4) returning employee_no into :autoparam5
Bindings      : []
' in C:\xampp\htdocs\example\vendor\yajra\laravel-pdo-via-oci8\src\yajra\Pdo\Oci8\Statement.php:160
Stack trace:
#0 C:\xampp\htdocs\example\vendor\yajra\laravel-oci8\src\yajra\Oci8\Query\Processors\OracleProcessor.php(42): yajra\Pdo\Oci8\Statement->execute()
#1 C:\xampp\htdocs\example\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1725): yajra\Oci8\Query\Processors\OracleProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into exa...', Array, 'employee_no')
#2 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'employee_no')
#3 C:\xampp\htdocs\example\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(933): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\example\vendor\compiled.php(10095): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#5 C:\xampp\htdocs\example\vendor\compiled.php(10095): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'employee_no')
#6 C:\xampp\htdocs\example\vendor\compiled.php(10085): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#7 C:\xampp\htdocs\example\vendor\compiled.php(10042): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 C:\xampp\htdocs\example\app\Http\Controllers\Admin\ImportController.php(107): Illuminate\Database\Eloquent\Model->save()
#9 [internal function]: App\Http\Controllers\Admin\ImportController->postImport(Object(App\Http\Requests\Import\Import1Request))
#10 C:\xampp\htdocs\example\vendor\compiled.php(8558): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\example\vendor\compiled.php(8626): Illuminate\Routing\Controller->callAction('postImport', Array)
#12 C:\xampp\htdocs\example\vendor\compiled.php(8605): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Admin\ImportController), Object(Illuminate\Routing\Route), 'postImport')
#13 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\example\vendor\compiled.php(9244): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\example\vendor\compiled.php(9227): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\example\vendor\compiled.php(8606): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 C:\xampp\htdocs\example\vendor\compiled.php(8592): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Admin\ImportController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postImport')
#19 C:\xampp\htdocs\example\vendor\compiled.php(7583): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'postImport')
#20 C:\xampp\htdocs\example\vendor\compiled.php(7554): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\example\vendor\compiled.php(7219): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\example\vendor\compiled.php(9244): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\example\vendor\compiled.php(9227): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\example\vendor\compiled.php(7220): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 C:\xampp\htdocs\example\vendor\compiled.php(7209): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\example\vendor\compiled.php(7194): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\example\vendor\compiled.php(2040): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\example\vendor\compiled.php(9244): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\example\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 C:\xampp\htdocs\example\vendor\compiled.php(9236): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\xampp\htdocs\example\vendor\compiled.php(2548): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\xampp\htdocs\example\app\Http\Middleware\VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 C:\xampp\htdocs\example\vendor\compiled.php(9236): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\xampp\htdocs\example\vendor\compiled.php(12416): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\example\vendor\compiled.php(9236): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\xampp\htdocs\example\vendor\compiled.php(11106): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\xampp\htdocs\example\vendor\compiled.php(9236): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\example\vendor\compiled.php(12118): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\xampp\htdocs\example\vendor\compiled.php(9236): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 C:\xampp\htdocs\example\vendor\compiled.php(12066): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\xampp\htdocs\example\vendor\compiled.php(9236): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\xampp\htdocs\example\vendor\compiled.php(2589): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\xampp\htdocs\example\vendor\compiled.php(9236): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 C:\xampp\htdocs\example\vendor\compiled.php(9227): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\example\vendor\compiled.php(1996): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 C:\xampp\htdocs\example\vendor\compiled.php(1983): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#51 C:\xampp\htdocs\example\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#52 {main}
</pre>

**Comment by yajra** [comment]
How did you declare your model? I think you set employee_no as primary but did not set incrementing to false?

**Comment by yuki104** [comment]
Thank you for the reply.
Should I add the following code to Model?

<pre>
public $incrementing = false;
</pre>

Migration file

<pre>
class CreateTemporaryTable extends Migration {

    protected $table = 'temporary';

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create($this->table, function(Blueprint $table) {
            $table->string('employee_no', 10);
            $table->string('deduction_code', 1);
            $table->integer('payroll_deduction');
            $table->integer('bonus_deduction');
            $table->timestamp('created_at'); 
            $table->primary(['employee_no', 'created_at']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop($this->table);
    }

}
</pre>

Model

<pre>
class Temporary extends Model {

    protected $table = 'temporary';
    //protected $primaryKey = ['employee_no', 'created_at'];
    protected $primaryKey = 'employee_no';
    protected $fillable = [
        'employee_no',
        'deduction_code',
        'payroll_deduction',
        'bonus_deduction',
        'created_at'
    ];
    public $timestamps = false;

}
</pre>

**Comment by yajra** [comment]
Yes, you need to add `public $incrementing = false;` since your PK is a string.

**Comment by yuki104** [comment]
Thank you so much !
