### ISSUE TITLE
Persistent connection - pooling?

### ISSUE THREAD

**Issue by jurosh** [yajra/laravel-oci8#169]
Hello @yajra ,

is somehow possible to start connection as persistent like in docs http://php.net/manual/en/oci8.connection.php ?

I see that in parent project pdo-via-oci it's configured like with option PDO::ATTR_PERSISTENT but I cannot find in this project if it's used or not. And as I understand it's quite important to use persistent connection with oci_pconnect with oracle database.

Thanks

**Comment by yajra** [comment]
Just add this on your configuration file to use persistent connection:
```php
    'options'   => [
        PDO::ATTR_PERSISTENT => true,
    ],
```

**Comment by praveenreddy84** [comment]
You mean like this

'oracle' => [
        'driver'   => 'oracle',
        'tns'      => env('DB_TNS', ''),
        'host'     => env('DB_HOST', ''),
        'port'     => env('DB_PORT', '1521'),
        'database' => env('DB_DATABASE', ''),
        'username' => env('DB_USERNAME', ''),
        'password' => env('DB_PASSWORD', ''),
        'charset'  => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'   => env('DB_PREFIX', ''),
'options'   => [
        PDO::ATTR_PERSISTENT => true,
    ],
    ],

**Comment by jurosh** [comment]
Thanks guys, yes.

**Comment by yajra** [comment]
@praveenreddy84 YES, thanks for completing the config. I just realized that my answer is incomplete and a bit confusing.

**Comment by Sithcarlos** [comment]
@praveenreddy84  thanks very much
