### ISSUE TITLE
yajra\Pdo\Oci8 Not found

### ISSUE THREAD

**Issue by uqcgreen** [yajra/laravel-oci8#177]
Hi there,

I had problems with this error being thrown in the Oracle Connector using both the 1.x and 2.x branches of the code.

I changed yajra/Oci8/Connectors/OracleConnector.php line 6 to have an uppercase Yajra and it sprung to life.

**Comment by mstaack** [comment]
yes this is right. the namespaces change some time ago
https://github.com/yajra/laravel-oci8/blob/5.2/src/Oci8/Connectors/OracleConnector.php#L3
