### ISSUE TITLE
help with conection

### ISSUE THREAD

**Issue by migueltorio** [yajra/laravel-oci8#181]
im trying to switch to laravel with yajwa/laravel-oci, my actual conection settings are
	putenv ('ORACLE_HOME=/usr/lib/oracle/11.1.0.1/client');
	putenv ('TNS_ADMIN=/etc/oracle');
$conn = NewADOConnection("oci8"); 
 $host =' (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 10.111.111.98)(PORT = 1521)) 
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = dbdesa)
    )
  )
';
$conn->Connect($host, "user", "password");
$conn->Execute("SET NAMES 'utf8'"); 

i've tried this conf, but im still not able to do it

return [
    'oracle' => [
    'driver' => 'oracle',
    'host' => '10.111.111.98',
    'port' => '1521',
    'database' => 'dbdesa',
    'service_name' => 'dbdesa',
    'username' => 'username',
    'password' => 'password',
    'charset' => 'utf8',
    'prefix' => '',
    ]
];

im getting this error message
ORA-12705: Cannot access NLS data files or invalid environment specified

**Comment by migueltorio** [comment]
im getting this error message
ORA-12705: Cannot access NLS data files or invalid environment specified

**Comment by yajra** [comment]
ORA-12705 appears to be an environment issue. See this [SO](http://stackoverflow.com/questions/7700330/ora-12705-cannot-access-nls-data-files-or-invalid-environment) for possible fix.
