### ISSUE TITLE
Help with inserts

### ISSUE THREAD

**Issue by vitroz** [yajra/laravel-oci8#186]
Hello
I know there are some issues already opened on this subject, but unfortunatelly, i could not solve my issue.

Should I have a field on all my tables to hold the sequence, for auto increment?

what is all the setup you need to properly do inserts?

right now I have my model like this.

`class Consulta extends Model {

    /**
     * Generated
     */

    protected $table = 'consulta_db';
    protected $primaryKey = 'id_consulta';
    protected $fillable = ['nome', 'query'];

    public $timestamps = false;
    protected $incrementing = false;

       
}`

on my controller i have:

`    public function postCreateconsulta()
    {
        $request = Request::all();

        $consulta = $this->consultaRepository->create($request);`

But everytime I try to insert, i get

`RA-01400: cannot insert NULL into ("CNQ"."CONSULTA_DB"."ID_CONSULTA")
Position : 0
Statement : insert into consulta_db (nome, query) values (:p0, :p1) returning id_consulta into :p2
Bindings : [Atendimentos,select * from lis.atendimentos,0]`

any ideas, on what might be causing this?

**Comment by yajra** [comment]
Since your id is not incrementing, you need to manually set it's value just like the error states. 

If you have a sequence for that table, try adding:
```php
public $sequence = 'your_id_seq';
protected $incrementing = true;
```

**Comment by vitroz** [comment]
Hi yajra, thanks for the help.

I tried doing that, but I am still getting cannot insert NULL, by the way, eloquent only accepted my variable incrementing if its visibity was set to public.

right now, my model is written like this:

`    protected $table = 'consulta_db';
    protected $primaryKey = 'id_consulta';
    protected $fillable = ['nome', 'query'];

    public $sequence = 'sq_consulta_db';
    public $incrementing = true;


    public $timestamps = false;`

Should I be doing something else when I am inserting on the DB?

**Comment by chrislandeza** [comment]
@vitroz -  Either 'nome' or 'query' attribute is empty (or they're not present in the request).
If any of your column isn't  really required, you have to make them nullable()

On your migration script:
    $table->string('nome')->nullable();
    $table->string('query')->nullable();

**Comment by vitroz** [comment]
Thanks for the help @chrislandeza, but they were being sent properly, I checked.

Anyway, I managed to solve the issue, by creating the migrations on laravel, and creating my database through it, somehow that solved it for me.
