### ISSUE TITLE
Executing Procedures

### ISSUE THREAD

**Issue by mstaack** [yajra/laravel-oci8#187]
I have  a little Issue:

given a migration like (https://github.com/yajra/laravel-oci8/wiki/Oracle-Procedure):
```
$command = "
CREATE OR REPLACE PROCEDURE demoproc(p1 IN NUMBER, p2 OUT NUMBER) AS
BEGIN
p2 := p1 * 2;
END;
";

DB::connection()->getPdo()->exec($command);
```

i can use:
```
$pdo = DB::getPdo();
$p1 = 8;

$query = $pdo->prepare("begin demoproc(:p1, :p2); end;");
$query->bindParam(':p1', $p1, PDO::PARAM_INT);
$query->bindParam(':p2', $p2, PDO::PARAM_INT);
$query->execute();
```
and $p2 is the result

but using
```
$result1 = DB::executeFunction('demoproc(:binding_1,:binding_n)', [':binding_1' => 8'], PDO::PARAM_INT)
```
is not really working....

i know the binding is wrong here... but how should it look?  binding_2 => $result2 ? then i dont need the other $result1
how would you call this procedure?

@Tylerian @yajra

**Comment by yajra** [comment]
@mstaack that procedure's structure is different than the way it was created for the function. So it will basically not work. On that example, `p2` was described as the result while using `executeFunction` will bind it on `:result` variable.

```php
$query = $this->getPdo()->prepare('begin :result := ' . $sql . '; end;');
```

**Comment by yajra** [comment]
In addition, I think you can only return values on stored proc via `OUT` parameter which means that `executeFunction` will definitely not work on SP.
