### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by rainying** [yajra/laravel-oci8#188]
I don't use the migrate . 
Is there provide related functions or change the code ? 

yajra/homestead-oracle is work

#php artisan make:auth
#php artisan migrate
 [Yajra\Pdo\Oci8\Exceptions\Oci8Exception]

**Comment by mstaack** [comment]
migrate works fine for me..

which version are u using?

**Comment by rainying** [comment]
5.2

**Comment by rainying** [comment]
my env

**Comment by marsimunic** [comment]
Hi, I have the same problem 
#php artisan migrate
[Symfony\Component\Debug\Exception\FatalErrorException]
Call to undefined function Yajra\Pdo\oci_connect()

but when I run the file route.php with the following example work properly
 
Route::get('/', function () {
    $data = DB::connection('oracle')->table('codigos')->take(1)->get();
    var_dump($data);
});

**Comment by mstaack** [comment]
@marsimunic add oci8 extension to your php.ini  for console!

**Comment by marsimunic** [comment]
Thanks mstaack, but it isn't working.
My php.ini 
extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
and phpinfo()
OCI8 Support 	                enabled
OCI8 DTrace Support 	disabled
OCI8 Version 	                 2.0.10
Revision 	                          $Id: f5a3ee1083d1ffa6adb5143efda6eafa210b8414 $
Oracle Run-time Client Library Version 	       12.1.0.2.0
Oracle Compile-time Instant Client Version 	12.1

**Comment by mstaack** [comment]
run `php -m`  does it list the oci8 extension?

**Comment by marsimunic** [comment]
yes, you have reason its only enabled for apache web.
