### ISSUE TITLE
Error with Laravel version 5.2.42

### ISSUE THREAD

**Issue by ValentinBregeon** [yajra/laravel-oci8#194]
Hi @yajra ,

I have a mistake with the new version of Laravel.

I did a `composer update` this command update laravel from 5.2.41 to 5.2.42 and when i refresh my app, I have this error : 

> Argument 3 passed to Yajra\Pdo\Oci8\Statement::setFetchMode() must be of the type array, null given, called in D:\DATA\IIS\ADLDAP2\vendor\yajra\laravel-pdo-via-oci8\src\Pdo\Oci8\Statement.php on line 563 and defined (SQL: SELECT * FROM MY_TABLE) ....

Before this update all my app works fine. I really don't understand where the problem is.

Need help please :)

(Sorry for my english)

**Comment by mstaack** [comment]
will be fixed soon:
https://github.com/yajra/pdo-via-oci8/pull/36

**Comment by ValentinBregeon** [comment]
All right, Thx !

**Comment by ramadani** [comment]
Hi @mstaack, can you merge it as soon as posible, because that PR is still open. thank you

(sorry for my english)

**Comment by yajra** [comment]
pdo-via-oci8 v1.1.1 released that should fix this issue. Thanks for reporting!
