### ISSUE TITLE
DBLINK Relationship Many to Many Table A to DBLINK B

### ISSUE THREAD

**Issue by arredgroup** [yajra/laravel-oci8#196]
I have two models

    class PlanMejora extends Eloquent{

        protected $table = "ULA_SPM_PLAN_MEJORA";
        protected $primaryKey = "id_plan_mejora";
        public $sequence = "ULA_SPM_PLAN_MEJORA_SEQ";
        public $timestamps = false;
        public $incrementing = true;
        public function carreras(){
            return $this->belongsToMany('App\Carrera','ULA_SPM_PLAN_CARRERA','id_plan_mejora','carr_cod');
    }

and

    class Carrera extends Eloquent{

    protected $table = "carr@idelfos";
    protected $primaryKey = "carr_cod";
    public $timestamps = false;
    public $incrementing = false;
    public function planes(){
        return $this->belongsToMany('App\PlanMejora','ULA_SPM_PLAN_CARRERA', 'carr_cod','id_plan_mejora');
    }

When I try to list all carreras of PlanMejora, appear this error:

 ErrorException in Connection.php line 729:
Error Code : 2084
Error Message : ORA-02084: database name is missing a component
Position : 12
Statement : select carr@idelfos.*, ULA_SPM_PLAN_CARRERA.id_plan_mejora as pivot_id_plan_mejora, ULA_SPM_PLAN_CARRERA.carr_cod as pivot_carr_cod from carr@idelfos inner join ULA_SPM_PLAN_CARRERA on carr@idelfos.carr_cod = ULA_SPM_PLAN_CARRERA.carr_cod where ULA_SPM_PLAN_CARRERA.id_plan_mejora = :p0
Bindings : [3,3]
(SQL: select carr@idelfos.*, ULA_SPM_PLAN_CARRERA.id_plan_mejora as pivot_id_plan_mejora, ULA_SPM_PLAN_CARRERA.carr_cod as pivot_carr_cod from carr@idelfos inner join ULA_SPM_PLAN_CARRERA on carr@idelfos.carr_cod = ULA_SPM_PLAN_CARRERA.carr_cod where ULA_SPM_PLAN_CARRERA.id_plan_mejora = 3) (View: /Users/carredon/Sites/SPM/local/resources/views/administracion/planes.blade.php)

the problem is `carr@idelfos.* and carr@idelfos.carr_cod`

but when I try to add a new carrera to PlanMejora works

please help me!!! Thanks

**Comment by yajra** [comment]
@arredgroup I am not using database link on my projects yet so debugging this might took longer. If you can, please do not hesitate to submit a PR for a possible fix. Thanks!

**Comment by arredgroup** [comment]
I'm sorry, I fixed this issue creating a Synonym in database

Thanks!

**Comment by yajra** [comment]
@arredgroup good point. Synonym would definitely help! Thanks for pointing it out!
