### ISSUE TITLE
Unsupported driver [oracle]

### ISSUE THREAD

**Issue by dheersudheer** [yajra/laravel-oci8#198]
Hi , I'm working with lumen and database is oracle , I have configured yajra/lravel-oci8. I'm getting following error 
Unsupported driver [oracle]
Please help me to resolve this

**Comment by mstaack** [comment]
did u add the serviceprovider?

**Comment by dheersudheer** [comment]
You mean  adding ' Yajra\Oci8\Oci8ServiceProvider::class;' ? . I did it in bootstrap/app.php.  In lumen there is no configuration/app.php.

**Comment by mstaack** [comment]
add this to yout database.php config:

```
        'oracle' => [
            'driver'        => 'oracle',
            'tns'           => env('DB_TNS', ''),
            'host'          => env('DB_HOST', ''),
            'port'          => env('DB_PORT', '1521'),
            'database'      => env('DB_DATABASE', ''),
            'service_name'  => env('DB_SERVICE_NAME', ''),
            'username'      => env('DB_USERNAME', ''),
            'password'      => env('DB_PASSWORD', ''),
            'charset'       => env('DB_CHARSET', 'AL32UTF8'),
            'prefix'        => env('DB_PREFIX', ''),
            'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
        ],
```

**Comment by dheersudheer** [comment]
I already added this

**Comment by mstaack** [comment]
there must be an config/app.php  in lumen...
i added the provider  like this in AppServiceProvider:

```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //core services
        $this->app->register(\Yajra\Oci8\Oci8ServiceProvider::class);
```

**Comment by mstaack** [comment]
also make sure u are using latest versions of lumen & laravel-coi8

**Comment by dheersudheer** [comment]
Thanks  it is working

**Comment by rizdian** [comment]
Still Unsupported driver [oracle].

i use lumen 5.4 , and i've to write 

$this->app->register(\Yajra\Oci8\Oci8ServiceProvider::class);

in app\Providers\AppServiceProvider.php

**Comment by alissonalberini** [comment]
Olá pessoal, recentemente, me deparei com este erro em um dos nossos servidores de produção. 
Logo de imediato, foram revisados as configurações, e estavam de acordo como sempre foram.

Resolvido adicionando em config/app.php (mesmo sendo opcional segundo a doc para v5+).

Yajra\Oci8\Oci8ServiceProvider::class,
