### ISSUE TITLE
Error when using CLOB field

### ISSUE THREAD

**Issue by jacklyh** [yajra/laravel-oci8#203]
### Summary of problem or feature request

It happen with the table with CLOB field

Error Message : ORA-00932: inconsistent datatypes: expected CLOB got BLOB

The insert statement use EMPTY_BLOB() on binary field.

**Comment by yajra** [comment]
Can you please paste your code? The package considers CLOB as a string. There is no need for EMPTY_BLOB() when saving it.

**Comment by rajkumarsakthi** [comment]
@yajra 

I am using table with CLOB field in my project and I got error so could you please help me.

Couldn't find constant PDO::PARAM_CLOB

**Comment by vplanas** [comment]
Same problem here. ORA-00932: inconsistent datatypes: expected CLOB got BLOB.
When I try to insert or update a model using eloquent, with a CLOB column it throws this messages.

`Route::get('test', function() {
  $ticket = new App\ticket; // or App\ticket::find(407027) ;
  //$ticket->descticket= '##';
  $ticket->idhardware=39574;
  $ticket->description='Hola!'; // This is is a CLOB column in the table `tickets`
  $ticket->save();
});`

**Comment by vplanas** [comment]
Ok... I found the soultion. 
In the model class i was defining description as a binary...

<?php

namespace App;

use Yajra\Oci8\Eloquent\OracleEloquent as Eloquent;

```
class Ticket extends Eloquent {
   // define binary/blob fields
   //**protected $binaries = ['description'];** <- Here was the error

  protected $table = 'TICKETS';
  public $timestamps = false;
  public $primaryKey = 'idticket';
}
```

**Comment by ChaosPower** [comment]
Please open a new issue if there's more. Thanks for sharing! Closing this issue.
