### ISSUE TITLE
Call to undefined function Yajra\Pdo\oci_connect()

### ISSUE THREAD

**Issue by dheersudheer** [yajra/laravel-oci8#204]
I'm using  AMPPS in windows , when I connect to oracle  then I'm getting this error . 
Enabled php_oci8_12c.dll , php_pdo_oci.dll
  
- Operating System : windows
- PHP Version: 7.0.6
- Laravel Version :5.2
-Databse :oracle

**Comment by yajra** [comment]
Can you try running `php -m | grep oci8` to check if the extension is loaded? This a php oci8 extension configuration/installation issue. Try searching some closed issue like this for possible solutions.
