### ISSUE TITLE
Column name is a reserved oracle word

### ISSUE THREAD

**Issue by pedrofsantoscom** [yajra/laravel-oci8#205]
### Summary of problem or feature request

Creating a query where the column name is the reserved keyword "password", turns into and exception. Is there any way to escape the column name, besides bypassing this problem removing the "PASSWORD" keyword from the OracleReservedWords file?
Note: I can't rename the table column name as it's a database from another project.

### Code snippet of problem

```php
User::where("password", "dont_tell_anyone")->where("code_user", "user1")->get();

PHP warning:  oci_execute(): ORA-00904: "password": invalid identifier in ...\vendor\yajra\laravel-pdo-via-oci8\src\Pdo\Oci8\Statement.php on line 153
Illuminate\Database\QueryException with message 'Error Code    : 904
Error Message : ORA-00904: "password": invalid identifier
Position      : 26
Statement     : select * from users where "password" = :p0 and code_user = :p1
Bindings      : [dont_tell_anyone,dont_tell_anyone,user1,user1]
 (SQL: select * from users where "password" = dont_tell_anyone and code_user = user1)'
```

### System details

- Windows 10
- PHP 5.6.15
- Laravel 5.2

**Comment by yajra** [comment]
Try adding a double quote on your query like:

```php
User::where('"password"', "dont_tell_anyone")->where("code_user", "user1")->get();
```

This is to force the reserved word to be lowercase because the migration creates the column quoted.

**Comment by pedrofsantoscom** [comment]
I'm not using migration for the users table.
Fixed the problem refering the column as PASSWORD instead of all lower case. Are the column names case sensitive? Because all the column names on the database are capitalized, and I don't know if referencing the column name full capitalized, bypassed the reserved words or was because its the exact column name?

Anyway, thanks for the help.

**Comment by yajra** [comment]
@pedrofsantoscom Yes, for oracle, it is case sensitive when you use `"` when creating the columns and since the introduction of Oracle Reserved words, reserved columns and enclosed with double quote which causes this issue. Making it all caps would then fix your issue. Thanks!
