### ISSUE TITLE
how can i setup oracle database in .env

### ISSUE THREAD

**Issue by kaysus** [yajra/laravel-oci8#206]
please help me!!!!

APP_ENV=local
APP_KEY=base64:b5CROcrVSFanQDn7AB55O1ZI0djK6xHnOYmLZ7Zu/SI=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=

**Comment by kaysus** [comment]
i am using laravel 5.3

**Comment by yajra** [comment]
Example env you can use:

```php
DB_CONNECTION=oracle
DB_HOST=127.0.0.1
DB_PORT=1521
DB_DATABASE=xe
DB_USERNAME=homestead
DB_PASSWORD=secret
```

**Comment by kaysus** [comment]
i have already this error :(
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined function Yajra\Pdo\oci_connect( )


my oracle.php file:

<?php

return [
    'oracle' => [
        'driver'        => 'oracle',
        'tns'           => env('DB_TNS', 'salima'),
        'host'          => env('DB_HOST', '172.16.0.16'),
        'port'          => env('DB_PORT', '1521'),
        'database'      => env('DB_DATABASE', 'salima'),
        'username'      => env('DB_USERNAME', 'TEST'),
        'password'      => env('DB_PASSWORD', 'TEST'),
        'charset'       => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'        => env('DB_PREFIX', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
    ],
];



my .env file :+1: 


APP_ENV=local
APP_DEBUG=true
APP_KEY=base64:+wgXCOFwVBlHUJCU3Hxi518odYFRjWpP0PMUFTDJW0k=
APP_URL=http://localhost

DB_CONNECTION=oracle
DB_HOST=172.16.0.16
DB_PORT=1521
DB_DATABASE=salima
DB_USERNAME=TEST
DB_PASSWORD=TEST

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null


database.php file:

 'default' => env('DB_CONNECTION', 'oracle'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
        ],

        'oracle' => [
            'driver' => 'oracle',
            'host' => env('DB_HOST', '172.16.0.16'),
            'port' => env('DB_PORT', '1521'),
            'database' => env('DB_DATABASE', 'salima'),
            'username' => env('DB_USERNAME', 'TEST'),
            'password' => env('DB_PASSWORD', 'TEST'),
            'charset' => 'AL32UTF8',
            'prefix' => '',
            'schema' => 'public',
        ],

    ],

    /*

**Comment by yajra** [comment]
@kaysus are you getting this error on terminal or in the browser? Make sure you have oci8 extension enabled on your php.ini for both CLI and FPM.

**Comment by yajra** [comment]
@kaysus here are some [duplicate issues](https://github.com/yajra/laravel-oci8/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20Call%20to%20undefined%20function%20Yajra%5CPdo%5Coci_connect(%20)) that you can use as ref to fix your issue.

**Comment by kaysus** [comment]
Good morning,
this problem is shown in the terminal. the oci8 extension is enabled on my php.ini
the problem is still 
 -----
Cordialement,
Kais Chaabane  

    Le Samedi 14 janvier 2017 2h44, Arjay Angeles <notifications@github.com> a écrit :
 

 @kaysus are you getting this error on terminal or in the browser? Make sure you have oci8 extension enabled on your php.ini for both CLI and FPM.—

**Comment by adrianjimz** [comment]
Is it solved?
