### ISSUE TITLE
Oracle Procedure

### ISSUE THREAD

**Issue by mmteyrek** [yajra/laravel-oci8#208]
### Summary of problem or feature request
Getting Error when trying to launch a stored procedure

following the wiki I'm using this synthax to execture my stored procedure :+1: 
           	$procedureName = 'oracle_package.procedure_name';
                	$bindings = ['var'  => $var];
                	$result = DB::executeProcedure($procedureName, $bindings);
### Code snippet of problem
call_user_func_array() expects parameter 1 to be a valid callback, class 'Yajra\Oci8\Oci8Connection' does not have a method 'executeProcedure'

**Comment by yajra** [comment]
@mmteyrek what version are you using? executeProcedure is only available for `Laravel 5.3` atm.
ping @mstaack, maybe we can also implement it on lower version?

**Comment by mmteyrek** [comment]
Thank you for you answer.
Actually I moved to laravel 5.3 yesterday, but now I'm facing this error message :+1: 

Oci8Exception in Statement.php line 177:
Error Code : 6550
Error Message : ORA-06550: Ligne 1, colonne 7 :
PLS-00306: wrong number or types of arguments in call to 'CONTEXTID_OPEN'
ORA-06550: Ligne 1, colonne 7 :
PL/SQL: Statement ignored
Position : 6
Statement : begin pack_context.contextid_open(:v_context_id, :cursor); end;
Bindings : [92031,Resource id #307]

The point is that I dont understand why I'm getting the parameter " :cursor"??

**Comment by mmteyrek** [comment]
when I use this following synthax, every thing is OK :+1: 

                    $pdo = DB::getPdo();
                    $procedureName = ' begin pack_context.contextid_open('.$context_id.'); end;';
                    $stmt = $pdo->prepare($procedureName);
                    $stmt->execute();

**Comment by yajra** [comment]
`executeProcedure` was specifically designed for procedures that have a cursor output but may also work with other data types. However, I think your procedure does not have any return values so I guess it's better to use raw pdo call like on your snippet.

**Comment by mstaack** [comment]
@yajra will pr next week
