### ISSUE TITLE
 Error two tables related

### ISSUE THREAD

**Issue by ffigueroa2803** [yajra/laravel-oci8#209]
Failed to list my products

![1](https://cloud.githubusercontent.com/assets/5760999/18647313/007f3faa-7e7b-11e6-9712-8e5ff3dbcadc.png)
![2](https://cloud.githubusercontent.com/assets/5760999/18647318/02afbf20-7e7b-11e6-9300-ce6c8234f6c7.png)
![3](https://cloud.githubusercontent.com/assets/5760999/18647319/04718398-7e7b-11e6-81f4-a03a470bda58.png)
![4](https://cloud.githubusercontent.com/assets/5760999/18647321/05e38e10-7e7b-11e6-8a12-0db27f1bb921.png)

![5](https://cloud.githubusercontent.com/assets/5760999/18647391/6168e6cc-7e7b-11e6-82e5-5bba9967d2e6.png)

**Comment by yajra** [comment]
@ffigueroa2803 there is a typo on your Product model. The error is on php level and not on the package.

```php
s<?php
```

**Comment by ffigueroa2803** [comment]
thank you Sorry!

**Comment by yajra** [comment]
welcome 👍
