### ISSUE TITLE
 oci8 for support oracle 12c AND issue of offset and limit order

### ISSUE THREAD

**Issue by hamedmohammadi** [yajra/laravel-oci8#21]
first :oracle 12c support
     i edited your package for support offset and limit support for pagination and other stuffs 
and the way that package query for this 2 function if you wonder i will give it to you

second:
    i edited the order of offset and limit in the array in order to compile the offset before limit

**Comment by yajra** [comment]
I think this is not highly needed and I may not be able to work on this because I don't use 12c atm. But open to PR's in case someone wants to implement this. Thanks!
