### ISSUE TITLE
Laravel 5.2 and Call to undefined function Yajra\Pdo\oci_connect()

### ISSUE THREAD

**Issue by BinSilva** [yajra/laravel-oci8#218]
Hello, after long search, still meeting. 
![image](https://cloud.githubusercontent.com/assets/10469144/19447595/e92fceb0-947c-11e6-8250-aa87c223a8e9.png)

My oci8 in apache
![image](https://cloud.githubusercontent.com/assets/10469144/19447648/2799741c-947d-11e6-919d-757ba3d30a71.png)

My result test connection
![image](https://cloud.githubusercontent.com/assets/10469144/19447673/4300c9e4-947d-11e6-8dc7-3f45111f72d2.png)

When run migrate command, error continue...

- Operating System: Linux 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64
- PHP Version: 5.5.9-1
- Laravel Version: 5.2.*

**Comment by yajra** [comment]
Do you have oci8 enabled on CLI? Try checking using `php -m | grep oci8`.

**Comment by BinSilva** [comment]
Hi, my solution for php -m | grep oci8
http://stackoverflow.com/questions/27774337/how-to-use-oracle-client-11-2-with-php-xampp-on-win7-x64

But, have new problem run php artisan migrate

PHP Warning:  Module 'oci8' already loaded in Unknown on line 0
Warning: Module 'oci8' already loaded in Unknown on line 0

  [Yajra\Pdo\Oci8\Exceptions\Oci8Exception]
  ORA-24315: tipo de atributo invßlido

**Comment by yajra** [comment]
I think it means that oci8 extension was added twice in you php.ini and/or in another ini file loaded by php. Double check you cli config and make sure it's not added multiple times.

**Comment by BinSilva** [comment]
Exactly, i'm use now:
;extension=php_oci8_11g.dll  ; Use with Oracle 11gR2 Instant Client
extension=php_oci8.dll

Working, solved
