### ISSUE TITLE
Call Oracle stored procedure with cursor 

### ISSUE THREAD

**Issue by janakapdj** [yajra/laravel-oci8#219]
I am trying to call simple oracle procedure with laravel 5.3 + yajra

create or replace PROCEDURE S_IN_GET_PRODUCT_TYPES ( PO_RESULTS OUT SYS_REFCURSOR )AS VAR_QUERY_STR VARCHAR2(30000); BEGIN VAR_QUERY_STR:='SELECT \* FROM CA_IN.T_IN_PRODUCT_TYPES'; OPEN PO_RESULTS FOR VAR_QUERY_STR; END;

php code

$results = DB::executeProcedure($query,$parameters); return $results;

but I am getting ORA-06553: PLS-306: wrong number or types of arguments in call to 'S_IN_GET_PRODUCT_TYPES' error does any one has idea how to sorted this

**Comment by mstaack** [comment]
looks like your arguments dont work out right....did you try to run it manually?

have a look how this works internally:
https://github.com/yajra/laravel-oci8/blob/5.3/src/Oci8/Oci8Connection.php#L252

**Comment by janakapdj** [comment]
thnx for reply mstaack

I pass only the procedure name and empty array for parameters and when I run the procedure manually its work fine

**Comment by mstaack** [comment]
@janakapdj i am in the progress of cleaning things out with executing procedure...

can you show me your exact call with params etc?

and please try this:

```

        $cursor = DB::executeProcedure('packagename.procedurename', [ ], null);

        $statement = new Statement($cursor, $pdo);
        $statement->execute();
        $result = $statement->fetchAll(PDO::FETCH_CLASS);
        $statement->closeCursor();

        dd($result);

```
