### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Leshgan** [yajra/laravel-oci8#221]
I am using laravel 5.3.19 in yajra/homestead-oracle

 composer require yajra/laravel-oci8:"5.1.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.3.19
    - Conclusion: don't install laravel/framework v5.3.19
    - yajra/laravel-oci8 v5.1.0 requires illuminate/database ~5.1.20 -> satisfiable by illuminate/database[v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41].
    - yajra/laravel-oci8 v5.1.1 requires illuminate/database ~5.1.20 -> satisfiable by illuminate/database[v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41].
    - yajra/laravel-oci8 v5.1.2 requires illuminate/database ~5.1.20 -> satisfiable by illuminate/database[v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41].
    - yajra/laravel-oci8 v5.1.3 requires illuminate/database ~5.1.20 -> satisfiable by illuminate/database[v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41].
    - don't install illuminate/database v5.1.20|don't install laravel/framework v5.3.19
    - don't install illuminate/database v5.1.22|don't install laravel/framework v5.3.19
    - don't install illuminate/database v5.1.25|don't install laravel/framework v5.3.19
    - don't install illuminate/database v5.1.28|don't install laravel/framework v5.3.19
    - don't install illuminate/database v5.1.30|don't install laravel/framework v5.3.19
    - don't install illuminate/database v5.1.31|don't install laravel/framework v5.3.19
    - don't install illuminate/database v5.1.41|don't install laravel/framework v5.3.19
    - Installation request for laravel/framework (locked at v5.3.19, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.19].
    - Installation request for yajra/laravel-oci8 5.1.* -> satisfiable by yajra/laravel-oci8[v5.1.0, v5.1.1, v5.1.2, v5.1.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by yajra** [comment]
You need to use `composer require yajra/laravel-oci8:"5.3.*"` since your are using 5.3.

**Comment by Leshgan** [comment]
@yajra thanks a lot!

**Comment by zender65** [comment]
Hi yajra i am experiencing   Problem 1
    - yajra/laravel-oci8 v5.5.3 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.Oci8 is installed and working >kindly assist
