### ISSUE TITLE
Yajra\Pdo\Oci8\Exceptions\Oci8Exception - ORA-22859: invalid modification of columns

### ISSUE THREAD

**Issue by robsonpsdesv** [yajra/laravel-oci8#222]
Hello, 

I'm in error when migrating:
![image](https://cloud.githubusercontent.com/assets/10469144/19569660/566c4f30-96d5-11e6-8402-c4fbdfc5b8ff.png)

The tables are created start and stop.

I'm using a CRUD generator
https://github.com/crocodic-studio/crudbooster

Operating System: Linux 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64
PHP Version: 5.5.9-1
Laravel Version: 5.2.*

**Comment by yajra** [comment]
@BinSilva does the generated query works when executed directly on sql developer/sql tool you are using? This might be an edge case and I suggest you use `DB::statement()` for the alter migration.

This [SO post](http://dba.stackexchange.com/questions/5948/how-to-replace-a-clob-column-by-a-varchar24000-column) might assist to fix the issue if manually executed.

**Comment by BinSilva** [comment]
I made the migration by using SQL Developer and is apparently working.
Only consultations are adding the Where clause everywhere.

QueryException in C:\xampp\htdocs\corporativo\vendor\laravel\framework\src\Illuminate\Database\Connection.php line 730:
Error Code : 936
Error Message : ORA-00936: missing expression
Position : 49
Statement : select count(*) as aggregate from cms_pages where
Bindings : []
(SQL: select count(*) as aggregate from cms_pages where)

**Comment by yajra** [comment]
Can you please paste some snippets to reproduce the issue?

**Comment by BinSilva** [comment]
In Connection.php
result print_r($query) in mysql => select * from `cms_moduls` where `controller` in (?, ?)
result print_r($query) in oracle => ALTER SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS = '.,'

protected function run($query, $bindings, Closure $callback)
    {
        print_r($query);
        exit;
        $this->reconnectIfMissingConnection();

        $start = microtime(true);

        // Here we will run this query. If an exception occurs we'll determine if it was
        // caused by a connection that has been lost. If that is the cause, we'll try
        // to re-establish connection and re-run the query with a fresh connection.
        try {
            $result = $this->runQueryCallback($query, $bindings, $callback);
        } catch (QueryException $e) {
            if ($this->transactions >= 1) {
                throw $e;
            }

            $result = $this->tryAgainIfCausedByLostConnection(
                $e, $query, $bindings, $callback
            );
        }

        // Once we have run the query we will calculate the time that it took to run and
        // then log the query, bindings, and execution time so we will report them on
        // the event that the developer needs them. We'll log time in milliseconds.
        $time = $this->getElapsedTime($start);

        $this->logQuery($query, $bindings, $time);

        return $result;
    }

after that runQueryCallback QueryException error
