### ISSUE TITLE
Connect oracle with service_name

### ISSUE THREAD

**Issue by 1012403** [yajra/laravel-oci8#225]
Sorry if it is duplicated.
I try to connect to oracle database and get some error:
![image](https://cloud.githubusercontent.com/assets/3765142/19958510/6cacdd7a-a1d2-11e6-9d35-3b848c542adb.png)

and this is my tns string: 
ORC_DB_TEST =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ORC_DB_TEST)
    )
  )
how can I connect with "SERVICE_NAME" instead of "SID"?
Thank so much.

**Comment by yajra** [comment]
@1012403 see this [wiki](https://github.com/yajra/laravel-oci8/wiki/Installation) for possible configuration.

> If your database uses SERVICE NAME alias, use the config below:
```php
'oracle' => [
    'driver' => 'oracle',
    'host' => 'oracle.host',
    'port' => '1521',
    'database' => 'xe',
    'service_name' => 'sid_alias',
    'username' => 'hr',
    'password' => 'hr',
    'charset' => '',
    'prefix' => '',
]
```

**Comment by 1012403** [comment]
Thank so much. I solved it.

**Comment by elton182** [comment]
This should be added to the readme.md, I'll send a PR
