### ISSUE TITLE
Cannot connect to oracle 10g but success with oracle 11g.

### ISSUE THREAD

**Issue by faaazma** [yajra/laravel-oci8#230]
### Summary of problem or feature request
I have a Laravel application which use yajra laravel-oci8 and working fine connecting oracle 11g server.
However I got error when connecting to oracle 10g server.
The error that i got is 
Yajra \ Pdo \ Oci8 \ Exceptions \ Oci8Exception

**ORA-12505: TNS:listener does not currently know of SID given in connect descriptor**

I can connect to both database using Oracle SQL Developer.  
Both server had the same schema. So i just change the connection detail according to the successful setting in Oracle SQL Developer.

Thanks.

### System details

- Operating System
- PHP Version 5.5.6
- Laravel Version 5.1 
- Laravel-OCI8 Version 2.0

**Comment by yajra** [comment]
@faaazma there were cases where SID is case sensitive. Can you try doing an all caps SID on your config file?
