### ISSUE TITLE
Oci8Connection::executeProcedure is a silly implementation

### ISSUE THREAD

**Issue by jjware** [yajra/laravel-oci8#234]
### Summary of problem or feature request

The only time that the Oci8Connection::executeProcedure method is usable, is when your stored procedure is defined to output a cursor as the last parameter. It is very common to not output a cursor from your stored procedure at all.

Perhaps it is just the name of the method that is throwing me here. I had a developer on my team that was very confused about an error he was getting when using this method for the first time. He (perhaps wrongfully) assumed that the method would be able to handle any kind of procedure, as the name does not indicate that you are forced to have a cursor out parameter defined in your procedure when utilizing it.

Since this is just basically a shortcut method that only works for a very specific instance, does it really belong in this library at all?

**Comment by mstaack** [comment]
Yes your right...let's fix this so it handles all kinds of procedure calls

**Comment by yajra** [comment]
Yes, I agree that we should fix this. It was attempted to handle all procedure calls but it seems like it needs some fix. Please do not hesitate to submit a PR for possible enhancement/fix. Thanks!

**Comment by sonu1** [comment]
What is the work around this if we have 2 input and 1 out. I am getting a ORA-06502 PL/SQL: numeric or value error

**Comment by jjware** [comment]
@sonu1 the problem that you are experiencing is most likely a conflict between the type that your procedure is expecting, and the value that you are providing for one of the inputs.

**Comment by mstaack** [comment]
i am in the process of refactoring non normal sql calls like procedures and functions

trying to handle all types of return and input values...

but for nwo its still WIP

see https://github.com/yajra/laravel-oci8/blob/execute-procedure/tests/Functional/ProceduresTest.php
and https://github.com/yajra/laravel-oci8/blob/execute-procedure/src/Oci8/Oci8Connection.php#L263

will let you know when its done
