### ISSUE TITLE
WhereDate Compare Issue

### ISSUE THREAD

**Issue by Jobinjose01** [yajra/laravel-oci8#235]
### Summary of problem or feature request
Hello,

first of all thanks for the great package, 
I have some issue with date compare ,I trying to fetch the count of rows from a table current date. but the query **return 0** and when I wrote the same query in Oracle Developer its works correctly any idea ?
In DB the date is stored like 28-12-16 11:38:52.000000000 AM

### Code snippet of problem

``` 
echo $count = \DB::table('apprisal_entries')
                    ->Where('user_id',24)
                    ->Where('parameter_id',1)
                    ->WhereDate('created_at',"=",date('d-m-y'))
                    //->Where(\DB::raw('trunc(created_at)'),'28-12-16')
                    ->count();
```

### System details

- Operating System
- PHP Version 5.6
- Laravel Version 5.3
- Laravel-OCI8 Version 5.3

**Comment by yajra** [comment]
@Jobinjose01, the package sets the NLS Session date format to `YYYY-MM-DD HH24:MI:SS` and thus you need follow this format or use a `Carbon` instance for the date values.

```php
echo $count = \DB::table('apprisal_entries')
                    ->Where('user_id',24)
                    ->Where('parameter_id',1)
                    ->WhereDate('created_at',"=",date('Y-m-d'))
                    //->Where(\DB::raw('trunc(created_at)'),'2016-12-28')
                    ->count();
```
