### ISSUE TITLE
CRUD Laravel with oracle database

### ISSUE THREAD

**Issue by mfhujaeri** [yajra/laravel-oci8#236]
hi all,
I'm trying to develop an application using php framework laravel and oracle database, but I find it difficult to try to insert into table with oracle database. when I tried to connect her that all went well, but I have not found a way to CRUD laravel with oracle database. does anyone have to do?

- Operating System
- PHP 5.6.28
- Laravel 5.3
- Laravel-OCI8 Version

**Comment by yajra** [comment]
@mfhujaeri crud with oracle should work the same with how you do it on mysql and other db supported by Laravel. I think there are fee tutorials at [laracasts](laracasts.com).
