### ISSUE TITLE
 Why there are "" (double quote) wrap around column identifier?

### ISSUE THREAD

**Issue by phatchai** [yajra/laravel-oci8#237]
When I write an eloquent model like this:

```php
$this->first_login = strtotime('now');
$this->user_type = $person['type'];
$this->degree = substr($this->username, 0, 2) == 'gs' ? 'grad' : 'undergrad';
...
```

I got this error message:

```
QueryException in Connection.php line 770:
Error Code : 904
Error Message : ORA-00904: "degree": invalid identifier
Position : 81
Statement : update "CLIENTS" set "LAST_LOGIN" = :p0, "FIRST_LOGIN" = :p1, "USER_TYPE" = :p2, "degree" = :p3, "OS" = :p4 where "USERNAME" = :p5
Bindings : [2017-01-04 02:18:35,2017-01-04 02:18:35,student,undergrad,iOS,ns581010109]
(SQL: update "CLIENTS" set "LAST_LOGIN" = 2017-01-04 02:18:35, "FIRST_LOGIN" = 2017-01-04 02:18:35, "USER_TYPE" = student, "degree" = undergrad, "OS" = iOS where "USERNAME" = ns581010109)
```

Why there are "" wrap around column identifier? I was using older version of this package and it was working fine. Now it introduce bugs in my code base. Please help.

**Comment by yajra** [comment]
@phatchai there was a recent update that adds this wrapper for security purposes. Did you migrate the tables using the package? It appears that "degree" is a reserved word and so the package converts it to lower case.

**Comment by yajra** [comment]
Changes are located on https://github.com/yajra/laravel-oci8/pull/223.

**Comment by phatchai** [comment]
I see I have to use `DB::raw()` for select, what about Insert and update.
How can I insert a table in Eloquent way? As you can see there is "" wrap in other columns too.

"first_login", "last_login", ...

Is there a work around this? 

thanks for replying.

**Comment by phatchai** [comment]
Ok, so I have to **UPPERCASE** the column name and table name on all of my eloquent fields and can't use a reserved word for column name right?

It seem to work now, do I miss something else? 
May you update your document to cover this point? I'm actually not that keen on Oracle other people may run into this issue as myself. thanks.
