### ISSUE TITLE
oracle & dotted table name

### ISSUE THREAD

**Issue by gpx75** [yajra/laravel-oci8#238]
### Summary of problem or feature request

Hi,
We are using some oracle tables with a dotted schema name and db link like this diaxgo.ma_stamm@pintra02

which produce the following exception:

Oci8Exception in Statement.php line 177: Error Code : 942
Error Message : ORA-00942: table or view does not exist
Position : 23
Statement : select * from "DIAXGO"."MA_STAMM@PINTRA02" where "DIAXGO"."MA_STAMM@PINTRA02"."MA_ID" in (:p0)
Bindings : [1425652]

I'm trying do do eloquent on existing table name and its not possible to change the table name 

### Code snippet of problem

`class maStamm extends Model
{
    protected $connection = "clarify";
    protected $table  = 'diaxgo.ma_stamm@pintra02';
    protected $primaryKey = "ma_id";
}`
### System details

laravel/homestead with 

PHP 7.0.14 (cli) (built: Dec  8 2016 23:34:17) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

**Comment by yajra** [comment]
I think the issue here is that you are using a DB link? Can you please try if the sql below is working? We might need to adjust the wrapper to handle DB link connections.

```sql
select * from "DIAXGO"."MA_STAMM"@"PINTRA02"
```

In addition, maybe try the solution suggested on this [issue](https://github.com/yajra/laravel-oci8/issues/196) too.

BTW, as per my understanding on the structure: 
`"DIAXGO"`  - refers to schema
`"MA_STAMM"` - refers to table
`@PINTRA02` - refers to DB link connection

**Comment by gianpix** [comment]
Hi 
The sql 
`select * from "DIAXGO"."MA_STAMM"@"PINTRA02"` 
works on sqldeveloper. 

but this is not working: ... this is the query produced by using the hasOne() relation manually adjusting as suggested in your sql aboth
`select * from "DIAXGO"."MA_STAMM"@"PINTRA02" where "DIAXGO"."MA_STAMM"@"PINTRA02"."ma_id" in (1425652)`

and the error is 
> ORA-04054: the database link 'PINTRA02.MA_ID' doesn't  exist

and this works on sqldeveloper... the produced sql should look like this  select * from "DIAXGO"."MA_STAMM"@"PINTRA02" where ma_id in (1425652)

Until im not using any relation like hasOne() it works by using  DB:raw within a construct in the model class 

The wrapper is messing also after the where clause and wrapping the column as a dblink 

> "DIAXGO"."MA_STAMM@PINTRA02"."MA_ID"

> 
> QueryException in Connection.php line 770: Error Code : 942
> Error Message : ORA-00942: table or view does not exist
> Position : 23
> Statement : select * from "DIAXGO"."MA_STAMM@PINTRA02" where "DIAXGO"."MA_STAMM@PINTRA02"."MA_ID" in (:p0)
> Bindings : [1425652]
> (SQL: select * from "DIAXGO"."MA_STAMM@PINTRA02" where "DIAXGO"."MA_STAMM@PINTRA02"."MA_ID" in (1425652))

This structure is correct:
"DIAXGO" - refers to schema
"MA_STAMM" - refers to table
@PINTRA02 - refers to DB link connection

about creating a synonym: 
unfortunately i haven't sufficient rights to create a synonym on the DB

thanks in advance
