### ISSUE TITLE
How can we do client_identification binding in YAJRA , for example below straight connection in yajra ?Thanks in advance. 

### ISSUE THREAD

**Issue by yogeshaneja** [yajra/laravel-oci8#239]
### Summary of problem or feature request

How can we do initialize oracle session variable set_identifier in YAJRA
For example converting below RAW intilazing , how to do the same in YAJRA ?
Thanks in advance. 

```php
$conn = oci_connect($db_username, $db_password , $tns);
$s = oci_parse($conn, "begin dbms_session.set_identifier(:id1); end;");
oci_bind_by_name($s, ":id1", $username);
oci_execute($s);
```

**Comment by yajra** [comment]
I think you can this on the PDO level. See this [doc](https://yajrabox.com/docs/laravel-oci8/master/function) for some ref on how a function was executed using pdo.

```php
$pdo = DB::getPdo();
$stmt = $pdo->prepare("begin dbms_session.set_identifier(:id1); end;");
$stmt->bindParam(':id1', $username);
$stmt->execute();
```

**Comment by yogeshaneja** [comment]
Hi Thanks , for the reply , above method works however i wanted to set identifier to audit username at database level. 
It works and keep username as identifier when i run query by db connection , 
but it does not keep username as identifier when query is run  at eloquent level by the model. 

For example : 
 Below query send the identifier ($username)
$affected = DB::update('update users set votes = 100 where name = ?', ['John']);

However , below update by model doesn't have $username as identifier : 
 $editUser->votes = $request->votes; \\100


Any suggestions, Thanks in advance.

**Comment by yajra** [comment]
Does the model connection instance differs from DB instance? 

Anyways, maybe try adding the statement above inside the boot method of your model. You can create a base model or use a trait so that you can reuse it. 

Another way I can think of is by using database event listener to set the client identifier?

**Comment by yogeshaneja** [comment]
Adding at boot method of base model worked , Thanks , Yajra :+1:
