### ISSUE TITLE
Question: can we use ->nocache() when creating sequence ?

### ISSUE THREAD

**Issue by h3ndro** [yajra/laravel-oci8#240]
### Summary of problem
Hi, currently i'm searching a way to reset my sequence. I know that we can use 
```php
$sequence->drop('seq_name');
$sequence->create('seq_name');
```
but the result is always  a sequence with cache.
From documentation we can use something like 
```php
Schema::create('posts', function($table)
{
    $table->increments('id')->start(10000)->nocache();
    $table->string('title');
}
```
but thats when we create migration
### Question
my, question is, can we use something like
```php
$sequence->create('seq_name')->nocache();
```
to disable a cache when we create sequence using $sequence->create('seq_name');?

thank you

**Comment by yajra** [comment]
Yes you can but by sending additional parameters on the create method.

```php
public function create($name, $start = 1, $nocache = false)
```

**Comment by yajra** [comment]
I just updated the [docs](https://yajrabox.com/docs/laravel-oci8/master/sequence) as an answer to this question. Thanks!

**Comment by h3ndro** [comment]
thank you very much for this
