### ISSUE TITLE
Wrapping columns that have modifiers

### ISSUE THREAD

**Issue by chekovsky** [yajra/laravel-oci8#241]
### Summary of problem or feature request

Hi there!

After updating laravel-oci8 to v5.3.8, all eloquent queries that use some kind of modifier is not working anymore. For example, to ensure that a search functionality is case-insensitive, I usually use UPPER in the column I'm searching, for example:

```php
$query->where('upper(nome)', 'like', '%'.mb_strtoupper($request->input('solicitante')).'%');
```

This will ensure that this query is case-insensitive, since Oracle does not support case-insensitive collation.

I guess that v5.3.6 started double-quoting everything, so the query above will generate the following SQL:

```sql
select * from "MY_TABLE" where "UPPER(NOME)" like :p0
```

Since "UPPER(NOME)" is not the column name, the following error is thrown:

```
ORA-00904: "UPPER(NOME)": invalid identifier
```

In the past the SQL generated would not have that double quote, so it worked just fine.

How to work with case-insensitive queries in v5.3.8? For now I'll have to rollback to v5.3.5 to get things working again.

Best regards,
Rafael Pacheco.

### System details

- Operating System: Linux
- PHP Version: 7.0.0
- Laravel Version: 5.3.29
- Laravel-OCI8 Version: 5.3.8

**Comment by yajra** [comment]
It's because of this security fix https://github.com/yajra/laravel-oci8/pull/223. DB raw are properly enforced on latest version for security purposes. You need to use `DB::raw('UPPER(NOME)')` to fix this issue. Thanks!

**Comment by chekovsky** [comment]
Hi @yajra!

DB::raw('UPPER(NOME)') worked like a charm!

Thank you very much.

Best regards,
Rafael Pacheco.
