### ISSUE TITLE
ORA-00955: name is already used by an existing object

### ISSUE THREAD

**Issue by mohd-aidi** [yajra/laravel-oci8#245]
I cant migrate my DB.

$ php artisan migrate
Migration table created successfully.

  [Illuminate\Database\QueryException]
  Error Code    : 955
  Error Message : ORA-00955: name is already used by an existing object
  Position      : 16
  Statement     : create sequence e_users_id_seq start with 1
  Bindings      : []
   (SQL: create sequence e_users_id_seq start with 1 )

  [Yajra\Pdo\Oci8\Exceptions\Oci8Exception]
  Error Code    : 955
  Error Message : ORA-00955: name is already used by an existing object
  Position      : 16
  Statement     : create sequence e_users_id_seq start with 1
  Bindings      : []

**Comment by johnathansantos** [comment]
Verify if sequence exists: 
```sql
select * from ALL_SEQUENCES where sequence_name='E_USERS_ID_SEQ';
```

and drop 
```sql
DROP SEQUENCE E_USERS_ID_SEQ; 
```

**Comment by mohd-aidi** [comment]
Thank u jonathan..its working now..

**Comment by sa4dkhan** [comment]
@johnathansantos 

Verify if sequence exists:

select * from ALL_SEQUENCES where sequence_name='E_USERS_ID_SEQ';
and drop

DROP SEQUENCE E_USERS_ID_SEQ; 

I am having this same issue. Can please explain more about this solution of yours. Thanks in advance.

**Comment by johnathansantos** [comment]
@sa4dkhan 

the migration was trying to create the sequence with the name `e_users_id_seq`. 
But in this case the error is that the sequence in oracle already existed.
Then run these sql in oracle to identify if the sequence exists then I delete.

**Comment by sa4dkhan** [comment]
@johnathansantos Thank you bro. It worked.

**Comment by leandrobhbr** [comment]
The code Can Verify if sequence exists, and create if dont exist?

**Comment by michaelsabatino** [comment]
I'm running into this problem as well. Just so I'm clear, if we have a migration that creates a sequence in up(), for instance...

`$table->id();`

...then we have to add the "drop sequence" SQL statement somewhere in down() for when we need to do rollbacks?
