### ISSUE TITLE
[5.4] Fetchmode 

### ISSUE THREAD

**Issue by sostenesgomes** [yajra/laravel-oci8#246]
I migrated to version 5.4 and noticed a difference in the return of a query.

In 5.3 it returns:
{
      "id_departamento": 1,
      "denominacao": "BRANCA"
},

In 5.4 returns:
{
      "0": "1",
      "1": "BRANCA",
      "id_departamento": 1,
      "denominacao": "BRANCA"
},

Please help me understand and check the best way to fix.

- Ubuntu Linux
- PHP Version 7.0
- Laravel Version 5.4.4
- Laravel-OCI8 5.4.0

**Comment by yajra** [comment]
Is this using the default fetch mode or you are using a different one?

**Comment by sostenesgomes** [comment]
I did not set anything in the configuration in relation to this.

**Comment by vystepanenko** [comment]
hello!
i have the same problem in laravel 5.4.
to be more concrete
We have table TESTS in Oracle DB. 
```
  Schema::create('tests', function (Blueprint $table) {
            $table->increments('id');
            $table->string('testname');
```
And if we try to fetch data we receive an error
```
>>> $tests = DB::table('tests')->get();
=> Illuminate\Support\Collection {#679
     all: [
       [
         0 => "1",
         "id" => "1",
         1 => "same name",
         "testname" => "same name",
       ],
     ],
   }
>>> $tests->testname
Exception with message 'Property [testname] does not exist on this collection instance.'
```

**Comment by grexx** [comment]
Same issue as sostenesgomes  since i've migrated to 5.4

for example in my controller : 
```
    public function test(){
        $dual = DB::connection('oracle')->select('select * from dual');	
        foreach ($dual[0] as $key => $value){
            Log::info( $key." - ".$value );
        }	
	return $dual;
    }  
```

gives : 
`[2017-02-01 15:40:47] local.INFO: 0 - X
[2017-02-01 15:40:47] local.INFO: dummy - X
`
and 
[{"0":"X","dummy":"X"}]

in 5.3, i had only this key value pair : 
[{"dummy":"X"}]

**Comment by yajra** [comment]
I just tried and replicated the issue. Will try to fix this as soon as I can. Thanks!

**Comment by yajra** [comment]
Updating to v5.4.1 should fix the issue. Thanks!
