### ISSUE TITLE
your security credential

### ISSUE THREAD

**Issue by sysdocearth** [yajra/laravel-oci8#247]
Hi 
your SSL Certificate were expired 9 days ago.
I want read your laravel-oci8 documentation but cannot read ,so please  renewal your  SSL Certificate.
best regards.

**Comment by yajra** [comment]
@sysdocearth yeah, my friend who sponsored hosting my site still not responding on my request to renew the SSL (letsencrypt). Don't have permission to do so. 

Have disabled force SSL atm. Thanks!

**Comment by sysdocearth** [comment]
Thank you early respond.
I will wait to open your documentation.

**Comment by yajra** [comment]
FYI: SSL was fixed. Thanks!
