### ISSUE TITLE
[5.4] ORA-00972:  Identifier is too long

### ISSUE THREAD

**Issue by silencesys** [yajra/laravel-oci8#251]
Hello, 

I've recently updated your plugin to version 5.4.1 from 5.3.2 and my sql now returns ORA-00972 error, I've found that the problem is in my where clause, because in older version was possible to do `LOWER(jmeno || ' ' || prijmeni)` and now it seems not, was there any change or is there any possibility to do similar thing in different way?

### Snippet
Snippet of that part of my SQL request.
```php
->where(function($q) use ($name, $condition, $titles_before) {
    if ($condition == '=') {
    ...
    } else {
        $q->orWhere('LOWER(jmeno || \' \' || prijmeni)', $condition, '%'.$name.'%')
            ->orWhere('LOWER(jmeno || \' \' || prijmeni)', $condition, '%'.$name.'%');
    }
})
```

**Comment by silencesys** [comment]
I've found solution with `orWhereRaw` which probably isn't documented anywhere, but it works.

```php
->where(function($q) use ($name, $condition) {
     if ($condition == '=') {
        ...
     } else {
        $q->orWhereRaw("LOWER(jmeno || ' ' || prijmeni) ".$condition." '%".$name."%'")
            ->orWhereRaw("LOWER(prijmeni || ' ' || jmeno) ".$condition." '%".$name."%'");
    }
})
```

**Comment by yajra** [comment]
@silencesys are more secure way to prevent sql injection:

```php
$q->orWhere(DB::raw('LOWER(jmeno || \' \' || prijmeni)'), $condition, '%'.$name.'%')
    ->orWhere(DB::raw('LOWER(jmeno || \' \' || prijmeni)'), $condition, '%'.$name.'%');
```

**Comment by silencesys** [comment]
Thank you, I'll change it. :)
