### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by sciracioglu** [yajra/laravel-oci8#255]
### Summary of problem or feature request
Hi Yajra,

I have a problem.

I have a 2 databases.

Default connection is conn1. The other one is conn2

Default models has no $connection, and other models use $connection value;

I used laravel 5.3 I didn’t any problem.

But   when update 5.4 I got problems if I use create method.

If I use 

$model = new Model();
$model->foo = ‘bar’;
$model->save();

Its working.

But Model::create([
                ‘foo’ => ‘bar’,
]);

I got ORA-00942: table or view does not exist

Select is ok. But create is not.

I hope you know what I mean.

Thank you.

- Operating System Debian
- PHP Version 7.1
- Laravel Version 5.4
- Laravel-OCI8 Version 5.4

**Comment by mstaack** [comment]
did you try to explicitly set the $connection variable in both models?

**Comment by sciracioglu** [comment]
yes.

**Comment by mstaack** [comment]
did you try latest v5.4.2 version?

**Comment by sciracioglu** [comment]
i have already 5.4.2 :(

**Comment by mstaack** [comment]
any special chars in table name? what are their names?

**Comment by sciracioglu** [comment]
no. for example table name is "parameters"

**Comment by yajra** [comment]
Just tested this and works well on my side.

Model 1
```php
class Demo extends Model
{
    public $sequence = 'demo_seq';
    public $timestamps = false;
}
```

Model 2
```php
class DTDemo extends Model
{
    protected $connection = 'datatables';
    protected $table = 'demos';
    public $sequence = 'demos_seq';

    public $timestamps = false;
}
```

Can you please provide some snippets to replicate the issue?

**Comment by sciracioglu** [comment]
i had change the all codes from 
Model::create($data) 
to 
$model = new Model(); $model->fill($data)->save();

its working now.

**Comment by dordze** [comment]
I was having the same problem with the create method.  I found that  builder class was calling
$this->query->getConnection()->getName()   which was returning null

I added 'name' => 'connection-name' to my connection array and it starting working.
