### ISSUE TITLE
Eloquent query fails when attempting to order by column named 'time'

### ISSUE THREAD

**Issue by rbrowndev** [yajra/laravel-oci8#258]
### Summary of problem or feature request

I am currently working on a Laravel 5.4 project with a legacy Oracle database. One of my tables has a timestamp field simply called 'TIME'. I am attempting to write an eloquent query to return records ordered by the 'time' field, but am getting an error. I believe this is due to a reserved word issue, as when I temporarily rename the column to 'TIME2', the query will execute correctly. 

### Code snippet of problem

App\Appointment::where('id', '=', '522551')->orderBy('time')->get()

oci_execute(): ORA-00904: "time": invalid identifier in /var/www/html/oracletest/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8/Statement.php on line 153

If I change the column name to something else (e.g. TIME2)

App\Appointment::where('id', '=', '522551')->orderBy('time2')->get()

Success

I really can't change the database as other apps depend on it. Is there a way to continue using eloquent and get the query to escape the reserve word or do I need to fall back to using raw SQL?

Thanks

### System details

- Operating System (Ubuntu 16.04)
- PHP Version (7.1.1)
- Laravel Version (5.4)
- Laravel-OCI8 Version (5.4)

**Comment by yajra** [comment]
@rbrowndev yes, you need to use raw sql but using Laravel's way. Something like:

```php
App\Appointment::where('id', '=', '522551')->orderByRaw('time')->get()
```

**Comment by yajra** [comment]
@rbrowndev on v5.5, reserved words will be uppercase by default which might fix this issue without the workaround. Thanks!
