### ISSUE TITLE
queryBuilder->groupBy 

### ISSUE THREAD

**Issue by vystepanenko** [yajra/laravel-oci8#259]
Hello!
I have a little issue with groupBy().
When we create sql, for example:

`App\Post::selectRaw('count(*), title')->groupBy('title')->get()`

we get such result:

`select count(*), title from "POSTS" group by "TITLE"`

I want to know why groupBy parameter in double quotes? In oracle they are not necessary. Even more it can make some problem. In case when groupBy not a single column or it is function such construction with double quotes do not working.

Can I somehow remove this double quotes and receive something like this:
`select count(*), title from "POSTS" group by TITLE`

or even more:
`select count(*), title from POSTS group by TITLE`

**Comment by yajra** [comment]
I think there is a `groupByRaw('title')` method that you can use. If not, then you need to adjust your select to `selectRaw('count(*), "TITLE"')`. Escaping on double quotes is a standard behavior of Laravel to protect us from SQL Injection. Thanks!

**Comment by vystepanenko** [comment]
Unfortunately there is no method groupByRaw()

`BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::groupByRaw()'`
