### ISSUE TITLE
Oracle 12c ansi pagination (the new way)

### ISSUE THREAD

**Issue by peyobr** [yajra/laravel-oci8#264]
Hi Arjay,
today i make some test on Oracle 12c new ansi pagination support (OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY).

Huge performance increase. It would be a critical improvment when working with million of records (it's the case for me!!)
What about implement an Oracle12c specific feature? Maybe adding a configuration option?

What do you think about?

Thank you!!!

**Comment by yajra** [comment]
Sounds good to me, I agree that we can add a config on database like `version => 12` but set it as 11 by default?

Please submit a PR so that we can tests. Thanks!

**Comment by peyobr** [comment]
Test failed because:

1) Oci8QueryBuilderTest::testSubSelectWhereIns

BadMethodCallException: Method Mockery_3_Illuminate_Database_ConnectionInterface::getConfig() does not exist on this mock object

But still i think this is the cleanest way to get Oracle configuration:

     protected function compileAnsiOffset(Builder $query, $components)
     {
+        // Improved response time with FIRST_ROWS(n) hint for ORDER BY queries
         if ($query->getConnection()->getConfig("server_version") == "12c") {


What do you think??

**Comment by yajra** [comment]
Yes, I think that is the best way to get the config.

**Comment by peyobr** [comment]
Ok, so have i to alter tests in order to get the config this way? (at the moment it is not possible)

**Comment by yajra** [comment]
Fix via #265 Thanks!
