### ISSUE TITLE
oci8 and mysql

### ISSUE THREAD

**Issue by fabien44300** [yajra/laravel-oci8#268]
Hello,

I have 2 service Provider
First for authentification is MYSQL
Second I try to config is ORACLE(yajra-oci8) to do queries on tables

When I try to query a table from Oracle with for example : 

**$data = DB::connection('oracle')->table('mytable')->take(1)->get();**

When I debug, the oracle provider call the oracle.php config file but at the end of the process, the .env file rewrite config : 

Error message : all config from .env file  rewrite the oracle.php file, only charset field from oracle.php what doesn't exist in .env file is ok
.....
at Oci8->connect('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 3306)) (CONNECT_DATA =(SID = myDatabase)))', 'root', '', array(2, 2, 0, 'charset' => 'AL32UTF8'), 'AL32UTF8') in Oci8.php line 78
......

If I change .env file config with Oracle config, the query is OK,but  it's my first Mysql provider who can't now connect.

How force laravel to use oracle.php without be rewrite by env.file ? Or do I need to change something to prioritize files from config folder instead of env. file ?

thank you

- Operating System : WAMP
- PHP Version 5.6.25
- Laravel Version 5.4
- Laravel-OCI8 Version 5.4

**Comment by yajra** [comment]
You should append/copy `oracle.php` contents on `database.php` config file and use an oracle specific env variable so that it will not conflict with your main mysql connection.

**Comment by fabien44300** [comment]
Thank your for your answer.

I resolved my problem. In fact, in the oracle.php, I used the example configuration without remove env('xxxx') and this is why Laravel always call and get the .env file

My beginner's mistake :
'database' => env('DB_DATABASE', 'MyOwnDatabase'),

The simple solution :
'database' => 'MyOwnDatabase'
