### ISSUE TITLE
Can't use reserved words with relationships

### ISSUE THREAD

**Issue by DarKDinDoN** [yajra/laravel-oci8#270]
### Summary of problem or feature request

I have access to a database I do not own. This database uses oracle reserved words like "oid".
When I try to query a relationship (the Laravel way), I get an error because the query builder tries to use the reserved words lowercase when it should be uppercase.

### Code snippet of problem

This works:
```php
$data = Model::select(DB::raw('OID'), 'otherColumn')
            ->get();
```

This doesn't work:
```php
$data = Model::select(DB::raw('OID'), 'otherColumn')
            ->whereHas('relationName', function($query)
            {
                $query->select(DB::raw('OID'))
                            ->whereIn(DB::raw('OID'), [0,1,2]);
            })
            ->get();
```

Here is how I declare the relation in the model:
```php
public function model1()
{
    return $this->belongsTo(model2::class, 'column', 'OID');
}

public function model2()
{
    return $this->hasMany(model1::class, 'column', 'OID');
}
```

Example of query generated:
```
select
    OID
from
    "SCHEMA_PREFIX"."TABLE"
where exists
   (select
        OID
    from
        "SCHEMA_PREFIX"."RELATED_TABLE"
    where
        "SCHEMA_PREFIX"."TABLE"."TABLE_REFERENCE" = "SCHEMA_PREFIX"."RELATED_TABLE"."oid"
    and
        OID in (0, 1, 2))
```

As you can see the relation is generated with the "oid" column lowercase.

### System details

- Operating System (Ubuntu 16.04)
- PHP Version (7.1.2)
- Laravel Version (5.4.16)
- Laravel-OCI8 Version (5.4.7)

**Comment by DarKDinDoN** [comment]
For the time being, I override the OracleReservedWords Trait with composer (thank you psr-4)
```
"psr-4": {
            "Yajra\\Oci8\\": "app/Oracle"
        }
```

**Comment by yajra** [comment]
Fix will be done on Laravel 5.5 version as per this PR https://github.com/yajra/laravel-oci8/pull/262.

Would you mine sharing some more snippets how you manage it with PSR-4? It could be a work around until we fix this on next major release. Thanks!

**Comment by DarKDinDoN** [comment]
Nothing fancy really.

Just configure psr-4 in composer.json :

```json
"psr-4": {
            "Yajra\\Oci8\\": "app/Oracle"
        }
```

Copy the trait OracleReservedWords.php without changing the namespace in "app/Oracle". Then modify the list of reserved words ("oid" was the only problem I encountered with the database).

```php
<?php

namespace Yajra\Oci8;

use Illuminate\Support\Str;

trait OracleReservedWords
{
    /**
     * Lists of reserved words.
     *
     * @see https://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm
     * @var array
     */
    protected $reserves = [
        'ACCESS',
        // 'ACCOUNT', <-- just comment some reserved words
        'ACTIVATE',
        'ADD',
        'ADMIN',
        ...
```

With psr-4, Laravel will try to get the files with this namespace in the folder configured first. Then if the files doesn't exist, Laravel will default to the vendors.

Don't forget do ```composer dumpautoload```

**Comment by mstaack** [comment]
@yajra i have the problem with laravel 5.4
```
{"message":"Error Code : 904\nError Message : ORA-00904: \"password\": invalid identifier\nPosition : 60\nStatemen
```

commenting password in OracelReservedWordsTrait fixes this... whats wrong here?

**Comment by mstaack** [comment]
We should fix this also for 5.4

**Comment by yajra** [comment]
@DarKDinDoN is it possible to use raw when defining the relations?

```ph
return $this->hasMany(model1::class, 'column', DB::raw('OID'));
```

@mstaack if we can do a non breaking fix then we can implement it.

Thanks!

**Comment by DarKDinDoN** [comment]
Hello @yajra 

No it is not possible.

**Comment by mstaack** [comment]
@DarKDinDoN thanks btw for the temporary psr-4 fix idea...helped me out recently ;)

so basically we have two uses of the trait:
Grammar: https://github.com/yajra/laravel-oci8/blob/6f851d75db5d800361e068d037e75cbe7ebd4175/src/Oci8/Query/Grammars/OracleGrammar.php#L206
Schema: https://github.com/yajra/laravel-oci8/blob/431e267a0590762f45917a352ed5f5b609a3565f/src/Oci8/Schema/Grammars/OracleGrammar.php

how about just uppercase if its a reserved word?  oracle docs say wrapping in double braces should be enough: `Double quotes do work around the reserved words.`

**Comment by mstaack** [comment]
@yajra @DarKDinDoN startet a little playground to work on this:
https://github.com/yajra/laravel-oci8/pull/278

**Comment by yajra** [comment]
Reserved words are now uppercase by default on v5.5 via #262
