### ISSUE TITLE
Table with CLOB field issue

### ISSUE THREAD

**Issue by rajkumarsakthi** [yajra/laravel-oci8#272]
@yajra

I am using table with CLOB field in my project and I got error so could you please help me.

Couldn't find constant PDO::PARAM_CLOB

**Comment by yajra** [comment]
@rajkumarsakthi sorry for late response. What's the issue? There is indeed no `PDO:PARAM_CLOB` but using clob, you directly save string values on the DB as far as I know. No need for special binding.
