### ISSUE TITLE
Laravel passport

### ISSUE THREAD

**Issue by fractalzombie** [yajra/laravel-oci8#273]
Have an issue with migration.

>  [Illuminate\Database\QueryException]                                                                        
>   Error Code    : 955                                                                                         
>   Error Message : ORA-00955: name is already used by an existing object                                       
>   Position      : 13                                                                                          
>   Statement     : create index oauth_personal_access_clients_ on oauth_personal_access_clients ( client_id )  
>   Bindings      : []                                                                                          
>    (SQL: create index oauth_personal_access_clients_ on oauth_personal_access_clients ( client_id ))          
>                                                                                                               
> 
>                                                                                                               
>   [Yajra\Pdo\Oci8\Exceptions\Oci8Exception]                                                                   
>   Error Code    : 955                                                                                         
>   Error Message : ORA-00955: name is already used by an existing object                                       
>   Position      : 13                                                                                          
>   Statement     : create index oauth_personal_access_clients_ on oauth_personal_access_clients ( client_id )  
>   Bindings      : []

**Comment by yajra** [comment]
@fractalzombie yes I know this issue. I once tried to submit a PR on passport but was rejected by the author. https://github.com/laravel/passport/pull/44. 

Anyways, you need to create you own migration if you want to use passport.

**Comment by gmancoder** [comment]
@yajra I too had issues getting passport and oracle to play nice. When I got to the migrate step in the instructions here:  https://laravel.com/docs/5.3/passport, it failed on one of the indexes. I had to modify two of the migrations that come with passport:
The first one I had an error with was oauth_personal_access_clients. I modified /vendor/laravel/passport/database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php to have an up function that looks like this:

`public function up()
    {
        Schema::create('oauth_personal_access_clients', function (Blueprint $table) {
            $table->increments('id');
            //$table->integer('client_id')->index();
            $table->integer('client_id');
            $table->timestamps();

            $table->index('client_id', 'opa_client_id');
        });
    }`

I also noticed that there is another one that will exceed the 30 character limit. In 2016_06_01_000003_create_oauth_refresh_tokens_table.php, I updated the up function as follows:

`public function up()
    {
        Schema::create('oauth_refresh_tokens', function (Blueprint $table) {
            $table->string('id', 100)->primary();
            //$table->string('access_token_id', 100)->index();
            $table->string('access_token_id', 100);
            $table->boolean('revoked');
            $table->dateTime('expires_at')->nullable();

            $table->index('access_token_id', 'ort_access_token_id');
        });
    }`

Migration was successful and so wasn't installation. Was able to complete setup and test getting a token and it was successful. Hope this helps!

**Comment by gvgvgvijayan** [comment]
@gmancoder  Thanks for the fix.

**Comment by yajra** [comment]
Now supported on Laravel 5.6 version out of the box via #391.
