### ISSUE TITLE
Long connection time 

### ISSUE THREAD

**Issue by m4gn3to** [yajra/laravel-oci8#274]
Hi,

First of all thanks for the package, it works like a charm.

I only have one question, is normal that it takes about 6 seconds to open the connection?

I've tried many databases, but my main problem is the time taken to open the connection the first time, once the connection is opened it is fast but it takes about 5-6 seconds to open the connection.

- Operating System: Centos 7
- PHP Version: 5.6
- Laravel Version: 5.1.46
- Laravel-OCI8 Version: 5.1.3

**Comment by mstaack** [comment]
must be something with your network/env. never had this problem on my site...

try pinging your database or give `mtr` tool on linux a try...will show you weak hops on your connection

cheers max
