### ISSUE TITLE
Fetch mode

### ISSUE THREAD

**Issue by Viking0607** [yajra/laravel-oci8#276]
Hello! Say please, can I change **fetch mode** in custom query? Example _chech_view_ function 
```
namespace App;

use Yajra\Oci8\Eloquent\OracleEloquent as Eloquent;

class Testlaravel extends Eloquent
{
    public function check_view(){
        $sql = "Select * from v_stud where FSDEPCODE = :gr";
        $query_arr = (['gr'=>'1661м']);
        // \DB::setFetchMode(\PDO::FETCH_CLASS);
        $users = \DB::select($sql,$query_arr);
        return $users;
    }
}
```
- PHP Version - 7.0.5
- Laravel Version - 5.4

**Comment by yajra** [comment]
I think fetchMode support was removed on Laravel Framework since 5.4 so I guess this may not work anymore.

**Comment by yajra** [comment]
As per upgrade guide https://laravel.com/docs/5.4/upgrade:

## Fetch Mode

> Laravel no longer includes the ability to customize the PDO "fetch mode" from your configuration files. Instead, PDO::FETCH_OBJ is always used. If you would still like to customize the fetch mode for your application you may listen for the new Illuminate\Database\Events\StatementPrepared event:

```php
Event::listen(StatementPrepared::class, function ($event) {
    $event->statement->setFetchMode(...);
});
```
