### ISSUE TITLE
Class db does not exist

### ISSUE THREAD

**Issue by mowelsch** [yajra/laravel-oci8#287]
Using freshly installed laravel 5.4

Yajra\Oci8\Oci8ServiceProvider::class,
When i add this line to my app.php in the section providers then the following error occurs

ReflectionException in Container.php line 721:
Class db does not exist

The line in the Oci8ServiceProvider.php file makes the error.
$this->app['db']->extend('oracle', function ($config) {
            $connector  = new Connector();
            $connection = $connector->connect($config);
            $db         = new Oci8Connection($connection, $config["database"], $config["prefix"], $config);

Thanks

**Comment by yajra** [comment]
Try updating to the latest v5.4.9 of laravel-oci8.
