### ISSUE TITLE
Unsupported driver [oci8]

### ISSUE THREAD

**Issue by munfor** [yajra/laravel-oci8#288]
After update vendor libraries with **composer update**, when I make a request,  like this:

```
Registry::where(function($q) use ($year) {
		$q->whereYear('fecini', '=', $year)
		    ->whereYear('fecfin', '=', $year);
	})->get();
```

An exception with the message _Unsupported driver [oci8]_ is triggered.

My model is configured with the protected variable _$connection_ for choose the database connection.

```
class Registry extends Model {
	protected $connection = 'oracle';
}
```

After execute _composer update_:
> Operating System: Windows Server 2008
> PHP **5.6.8**
> Lavarel Framework **5.4.23**
> yajra/laravel-pdo-via-oci8 **1.3.1**
> yajra/laravel-oci8 **5.4.9**

> **NOTE**: With yajra/laravel-oci8 versión **5.4.0** it works.

Thank you.

**Comment by yajra** [comment]
You might still be using the old config`oci8` on your oracle database settings? Maybe try updating the driver to `oracle`?

```php
        'oracle' => [
            'driver'   => 'oracle',
            'host'     => env('DB_HOST', 'localhost'),
            'database' => env('DB_DATABASE', 'xe'),
            'username' => env('DB_USERNAME', 'cms_dev'),
            'password' => env('DB_PASSWORD', 'secret'),
            'port'     => env('DB_PORT', '1521'),
            'prefix'   => '',
        ],
```
