### ISSUE TITLE
Calling Stored Function with date parameters

### ISSUE THREAD

**Issue by 854R** [yajra/laravel-oci8#297]
### Summary of problem or feature request

What is the correct way to pass 2 date parameters to a stored function? We have a stored function that takes in 2 dates and returns a calculated value. When the function is called, Oracle reports either:
- ORA-01843: Not a valid month - when passing a date as a string in MM-DD-YYYY format
or 
- ORA-01858: a non-numeric character was found where a numeric was expected - when passing a date as a string in DD-MON-YYYY format

It seems no matter what date format I use to pass the date as a string, I'll get an Oracle error. However, when I execute the same SQL command in my Oracle IDE (PL/SQL Developer), it works fine.

Below are different variations I've coded in Laravel. Even using an explicit TO_DATE() still produces the Oracle error msg.

### Code snippet of problem

```php
// this one returns invalid month error
$result = DB::selectOne("SELECT CalculatePeriod('01-31-2009', '01-01-1972') AS Period FROM DUAL");

// this one returns non-numeric character
$result = DB::selectOne("SELECT CalculatePeriod('31-JAN-2009', '01-JAN-1972') AS Period FROM DUAL");

// this one returns invalid month error
$result = DB::selectOne("SELECT CalculatePeriod(to_date('01-31-2009', 'MM-DD-YYYY'), to_date('01-01-1972', 'MM-DD-YYYY')) AS Period FROM DUAL");
```

### System details

- Operating System
- PHP Version - 7.0.x
- Laravel Version - 5.4
- Laravel-OCI8 Version - latest

**Comment by 854R** [comment]
OK, I just tried this code and it works. But notice the format of setFormat and the date parameters are different! The weird thing is when I use setFormat('MM-DD-YYYY') to match the date parameters, I get ORA-01858: non-numeric character...

```
DB::setFormat('DD-MON-YYYY');
$result = DB::selectOne("SELECT CalculatePeriod('01-31-2009', '01-01-1972') AS Period FROM DUAL");
```

**Comment by yajra** [comment]
@854R I think it's [`DB::setDateFormat('DD-MON-YYYY');`](https://yajrabox.com/docs/laravel-oci8/master/date-format)

You can also try using [DB::executeFunction()](https://yajrabox.com/docs/laravel-oci8/master/function) method.

**Comment by yajra** [comment]
BTW, the default date session format we use is `YYYY-MM-DD HH24:MI:SS`.
