### ISSUE TITLE
SSH Tunnel

### ISSUE THREAD

**Issue by J-Ibarra** [yajra/laravel-oci8#299]
### How can connect to remote database with SSH Tunnel

hello, I need some tips, I need connec to to remote database, but the port 1521 no its open for other ip, only 127.0.0.1

I have a user and password to connect via ssh

thank very much

- Operating Ubuntu 17
- PHP 7.0
- Laravel 5.4

**Comment by yajra** [comment]
I think @ChaosPower can you help you on this. Ping @ChaosPower

**Comment by J-Ibarra** [comment]
Thank very much @yajra!

Ping @ChaosPower, please help me

**Comment by ChaosPower** [comment]
@J-Ibarra you may try using ssh tunnels.

`ssh -L local-port:host:remote-port serverUser@serverhost`

```bash
 ssh -L 1521:127.0.0.1:1521 serverUser@serverhost
```

**Comment by J-Ibarra** [comment]
@ChaosPower, thank very much,

Tomorrow I will try, and the feedback for this medium

**Comment by ChaosPower** [comment]
@J-Ibarra if you want to silence it or run in the background.

try this connecting using this

```bash
ssh -M -S name-of-socket -fnNT -L 1521:127.0.0.1:1521 someuser@somehost
```

To check for background tunnels

```bash
ssh -S name-of-socket -O check user@host
```

Now to exit it cleanly

```bash
ssh -S name-of-socket -O exit user@host
```

You may also use this to sniff packets ;)

**Comment by J-Ibarra** [comment]
@ChaosPower, @yajra, Excellent friends, Thank very much, 
I think I have to study more
