### ISSUE TITLE
Triggers and Sequences not considering prefix_schema param

### ISSUE THREAD

**Issue by renanwilliam** [yajra/laravel-oci8#300]
### Summary of problem or feature request
When it's configured in connection settings a `prefix_schema` value, it's only considered on read/write table operations. If you have a auto increments, the sequence/triggers created will not consider the `prefix_schema` param

### Code snippet of problem
In `Yajra\Oci8\Schema\OracleAutoIncrementHelper`

```php
     /**
     * Create an object name that limits to 30 chars.
     *
     * @param  string $prefix
     * @param  string $table
     * @param  string $col
     * @param  string $type
     * @return string
     */
    private function createObjectName($prefix, $table, $col, $type)
    {
        // max object name length is 30 chars
        return substr($prefix . $table . '_' . $col . '_' . $type, 0, 30);
    }

```
At this point the param prefix_schema  needs to be considered.
### System details

- Operating System : Windows 10
- PHP Version: 7.1.4
- Laravel Version: 5.4.25
- Laravel-OCI8 Version: 5.4.9

**Comment by yajra** [comment]
Fixed on v5.4.16 👍
