### ISSUE TITLE
Exception since 5.4.10

### ISSUE THREAD

**Issue by jesusvpct** [yajra/laravel-oci8#306]
Since 5.4.10 I have exception when trying to create/update a form . The error is:

"Type error: Argument 1 passed to Yajra\Oci8\Eloquent\OracleEloquent::checkBinary() must be of the type array, null given, called in C:\Proyectos\Laravel\wastia\vendor\yajra\laravel-oci8\src\Oci8\Eloquent\OracleEloquent.php on line 95

The form have input text, selects, and radio buttons for saving as char (0 or 1) on the table.

On 5.4.9 is working perfect but on 5.4.10 throws that exception.

```php
$section->update($request->all());
```

### System details
- Operating System: Windows 7 64 bit
- PHP Version: 7.0.13
- Laravel Version: 5.4.27
- Laravel-OCI8 Version: 5.4.10

**Comment by yajra** [comment]
Whoops sorry for the inconvenience. Can you please check if #307 fixes the issue? Got too hasty on refactoring. :(

**Comment by jesusvpct** [comment]
Now I have other exception.



![error](https://user-images.githubusercontent.com/5315258/27435189-ac8c7862-575b-11e7-81ee-d92a6ec6de2b.jpg)

**Comment by yajra** [comment]
Thanks for the feedback. I have updated the PR and removed the `options`. Options are removed on 5.4 and our current implementation is not updated.

**Comment by jesusvpct** [comment]
So I have to stay on downgraded version?

**Comment by yajra** [comment]
I suggest to stay downgraded until issue is fixed. Would appreciate any help on testing the PR. Does it work on you now?

**Comment by jesusvpct** [comment]
Yes, with last change (removing `options`) works fine.

**Comment by yajra** [comment]
Released on v5.4.11. Thanks!
