### ISSUE TITLE
Laravel Queue Job Table with Oracle 11g Database

### ISSUE THREAD

**Issue by Adam2Marsh** [yajra/laravel-oci8#308]
### Summary of problem or feature request

Has anyone got Laravel Queues working with a Oracle 11g database? I'm having an issue with the ID column.

Oracle 11g doesn't support Auto-Increment Columns and unless you're inserting into Modal table there doesn't seem to be an option to specify a sequence to use.

### Code snippet of problem

When you try to dispatch a job it fails when trying to insert into the jobs table advising the ID column cannot be NULL.

I believe the issue lies here in the code:
```php
    /**
     * Insert a new record and get the value of the primary key.
     *
     * @param array $values
     * @param string $sequence
     * @return array
     */
    protected function incrementBySequence(array $values, $sequence)
    {
        $builder     = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT, 5)[3]['object'];
        $builderArgs = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT, 5)[2]['args'];

        if (! isset($builderArgs[1][0][$sequence])) {
            if ($builder instanceof EloquentBuilder) {
                $model = $builder->getModel();
                if ($model->sequence && $model->incrementing) {
                    $values[] = (int) $model->getConnection()->getSequence()->nextValue($model->sequence);
                }
            }
        }

        return $values;
    }
```
It only checks for a sequence if it's a model requesting the insert, otherwise you get no ID.

### System details

- Database Version: 11g
- PHP Version: 7.1
- Laravel Version: 5.4
- Laravel-OCI8 Version: 5.4.4

Thanks in advanced, just wondering if anyone has found a way round this?

**Comment by yajra** [comment]
On your model, just set the sequence property.

```php
class User extends Model {
  public $sequence = 'user_id_seq';
}
```

**Comment by Adam2Marsh** [comment]
Hi Yajra,

There is no model as it's a job.

Thanks

**Comment by yajra** [comment]
Oic, did you create the failed jobs table manually? If you use the migration, then auto-increment is added automatically on that table by creating a trigger and a sequence.

```php
Schema::create('failed_jobs', function (Blueprint $table) {
            $table->increments('id');
            $table->text('connection');
            $table->text('queue');
            $table->longText('payload');
            $table->timestamp('failed_at')->useCurrent();
        });
```

If the table is manually created, you then need to make the id to increment for it to work.

**Comment by Adam2Marsh** [comment]
Yes we created both the jobs and failed_jobs table manually. We're unfortunately not allowed triggers (DBA rule) so by specifying the sequence on a modal it got round that issue. 

I was kinda hoping we could do something similar for jobs.

Thanks

**Comment by yajra** [comment]
Sorry, but I think the only solution for this issue is to create a trigger that increments the ID.

I tried to dig the framework and maybe you can work around by overriding `queue.failer` instance for failed jobs. However, I do cannot find a way to override the `jobs` handler.

On `QueueServiceProvider`:

```php
protected function databaseFailedJobProvider($config)
    {
        return new DatabaseFailedJobProvider(
            $this->app['db'], $config['database'], $config['table']
        );
    }
```

Log method on `DatabaseFailedJobProvider`:

```php
public function log($connection, $queue, $payload, $exception)
    {
        $failed_at = Carbon::now();

        $exception = (string) $exception;

        return $this->getTable()->insertGetId(compact(
            'connection', 'queue', 'payload', 'exception', 'failed_at'
        ));
    }
```

**Comment by Adam2Marsh** [comment]
Hi Yajra,

I had a feeling that was the answer so we'll go with plan b and use a mysql database which I know works :)

Thanks for your help, I'll close this down.
