### ISSUE TITLE
hasTable returns always bool (false)

### ISSUE THREAD

**Issue by manuzcom** [yajra/laravel-oci8#309]
```php
Capsule::schema()->hasTable('tests')
```

returns always false;

query log is like this
```sql
select 
  * 
from 
  all_tables 
where 
  upper(owner) = upper(?) 
  and upper(table_name) = upper(?)
```
1 = null
2 = tests

so i look in to the OracleBuilder.php line 128
```php
$database = $this->connection->getConfig('username');
```

this line return null;
i miss something?
or what's wrong?

i'm using yajra/laravel-oci8 without laravel.
using capsule.
connection like this.
```php
$capsule->addConnection([
    'driver'   => DBType,
    'host'     => DBHost,
    'database' => DBServiceName,
    'username' => DBUser,
    'password' => DBPass,
    'prefix'   => DBPrefix,
    'schema' => 'HONAM',
    'port'  => 1521
], 'default');
```

**Comment by manuzcom** [comment]
i fix it. 

i follow this.
https://yajrabox.com/docs/laravel-oci8/master/stand-alone

$db = new Oci8Connection($connection, $config["database"], $config["prefix"]);
to
$db = new Oci8Connection($connection, $config["database"], $config["prefix"], $config);
fix it.

now is ok.

**Comment by yajra** [comment]
What version are you using? I think you are using a lower version of the package. Please update to the latest.

**Comment by yajra** [comment]
OIC, glad you sorted this out. Thanks!

**Comment by manuzcom** [comment]
@yajra i'm using latest version.
