### ISSUE TITLE
Trouble using find or findOrFail when id is a string

### ISSUE THREAD

**Issue by jesusvpct** [yajra/laravel-oci8#312]
### Summary of problem or feature request
~~When I have a field ID on a table defined as Varchar2, when executing find or findOrFail , it hangs the application forever.~~

Sorry! I was using a VIEW not a Table!

### Code snippet of problem
$person = $person = Person::whereId('a123456T')->get(); // This works, returns a collection
$person = Person::where('id', 'a123456T')->get()->first(); // This works
$person = Person::find(''a123456T''); // This hangs forever
$person = Person::findOrFail(''a123456T''); // This hangs forever

### System details
- Operating System: Windows 7 64 bit
- PHP Version: 7.0.13
- Laravel Version: 5.4.27
 - Laravel-OCI8 Version: 5.4.11

**Comment by yajra** [comment]
I think this is a Laravel behavior where id is being **casted to integer** when using `find/findOrFail`. Maybe you should use `firstOrFail` instead.
