### ISSUE TITLE
Oracle Custom Sequence

### ISSUE THREAD

**Issue by jhjm32087** [yajra/laravel-oci8#315]
### Summary of problem or feature request

While using custom Oracle Sequences the property defined in OracleEloquent Class is set to protected, but in OracleProcessor->incrementBySequence function and it's attempting to call a property outside the scope and its return null. Either the OracleEloquent->sequence property would need to public or OracleProcessor namespace would need to be adjusted.
```php
class Contract extends Model
{
    protected $table = 'contract';
    public $timestamps = false;
    protected $primaryKey = 'contract_id';
    public $sequence = 'contract_contract_id_seq';
}
```
### System details

- Operating System Linux
- PHP Version 7.0.x
- Laravel Version 5.4
- Laravel-OCI8 Version 12.x

**Comment by yajra** [comment]
Patch released on v5.4.13. Thanks!
