### ISSUE TITLE
Cannot using php artisan migrate properly

### ISSUE THREAD

**Issue by akbarilhamk** [yajra/laravel-oci8#317]
### Summary of problem or feature request

Hi Yajra, Thank you for the brilliant package.

I'm a newbie in Oracle database and i'm trying to combine Oracle database to my Laravel. I need to queue process in laravel, when i try to **php artisan migrate** I'm getting the following error: 

`  [Illuminate\Database\QueryException]
  Error Code    : 942
  Error Message : ORA-00942: table or view does not exist
  Position      : 75
  Statement     :
              create trigger migrations_id_trg 
              before insert on migrations
              for each row
                  begin 
              if :new.id is null then
                  select migrations_id_seq.nextval into :new.id from dual;
              end if;
              end;
 Bindings      : []
   (SQL:
              create trigger migrations_id_trg
              before insert on migrations
              for each row
                   begin
              if :new.id is null then
                  select migrations_id_seq.nextval into :new.id from dual;
              end if;
              end;)`

The question is: Is it possible to using php artisan migrate in composer directly?

### Code snippet of problem

![image](https://user-images.githubusercontent.com/25839296/28657825-e6326788-72d2-11e7-9248-0b6e4f8deec4.png)

### System details

- Windows 10 Pro
- PHP 5.6
- Laravel 5.4
- Laravel-OCI8 "yajra/laravel-oci8": "5.4.*",

**Comment by mstaack** [comment]
artisan migrate works perfectly for me.  must be something on your site...
how does your migration looks like?

usually you wont create triggers on normal table creation

cheers max

**Comment by kidznapper** [comment]
Hi Max, thanks for the replied..

First, i created migration using **php artisan queue:table**
Second, i also created migration using **php artisan queue:failed-table**
After that, i'm getting the following error as i mentioned it.

I have disabled all the triggers in this database before i run **php artisan migrate**

**Comment by mstaack** [comment]
do you have different connections ?
`table or view does not exist` means you are on the wrong connection
