### ISSUE TITLE
Using laravel-oci8 in Laravel console command??

### ISSUE THREAD

**Issue by nhurock** [yajra/laravel-oci8#322]
### Summary of problem or feature request

Normally, i use **laravel-oci8** connect to Oracle DB is success. However, i'm using schedule task of Laravel with console command, its not worked, error: Call to undefined function Yajra\Pdo\oci_connect()

Please help me, thanks guys :D

### Code snippet of problem

Call to undefined function Yajra\Pdo\oci_connect()

My code:

use Illuminate\Support\Facades\DB;
use PDO;

 $pdo = DB::Connection('oracle')->getPdo();

### System details

- Win server 2008 R2
- Wamp
- PHP: 5.6
- Laravel Version: 5.4
- Laravel-OCI8: 12

**Comment by sciracioglu** [comment]
me toooo

**Comment by yajra** [comment]
Make sure you oci8 extension enable on php cli config. You check using this command:

```bash
php -m | grep oci8
php -i | grep oci8
```

**Comment by sciracioglu** [comment]
i m using php-fpm
i think the problem is..

**Comment by nhurock** [comment]
@yajra thank for your reply.  I'm sure, i enabled oci8 extentions (php_oci8_12c.dll, php_pdo_oci.dll)

**Comment by yajra** [comment]
Note that some php installations (especially fpm) have two `php.ini`. One for `fpm` and the other is for `cli`. You need to have oci8 extension enable on both config.

To find which config your cli uses: `php -i | grep php.ini`.

**Comment by sciracioglu** [comment]
Thank you very much.
		
		

		iOS için Outlook uygulamasını edinin
	




On Fri, Aug 4, 2017 at 8:13 AM +0300, "Arjay Angeles" <notifications@github.com> wrote:












Note that some php installations (especially fpm) have two php.ini. One for fpm and the other is for cli. You need to have oci8 extension enable on both config.


To find which config your cli uses: php -i | grep php.ini.

**Comment by mstaack** [comment]
yeah usually you are missing extension=oci8  in one of your inis..

check `php --ini` to find them ;)
