### ISSUE TITLE
Rollback Command Failing When DB Config set to fetch PDO::FETCH_ASSOC

### ISSUE THREAD

**Issue by blackdrago** [yajra/laravel-oci8#323]
When I run php artisan migrate:rollback, I am getting this error:

[ErrorException]
Trying to get property of non-object

The log has the following:
[2017-08-02 14:56:35] local.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/html/customware/vendor/yajra/laravel-oci8/src/Oci8/Schema/OracleAutoIncrementHelper.php:150

I've attached the rest of the error log for this. It seems like it is trying to drop autoincrement objects and trying to get the primary key of a table called chemlists_settings. This table doesn't have a primary key nor an autoincrement. Could this be the issue? 

[log-rollbackissue.txt](https://github.com/yajra/laravel-oci8/files/1194313/log-rollbackissue.txt)

**Comment by blackdrago** [comment]
As an experiment, I removed the script that deals with that particular table and tried to migrate/rollback the database. I received the same exact error for a different table that has a primary key, auto-incrementation, and a sequence. 

These are the same scripts I was migrating and rolling back about two weeks ago. They worked fine then, but they're currently failing on rollback, even if I start the DB from scratch.

**Comment by blackdrago** [comment]
I've recently discovered that switching my database settings from PDO::FETCH_ASSOC to PDO::FETCH_OBJ (back to the default setting) enables the rollback command to work again.

I'm not sure why this setting breaks Oci8, but can it be fixed? My entire application is set to PDO::FETCH_ASSOC for a reason.

**Comment by yajra** [comment]
I think this is because the Oracle increment helper assumes that the framework uses object as indicated on this code https://github.com/yajra/laravel-oci8/blob/5.4/src/Oci8/Schema/OracleAutoIncrementHelper.php#L150.

Also, afaik, I think laravel framework has already dropped the support for fetch type and defaults to PDO::FETCH_OBJ since 5.4?

Anyways, maybe you can try the code below? If it works, then maybe we can implement it.

**FROM**
```php
if (count($data)) {
    return $data->column_name;
}
```

**TO**
```php
if (count($data)) {
    return $data['column_name'] ?: $data->column_name;
}
```

**Comment by mstaack** [comment]
@yajra yeah they switched to fetch object
