### ISSUE TITLE
Database [oracle] not configured.

### ISSUE THREAD

**Issue by techno46** [yajra/laravel-oci8#326]
hai.. I confuse for this problem , when I try to edit /config/oracle.php or /config/database.php .. and always get message "Database [oracle] not configured."
like this picture
![image](https://user-images.githubusercontent.com/6767399/29354998-8e9a37a4-8299-11e7-9fa7-dfd8c256789f.png)

I try test connection with this in controller:

$tes = DB::connection('oracle')->table('nas_voc_result');      
dd($tes); 

and DB configuration in database.php or oracle.php:

'oracle' => [
        'driver'        => 'oracle',
        'tns'           => env('DB_TNS', '(DESCRIPTION = (ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP) (HOST = 127.0.0.1) (PORT = 1521)))(CONNECT_DATA =(SERVICE_NAME = pranpc)))'),
        'host'          => env('DB_HOST', '127.0.0.1'),
        'port'          => env('DB_PORT', '1521'),
        'database'      => env('DB_DATABASE', 'pranpc'),
        'username'      => env('DB_USERNAME', 'secret'),
        'password'      => env('DB_PASSWORD', 'secret'),
        'charset'       => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'        => env('DB_PREFIX', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
    ],

thanks for help

**Comment by sciracioglu** [comment]
'oracle'      => [
   'driver'       => 'oracle',
   'host'         => 'host_ip',
   'port'         => '1521',
   'database'     => 'orcl',
   'service_name' => 'orcl',
   'username'     => 'secret',
   'password'     => 'secret',
   'charset'      => 'AL32UTF8',
   'prefix'       => '',
],

**Comment by yajra** [comment]
@techno46 make sure you register the service provider first to register the oracle driver?

On `config/app.php` add `Yajra\Oci8\Oci8ServiceProvider::class,`.

**Comment by techno46** [comment]
thanks @sciracioglu @yajra 

I've found that problem .. when i check with terminal php -v /or  php artisan config:cache  and I get message
PHP Warning: Module 'oci8' already loaded in Unknown on line 0
..
this problem because the oci8 module is already build in the binary of php

thanks for help.. 👍 👍 👍
