### ISSUE TITLE
Eager loading model's many-to-many relationship not working + weird side effects

### ISSUE THREAD

**Issue by cyberbit** [yajra/laravel-oci8#327]
### Summary of problem or feature request

When attempting to eager load a many-to-many relationship via `with()`, all primary models are loaded with empty relationship keys. See example below.

### Code snippet of problem

App\User.php
```php
class User extends Authenticatable
{
    use Notifiable;
    
    protected $primaryKey = "idusers";

    public $timestamps = false;

    public function groups() {
        return $this->belongsToMany(Group::class, "GROUPS_USERS", "IDUSERS", "IDGROUPS");
    }
}
```

App\Group.php
```php
class Group extends Model
{
    protected $primaryKey = "idgroups";
    protected $table = "T_GROUPS";
    
    public $timestamps = false;
}
```

Eager loading (not working):

```php
Route::get('/user/{id}', function($id) {
    $user = App\User::find($id)->with("groups")->get();

    // This also doesn't work
    $user = App\User::find($id);
    $user->load("groups");
    
    return response()->json(["user" => $user]);
});
```

This code produces output similar to this for `example.com/user/99`:
```
{
    "user": [
        {
            "idusers": 1,
            "username": "testuser",
            "fullname": "Test User",
            "email": "test.user@example.com",

            // ...
            // more attributes
            // ...

            "groups":[]
        },

        // ...
        // 100's more User models with empty groups keys
        // ...
    ]
}
```

This loads the `groups` relation correctly:
```php
Route::get('/user/{id}', function($id) {
    $user = App\User::find($id);
    $user->groups; // Touches the relation
    
    return response()->json(["user" => $user]);
});
```

Output for `example.com/user/99`:
```
{
    "user": {
        "idusers": 99,
        "novellid": "ciwolf",
        "fullname": "Chad Wolf",
        "email": "chad.wolf@example.com",

        // ...
        // more attributes
        // ...

        "groups": [
            {
                "idgroups": 49,
                "name": "Business Group",
                "description": "All work and no play",

                // ...
                // more attributes
                // ...

                "pivot": {
                    "idusers": "99",
                    "idgroups": "49"
                }
            },
            
            // ...
            // several more Group models
            // ...
        ]
    }
}
```

### System details

- Operating System: Ubuntu 16.04.2
- PHP Version: 7.1.7
- Laravel Version: 5.4.33
- Laravel-OCI8 Version: 5.4.13

**Comment by Bleno** [comment]
@cyberbit  Any solution ?

**Comment by cyberbit** [comment]
@Bleno I think there's actually an oversight in my code. This is one of the lines I used in the code:

```php
$user = App\User::find($id)->with("groups")->get();
```

But calling `App\User::find()` returns an Eloquent model, which then gets treated as a query builder when `with()` is called, causing _all_ models to be returned instead of just the one I was looking for. I was just starting to poke around with Laravel at this point, so I didn't know any better. Later projects I have worked on have revealed this behavior, and it's not limited to laravel-oci8.

I am no longer a part of the project for which this was an issue, so I don't have an ability to test the below potential solution, but it may be useful to you. Instead of using `find()`, you could try using `where()` to get a fluent query builder that respects the criteria you want when eager loading:

```php
$user = App\User::where('idusers', $id)->with('groups')->first();
```

YMMV, but I have used this structure on other projects and it does work with MySQL.

**Comment by yajra** [comment]
@cyberbit I think the query you used is indeed a bit wrong. I think the correct way to do this is:

```php
$user = App\User::with("groups")->find($id);
```
