### ISSUE TITLE
Laravel Passport authentication not working with laravel-oci8 but working with MySQL

### ISSUE THREAD

**Issue by gvgvgvijayan** [yajra/laravel-oci8#336]
### Laravel Passport authentication failed

I tried to create passport outh authentication for token verification during rest calls. It is working with MySQL but not with Oracle (using laravel-oci8 library)

### Code snippet of problem
```Route::post('/details', 'UserController@details')->middleware('auth:api');```
### System details

- Operating System: Windows Server 2012
- PHP Version - 7.1
- Laravel Version - 5.4
- Laravel-OCI8 Version - 5.4

**Comment by yajra** [comment]
Oracle authentication is case sensitive. Make sure you uses the same case for email & password. 

On the other hand, you can also use [OracleUserProvider](https://github.com/yajra/laravel-oci8#laravel-52-oracle-user-provider) to make case insensitive.

**Comment by gvgvgvijayan** [comment]
```
'providers' => [
        'users' => [
            'driver' => 'oracle',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

I used the above and checked it again. But **Unauthenticated** problem still persist. It's not solved authentication problem.

**Comment by ChaosPower** [comment]
```php
Route::post('/details', 'UserController@details')->middleware('auth:api');
```
can be

```php
Route::post('details', 'UserController@details')->middleware('auth:api');
```
your ```auth.php``` try it to be eloquent.

```php

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model'  => App\User::class,
        ],
    ],
```
Do not forget to ```php artisan migrate``` and ```php artisan passport:install```

**Comment by gvgvgvijayan** [comment]
Still it's not working so now I'm using https://github.com/tymondesigns/jwt-auth which is working properly with Oracle.

**Comment by yajra** [comment]
Now supported on Laravel 5.6 version out of the box via #391.
