### ISSUE TITLE
Invalid Identifier on reserved word

### ISSUE THREAD

**Issue by sakaye** [yajra/laravel-oci8#341]
### Summary of problem or feature request

I am getting this error with a fresh install of Laraval 5.5. I was browsing the other issues and saw the request to change all reserved words to uppercase.

In my database the password column is shown as lowercase in SQL Developer. 

I changed line 216 to:
$value = $this->isReserved($value) ? Str::lower($value) : Str::upper($value);

This seems to have fixed the problem for now. 

I've been using the 5.4 package with another Laravel 5.4 install with no issues.

### Code snippet of problem

  [Yajra\Pdo\Oci8\Exceptions\Oci8Exception]
  Error Code    : 904
  Error Message : ORA-00904: "PASSWORD": invalid identifier

insert into "USERS" ("NAME", "EMAIL", "PASSWORD", "ADMINISTRATOR", "DEPARTMENT", "UPDATED_AT", "CREATED_AT") values (:p0, :p1, :p2, :p3, :p4, :p5, :p6) returning "ID" in
  to :p7

### System details

- PHP Version >=7.0.0
- Laravel Version 5.5
- Laravel-OCI8 Version 5.5

**Comment by yajra** [comment]
@sakaye unfortunately you have to manually update the reserved columns to uppercase `"PASSWORD"` for it to work. Making it uppercase will prevent us from issues like I think on relationships where reserved word are used for the relation. Also, using uppercase is more compatible with oracle as per testing.

**Comment by sakaye** [comment]
@yajra Thanks. Making that manual change worked.
