### ISSUE TITLE
Issue with laravel 5.3+ (int -> string in Grammar)

### ISSUE THREAD

**Issue by ircop** [yajra/laravel-oci8#346]
This issue is more laravel-related, but maybe you can avoid it by extending some laravel classes...
So:

When joining some oracle table with raw numeric value, Laravel, starting from 5.3, mutates integer value into string. Oracle throws an ORA-00904 (invalid identifier) error.

### Code snippet of problem

```php
$query->join('SOMETABLE', function($join){
    $join->on('SOMETABLE.A', '=', 'BASETABLE.B');
    $join->on('SOMETABLE.B', '=', 123456);  # <---- here is the problem
});
```

Error Message : ORA-00904: "50136901": invalid identifier

### details

The problem is in Query\Builder::toSql() -> Database\Grammar::wrap( $value, $prefixAlias = false )

The wrap() result is always string, even if integer given.

The simple way is to patch it with something like " if( is_int($value) ) return $value "

**Comment by ircop** [comment]
Confirmed with Laravel 5.5

Laravel's contributors answer: "Oracle is not officially supported by Laravel" :(

**Comment by yajra** [comment]
@ircop I feel you there. I mostly get the same response that oracle is not officially supported :).

Anyways, have you tried using `DB::raw()` as a workaround?

```php
$query->join('SOMETABLE', function($join){
    $join->on('SOMETABLE.A', '=', 'BASETABLE.B');
    $join->on('SOMETABLE.B', '=',DB::raw(123456));  # <---- here is the problem
});
```

**Comment by ircop** [comment]
Yes, but the problem is that I have tons of code written for <=5.2, and refactoring it because of this little issue doesnt looks like a good idea.

In addition, changing the type of the passed variable inside function does not look good in itself, especially in the light of the trends of php - strict types, type hints
