### ISSUE TITLE
Error by install on Laravel 5.5.3

### ISSUE THREAD

**Issue by cschoeni** [yajra/laravel-oci8#353]
### Summary of problem or feature request
If I install the package on a new laravel installation, I get this error message.

### Code snippet of problem
Error after composer install

```bash
schoeni at Christophs-Air in ~/Projects/PHP/Laravel/template
$ composer require yajra/laravel-oci8:"5.5.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yajra/laravel-oci8 v5.5.3 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.2 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.1 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 v5.5.0 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - Installation request for yajra/laravel-oci8 5.5.* -> satisfiable by yajra/laravel-oci8[v5.5.0, v5.5.1, v5.5.2, v5.5.3].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/7.1/php.ini
    - /usr/local/etc/php/7.1/conf.d/php-memory-limits.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by mstaack** [comment]
@cschoeni you need to install and enable the oci8 extension for php.

for debian based systems you can have a look here to install it:
https://github.com/yajra/laravel-oci8/blob/5.5/oci8.sh

for mac a quick google search showed: 
https://gist.github.com/krisanalfa/09b765bb95012cd36fbd

so its a problem on your side.

cheers max

**Comment by NankoPrinzhorn** [comment]
Ok, so i have the same problem.

To fix it i had to install oracle instant client and an NTS dll of oci8_12g

when i start my WAMP i get this error:

[20-Feb-2018 13:40:38 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'd:/wamp64/bin/php/php5.6.31/ext/php_oci8_12c.dll'

 in Unknown on line 0

What do i do?

**Comment by mstaack** [comment]
@NankoPrinzhorn please look up php oci8 installation for apache. it's a problem on your side.
