### ISSUE TITLE
Option to remove 'rn' from result

### ISSUE THREAD

**Issue by karunkshrestha** [yajra/laravel-oci8#359]
### Excluding 'rn' attribute from result.

Is there an option to exclude the 'rn' attribute from the result? I am doing a post result clean up like so to remove it.

`
foreach ($rows as $key => $row) {
                    $data[] = array_except((array)$row,'rn');
                }
`
This is just to improve performance when dealing with large data sets.

- Laravel Version 5.5
- Laravel-OCI8 Version 5.5

**Comment by mstaack** [comment]
@karunkshrestha no this is how oracle handles rownums/pagination. 
you can use something like https://github.com/thephpleague/fractal to remove/cleanup your responses
