### ISSUE TITLE
Laravel OCI8

### ISSUE THREAD

**Issue by zender65** [yajra/laravel-oci8#360]
### Summary of problem or feature request

 Problem 1
    - yajra/laravel-oci8 v5.5.3 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-OCI8 Version

**Comment by mstaack** [comment]
this is a well known issue for new php oracle developers...
you need to install oci extension on your system
have a look here https://github.com/yajra/laravel-oci8/issues/353
