### ISSUE TITLE
Oracle error over the "level" reserved word

### ISSUE THREAD

**Issue by Gaven-ar** [yajra/laravel-oci8#362]
### Summary of problem or feature request

I've got an Oracle error when I run the next Laravel authorization instruction:

`$this->authorize('anAbilityName');`

Seems like this method derivate in a big SQL query and arise this Oracle error at runtime:

> ORA-01788: CONNECT BY clause required in this query block

I found out that **the error comes from referencing a column named "level" without quotes in one of the two ocurrences, in the query**.
A fragment of the generated query is below in "_Code snippet of problem_" section.
For Oracle DataBases, "level" is a reserved word. And **the problem is solved if I run the whole query directly in DataBase, with quotes around that column name** (2nd ocurrence).

**How is it possible to fix the generated query syntax?**

PS: I would not asking for help if I could rename that Database column.

### Code snippet of problem

[...] `or "level" < (select max(level) from` [...]

### System details

- Operating System: Windows 10
- PHP Version: 5.6.3
- Laravel Version: 5.2
- Laravel-OCI8 Version: 5.2

**Comment by yajra** [comment]
@Gaven-ar on `OracleReservedWords` class, can you try commenting out the `LIMIT` keyword and check if it will work?

**Comment by yajra** [comment]
BTW, I think this kind of issue will be fixed on Laravel 5.5 version as all reserved words are converted to uppercase. If you can, I suggest you upgrade to 5.5 if possible. Thanks!

**Comment by Gaven-ar** [comment]
I updated the post title and the content, because I came to this situation with the "level" reserved word, and not "limit". So I correct de text. Anyway, is the same situation.

I tried commenting out the "LEVEL" keyword in the class `OracleReservedWords` but it didn't fix the issue.

I will consider upgrade to Laravel 5.5, but for now seems like there is no solution.
