### ISSUE TITLE
Error 904 (invalid identifier) after upgrading to v5.5.3

### ISSUE THREAD

**Issue by joelcuevas** [yajra/laravel-oci8#366]
After upgrading to laravel-oci8 v5.5.3 from v5.4.18, I'm getting the following error:

```
Error Code    : 904 
Error Message : ORA-00904: "PASSWORD": invalid identifier Position      : 19 
Statement     : update "USERS" set "PASSWORD" = :p0, "UPDATED_AT" = :p1 where "ID" = :p2 
Bindings      : [$2y$10$Hlx2aMSoA1IcOQ8JlwziMAm4um01qXGeXSnFKc4T6D0ebnjMrtzzK,2017-10-18 18:59:49,3] 
(SQL: update "USERS" set "PASSWORD" = $2y$10$Hlx2aMSoA1IcOQ8JlwziMAm4um01qXGeXSnFKc4T6D0ebnjMrtzzK, "UPDATED_AT" = 2017-10-18 18:59:49 where "ID" = 1)
```

I'm pasting verbatim from Laravel default error page.

And this is the migration that created the table:

```php
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->string('username')->unique();
    $table->string('name');
    $table->string('email')->nullable();
    $table->tinyinteger('profile')->default(0);
    $table->string('password');
    $table->rememberToken();
    $table->timestamps();
});
```

Exactly the same code was working before upgrading. Do I need to do some changes on my code? I didn't found nothing on the docs.

### System details

- Operating System: Ubuntu 16.04.2 LTS / Windows Server 2012 R2 Standard
- PHP Version: 7.1
- Laravel Version: 5.5.17
- Laravel-OCI8 Version: 5.5.3

**Comment by yajra** [comment]
@joelcuevas unfortunately as of 5.5, reserved words are converted to uppercase to have a better compatibility with oracle. In this regard, you need to update all the reserved words column manually to uppercase. For this instance, `password` should be updated on the database level as `PASSWORD` from `"password"`. Thanks!

**Comment by yajra** [comment]
For the docs, it was only added on [changelog](https://github.com/yajra/laravel-oci8/blob/5.5/CHANGELOG-5.5.md#changed). Will try to create an upgrade guide when I got the chance. Thanks!
