### ISSUE TITLE
Usage in standalone instance of Illuminate/Database

### ISSUE THREAD

**Issue by aGrmbl** [yajra/laravel-oci8#37]
Hello,

While trying to use standalone Illuminate/Database with OCI8 I run into errors related to missing "oracle" driver.

At the first glance it looks like one needs to set up Laravel application to register OCI service provider etc.

Is there a way to use OCI support for standalone DB usage?

**Comment by WRLin** [comment]
// Set the event dispatcher used by Eloquent models... (optional)
use Illuminate\Events\Dispatcher;
use Illuminate\Container\Container;
$capsule->setEventDispatcher(new Dispatcher(new Container));

// Make this Capsule instance available globally via static methods... (optional)
$capsule->setAsGlobal();

**Comment by yajra** [comment]
thanks!
