### ISSUE TITLE
call a function oracle with date params

### ISSUE THREAD

**Issue by oohdeveloper** [yajra/laravel-oci8#370]
I tried to execute this code:

`$date = DB::selectOne("select f_recibo_fec_ultpago(36601,'2017/10/23') from dual");`

but, it is not working. give me this error.
"""
Error Code    : 1861\r\n
Error Message : ORA-01861: literal does not match format string\n
ORA-06512: at "AMERIKA.F_RECIBO_FEC_ULTPAGO", line 4\r\n
Position      : 7\r\n
Statement     : select f_recibo_fec_ultpago(36601,'2017/10/23') from dual\r\n
Bindings      : []\r\n
 (SQL: select f_recibo_fec_ultpago(36601,'2017/10/23') from dual)
"""
I execute the function in sql developer and it works just fine. I do not what i'm doing wrong.

I'm using laravel 5.5 and the same laravel-oci8 version. 
Sorry bad english.

**Comment by yajra** [comment]
@oohdeveloper the default date format that we are using is `RRRR-MM-DD HH24:MI:SS`. You need to follow this format when working with dates.

```php
$date = DB::selectOne("select f_recibo_fec_ultpago(36601,'2017-10-23') from dual");
```

If you want to alter the date format, see this [doc](http://yajrabox.com/docs/laravel-oci8/master/date-format).

**Comment by oohdeveloper** [comment]
yes, i tried to use that to but it apears an error.

"Call to undefined method Illuminate\Database\MySqlConnection::setDateFormat()".

And in the doc does not say if a have to import something else.

**Comment by mstaack** [comment]
@oohdeveloper looks like you are not on an oracle connection! fix that first...you are using mysql there ;)
