### ISSUE TITLE
OCI-Lob Error when using ROWID

### ISSUE THREAD

**Issue by mybigman** [yajra/laravel-oci8#373]
Querying a table that has a field data type of "ROWID" generates the following error.

```
Illuminate\Database\QueryException with message
PHP Warning:  OCI-Lob::load(): OCI_INVALID_HANDLE in /var/www/laravel53/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8/Statement.php on line 354
```

Source code at error.
```
// convert LOB to string
if ($this->returnLobs && is_object($value)) {
    $object->$field = $value->load(); ### LINE 354
} else {
    $object->$field = $value;
}
```
This is a vendors database, therefore I have no permissions to make changes on their DB.

Laravel Version - 5.3.31
"yajra/laravel-oci8": "^5.3",

Can this be resolved?

Thanks

**Comment by yajra** [comment]
Can you please provide some snippet to reproduce the issue? Will try check this as soon as I can. Thanks!

**Comment by mybigman** [comment]
Hi Yajra,

It was just a standard select statement.

```
select col1, col2, col3 from table
```
If I leave out the col that has the data type of "ROWID" then the query works successfully.

**Comment by cartbeforehorse** [comment]
I have the same issue.  Simply creating a scope as follows (then calling the scope from the Controller):

    public function scopeGetAll ($query)
    {
        return $query -> select() -> where ('supplier_id','200') -> get();
    }

If I do:

        return $query -> select('rowid') -> where ('supplier_id','200') -> get();

I get the same error.  If I do:

        return $query -> select('rowidtochar(rowid) rowid') -> where ('supplier_id','200') -> get();

it works fine.

I think that strictly speaking, this is an error in the Oracle driver that it doesn't do the conversion correctly.  However, it would be wonderful if we could work-around the error in this vendor-component.

**Comment by cartbeforehorse** [comment]
I've been looking at this in a bit more detail this morning, and the more I look, the deeper the problem seems to become.  I've come up with a couple of ideas that I'm finding difficult to verify, because of the (apparently) fundamental nature of the problem:

1. Is the problem specific to Windows?  I'm using Windows 7 as my development platform - can't speak for @mybigman of course
2. Is the problem due to an incompatibility between 32-bit Oracle Client, and 64-bit Oracle DB?
3. Is this related somehow to NLS_LENGTH_SEMANTICS.  On the database the value has been set to CHAR, but if the session is connecting as BYTE, it could confuse the OCI driver as to where the EOF character lies.  [How would I verify NLS parameters for the PHP session??]

All these points might be completely irrelevant of course :-/

**Comment by mybigman** [comment]
I know it probably doesn't help but I am using Debian 7.11

As for the Oracle environment I couldn't tell you without jumping through hopes with the vendor to find out.

**Comment by yajra** [comment]
I was able to replicate the issue. Will try to fix / support `rowid` as soon as I can. Thanks!

**Comment by yajra** [comment]
As per this [bug report](https://bugs.php.net/bug.php?id=41996), we can use a workaround atm using `ROWIDTOCHAR` function:

```php
DB::table('users')->selectRaw('ROWIDTOCHAR(rowid) as "rowid"')->get()
```

**Comment by yajra** [comment]
Based on this [post](http://grokbase.com/t/php/php-db/011qkkhp7e/oracle-oci8-and-rowid):

>rowid is an opaque datatype in php. you cannot "output" it
but only use it for further processing using ocibindbyname().

This answer is in-sync with the example on [php.net](http://php.net/manual/en/function.oci-new-descriptor.php).
```php
$conn = oci_connect($user, $password);
$stmt = oci_parse($conn, "select rowid from $table $where");
$rowid = oci_new_descriptor($conn, OCI_D_ROWID);
oci_define_by_name($stmt, "ROWID", $rowid);
oci_execute($stmt);
while (oci_fetch($stmt)) {
    $nrows = oci_num_rows($stmt);
    $delete = oci_parse($conn, "delete from $table where ROWID = :rid");
    oci_bind_by_name($delete, ":rid", $rowid, -1, OCI_B_ROWID);
    oci_execute($delete);
    echo "$nrows\n";
    if (($nrows % $commitsize) == 0) {
        oci_commit($conn);
    }
}
$nrows = oci_num_rows($stmt);
echo "$nrows deleted...\n";
oci_free_statement($stmt);
oci_close($conn);
```

Given this findings, I think the only solution here is to use the `ROWIDTOCHAR` function.
