### ISSUE TITLE
Cannot run php artisan migrate

### ISSUE THREAD

**Issue by mohd-aidi** [yajra/laravel-oci8#381]
### Summary of problem or feature request
When i use command change() to change the column size or type, it return error cannot find column name.

### Code snippet of problem

 C:\xampp\htdocs\mbpj-elesen>php artisan migrate
Migration table created successfully.
                                                
  [Doctrine\DBAL\Schema\SchemaException]                                    
  There is no column with name 'saiz_meja' on table 'el_permit_sementara'.  

```

Schema::connection($this->connection)->table('permit_sementara', function(Blueprint $table) {
            $table->string('saiz_meja', 100)->change();
        });

```

### System details

- Operating System = Windows 10 64bit
- PHP Version = PHP 7.0.22 (cli) (built: Aug  1 2017 14:13:55) ( ZTS )
- Laravel Version = 5.1.*
- Laravel-OCI8 Version = 5.1.*

**Comment by mstaack** [comment]
did you recheck that this column exists in your table?..the error message is clearly!
or are you on the wrong connection?

**Comment by mohd-aidi** [comment]
what is clear? if i didnt use function change, the migration run smooth...but when i include the change() it display error..

and yes i do check the table is exist and i'm not in the wrong connection since i can do other thing very well...

**Comment by mohd-aidi** [comment]
how about you respect the bug report and try to proof me wrong by create the migration...im not on the enemy side here...

**Comment by yajra** [comment]
@mohd-aidi were you able to install the required doctrine package as per laravel [docs](https://laravel.com/docs/5.5/migrations#modifying-columns)?

**Comment by yajra** [comment]
Will try to replicate this later if I can.

**Comment by mohd-aidi** [comment]
@yajra yes all required packages is installed successfully..i can run my system without any complication only function change() cannot be run in migration.

i use mysql also in my server and it migrate the change function well.
