### ISSUE TITLE
"password" invalid identifier

### ISSUE THREAD

**Issue by omankopyor** [yajra/laravel-oci8#385]
### Summary of problem or feature request

I'm building an app using laravel with an oracle database. I have a problem with insert user to the database.
![db_user](https://user-images.githubusercontent.com/29575168/33920301-ce821158-dfef-11e7-960d-9eec7adb3cd1.PNG)
![query_insert_users](https://user-images.githubusercontent.com/29575168/33920302-ceceb9ea-dfef-11e7-8106-d59f38f96d7b.PNG)

I have replaced the "password" with "PASSWORD" in the database.
is there my code wrong?
why only the password field is lowercase?

### System details

- Debian 8.8
- PHP 5.6
- Laravel 5.4
- Laravel-OCI8 5.4.*

**Comment by yajra** [comment]
@omankopyor on version 5.4 & below, oracle reserved words are forced to use lowercase like for this instance `PASSWORD` in added as `"password"`.

If your app is new, I suggest you use 5.5 as it uses uppercase on reserved words that fixes this kind of issue. Thanks!

**Comment by omankopyor** [comment]
@yajra I am not ready to use laravel 5.5 because of some things. any other suggestions for this password field to be uppercase in adding user? I've made changes in the create user code with a capital letter, but no changes have occurred

**Comment by yajra** [comment]
Are you using migration the migration? Maybe try using `DB::raw('password')`. However, not sure if this may affect the login function, etc where password is used since the package converts this field to lowercase.

**Comment by omankopyor** [comment]
I use migration to create tables. the login function runs fine and there is no problem. only on adding the user password field to lowercase

**Comment by yajra** [comment]
Does raw works?
```php
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->string('email');
    $table->string('first_name');
    $table->string('last_name');
    $table->string(DB::raw('password'), 60);
    $table->rememberToken();
    $table->timestamps();
});
```

Or try this too:
```php
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->string('email');
    $table->string('first_name');
    $table->string('last_name');
    $table->string('"PASSWORD"', 60);
    $table->rememberToken();
    $table->timestamps();
});
```

**Comment by omankopyor** [comment]
there is no problem in creating tables. this is my code in user creation
`User::create([
    'first_name' => strtoupper($data['first_name']),
    'email' => strtolower($data['email']),
    'password' => bcrypt($data['password'])
]);`

**Comment by omankopyor** [comment]
when I replace the "PASSWORD" field to "PASSWORD_KEY" there is no problem in filling the data. but there is a problem with the login

**Comment by yajra** [comment]
I see, this is what I also refer to on:
> However, not sure if this may affect the login function, etc where password is used since the package converts this field to lowercase.

Since the package converts the reserved words to `"password"`. If you really need this to be uppercase, I suggest you fork the package, and uncomment the [PASSWORD](https://github.com/yajra/laravel-oci8/blob/5.4/src/Oci8/OracleReservedWords.php#L317) value on reserved words. Then use your own fork. We can't released that change cause it may break other installations.

**Comment by omankopyor** [comment]
ok. i will find it. thank you for your answers

**Comment by omankopyor** [comment]
hy @yajra  I have done uncomment the PASSWORD value on reserved words. It work. no login function effect. thanks
