### ISSUE TITLE
[PDO] Wrong return type.

### ISSUE THREAD

**Issue by seminsergey** [yajra/laravel-oci8#386]
**Summary of problem or feature request**

Bind parameter of type int returned as a string.

path: /vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8/Statement.php

**Code snippet of problem**

```
  case PDO::PARAM_INT:
      $ociType = **SQLT_LNG;**
      break;
```
 **update on**
```

 case PDO::PARAM_INT:
      $ociType = **SQLT_INT;**
      break;

```
- Ubuntu 16.04.2 LTS
- PHP 7.1
- Lumen 5.5.2
- Laravel-OCI8 5.5.5

**Comment by yajra** [comment]
@seminsergey can you please send a PR for the fix on https://github.com/yajra/pdo-via-oci8 repo. Thanks!

**Comment by yajra** [comment]
Just remember that a https://github.com/yajra/pdo-via-oci8/pull/42 PR was merged and is directly related to this. Reverting the PR in favor of this.

**Comment by yajra** [comment]
Please update pdo-via-oci8 to v1.3.6, thanks for reporting.
