### ISSUE TITLE
Illegal offset type in Oci8ServiceProvider.php:48

### ISSUE THREAD

**Issue by BaronVonPerko** [yajra/laravel-oci8#388]
### Summary of problem or feature request

We have an application growing in users, and have started seeing this error.  It seems that our persistent connection is getting dropped for many users.  The temporary fix we have is to restart the webserver.  It doesn't happen all of the time and is difficult to reproduce.

Is there a way to recycle or restart the lost connections?  

### System details

- Operating System - RedHat Enterprise Linux 6.7
- PHP Version - 7.0
- Laravel Version 5.5
- Laravel-OCI8 Version 5.5

**Comment by yajra** [comment]
There was a recent [PR](https://github.com/yajra/laravel-oci8/pull/368) that address this issue. Are you using the latest version?

**Comment by BaronVonPerko** [comment]
Awesome. I believe we are releasing an update to production tomorrow evening. I'll make sure we get the latest version and will monitor it. Thanks!
