### ISSUE TITLE
Does Laravel-OCI8 support UTF-8 ? 

### ISSUE THREAD

**Issue by mansouralex** [yajra/laravel-oci8#39]
Hello Arjay, we tried to post Arabic data to the oracle database but we found that the data isn't in the correct Arabic language. The problem caused in the save operation (Laravel receives the data correctly). 

If we enter the data from navicat for oracle the data saves correctly.

what we have to change to avoid this issue ?

Thanks

**Comment by yajra** [comment]
Closing Remarks: 
UTF-8 should be supported **BUT** your database configuration/charset should also support it to work well.

**Comment by mansouralex** [comment]
Yes it should be configured on the database level. I have already solve these issues. Thanks

**Comment by yasserodb** [comment]
Hello Arjay , hello mansouralex  , i also had the same problem with Arabic language  characterset set of database level is  AR8MSWIN1256 and characterset of php level is utf8 
Note that the same settings worked with Arabic language  with pure PHP .

setting of pure php that worked correctly :+1: 
<?php

$tns = "
    (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.6)(PORT = 1521))
        (CONNECT_DATA =
            (SERVER = DEDICATED)
            (SERVICE_NAME = xe )
        )
    )
";


$pdo_string = 'oci:dbname='.$tns.';charset=utf8';

try {
    $dbh = new PDO($pdo_string, 'username', 'password' );
} catch (PDOException $e) {
    echo "Failed to obtain database handle: " . $e->getMessage();
    exit;
}

$query = "SELECT * FROM personnel";

$stmt = $dbh->prepare($query);

if ($stmt->execute()) {
    echo "<h4>$query</h4>";
    echo "<pre>";
    while ($row = $stmt->fetch()) {
        print_r($row);
    }
    echo "</pre>";
}

setting of laravel that not worked correctly :-1: 
config/database.php
'oracle' => [
            'driver' => 'oracle',
            'host' => '192.168.1.6',
            'port' => '1521',
            'database' => 'XE',
            'username' => 'erpdbw',
            'password' => 'erpdbw',
            'charset' => 'utf8',
            'prefix' => '',
        ]

app/http/route

Route::get('connection', function()
{
    return $users = DB::connection('oracle')->table('personnel')->select('*')->get();
});

please could you solve my problem

**Comment by mansouralex** [comment]
Hi @yasserodb try to set your php charset to AL32UTF8. And as I remember you need to install the Arabic related libraries while installing the oracle database.

**Comment by ali2535** [comment]
my database config is utf8 but it save strings in table by ????????? . 
string insert from mobile and result show in browser . 
how to solve it? 
Thanks

**Comment by ali2535** [comment]
@yajra 

hi yajra 
its my problem too . 
i cant insert persian alphabet in my table (like arabic alphabet)
thid symbols insert into db 

������������

where i must change ? 
thank you
