### ISSUE TITLE
NLS_TIMESTAMP_TZ_FORMAT

### ISSUE THREAD

**Issue by T0miii** [yajra/laravel-oci8#403]
Hi,

is there a config optio to set the NLS_TIMESTAMP_TZ_FORMAT ?
I cant seem to find any info about it.

**Comment by yajra** [comment]
You can use `DB::setDateFormat('YYYY-MM-DD')`. This command will set both date and timestamp format though. See https://yajrabox.com/docs/laravel-oci8/master/date-format.

**Comment by yajra** [comment]
Oh, is `NLS_TIMESTAMP_FORMAT` equivalent to `NLS_TIMESTAMP_TZ_FORMAT`? If not, you will have to do a manual statement.

```
DB::statement("ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD'");
```
