### ISSUE TITLE
Error using oracle 12c with laravel 5.6 

### ISSUE THREAD

**Issue by michini** [yajra/laravel-oci8#404]
### Summary of problem or feature request

I configured the connection in laravel 5.6 and this error jumps

My configuration
![error](https://user-images.githubusercontent.com/9531905/36187308-61d14fd4-1112-11e8-990f-2bc460872f74.JPG)

Error
![error1](https://user-images.githubusercontent.com/9531905/36187576-2e0773a2-1114-11e8-9d31-2d1714303c0f.JPG)

- Operating System W10
- PHP Version 7.1.6
- Laravel Version 5.6
- Laravel-OCI8 Version 2.1.4

**Comment by XenitXTD** [comment]
I got the same and rolled back to 5.5 until they actually release a working 5.6 version

**Comment by yajra** [comment]
Will try to release a 5.6 version on weekend. Don't have time yet for opensource projects due to some work deadlines. We are open for PR's incase you can. Thanks!

**Comment by yajra** [comment]
v5.6.0 released. Sorry for the delays. 🍻

**Comment by michini** [comment]
@yajra so many thanks!
