### ISSUE TITLE
Issue while connecting to the DB using Service Name instead of SID

### ISSUE THREAD

**Issue by FabioSmeriglio** [yajra/laravel-oci8#406]
### Summary of problem or feature request

Hello there,
i was trying to connect my Laravel app to my Oracle DB.
This database uses a service name alias instead of a SID so i looked up around and found a couple of suggestions about how to configure it properly BUT, whenever i try to access my app i get this exception:

ErrorException thrown with message "Declaration of Yajra\Oci8\Oci8Connection::causedByLostConnection(Exception $e) should be compatible with Illuminate\Database\Connection::causedByLostConnection(Throwable $e)"

Stacktrace:
#13 ErrorException in /var/www/LaravelTest/vendor/yajra/laravel-oci8/src/Oci8/Oci8Connection.php:0
#12 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /var/www/LaravelTest/vendor/composer/ClassLoader.php:444
#11 include in /var/www/LaravelTest/vendor/composer/ClassLoader.php:444
#10 Composer\Autoload\includeFile in /var/www/LaravelTest/vendor/composer/ClassLoader.php:322
#9 Composer\Autoload\ClassLoader:loadClass in [internal]:0
#8 spl_autoload_call in /var/www/LaravelTest/vendor/yajra/laravel-oci8/src/Oci8/Oci8ServiceProvider.php:50
#7 Yajra\Oci8\Oci8ServiceProvider:Yajra\Oci8\{closure} in /var/www/LaravelTest/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:272
#6 Illuminate\Database\Connectors\ConnectionFactory:createConnection in /var/www/LaravelTest/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:77
#5 Illuminate\Database\Connectors\ConnectionFactory:createSingleConnection in /var/www/LaravelTest/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:51
#4 Illuminate\Database\Connectors\ConnectionFactory:make in /var/www/LaravelTest/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:119
#3 Illuminate\Database\DatabaseManager:makeConnection in /var/www/LaravelTest/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:74
#2 Illuminate\Database\DatabaseManager:connection in /var/www/LaravelTest/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:327
#1 Illuminate\Database\DatabaseManager:__call in /var/www/LaravelTest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
#0 Illuminate\Support\Facades\Facade:__callStatic in /var/www/LaravelTest/public/index.php:66

This is my oracle.php config file:
'oracle' => [
                'driver' => 'oracle',
                'host' => 'my_host',
                'port' => 'my_port',
                'database' => '',
                'service_name' => 'my_db_service_name',
                'username' => 'my_username
                'password' => 'my_password',
                'charset' => '',
                'prefix' => '',
        ]

As for the index.php file, all i do is this:
```php
 $items = DB::select('select * from my_table'); ?>
```

I'm pretty new to Laravel so, if this is a silly question, forgive me but every help will be greatly appreciated.
@Edit: I Forgot to say that i'm currently using the latest version of both Laravel and this extension.

**Comment by yajra** [comment]
PR merged, thanks!
