### ISSUE TITLE
I get the 'Unsupported driver [pdo-via-oci8]' error message on Ubuntu 14.10

### ISSUE THREAD

**Issue by ertuncefeoglu** [yajra/laravel-oci8#41]
I configured a Windows machine with this driver and it works as expected. However I get the error 'Unsupported driver [pdo-via-oci8]' on my Ubuntu 14.10. I installed lamp-server^ package. Configured it for oci8 extension. Using oci8, I can connect to database both in plain php and laravel (i.e oci_connect). However using laravel DB::select it produces the above mentioned error. Any idea how to connect?

**Comment by robincasas** [comment]
Sometimes I get this error: http://prntscr.com/6icuzq help me, ubuntu 14.04 PHP 5.5.9-1ubuntu4.4 Laravel 4.1.30

**Comment by yajra** [comment]
@robincasas what version of laravel-oci8 are you using?

**Comment by robincasas** [comment]
laravel-pdo-via-oci8,

**Comment by robincasas** [comment]
yajra/laravel-pdo-via-oci8 (0.7.0)

**Comment by yajra** [comment]
thanks for the info. How about your yajra/laravel-oci8 version? The 2 project is working together. Anyways, I think you should upgrade your version by running `composer update yajra/laravel-oci8`. Since your using PHP 5.5.9, it should work.

**Comment by robincasas** [comment]
Thanks, ya esta trabajando bien!
