### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by NankoPrinzhorn** [yajra/laravel-oci8#411]
### Summary of problem

I have oci8 installed for php 7.1.19
Running on Laravel Framework 5.6.3

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yajra/laravel-oci8 v5.6.0 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 5.6.x-dev requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - yajra/laravel-oci8 5.6.x-dev requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
    - Installation request for yajra/laravel-oci8 5.6.* -> satisfiable by yajra/laravel-oci8[5.6.x-dev, v5.6.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\wamp\bin\php\php7.1.9\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
When i make a test.php in WAMP it works and no errors, but now i want it to work for laravel as well.

### Code snippet
```php
//this is the code that i used to test it
<?php
	$conn = oci_connect('Name', 'Password', 'Localhost');

	if ($conn) {
		echo "connect succesfull";
	}
?>

```

The command i run to install it in laravel is:

'composer require yajra/laravel-oci8:"5.6.*"'

I understand that this might not be the right command, soo i tried this:

'composer require yajra/laravel-oci8:"7.1.19"'

But that one doesnt exists

**Comment by NankoPrinzhorn** [comment]
Or is there a way to ignore this issue

**Comment by yajra** [comment]
Make sure you have oci8 enabled on CLI config. You can browse the closed issues too for similar issues. Lot of them available here. Thanks!

**Comment by NankoPrinzhorn** [comment]
So after some struggle i fixed it, by putting all the .dll files of oci in my system32 and enabling oci.dll version 11g in my apache.

Thanks

**Comment by krunaladaptit** [comment]
I am facing the same problem.
Can anyone please help me too?
