### ISSUE TITLE
oci_bind_by_name null value in maxlenght cause ORA-014060.

### ISSUE THREAD

**Issue by sasanet** [yajra/laravel-oci8#413]
### Summary of problem or feature request

The value of maxlength in oci-bind-by-name maybe -1 or another but not null.
this condition cause ORA 01460 but not in all versione of oci8. (http://php.net/manual/en/function.oci-bind-by-name.php)

please fix this error in method  "addBindingsToStatement".
You must set $length = -1 instead of $length = null at line 435.

Thanks.

- Centos 7
- PHP Version 5.6.2
- Laravel Version 5.4
- Laravel-OCI8 Version 5.4

**Comment by yajra** [comment]
Can you please a PR on 5.4 branch for your proposed solution? Thanks!

**Comment by sasanet** [comment]
What's PR?

Il Dom 11 Mar 2018 04:21 AM Arjay Angeles <notifications@github.com> ha
scritto:

**Comment by yajra** [comment]
Oh, a Pull Request so that package users can review and test the proposed changes/solution. Thanks!

**Comment by sasanet** [comment]
ok , i have submit my first pull request. I don't know if correct.

Thanks.

**Comment by sasanet** [comment]
Hi Yajra, if you do not have time to spent for resolve  this issue, i may contribute to this fix.
Can you help me?

**Comment by yajra** [comment]
Sorry for late response, a bit busy on work projects. Anyways, have implemented the fix on #427 as you proposed. Thanks!

**Comment by yajra** [comment]
Released on v5.6.1, kindly update and confirm.

**Comment by mstaack** [comment]
thx for this fix btw!
