### ISSUE TITLE
ORA-01086: savepoint 'TRANS2' never established

### ISSUE THREAD

**Issue by kayobruno** [yajra/laravel-oci8#414]
### Summary of problem or feature request

I am trying to run the **php artisan migrate** and I get the following error:

  **Error Code:** 1086                                             
  **Error Message:** ORA-01086: savepoint 'TRANS2' never established  
  **Position:** 0                                                
  **Statement:** ROLLBACK TO SAVEPOINT trans2                     
  **Bindings:** []    

### System details

- Operating System: Red Hat Enterprise Linux Server release 7.4
- PHP Version: 7.1.13
- Laravel Version: 5.4
- Laravel-OCI8 Version: 5.4

**Comment by yajra** [comment]
Can you please some snippets to reproduce the issue?
