### ISSUE TITLE
Call to undefined method Yajra\Oci8\Schema\Grammars\OracleGrammar::typeIpAddress()  

### ISSUE THREAD

**Issue by shuvo321** [yajra/laravel-oci8#416]
### Summary of problem or feature request

I am using laravel 5.5.* . 

### Code snippet of problem

When I try to migrate, This problem is occured.

### System details

- Operating System : Ubuntu 16.04
- PHP Version : 7.2
- Laravel Version :5.5.*
- Laravel-OCI8 Version :5.5.x

**Comment by Jon4t4n** [comment]
It's defined as varchar(45) in MySsqlGrammar.
https://github.com/laravel/framework/blob/15bd214be27426ed251e916700c23ca396bb335c/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L695.

So you can define your ip field as a normal string, because laravel does that under the hood anyway.
