### ISSUE TITLE
 Package yajra/laravel-oci8 at version 5.6.* has a PHP requirement incompati     ble with your PHP version (7.0.28)

### ISSUE THREAD

**Issue by harabdo4** [yajra/laravel-oci8#425]
When I try to execute this line command <composer require yajra/laravel-oci8:"5.6.*"> I got this message error :
" [InvalidArgumentException]                                                   
  Package yajra/laravel-oci8 at version 5.6.* has a PHP requirement incompati  
  ble with your PHP version (7.0.28) "

do you have any idea, thanks

### System details

PHP version : 

- Operating System :ubuntu0.16.04.1
- PHP Version :  7.0.28
- Laravel Version: 5.6
- Laravel-OCI8 Version : I enabled this line : extension=php_oci8_12c.dll in php.ini

**Comment by yajra** [comment]
Laravel 5.6 requires PHP >=7.1.3 afaik. Please update your php version.
