### ISSUE TITLE
How to close connection using oci_close() ?

### ISSUE THREAD

**Issue by afifnandya** [yajra/laravel-oci8#426]
Anyone know to manually close the connection using oci_close() function ? becase it seems like my production server oracle connection pool is full with the idle connection

**Thanks !**

**Comment by mstaack** [comment]
normally everything is closed automatically by `__destruct `
must be some issues with your shutdown process in your app...

**Comment by seminsergey** [comment]
When using connection in **laravel jobs**, connection **not close** after to end execute,  need add method **close()** or **disconnect()**.

**Comment by seminsergey** [comment]
I dont use PDO::ATTR_PERSISTENT in $options.

**Comment by mstaack** [comment]
@seminsergey than please try it out, usually its a really good idea to use persistent connections to dbs etc..... helps you to reduce connection overhead...

**Comment by seminsergey** [comment]
@mstaack limit max_connection does not allow me to use a persistent connection.
