### ISSUE TITLE
Request: Support for dropAllTables()

### ISSUE THREAD

**Issue by robertogallea** [yajra/laravel-oci8#435]
### Summary of problem or feature request

When I run a fresh migration, LogicException is raised with the following message:

LogicException  : This database driver does not support dropping all tables.

### Code snippet of problem

`php artisan migrate:fresh`

### System details

- Windows 10
- PHP 7.1.2
- Laravel 5.6
- Laravel-OCI8 Version 5.6

**Comment by yajra** [comment]
Yes, this is not yet supported. ATM, try using the older way of doing this via `php artisan migrate:refresh`. Thanks!

**Comment by yajra** [comment]
Feature released on v5.6.3 🚀 🍻

**Comment by robertogallea** [comment]
Hi,
I also create some views in migrations: do you think that dropAllTables() should also drop them? I ask this because if I run "php artisan:migrate fresh" views remains untouched and the command fails. From the other side, php artisan migrate:rollback" succeeds because I drop the views in the down() of the migrations.

Thank you!
