### ISSUE TITLE
TNSNAME connetion supported ?

### ISSUE THREAD

**Issue by barbuslex** [yajra/laravel-oci8#44]
Hi,

The connection through a TNSNAME it is supported by the plugin ?

If so, how is it used ? 

Thanks

**Comment by yajra** [comment]
Hi, 

database should not be required now if `tns` is set on the config file using [v2.0.8](https://github.com/yajra/laravel-oci8/tree/v2.0.8)

**Comment by ali2535** [comment]
hi yajra i can not insert persian alphabet into database . it is like arabic . 
i user utf8 , utf-8 , UTF-8 , UTF8 but not changed and insert ������������ symbols.
