### ISSUE TITLE
Problem 1     - yajra/laravel-oci8 v5.6.3 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system. [Question][Need help] 

### ISSUE THREAD

**Issue by gaalves** [yajra/laravel-oci8#440]
# I followed several tutorials to install oci8 Debian 9 php 7.2 and still have not got results

### PHP Version
![php-v](https://user-images.githubusercontent.com/31774273/41295324-ad1c8ee2-6e30-11e8-9970-813300f7798a.PNG)
### Linux Version
![linuxversion](https://user-images.githubusercontent.com/31774273/41295428-f79b5eee-6e30-11e8-827d-d22e8007ba6c.PNG)

### Error after install with pecl install oci8
![error1](https://user-images.githubusercontent.com/31774273/41295501-1d3ac9f0-6e31-11e8-9bf6-0644d2f052dc.PNG)

### Error composer 
![error2](https://user-images.githubusercontent.com/31774273/41295575-4763a4d6-6e31-11e8-9dae-dc498c2cecb5.PNG)

**Comment by mstaack** [comment]
follow instructions here on a fresh install:

https://github.com/yajra/laravel-oci8/blob/5.6/oci8.sh
