### ISSUE TITLE
Error Code : 2421 Error Message : ORA-02421:

### ISSUE THREAD

**Issue by claudemirton** [yajra/laravel-oci8#444]
### Summary of problem or feature request

Hi, Yajra
I´m facing a problem when trying to connect a Oracle database 10g. According to DBA, it´s not possible alter these paremeters (time and date) on that version of database :(

What should i do? Any workaround?

Thanks in advance.

### System details

- Operating System - windows 10 
- PHP Version - 7.1.9
- Laravel Version - 5.6.25
- Laravel-OCI8 Version 5.6.3

**Comment by yajra** [comment]
For a workaround, you can duplicate the `Oci8ServiceProvider.php` class and remove any alter session that is not applicable on your DB version.

You will also need to disable auto package discovery for the package and load the custom provider manually on your app config providers. Search the laravel docs on how providers works in case you are not familiar with it.

P.S. Laravel may not work properly if we don't set the time format like on PHP. Make sure you convert any date related sql to match your DB date format.
