### ISSUE TITLE
Cannot access NLS data files or invalid environment specified

### ISSUE THREAD

**Issue by nennnelson** [yajra/laravel-oci8#445]
### Summary of problem
Hi Yajra!

I have a project in mind that can be easily achieved with **Laravel** but the data source comes from an **external Oracle DB server** so I requested laravel-oci8 package. After fighting on configuring **XAMPP** to be able to deal with **OCI**  following some guides I did halfway succeeded.

The problem comes when I try to run a connection with a little query as shown below:

#### Added DB_TNS string on **oracle.php** configuration file
```php
(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.***)(PORT=1521))(CONNECT_DATA=(SID=d***)))
```

#### Environment configuration
```php
DB_CONNECTION=oracle
DB_HOST=172.***
DB_PORT=1521
DB_DATABASE=d***
DB_USERNAME=u***
DB_PASSWORD=p***
DB_CHARSET=WE8MSWIN1252
```

#### Controller
```php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class DatabaseController extends Controller
{
    //
    public function connect() {
        $users = DB::connection('oracle')->select('SELECT * FROM t***');

        return $users;
    }
}
```

#### Output error
```text
"ORA-12705: Cannot access NLS data files or invalid environment specified"
```

Everything seems to work but this sudden error pups up. Please for any solution. 

#### System details

- Operating System Windows 7
- PHP Version 7.2.6
- Laravel Version 5.6
- Laravel-OCI8 5.6

**Comment by yajra** [comment]
Not sure on this but have you override some the config like language?

```
The ORA-12705 error is indeed controlled by NLS_LANG, and the ORA-12705 commonly happens when Oracle does an automatic "alter session" at login time and discovers an invalid NLS_LANG setting.  The Oracle documentation notes are not very helpful:
