### ISSUE TITLE
Call to undefined method Yajra\Oci8\Schema\Grammars\OracleGrammar::typeIpAddress() 

### ISSUE THREAD

**Issue by Sevyls** [yajra/laravel-oci8#446]
### Summary of problem or feature request

Database migration with column of type ipAddress is not working.

```
In Grammar.php line 120:
                                                                                      
[Symfony\Component\Debug\Exception\FatalThrowableError]                             
Call to undefined method Yajra\Oci8\Schema\Grammars\OracleGrammar::typeIpAddress() 
``` 

It should at least map to a varchar2 representation or a number field.

### Code snippet of problem

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTestTable extends Migration {
    
    public function up()
    {
        Schema::create('test', function (Blueprint $table) {
            $table->increments('id');
            $table->string("displayName");
            $table->text("description");
            $table->ipAddress("ip_address");
            $table->timestamps();
        });
    }

   
    public function down()
    {
        Schema::dropIfExists('monitors');
    }
}
```

### System details

- Operating System: Mac OS X 10.13.5
- PHP Version: 7.2.7 
- Laravel Version: Lumen 5.5.2
- Laravel-OCI8 Version 5.5.9

**Comment by yajra** [comment]
I think `ipAddress` type is not yet supported by the package. Will add support for it when I got the chance or please submit a PR if you can. Thanks!

**Comment by Sevyls** [comment]
Great! Will test in the next few days!

Robert Stubbs <notifications@github.com> schrieb am Mo. 6. Aug. 2018 um
17:24:

**Comment by yajra** [comment]
@saragan can you please send a PR. Thanks!

**Comment by aventrax** [comment]
Problem still there. Just use a VARCHAR and let the error desappear.

**Comment by saragan** [comment]
"@saragan can you please send a PR"

I dont usually comment on these things? whats a PR???

**Comment by yajra** [comment]
@saragan "PR" for Pull Request. So that we can merge and properly credit your contributions to the package. Thanks!
