### ISSUE TITLE
oci_connect exists in tinker but does not exists when loading the page

### ISSUE THREAD

**Issue by clcarver** [yajra/laravel-oci8#449]
### Summary of problem or feature request

Running into the "Call to undefined function Yajra\Pdo\oci_connect()" when loading the page. But when I run php artisan tinker, I can call my models and get results just fine.

running function_exists('oci_connect') in tinker returns true
running function_exists('oci_connect') in a route returns false

Has anyone run into this issue before?

### System details

- Operating System
-- Windows 10 64bit
-- IIS
- PHP Version 7.1.2
- Laravel Version 5.6
- Laravel-OCI8 Version 2.1.8 64bit

I have made sure my path is pointing to the correct php folder and IIS is using that same PHP path. My php is 64 bit, my oracle instant client is 64bit, and my oci8 connector is 64bit. Oci8 is showing up when I run php -m and php -v is showing the correct 7.1.20 version.

**Comment by yajra** [comment]
apache and cli have different `php.ini`. Make you have oci8 enabled on both config.

**Comment by gbryant200** [comment]
I have a Homestead/Laravel Vagrant box.  I'm using Apache for my site.  I have oci8 installed with version 11.1 of the instant client tools.  I have the oci8 extension added to all my php.ini files - apache, cli, cgi and fpm.  I have the LD_LIBRARY_PATH and ORACLE_HOME set in fpm's www.conf and in /etc/apache2/envars.  I also have an oracle.conf file in /etc/ld.so.conf.d that sets the location of the client library files. The oci8 driver still doesn't load for apache/fpm.  It runs fine from the command line.  This is driving me crazy.  I added the 'extension=oci8' to the php.ini files, not any external .conf file.

Any ideas would be greatly appreciated.

**Comment by anfazaba** [comment]
I am same :( I couldn't found a resolution for this. I deppend of this for my job.

Any idea?

**Comment by gbryant200** [comment]
If you can run php interactively and successfully query the database then everything is installed and configured correctly.  With Apache and php-fpm, you need to edit the /etc/php/7.3/fpm/pool.d/www.conf file; by default php-fpm clears all environment variables when the web server starts.  You can declare specific environment variables in the www.conf file that you need for the web server or just allow all of them by removing the `;` in front of the `;clear_env = no`

You have to restart apache and php-fpm for the settings to change.

The  main environment variable that OCI8 needed, at least in my case, was ORACLE_HOME.  Again, if you can successfully connect/query interactively, the put the ORACLE_HOME environment variable in the www.conf file and restart.

env[ORACLE_HOME] = 'every how you have it setup on your system'

for me, on Ubuntu 18.04
env[ORACLE_HOME] = /usr/lib/oracle/11.1/client64

I also added my LD_LIBRARY_PATH to the www.conf file.
