### ISSUE TITLE
Set named parameters in prepared query

### ISSUE THREAD

**Issue by barbuslex** [yajra/laravel-oci8#45]
Hi,

When i try to bind my named parameters in prepared query i got this error : 
In fr: 
>oci_bind_by_name(): ORA-01036: numéro/nom de variable interdit

In eng:
>oci_bind_by_name(): ORA-01036: illegal variable name/number

My code looks like this:
```php
$results = DB::select( DB::raw("SELECT * FROM some_table WHERE some_col = :somevariable"), array(
   'somevariable' => $someVariable,
 ));
```

My exact code is : 
```php
return DB::select(DB::raw("select * from structure WHERE STR_TYPE = :uf"), array(":uf" => 'UF'));
```

Can you help me to fix it ? Or maybe a bug ?

Thanks for you help

**Comment by yajra** [comment]
PR merge. thanks!
