### ISSUE TITLE
field type char (10) returns string of 10 positions. Return the trimmed value

### ISSUE THREAD

**Issue by johnathansantos** [yajra/laravel-oci8#450]
if in the database was declared a field of type char of 10 positions is correct return of a string of 10 positions?
Example: 
```
 "name": "xx        "  //length (10)
```

Is it possible to return the value with the trim applied?
Example: 
```
 "name": "xx" 
```

Operating System = Linux
PHP Version = 7.2.7
Laravel Version = 5.6
Laravel-OCI8 Version = 5.6

**Comment by yajra** [comment]
This is the expected behaviour. If you want it trimmed, I suggest you update the type to `varchar2` if possible.

**Comment by johnathansantos** [comment]
It is not possible, but okay, I will apply the trim function in the field in php. Thanks
