### ISSUE TITLE
How to use oci_set_client_identifier

### ISSUE THREAD

**Issue by henriquek3** [yajra/laravel-oci8#453]
### How to identify the users of the connections?

For audit issues I need to identify the user of the session in the database by a nickname defined by me.

### Code snippet of problem

```php
session_start();
$c = oci_pconnect('phpuser', 'welcome', 'localhost/orcl');
oci_set_client_identifier($c, $_SESSION['app_user_name']);
```

Font: http://www.oracle.com/technetwork/articles/dsl/php-web-auditing-171451.html
Font: http://php.net/manual/pt_BR/function.oci-set-client-identifier.php

### System details

- Windows 10
- PHP Version 7.2.4
- Laravel Version 5.5
- Laravel-OCI8 Version 5.5

**Comment by yajra** [comment]
Unfortunately, this is not yet supported. Will try to implement this when I got the chance. If you can, please do not hesitate to submit a PR on https://github.com/yajra/pdo-via-oci8 and this repo.

**Comment by sthales** [comment]
Any update on this?
