### ISSUE TITLE
[Question] Function-based Oracle Indexes in Models

### ISSUE THREAD

**Issue by blackdrago** [yajra/laravel-oci8#455]
- Operating System: Linux
- PHP Version: 5.6.32
- Laravel Version: 5.4
- Laravel-OCI8 Version: 5.4

This might be a feature request, but it's mostly a question.

Several of my tables have function-based indexes (mostly to optimize case-insensitive comparisons/searches). Normally, to query against these indexes, all I have to do is drop a hint, e.g.:

SELECT * FROM alias_values WHERE UPPER(name) = 'SOME NAME';

Since the case insensitive index is created via UPPER(name), Oracle will "know" that the best index is the function based index (called idx_alias_names if that matters).

While I can use DB::query(...) to make a query with an index hint, I'd prefer to add it to the appropriate Models instead, since the Models are used everywhere to find/compare data like this:

$aliases = AliasValue::query()->where('alias_name', '=', 'SOME NAME')->get();

It would be nice if I could make this the 'default' setting for the Eloquent models. If not, something like this would also work:

AliasValue::query()->useIndex('idx_alias_names')->where('alias_name', '=', 'SOME NAME')->get();

However, I haven't found any examples of this being used specifically with Oracle. (I've found a similar issue brought up @ https://github.com/laravel/ideas/issues/33 for other databases.) Is this kind of index handling possible with this package? Are there examples or tutorials of it being used with Eloquent?

**Comment by yajra** [comment]
Reading some issues lead me here, sorry I have overlooked this. Anyways, after some oracle index research, this is how it can be done on Oracle based on this [SO answer](https://stackoverflow.com/questions/1838094/force-index-use-in-oracle/1838107).

```php
class Fax extends Model
{
    /**
     * @param string $indexName
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder
     */
    public static function indexQuery(string $indexName)
    {
        $model = new static();

        return $model->query()
            ->selectRaw('/*+INDEX(' . $model->getTable() . ', ('. $indexName.')) */ *');
    }
}
```

To use:

```php
    return Fax::indexQuery('fax_pk')
       ->take(10)
       ->orderBy('faxid', 'desc')
       ->get();
````

**Comment by blackdrago** [comment]
What a beautiful and elegant solution! Thank you!
