### ISSUE TITLE
ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by radobarta** [yajra/laravel-oci8#456]
### Summary of problem or feature request

I have not problem to connect to oracle 12c directly from php with:
$conn = oci_connect('broktest', 'Br0kT3st', '172.16.0.3:1521/BROK12');

or with tinker
but laravel app shows 
ORA-12154: TNS:could not resolve the connect identifier specified

the same application and same connection on windows works well

### System details

- Operating System
- PHP Version 7.2
- Laravel Version 5.6
- Laravel-OCI8 Version

**Comment by radobarta** [comment]
solved
uff
solution is here: https://github.com/yajra/laravel-oci8/issues/111

i have changed oracle.php to
    'oracle' => [
        'driver'         => 'oracle',
        'tns'            => '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.0.3)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=brok12)))',
        // 'host'           => '172.16.0.3',
        // 'port'           => '1521',

thank everybody

**Comment by JesusHenriquez** [comment]
It worked
