### ISSUE TITLE
wherein导致ORA-01795: maximum number of expressions in a list is 1000

### ISSUE THREAD

**Issue by jiaoshengkang** [yajra/laravel-oci8#464]
### System details

- Operating System Debian 3.2.46
- PHP Version 7.1.6
- Laravel Version 5.5
- Laravel-OCI8 Version 5.5.x

**Comment by yajra** [comment]
You need to use [OracleEloquent](https://yajrabox.com/docs/laravel-oci8/master/oracle-eloquent) to fix this issue.

**Comment by jiaoshengkang** [comment]
ok，that's very nice of you!
