### ISSUE TITLE
Multiple schema connection in a controller

### ISSUE THREAD

**Issue by mohd-aidi** [yajra/laravel-oci8#466]
### Summary of problem or feature request

in my controller, i need to call 2 DB from different schema. for example schema deposit and schema majlis. 

        $user = GePrUser::where('username', $id)->first();//from majlis

        $thisUser = User::where('nric', $user->nirc)->first();//from deposit

the error as below : 

`
 ErrorException in Connection.php line 662:
 Error Code : 942
 Error Message : ORA-00942: table or view does not exist
 Position : 29
 Statement : select * from (select * from eca_users where nric = :p0) where rownum = 1 
 Bindings : [751006085488,751006085488]
 (SQL: select * from (select * from eca_users where nric = 751006085488) where rownum = 1) (View: 
 C:\xampp\htdocs\ecagaran\resources\themes\default\views\pruser\_list.blade.php) (View: 
 C:\xampp\htdocs\ecagaran\resources\themes\default\views\pruser\_list.blade.php) `

please someone help me or point me to the right solution. tq very much.

- Operating System - windows 10
- PHP Version - php 7.0
- Laravel Version  -  5.1
- Laravel-OCI8 Version   - 5.1

**Comment by yajra** [comment]
You can include the schema name on the table.

```php
class User extends Model {
    protected $table = 'deposits.users';
}

class GePrUser extends Model {
    protected $table = 'majlis.users';
}
```

Note: this config assumes that your main connection have access on these schemas.

**Comment by mohd-aidi** [comment]
> You can include the schema name on the table.
> 
> ```
> class User extends Model {
>     protected $table = 'deposits.users';
> }
> 
> class GePrUser extends Model {
>     protected $table = 'majlis.users';
> }
> ```
> 
> Note: this config assumes that your main connection have access on these schemas.

but i already put the prefix in database.php

>  'oramajlis' => [
>             'driver'    => env('DBMAJLIS_DRIVER', 'mysql'),
>             'host'      => env('DBMAJLIS_HOST', 'localhost'),
>             'database'  => env('DBMAJLIS_DATABASE', 'root'),
>             'username'  => env('DBMAJLIS_USERNAME', 'root'),
>             'password'  => env('DBMAJLIS_PASSWORD', ''),
>             'charset'  => env('DBMAJLIS_CHARSET', 'utf8'),
>             'collation'  => env('DBMAJLIS_COLLATION', 'utf8_unicode_ci'),
>             'prefix'    => env('DBMAJLIS_PREFIX', ''),
>             'port'          => env('DB_PORT', '3306'),
>             'schema' => env('DBMAJLIS_SCHEMA_PREFIX', ''),
>             'strict'    => false,
>             'options'   => array(
>                 PDO::ATTR_CASE =>  env('DBMAJLIS_ATTR_CASE', PDO::CASE_LOWER),
>             ),
>         ],

**Comment by mohd-aidi** [comment]
the connection is working fine if i use only one connection at a time. but when using multiple connection then it become like this. 

I cant put the schema name in model because we have multiple developer that use mysql too.

**Comment by yajra** [comment]
Maybe what you need is to set the connection. You can multiple connections on your config and just instruct the model on which connection to use. Something like:

```php
class User extends Model {
    public $connection = "deposits";
    protected $table = 'users';
}


class GePrUser extends Model {
    public $connection = "oramajlis";
    protected $table = 'users';
}


'deposits' => [
	'driver' => env('DBDEPOSITS_DRIVER', 'mysql'),
	'host' => env('DBDEPOSITS_HOST', 'localhost'),
	'database' => env('DBDEPOSITS_DATABASE', 'root'),
	'username' => env('DBDEPOSITS_USERNAME', 'root'),
	'password' => env('DBDEPOSITS_PASSWORD', ''),
	'charset' => env('DBDEPOSITS_CHARSET', 'utf8'),
	'collation' => env('DBDEPOSITS_COLLATION', 'utf8_unicode_ci'),
	'prefix' => env('DBDEPOSITS_PREFIX', ''),
	'port' => env('DB_PORT', '3306'),
	'schema' => env('DBDEPOSITS_SCHEMA_PREFIX', ''),
	'strict' => false,
	'options' => array(
		PDO::ATTR_CASE => env('DBDEPOSITS_ATTR_CASE', PDO::CASE_LOWER),
	),
],

'oramajlis' => [
	'driver' => env('DBMAJLIS_DRIVER', 'mysql'),
	'host' => env('DBMAJLIS_HOST', 'localhost'),
	'database' => env('DBMAJLIS_DATABASE', 'root'),
	'username' => env('DBMAJLIS_USERNAME', 'root'),
	'password' => env('DBMAJLIS_PASSWORD', ''),
	'charset' => env('DBMAJLIS_CHARSET', 'utf8'),
	'collation' => env('DBMAJLIS_COLLATION', 'utf8_unicode_ci'),
	'prefix' => env('DBMAJLIS_PREFIX', ''),
	'port' => env('DB_PORT', '3306'),
	'schema' => env('DBMAJLIS_SCHEMA_PREFIX', ''),
	'strict' => false,
	'options' => array(
		PDO::ATTR_CASE => env('DBMAJLIS_ATTR_CASE', PDO::CASE_LOWER),
	),
],
```

**Comment by yajra** [comment]
Also, the error `ORA-00942: table or view does not exist` clearly states that the object you are accessing is not available on your connection. That should be a hint that you have an invalid connection or do not have the necessary access on that schema / objects.

**Comment by mohd-aidi** [comment]
> Maybe what you need is to set the connection. You can multiple connections on your config and just instruct the model on which connection to use. Something like:
> 
> ```
> class User extends Model {
>     public $connection = "deposits";
>     protected $table = 'users';
> }
> 
> 
> class GePrUser extends Model {
>     public $connection = "oramajlis";
>     protected $table = 'users';
> }
> 
> 
> 'deposits' => [
> 	'driver' => env('DBDEPOSITS_DRIVER', 'mysql'),
> 	'host' => env('DBDEPOSITS_HOST', 'localhost'),
> 	'database' => env('DBDEPOSITS_DATABASE', 'root'),
> 	'username' => env('DBDEPOSITS_USERNAME', 'root'),
> 	'password' => env('DBDEPOSITS_PASSWORD', ''),
> 	'charset' => env('DBDEPOSITS_CHARSET', 'utf8'),
> 	'collation' => env('DBDEPOSITS_COLLATION', 'utf8_unicode_ci'),
> 	'prefix' => env('DBDEPOSITS_PREFIX', ''),
> 	'port' => env('DB_PORT', '3306'),
> 	'schema' => env('DBDEPOSITS_SCHEMA_PREFIX', ''),
> 	'strict' => false,
> 	'options' => array(
> 		PDO::ATTR_CASE => env('DBDEPOSITS_ATTR_CASE', PDO::CASE_LOWER),
> 	),
> ],
> 
> 'oramajlis' => [
> 	'driver' => env('DBMAJLIS_DRIVER', 'mysql'),
> 	'host' => env('DBMAJLIS_HOST', 'localhost'),
> 	'database' => env('DBMAJLIS_DATABASE', 'root'),
> 	'username' => env('DBMAJLIS_USERNAME', 'root'),
> 	'password' => env('DBMAJLIS_PASSWORD', ''),
> 	'charset' => env('DBMAJLIS_CHARSET', 'utf8'),
> 	'collation' => env('DBMAJLIS_COLLATION', 'utf8_unicode_ci'),
> 	'prefix' => env('DBMAJLIS_PREFIX', ''),
> 	'port' => env('DB_PORT', '3306'),
> 	'schema' => env('DBMAJLIS_SCHEMA_PREFIX', ''),
> 	'strict' => false,
> 	'options' => array(
> 		PDO::ATTR_CASE => env('DBMAJLIS_ATTR_CASE', PDO::CASE_LOWER),
> 	),
> ],
> ```

yes i did just like this. 
```
class GePrUser extends BaseModel
{
    //public $timestamps = false;
    protected $table = 'pruser';
    protected $connection = 'oramajlis';
    ................
```

**Comment by mohd-aidi** [comment]
> Also, the error `ORA-00942: table or view does not exist` clearly states that the object you are accessing is not available on your connection. That should be a hint that you have an invalid connection or do not have the necessary access on that schema / objects.

i have the connection and it works well when i only use one connection at a time. 

The problem is when i use two schema in one controller. like above. the query not include schema name in the select  statement.

**Comment by yajra** [comment]
Hmm, that's odd. My projects also uses multiple connections and multiple schema in same connections and does not have any problem at all. I even have a mixed connections of mysql, sqlserver and oracle in my project.

Anyways, will try to replicate on a fresh laravel installation when I got the chance.

**Comment by mohd-aidi** [comment]
> Hmm, that's odd. My projects also uses multiple connections and multiple schema in same connections and does not have any problem at all. I even have a mixed connections of mysql, sqlserver and oracle in my project.
> 
> Anyways, will try to replicate on a fresh laravel installation when I got the chance.

TQ, for now i use \DB for schema majlis and Model for schema deposit. I always encounter this problem. and i just hope you can find a solution for it..

**Comment by asundust** [comment]
I also encountered this kind of situation in the non laravel.
