### ISSUE TITLE
Optimize issue of date filter

### ISSUE THREAD

**Issue by dasun4u** [yajra/laravel-oci8#470]
My table has a huge transaction data set. I need a query like below. It returns 3-month transaction data set for specific merchant id. 

select "TX_TYPE", "TX_STATUS", "BRANCH_ID", "AMOUNT" from "RS_TRANSACTION_LOG" where "MERCHANT_ID" = "506" and trunc("TX_DATE") > "2018-07-25" and trunc("TX_DATE") < "2018-10-25"

Result get following eloquent code snippet. 

```php

    $transaction_start = Carbon::now()->subMonths(3)->toDateString();
    $transaction_end = Carbon::parse($request->input('transaction_end'))->toDateString();

    $transaction_data = TransactionLog::select('tx_type','tx_status','branch_id','amount')
    ->where("merchant_id",$merchant_id)
    ->whereDate('tx_date',">",$transaction_start)
    ->whereDate('tx_date',"<",$transaction_end)
    ->get();

```
The question is the optimization issue. Because "trunc" keyword read all the table rows and trunc the date value but the "between" keyword is more efficient than "trunc" keyword. How can I replace "trunc" keyword by "between" keyword with the using of eloquent query?

- Operating System - Red Hat Enterprise Linux Server 7.3 (Maipo)
- PHP Version - PHP 7.1.9
- Laravel Version - 5.4
- Laravel-OCI8 Version - 5.4

**Comment by yajra** [comment]
Try using `whereBetween` or `whereRaw` instead.
