### ISSUE TITLE
Call to undefined function Yajra\Pdo\oci_connect()  in Oci8.php line 459

### ISSUE THREAD

**Issue by blacq0o** [yajra/laravel-oci8#472]
Hi,
Wamp v3.0..6 ---- x86
laravel v5.4.*

composer require yajra/laravel-oci8 "5.4.*"

app.php = Yajra\Oci8\Oci8ServiceProvider::class,

php artisan vendor:publish --tag=oracle

oracle.php

        'host'     => env('ORACLE_HOST', 'my_host'),
        'port'     => env('ORACLE_PORT', '1521'),
        'database' => env('ORACLE_DATABASE', 'mydb'),
        'username' => env('ORACLE_USERNAME', 'myuser'),
        'password' => env('ORACLE_PASSWORD', 'mypass'),
        'charset'  => env('ORACLE_CHARSET', 'AL32UTF8'),
        'prefix'   => env('ORACLE_PREFIX', ''),

.env

ORACLE_HOST=my_host
ORACLE_PORT=1521
ORACLE_DATABASE=mydb
ORACLE_USERNAME=myuser
ORACLE_PASSWORD=mypass

php_oci8-2.0.8-5.6-ts-vc11-x86.zip  
---- all(6 oci8,oci8_11g,oci8_12c .dll and .pdb) files copy C:\wamp\bin\php\php5.6.25\ext

![image](https://user-images.githubusercontent.com/7234983/47914446-bd84af80-deb0-11e8-80d5-733d4b478bef.png)

![image](https://user-images.githubusercontent.com/7234983/47914478-e6a54000-deb0-11e8-82ee-2b3987cf20ac.png)

but php_info oci8 nothing

![image](https://user-images.githubusercontent.com/7234983/47914550-1eac8300-deb1-11e8-95d2-569ca4548bb5.png)

Thanks...

**Comment by imami** [comment]
I've faced the same issue with php7.2,

You should set the LD_LIBRARY_PATH environment variable.
also check if `/etc/ld.so.conf.d/oracle-instantclient.conf` exists and contains the correct path to the Oracle library.

**Comment by blacq0o** [comment]
Hi,
problem is solved.
problem win64_11gR2_client uninstall and install win32_11gR2_client.
thanks.
