### ISSUE TITLE
Problem with reserved words.

### ISSUE THREAD

**Issue by imami** [yajra/laravel-oci8#473]
I have a column in my oracle table, named `level`.
In `Laravel 5.7.12` with `laravel-oci8 5.7.2` the following codes caused the exception:
```php
MyModel::where('level', 400)->get()
```
> Error Message : ORA-00904: "LEVEL": invalid identifier

even if :
```php
MyModel::where('"level"', 400)->get()
```
>Error Message : ORA-01741: illegal zero-length identifier

This used to work with `Laravel 5.4.36` and `laravel-oci8 5.4.13` without any issues.
How should I resolve this?

**Comment by yajra** [comment]
Reserved word are converted to uppercase on latest version. To fix, I think you need to use raw sql.

```php
MyModel::where(DB::raw('"level"'), 400)->get()
```

**Comment by imami** [comment]
@yajra Thanks for the solution, this fixed my issue at the time,
but what if someone decide to change the project database to another engine (like mysql or ...) in the future, which has a different behavior with quotations? 
The whole project might be affected and someone should review all previous codes and change wherever I used `DB::raw('"level"')` syntax!

I think this can be handled in laravel-oci8 in a more peaceful way! am I right?

**Comment by imami** [comment]
@yajra Thanks
