### ISSUE TITLE
Auth problem with password and oracle connection

### ISSUE THREAD

**Issue by alazarog7** [yajra/laravel-oci8#475]
### Summary of problem or feature request

Auth::attemp() returns false  every time I test login with right data using oracle db, but postgres there is no problem.

### Code snippet of problem

Auth::attempt(['USUARIO_ALIAS'=>$request->usuario,'password'=>$request->pass])

**Comment by yajra** [comment]
Using the standard auth of laravel uses case sensitive credentials. If you want it case insensitive, use the auth provider included in the package. See https://github.com/yajra/laravel-oci8#laravel-52-oracle-user-provider.
