### ISSUE TITLE
unique constraint violated

### ISSUE THREAD

**Issue by mohd-aidi** [yajra/laravel-oci8#478]
### Summary of problem or feature request

first php artisan db:seed give out this error 

### Code snippet of problem

`` In Connection.php line 664:

  Error Code    : 1
  Error Message : ORA-00001: unique constraint (KESENIAN.KES_MENUS_ID_PK) violated
  Position      : 0
  Statement     : insert into "KES_MENUS" ("DESCRIPTION", "ICON", "ID", "KEY", "NAME", "ORDER", "PARENT_ID", "ROLE", "STATUS", "TARGET", "URL") select :p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10 from dual union
  all select :p11, :p12, :p13, :p14, :p15, :p16, :p17, :p18, :p19, :p20, :p21 from dual union all select :p22, :p23, :p24, :p25, :p26, :p27, :p28, :p29, :p30, :p31, :p32 from dual union all select :p33, :p34, :p35, :p36, :
  p37, :p38, :p39, :p40, :p41, :p42, :p43 from dual union all select :p44, :p45, :p46, :p47, :p48, :p49, :p50, :p51, :p52, :p53, :p54 from dual union all select :p55, :p56, :p57, :p58, :p59, :p60, :p61, :p62, :p63, :p64, :
  p65 from dual union all select :p66, :p67, :p68, :p69, :p70, :p71, :p72, :p73, :p74, :p75, :p76 from dual union all select :p77, :p78, :p79, :p80, :p81, :p82, :p83, :p84, :p85, :p86, :p87 from dual union all select :p88,
   :p89, :p90, :p91, :p92, :p93, :p94, :p95, :p96, :p97, :p98 from dual union all select :p99, :p100, :p101, :p102, :p103, :p104, :p105, :p106, :p107, :p108, :p109 from dual union all select :p110, :p111, :p112, :p113, :p1
  14, :p115, :p116, :p117, :p118, :p119, :p120 from dual
  Bindings      : [,,1,admin,Admin,1,0,,1,,/admin,,,2,user,User,1,0,,1,,/user,,,3,client,Client,1,0,,1,,/client,Website main menu,,4,main,Main,2,0,,1,,,Footer menu,,5,footer,Footer,3,0,,1,,,Social media menu,,6,social,Soci
  al,3,0,,1,,,,fa fa-bars,,,Menu,6,1,["superuser"],1,,admin/menu/menu,,fa fa-dashboard,,,Dashboard,1,1,,1,,admin,,,,,Twitter,11,6,,1,_blank,https://twitter.com/lavalitecms,,,,,GitHub,12,6,,1,_blank,https://github.com/LavaL
  ite,,,,,Facebook,13,6,,1,_blank,https://www.facebook.com/lavalite/]
   (SQL: insert into "KES_MENUS" ("DESCRIPTION", "ICON", "ID", "KEY", "NAME", "ORDER", "PARENT_ID", "ROLE", "STATUS", "TARGET", "URL") select , , 1, admin, Admin, 1, 0, , 1, , /admin from dual union all select , , 2, user,
   User, 1, 0, , 1, , /user from dual union all select , , 3, client, Client, 1, 0, , 1, , /client from dual union all select Website main menu, , 4, main, Main, 2, 0, , 1, ,  from dual union all select Footer menu, , 5, f
  ooter, Footer, 3, 0, , 1, ,  from dual union all select Social media menu, , 6, social, Social, 3, 0, , 1, ,  from dual union all select , fa fa-bars, , , Menu, 6, 1, ["superuser"], 1, , admin/menu/menu from dual union a
  ll select , fa fa-dashboard, , , Dashboard, 1, 1, , 1, , admin from dual union all select , , , , Twitter, 11, 6, , 1, _blank, https://twitter.com/lavalitecms from dual union all select , , , , GitHub, 12, 6, , 1, _blank
  , https://github.com/LavaLite from dual union all select , , , , Facebook, 13, 6, , 1, _blank, https://www.facebook.com/lavalite/ from dual )

In Statement.php line 182:

  Error Code    : 1
  Error Message : ORA-00001: unique constraint (KESENIAN.KES_MENUS_ID_PK) violated
  Position      : 0
  Statement     : insert into "KES_MENUS" ("DESCRIPTION", "ICON", "ID", "KEY", "NAME", "ORDER", "PARENT_ID", "ROLE", "STATUS", "TARGET", "URL") select :p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10 from dual union
  all select :p11, :p12, :p13, :p14, :p15, :p16, :p17, :p18, :p19, :p20, :p21 from dual union all select :p22, :p23, :p24, :p25, :p26, :p27, :p28, :p29, :p30, :p31, :p32 from dual union all select :p33, :p34, :p35, :p36, :
  p37, :p38, :p39, :p40, :p41, :p42, :p43 from dual union all select :p44, :p45, :p46, :p47, :p48, :p49, :p50, :p51, :p52, :p53, :p54 from dual union all select :p55, :p56, :p57, :p58, :p59, :p60, :p61, :p62, :p63, :p64, :
  p65 from dual union all select :p66, :p67, :p68, :p69, :p70, :p71, :p72, :p73, :p74, :p75, :p76 from dual union all select :p77, :p78, :p79, :p80, :p81, :p82, :p83, :p84, :p85, :p86, :p87 from dual union all select :p88,
   :p89, :p90, :p91, :p92, :p93, :p94, :p95, :p96, :p97, :p98 from dual union all select :p99, :p100, :p101, :p102, :p103, :p104, :p105, :p106, :p107, :p108, :p109 from dual union all select :p110, :p111, :p112, :p113, :p1
  14, :p115, :p116, :p117, :p118, :p119, :p120 from dual
  Bindings      : [,,1,admin,Admin,1,0,,1,,/admin,,,2,user,User,1,0,,1,,/user,,,3,client,Client,1,0,,1,,/client,Website main menu,,4,main,Main,2,0,,1,,,Footer menu,,5,footer,Footer,3,0,,1,,,Social media menu,,6,social,Soci
  al,3,0,,1,,,,fa fa-bars,,,Menu,6,1,["superuser"],1,,admin/menu/menu,,fa fa-dashboard,,,Dashboard,1,1,,1,,admin,,,,,Twitter,11,6,,1,_blank,https://twitter.com/lavalitecms,,,,,GitHub,12,6,,1,_blank,https://github.com/LavaL
  ite,,,,,Facebook,13,6,,1,_blank,https://www.facebook.com/lavalite/]

### System details

- Operating System : Windows10
- PHP Version     7.0.22
- Laravel Version    5.5
- Laravel-OCI8 Version    oracle12

**Comment by yajra** [comment]
As the error suggested, double check that there are no existing records that violates the unique constraints.

**Comment by dwain-lab** [comment]
Was this resolved?  I am getting the same error when there is no data in the tables.
