### ISSUE TITLE
how to fix this problem

### ISSUE THREAD

**Issue by monkhsaikhan** [yajra/laravel-oci8#48]
![fireshot screen capture 020 - whoops there was an error_ - localhost_8000_admin_report_request_start end request_type 2 form_id 21 question 43 21 question 46 question 21](https://cloud.githubusercontent.com/assets/6801431/5674734/d83fff66-97ea-11e4-926d-0e2a9d9f1bf7.png)

**Comment by monkhsaikhan** [comment]
If i remove "request.request_status_id = 2", it's working properly

**Comment by yajra** [comment]
Does the generated query works when you execute it on SQL Developer or any DB tools you are using?

**Comment by monkhsaikhan** [comment]
Yes! It works

**Comment by yajra** [comment]
Can you provide steps/details on how to replicate the error? Haven't encountered this issue before.

On the other hand, try researching on the [ORA-22922](http://psoug.org/oraerror/ORA-22922.htm) error code. And if you figure out the solution, kindly share for future reference. thanks!

**Comment by yajra** [comment]
Any updates on this? On my opinion, this is a complex sql that maybe needs a raw query. Just re-open if you still have this issue. Thanks!
