### ISSUE TITLE
MULTIPLE UNION ALL missing parenthesis (12c)

### ISSUE THREAD

**Issue by robsontenorio** [yajra/laravel-oci8#481]
### Summary of problem or feature request

When performing multiples UNION ALL Oracle throws ORA-933 , because parenthesis are missing through selects/union all.

DOES NOT WORK (current generated query, without parenthesis)
```sql
SELECT /*+ FIRST_ROWS(1) */   *
FROM USERS
WHERE COUNTRY_ID IN ('S1005') offset 0 ROWS FETCH NEXT 1 ROWS ONLY

UNION ALL 

SELECT /*+ FIRST_ROWS(1) */  * 
FROM USERS
WHERE COUNTRY_ID IN ('S1001') offset 0 ROWS FETCH NEXT 1 ROWS ONLY
```

WORKS (this should be the query, with parenthesis)
```sql
(SELECT /*+ FIRST_ROWS(1) */  *
FROM USERS
WHERE COUNTRY_ID IN ('S1005') offset 0 ROWS FETCH NEXT 1 ROWS ONLY)

UNION ALL 

(SELECT /*+ FIRST_ROWS(1) */ *
FROM USERS
WHERE COUNTRY_ID IN ('S1001') offset 0 ROWS FETCH NEXT 1 ROWS ONLY)
```

### Code snippet of problem

Relevant code from tests
https://github.com/yajra/laravel-oci8/blob/f1173094c2d738ac91f820c23c3f671d909f2a31/tests/Oci8QueryBuilderTest.php#L198

### System details

- Ubuntu 18.10
- PHP 7.2
- Laravel 5.7
- Laravel-OCI8 5.7

**Comment by yajra** [comment]
Thanks for reporting, will try to dig further when I got the chance. If you can, please do not hesitate to submit a PR for a fix.
