### ISSUE TITLE
Error While inserting data [Error Code : 1465 Error Message : ORA-01465: invalid hex number]

### ISSUE THREAD

**Issue by anasrullah** [yajra/laravel-oci8#484]
### Summary of problem or feature request

Hi, 

When I try to insert database, I got the error message with the error code is **[Error Code : 1465 Error Message : ORA-01465: invalid hex number]**

Thank you and sorry for my bad english.

my php insert to database code is :

DB::table('USERS_LOG')->insert([
            [
                'LOG_ID' => "SYS_GUID()", 
                'USER_ID' => "'".$value->user_id."'",
                'LAST_LOGIN_IP' => "'".$_SERVER['REMOTE_ADDR']."'",
                'LAST_LOGIN' => 'SYSDATE'
            ]
        ]);

the error :

> Error Code : 1465 Error Message : ORA-01465: invalid hex number Position : 150 Statement : insert into USERS_LOG (LOG_ID, USER_ID, LAST_LOGIN_IP,LAST_LOGIN) values (:p0, :p1, :p2, :p3) Bindings : [SYS_GUID(),'03C87F629C16443AAB429499680183DA','::1',SYSDATE] (SQL: insert into USERS_LOG (LOG_ID, USER_ID, LAST_LOGIN_IP,LAST_LOGIN) values (SYS_GUID(), '03C87F629C16443AAB429499680183DA', '::1', SYSDATE))

### System details

- Operating System : windows 10
- PHP Version : 7.1
- Laravel Version : 5.7
- Laravel-OCI8 Version : 5.7

**Comment by yajra** [comment]
I think you should specify some values as raw sql.

```php
DB::table('USERS_LOG')->insert([
[
'LOG_ID' => DB::raw("SYS_GUID()"),
'USER_ID' => "'".$value->user_id."'",
'LAST_LOGIN_IP' => "'".$_SERVER['REMOTE_ADDR']."'",
'LAST_LOGIN' => DB::raw('SYSDATE'),
]
]);
```

**Comment by anasrullah** [comment]
Thanks a lot yajra, my problem is solved. :)
