### ISSUE TITLE
Call to undefined function Yajra\Pdo\oci_connect() 

### ISSUE THREAD

**Issue by tima31** [yajra/laravel-oci8#487]
hello, I came here after long search 
![3](https://user-images.githubusercontent.com/47798916/53054714-9248bf00-34a5-11e9-9fbc-ce4111076522.PNG)

in php.ini i removed quotes to both oci8 and oci8_11g
![capture2](https://user-images.githubusercontent.com/47798916/53054814-ec498480-34a5-11e9-91b5-d51d29a1c08e.PNG)

in phpinfo() oci8 seems to be enabled 
![capture](https://user-images.githubusercontent.com/47798916/53054928-5104df00-34a6-11e9-8d40-78f48804b031.PNG)

oci8.dll and oci8_11g.dll exist in "C:\wamp\bin\php\php5.5.12\ext"

I use oracle 11g xe 
instantclient 11.2 downloaded and path added, I tried both 64 bit and 32 bit version 

on CLI :
run command "php -m"  => don't find oci8 
run command "php --ri oci8" => extension "oci8" not present

### System details

- Operating System : windows 7 - 64 bits
- PHP Version : 5.5.12
- Laravel Version : 5.2.*
- Laravel-OCI8 Version : 5.2

I tried this code in C:\wamp\www
![4](https://user-images.githubusercontent.com/47798916/53055945-e05fc180-34a9-11e9-86ab-22c20a308db6.PNG)
and that worked !
![5](https://user-images.githubusercontent.com/47798916/53055996-fff6ea00-34a9-11e9-8e64-4ce9aec486b9.PNG)

so any help please !

**Comment by yajra** [comment]
On some installations, `php.ini` for cli is different. I suggest you check which config file is being loaded on cli and then enable the oci8 plugin there. On mac, here is how I check it.

```
> php -i | grep php.ini

Configuration File (php.ini) Path => /usr/local/etc/php/7.1
Loaded Configuration File => /usr/local/etc/php/7.1/php.ini
```

**Comment by tima31** [comment]
Hi, thank you for your reply,
on windows  >php --ini and this is whet i've got 

![111](https://user-images.githubusercontent.com/47798916/53074783-e70f2880-34eb-11e9-8b80-9c2296ae3eac.PNG)

I suppose that the probleme is in the "Configuration File (php.ini) Path" because the file s not located there ! I really don't know how to fix this.

**Comment by tima31** [comment]
problem soleved ! 
it seems that php.ini shown in phpinfo() is used by apache , and it's diffrent from the one used by CLI
I enabled oci8 in php.ini which exist in the Loaded Configuration File and now it works.

Thank you

**Comment by bibi26** [comment]
### **__**cv 

> 

> 

> [``]([url]([url]([url](url
Duplicate of #))))

**Comment by anfazaba** [comment]
No solving. I have the same Issue.
I install Instant Client Downloads for Linux x86-64 v 19.3 and I have the same error:

{
    "error": "Internal error",
    "type": "Call to undefined function Yajra\\Pdo\\oci_connect()",
    "code": 500,
    "error_description": "Ha ocurrido un error, comuníquese con su proveedor",
    "line": 455,
    "file": "/home/vagrant/investigarpuj/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php"
}
With command  php -i | grep -i oracle I get this:

vagrant@homestead:~$ php -i | grep -i oracle
Oracle Run-time Client Library Version => 19.3.0.0.0
Oracle Compile-time Instant Client Version => 19.3
ORACLE_BASE => /usr/local/lib/instantclient_19_3
ORACLE_HOME => /usr/local/lib/instantclient_19_3
$_SERVER['ORACLE_BASE'] => /usr/local/lib/instantclient_19_3
$_SERVER['ORACLE_HOME'] => /usr/local/lib/instantclient_19_3

I dont know what to do and I'm going crazy!

**Comment by cbj4074** [comment]
@anfazaba Take a look at my post on StackOverflow (in particular, the section `Edit 5: Solution`):

https://stackoverflow.com/questions/50396992/how-does-one-enable-the-oci8-php-extension-using-the-oracle-instant-client-in

Basically, Homestead runs Ubuntu 18.04 LTS, which in turn uses `systemd`, and additional steps are required to set the environment appropriately when PHP-FPM is started via `systemd`.

**Comment by anfazaba** [comment]
Really, thank you so much! Description in _Edit 5: Solution_ solved all problem. I didn't know that doing all that process could solve the problem.

Basically doing the following points below:

Needless to say, we want to avoid editing the package maintainer's file (to avoid conflicts during future upgrades), so we extend it instead:

# mkdir /etc/systemd/system/php7.1-fpm.service.d
# touch /etc/systemd/system/php7.1-fpm.service.d/environment.conf
To this file we add the following:

[Service]
Environment=LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2
And to make the change effective:

# systemctl daemon-reload
# systemctl restart php7.1-fpm

Really thank you so much!!

**Comment by iburrows** [comment]
I cannot resolve this issue with the above solution. 
I am using PHP 7.1.33. Output frpm `phpinfo();`

![image](https://user-images.githubusercontent.com/21207059/70809088-5f1f4580-1dc1-11ea-9c44-9ed808378777.png)

Under Modules:

![image](https://user-images.githubusercontent.com/21207059/70809174-837b2200-1dc1-11ea-9d77-a1115ca5e2dd.png)

I am not sure what else to try.

Thanks for the help.
