### ISSUE TITLE
Issue when running raw select query

### ISSUE THREAD

**Issue by baneetsharma** [yajra/laravel-oci8#489]
I am trying to execute the following query, but it is always returning me just two records that too with NULL values but in actual there are more than 200 records matching following query.  Querry is working fine and giving me accurate results when I run directly on the database or with core PHP but failing when trying to do it with Laravel.

Following is the Code sample of the Laravel query: 

       $query_str = "  select b3.* from TEST_DB.HV_ORDERS o
        LEFT JOIN TEST_DB.hv_ord_det_denorm od on (o.ACCESS_W_PREFIX = 
        od.ACCESS_W_PREFIX )
       LEFT JOIN TEST_DB.CMD_REFERENCE b3 on (
      (REGEXP_SUBSTR(o.ACCESS_W_PREFIX, '[A-Z][A-Z]-') = 
      b3.ACCESS_NUMBER_STARTS_WITH )
      AND (b3.SALES_GROUP = (CASE WHEN SUBSTR(od.SALES_GROUP, 1, 3) in ('ABC', 'JKM', 
     'XYZ') THEN 'W2'
		ELSE '1099' END))
        AND (get_dec_val(od.collected_date_new) >= b3.START_DATE)
        AND (get_dec_val(od.collected_date_new) <= NVL(b3.END_DATE, sysdate+1))
     )
      where
		od.FINAL_DATE IS NOT NULL
                and (od.FINAL_DATE BETWEEN TO_DATE ('2019/01/03', 'yyyy/mm/dd') AND TO_DATE 
      ('2019/02/06', 'yyyy/mm/dd'))
                and o.ACCESS IN('12345678')
		order by od.FINAL_DATE desc";

       $result  = DB::connection('oracle')->select($query_str);

Now, this is always returning me just 2 records with null values.
 But If I run the same query with CORE PHP Like :

 
       $db = "(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1) 
        (PORT = 1521)))(CONNECT_DATA=(SERVICE_NAME=XXXXXXXXXXXXXXXXXXXX)))";

        $conn = oci_connect("XXXXXX", "XXXXXXXX", $db);
        if (!$conn) {
            $m = oci_error();
            echo $m['message'] . PHP_EOL;
            exit;
        } else {
            print "Oracle database connection online" . PHP_EOL;
            $s = oci_parse($conn, $query_str);
            oci_execute($s);
            oci_fetch_all($s, $res);
            dd($res);
        }
        oci_close($conn);

I am getting correct results for this. So I doubt there is something wrong in the library. 
Any help is appriciated.

### System details

- Operating System: Ubuntu 16.04
- PHP Version: 7.2.15
- Laravel Version: 5.7.20
- Laravel-OCI8 Version: 5.7.2

**Comment by yajra** [comment]
Can you please provide the error dump? The code looks fine.

**Comment by baneetsharma** [comment]
@yajra It is always returning me just two records that too with NULL values and no error logs.

For now, I have run this query in core PHP way and I am getting correct results for the same.

**Comment by bendparker** [comment]
I have this exact same issue and I believe that it is caused by the where clause involving a date, as any other where clauses seem to work correctly.  I can get the data using the bare bones PHP that OP provided, although I would love to get this working the "laravel" way.  I can provide any info that is needed.

**Comment by yajra** [comment]
@bendparker might indeed be related to dates. When using the package, the date format in session is set to `YYYY-MM-DD HH:MI:SS` if I recall correctly.  If values are not in this format, you need to consider using `TO_DATE()` or `TO_CHAR` on your query and map. accordingly.
