### ISSUE TITLE
Error: ORA-12505: TNS:listener does not currently know of SID given in connect descriptor

### ISSUE THREAD

**Issue by anowarcst** [yajra/laravel-oci8#49]
'oracle' => array(
                    'driver' => 'oracle',
                    'host' => '192.168.152.189',//server IP
                    'port' => '1521',
                    'database' => 'orcl', //SID
                    'username' => 'system',
                    'password' => '123456',
                ),
I've add this code in app/config/database.php
But I couldn't connected to Oracle with Laravel, from my client PC to Server.

show this Error: ORA-12505: TNS:listener does not currently know of SID given in connect descriptor

**Comment by yajra** [comment]
[double check your SID](http://docs.oracle.com/cd/B19306_01/server.102/b14219/net12500.htm).

ORA-12505: TNS:listener does not currently know of SID given in connect descriptor
Cause: The listener received a request to establish a connection to a database or other service. The connect descriptor received by the listener specified a SID for an instance (usually a database instance) that either has not yet dynamically registered with the listener or has not been statically configured for the listener. This may be a temporary condition such as after the listener has started, but before the database instance has registered with the listener.
Action:
- Wait a moment and try to connect a second time.

- Check which instances are currently known by the listener by executing: lsnrctl services <listener name>

- Check that the SID parameter in the connect descriptor specifies an instance known by the listener.

- Check for an event in the listener.log file.

**Comment by anowarcst** [comment]
I was install a oracle 11g client in my local PC to connect Oracle server (by IP). 
It is connected & working fine with CodeIgniter Framework. But I'm fail to connect with Laravel. 

as you tell:
I don't know about this listener & there (client) have no option to create listener. How can i config this listener? 
[Thanks for your kind reply & sorry for late.]

**Comment by yajra** [comment]
[Oracle listener](http://docs.oracle.com/cd/B28359_01/network.111/b28317/listener.htm#NETRF293) would need to be setup of the database server.

On the other hand, If it works on Codeigniter, then there must be something that we are missing. Can you check if you have the correct SID (case sensitive) as per issue #19

**Comment by uqcgreen** [comment]
In case it helps anyone, this error can be a result of not adding the "service_name" key to the connection array.

For a discussion on SIDs vs service names:
http://stackoverflow.com/questions/43866/how-sid-is-different-from-service-name-in-oracle-tnsnames-ora
