### ISSUE TITLE
Problem with JSON column after upgrade 

### ISSUE THREAD

**Issue by vystepanenko** [yajra/laravel-oci8#490]
### Summary of problem or feature request
After upgrade lumen from version 5.2.* to 5.7.* sql queries which contains json data are broken
### Code snippet of problem

I have table wich contains JSON column
```
CREATE TABLE tabjson
   (id          NUMBER NOT NULL,
    jsondata CLOB
    CONSTRAINT ensure_json CHECK (jsondata IS JSON));
```

In this "jsondata" column i have some data in valid json format
`{"uuid":"12345","name":"Foo"}`

I make such quirie
```
$client = DB::table('tabjson as tj')
        ->select('tj.jsondata.name')
        ->where('tj.jsondata.uuid', 12345)
        ->first();
```

Till upgrade to newer version everything was fine because it made queries in same case like
`select * from(select tj.jsondata.name from tabjson as tj where tj.jsondata.uuid = 12345)`

But now it make query parametrs  in UPPERCASE like
`select * from (select TJ.JSONDATA.NAME from TABJSON AS TJ where TJ.JSONDATA.UUID = 12345)`

This query return NULL because JSON data is case sensitive and
`TJ.JSONDATA.NAME != TJ.JSONDATA.name`

Is there any way to return old behavior without downgrade lumen to 5.2.* ?

### System details

- CentOS Linux release 7.6.1810
- PHP 7.2.13
- "laravel/lumen-framework": "5.7.*",
- "yajra/laravel-oci8": "^5.2"

**Comment by vystepanenko** [comment]
As quick solution and if you have not much queries to fix you can use this
```
$client = DB::table('tabjson as tj')
        ->selectRaw('tj.jsondata.name')
        ->whereRaw('tj.jsondata.uuid='. 12345)
        ->first();
```

**Comment by yajra** [comment]
@vystepanenko thanks for sharing the solution. It is indeed the new behaviour of the package to uppercase all entities for better compatibility with oracle. For some cases, the solution would be using raw sql like on your case.
