### ISSUE TITLE
ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by RParama** [yajra/laravel-oci8#497]
### Summary of problem or feature request
OCI8 already show in my phpinfo.php

but when i want to migrate in laravel its show
In Oci8.php line 464: 
ORA-12154: TNS:could not resolve the connect identifier specified

Please help, thank you

### System details

- Operating System : Windows 8
- PHP Version : 7.32
- Laravel Version : 5.4
- Laravel-OCI8 Version : 2.2.0

**Comment by joaomantovani** [comment]
Same issue here, but I'm on linux using PHP 7.32

**Comment by joaomantovani** [comment]
#492 fixed for me
