### ISSUE TITLE
Creating persistent connections

### ISSUE THREAD

**Issue by jubairsaidi** [yajra/laravel-oci8#50]
Is there a way to specify all connections using a persistent connection rather than on demand the way it is currently?

**Comment by jubairsaidi** [comment]
nm found it I think.  in the db config we need to add: 

		'options'   => [
			PDO::ATTR_PERSISTENT => true,
		],

Is this correct?

**Comment by jubairsaidi** [comment]
though... I wonder how/if it's working as intended?  for each life cycle of a request, I'd like to open a connection only once, re-use that connection for everything in that request and then only close it when the request is done.

**Comment by yajra** [comment]
```php
'options'   => [
        PDO::ATTR_PERSISTENT => true,
    ],
```

Does the code above doesn't work? Have not tried using persistent connection yet but I checked the code and I guess it should work as intended.

```php
// Attempt a connection
if (isset($options[PDO::ATTR_PERSISTENT]) && $options[PDO::ATTR_PERSISTENT])
{
	$this->_dbh = @oci_pconnect($username, $password, $dsn, $charset);
}
else
{
	$this->_dbh = @oci_connect($username, $password, $dsn, $charset);
}
```

**Comment by jubairsaidi** [comment]
It does work, but certain queries like:

```sql
alter session set NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
alter session set NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
ALTER SESSION SET CURRENT_SCHEMA = shcema_name
```
Are still being run per request which technically from what I gather don't need to if you are accessing an existing persistent connection.

**Comment by yajra** [comment]
Yes, those queries will be run per request because Laravel creates new connection every request and those queries were part of process when creating a new [Oci8Connection](https://github.com/yajra/laravel-oci8/blob/master/src/yajra/Oci8/Oci8ServiceProvider.php#L31). However, aside from that, persistent connection does work properly.

**Comment by jubairsaidi** [comment]
Ah, too bad there doesn't seem to be a way to check to see if there is a connection active, that would be useful...  Thanks!
