### ISSUE TITLE
oci_bind_by_name(): ORA-01036 illegal variable name/number

### ISSUE THREAD

**Issue by Rizlantamima** [yajra/laravel-oci8#502]
### Summary of problem or feature request

I'm using laravel 5.4, i try to use bind query, then i saw that, this issue can be solved if i pass the value direcly but, that isn't solve the problem because if i do that (directly) it will harmful for sql injection.

### Code snippet of problem
whereRaw("upper(bill_code) LIKE '%?%' ", [strtoupper($keyword)])

### System details

- Operating System
- PHP 7.2
- Laravel 5.4
- Laravel-OCI8 yajra/laravel-oci8 5.4

**Comment by yajra** [comment]
Can you please paste the full query to replicate the issue?

P.S. Sorry, but I may not be able to support Laravel 5.4 & lower version anymore. If you can fix, please do not hesitate to submit a PR.

**Comment by yajra** [comment]
The syntax you provided seems correct.

```php
->whereRaw("upper(bill_code) LIKE '%?%' ", [strtoupper($keyword)])
```

But I think this is how I would code it:

```php
whereRaw("upper(bill_code) LIKE upper(?)", ["%{$keyword}%")])
```
