### ISSUE TITLE
missing identifier Position : 242 Statement ALTER SESSION

### ISSUE THREAD

**Issue by muhghazaliakbar** [yajra/laravel-oci8#507]
### Summary of problem or feature request

Hi, @yajra 
I'm having problem with this:
```
Error Code : 931 Error Message : ORA-00931: missing identifier Position : 242 Statement : ALTER SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS = '.,' EDITION = 18.0.0.0 Bindings : [] (SQL: ALTER SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS = '.,' EDITION = 18.0.0.0)
```
<img width="1440" alt="Screenshot 2019-05-23 12 18 13" src="https://user-images.githubusercontent.com/8321936/58225501-df625880-7d54-11e9-8c81-eafb2287e9b8.png">

### Code snippet of problem

Here my `.env` config:
```
DB_ORACLE_HOST=192.168.10.101
DB_ORACLE_PORT=1521
DB_ORACLE_DATABASE=orclcdb
DB_ORACLE_USERNAME=system
DB_ORACLE_PASSWORD=oracle
DB_ORACLE_CHARSET=
DB_ORACLE_PREFIX=
DB_ORACLE_SCHEMA_PREFIX=
DB_ORACLE_EDITION=18.0.0.0
DB_ORACLE_SERVER_VERSION=18c
```

### System details

- Operating System: `MacOS Mojave`
- PHP Version: `7.3`
- Laravel Version: `5.8.*`
- Laravel-OCI8 Version: `5.8.*`

Is anyone can explain to me what happened and how to fix? I'm new in oracle btw :(

**Comment by yajra** [comment]
Might be on edition, try setting it to empty value:

```
DB_ORACLE_EDITION=
```

Or better, try executing the generated query using SQL Developer and debug it from there to see which session vars causes the issue.
