### ISSUE TITLE
Creating a CHAR column

### ISSUE THREAD

**Issue by christopheo** [yajra/laravel-oci8#51]
I had an error when I tried to create a column of the type CHAR. I solved it by adding this function to the OracleGrammar class :

```php
/**
 * Create the column definition for a char type.
 *
 * @param  \Illuminate\Support\Fluent  $column
 * @return string
 */
protected function typeChar(Fluent $column)
{
	return "char({$column->length})";
}
```

I don't know if this is normal.

**Comment by yajra** [comment]
thanks for reporting. fixed on [v2.1.0](https://github.com/yajra/laravel-oci8/commit/b99d612cbf7484a5bdc4b135edf841392ea784ba)
