### ISSUE TITLE
ORA-01400: cannot insert NULL into

### ISSUE THREAD

**Issue by kikikurniadi** [yajra/laravel-oci8#514]
### Summary of problem or feature request

Error Code     : 1400
Error Message : ORA-01400: cannot insert NULL into ("username"."table"."key")
Position      : 0
Statement     : insert into "USERS" ("NAME", "EMAIL", "PASSWORD", "UPDATED_AT", "CREATED_AT") values (:p0, :p1, :p2, :p3, :p4) returning "ID" into :p5
Bindings      : [kiki,skdba@anton,$2y$10$1ctYlMwzA6cJPAZ2ybwTCO5LUAXvjM0vxZ1po8XEo0l1eAgS76b5q,2019-07-19 01:21:43,2019-07-19 01:21:43,0]

### Code snippet of problem

DB_CONNECTION=oracle
DB_HOST=127.0.0.1
DB_PORT=1521
DB_DATABASE=xe
DB_USERNAME=skdba
DB_PASSWORD=password

### System details

- Operating System: windows 7
- PHP Version 7.1.3
- Laravel Version 5.8
- Laravel-OCI8 Version 5.8
- Oracle 10g xe

**Comment by kikikurniadi** [comment]
![Untitled](https://user-images.githubusercontent.com/52684994/61505374-c5698d00-aa08-11e9-8e1d-467f68c54a3b.png)

**Comment by yajra** [comment]
Can you provide some snippets to reproduce the issue? Did you create the table using Laravel
s schema builder?
