### ISSUE TITLE
Decide integer column precision?

### ISSUE THREAD

**Issue by mansouralex** [yajra/laravel-oci8#52]
How to decide the precision of the integer column?

**Comment by yajra** [comment]
```php
$table->integer('id')->length(10);
```

**Comment by mansouralex** [comment]
This is decide the column length of digits and the precision will be 0 by default. It displays as Number(10,0) in the table schema.

**Comment by yajra** [comment]
Oh got confused there. If that is the case then better use decimal instead. But this will use `number` instead of `integer`. Also, I think that a proper integer does not have decimal places?

```php
$table->decimal('id', 12, 3);
```

**Comment by mansouralex** [comment]
No it does, I already update the table schema by executing this query, and it take the changes : alter table example modify amount NUMBER(12,3);

**Comment by yajra** [comment]
[Integers](http://www.mathopenref.com/number.html) does not have precision/decimal places.

Does `decimal` solve your issue? Feel free to close this. Thanks!
