### ISSUE TITLE
Unsupported Laravel 6.0.x

### ISSUE THREAD

**Issue by NuBOXDevCom** [yajra/laravel-oci8#521]
### Summary of problem or feature request

The package (branch 5.8) Composer requires laravel 5.8. *.
As a result, it is impossible to pass Laravel to the latest version (6.0.x) currently.
Have you planned to fix this in the next few days? Thank you.

https://laravel.com/docs/6.0/releases
https://laravel.com/docs/6.0/upgrade

### Code snippet of problem
nothing

### System details
- Operating System: Debian 9.x
- PHP Version: 7.3.x
- Laravel Version: 6.0.0
- Laravel-OCI8: Version 5.8.*

**Comment by yajra** [comment]
Support for Laravel 6 added on master branch. Will tag later on after testing on actual projects. But as per tests, all are passing now. Kindly check too and provide some feedbacks when you got the chance. Thanks!

**Comment by NuBOXDevCom** [comment]
Perfect ! I'm testing this in production environment shortly and I'll tell you if it's OK for me.
Thanks.

**Comment by yajra** [comment]
v6.0.0 released 🚀

**Comment by NuBOXDevCom** [comment]
Thank you very much for your speed!
