### ISSUE TITLE
Sequences not considering prefix_schema

### ISSUE THREAD

**Issue by elislenio** [yajra/laravel-oci8#523]
### Summary of problem or feature request
Value of property $this->sequence is returned without considering prefix_schema config parameter

### Code snippet of problem
Sequence.php:

```php
public function nextValue($name)
    {
        if (! $name) {
            return 0;
        }

        return $this->connection->selectOne("SELECT $name.NEXTVAL as id FROM DUAL")->id;
    }
```

### System details
- PHP Version: 7.2
- Laravel Version 5.5
- Laravel-OCI8 Version 5.5

**Comment by elislenio** [comment]
Hi Ajay, it is quite simple to reproduce, this is the code snippet:

DB conf:
```
DB_CONNECTION=oracle
DB_HOST=localhost
DB_PORT=1521
DB_DATABASE=xe
DB_USERNAME=APP_USER_WWW  <- this is the web user, an empty schema
DB_SCHEMA_PREFIX=APP_SCHEMA   <- this is the schema where the sequence exists
```

Next, anywhere in the app, this code raises ORA-02289:
```
<?php
$nextValue = DB::getSequence()->nextValue('my_sequence');
?>
```
I think the function nextValue() needs to handle the schema prefix parameter to properly construct the select clause.

Regards,

**Comment by yajra** [comment]
@elislenio can you please give #535 a review if it fixes this issue? Thanks!
