### ISSUE TITLE
for update nowait

### ISSUE THREAD

**Issue by ramonribeiro96** [yajra/laravel-oci8#525]
Guys, how do I 'for update nowait' in a query?
Is there any alternative to this?

`for update nowait`

when I run, she doesn't hold in session, is probably committing soon after.

### System details

- Operating System Ubuntu Server
- PHP Version 7.3
- Laravel Version 5.8
- Laravel-OCI8 Version 5.8

**Comment by yajra** [comment]
Haven't used this feature yet but maybe try doing it inside a DB transaction to disable auto commit?

**Comment by ramonribeiro96** [comment]
I've been looking, it seems nowait is not a good practice. But in some cases there is nothing to do, only it remains!
So I used the default PHP connection to oci and got a result I needed!
Thanks for the reply, otherwise I'll try to use!
