### ISSUE TITLE
Inconsistent Datatypes

### ISSUE THREAD

**Issue by francisceril** [yajra/laravel-oci8#526]
### Summary of problem or feature request

I'm trying to authenticate my users and keep getting this error.

```oci_fetch_assoc(): ORA-00932: inconsistent datatypes: expected CHAR got ADT (SQL: select * from (select * from "SEC_USER_PROFILE" where "EMPLOYEE_ID" = 10001) where rownum = 1)```

I have no issues connecting to the database. This error only occurs when authenticating or when querying ```select *```. 
Query works fine if I use column names on my ```select``` statement.

### Test auth

```
$username = 10001;
$password = mypassword;

    if(Auth::attempt(['employee_id'=>$username, 'password'=>$password])) {
        alert('Yahoo!');
    }
```

### System details

- Operating System : MacOS 10.14.6
- PHP Version: 7.3.9
- Laravel Version: 6.0.x
- Laravel-OCI8 Version: Latest

**Comment by yajra** [comment]
Not familiar with ADT data type of Oracle. Maybe try removing that column by manually selecting only the needed columns?

**Comment by francisceril** [comment]
> Not familiar with ADT data type of Oracle. Maybe try removing that column by manually selecting only the needed columns?

Yes, that would definitely work as I can query tables when manually specifying the columns.
The problem is I have no idea how to make the authentication against a query and not directly from the table. 😀
