### ISSUE TITLE
Oracle functions exists?

### ISSUE THREAD

**Issue by adailsonm** [yajra/laravel-oci8#527]
I miss the use of the oracle's own functions like TRUNC, TO_DATE, DECODE would have to do this with this library, if yes, it would be interesting to document it, otherwise, I think to help in its contribution using even the doctrine that I have some ready. awaiting return.

**Comment by yajra** [comment]
Just use `DB::raw()` for these functions.

```php
->select(DB::raw("TRUNC(column)")...
```
