### ISSUE TITLE
laravel 5.8 php 7.2.14 

### ISSUE THREAD

**Issue by dont65** [yajra/laravel-oci8#528]
### Code snippet of problem

 Problem 1
    - Installation request for yajra/laravel-oci8 5.8.2 -> satisfiable by yajra/laravel-oci8[v5.8.2].
    - yajra/laravel-oci8 v5.8.2 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\wamp64\bin\php\php7.2.14\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
 
- Operating System
- PHP Version 7.2.14
- Laravel Version 5.8
- Laravel-OCI8 Version 2.1.8

**Comment by yajra** [comment]
As the error suggests, you need to have oci8 instant client installed. Please check several issues like this for ref.
