### ISSUE TITLE
Prefix Issue when using Query Builder.

### ISSUE THREAD

**Issue by pedrogaldino** [yajra/laravel-oci8#530]
### Summary of problem or feature request
My PHP process finish without any exceptions when i try to execute a query with the Query Builder.

Doing some tests, i've discovered that problems occurs when i set the oracle prefix configuration.

After i've removed this config variable, works fine.

Anyway, it's a problem.

### Code snippet of problem

```php
DB::table('MYTABLE')->first();
```
-->

### System details
- SO Version Mac OS High Sierra 10.13.06
- PHP Version 7.3.8
- Laravel Version 5.8
- Laravel-OCI8 5.8
- OCI Extension Version 2.2.0

**Comment by yajra** [comment]
Works well for me, can't replicate the issue.
