### ISSUE TITLE
mac-osx catalina

### ISSUE THREAD

**Issue by sciracioglu** [yajra/laravel-oci8#539]
### Summary of problem or feature request

Yajra\Pdo\Oci8\Exceptions\Oci8Exception
ORA-24415: Missing or null username. 

when i update osx. i get this error. 

### Code snippet of problem
Yajra\Pdo\Oci8::connect :460
vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php:460

### System details

- Operating System
macosx catalina
- PHP Version
php 7.3
- Laravel Version
laravel version 6.1
- Laravel-OCI8 Version
oci8-2.2.0

**Comment by renanwilliam** [comment]
I have a lot of projects using Catalina and have no problems. Looks like your connection is missing the username (maybe some file permission problem on config files?)

**Comment by sciracioglu** [comment]
i was back to mojave. i will try again. but can you tell me, which client version you use? i've tried all version through

**Comment by renanwilliam** [comment]
System details
Operating System: MacOS | Docker Debian Image
PHP Version: 7.2.21
Laravel Version: 5.8.34
Laravel-OCI8 Version: v5.8.2

**Comment by sciracioglu** [comment]
ok. because of docker I think.
