### ISSUE TITLE
Memory problem to fetch large datasets

### ISSUE THREAD

**Issue by renanwilliam** [yajra/laravel-oci8#540]
### Summary of problem or feature request

I'm selecting data from a VIEW in Oracle that in real size is around 50MB (61 columns and 263.000 rows). I only have one column with data length of 4000 and all others up to 100.

When I selecting using Laravel (split into packages of 10.000 records) it is occupying around 3GB in memory.

I have made some previous search and tried disable log queries using DB::disableQueryLog, $connection->disableQueryLog(), included gc_collect_cycles call after each SELECT and unset the results variable - without any effect.

I really not have sure if this is a normal behavior or have some problem or other way to do that. In my debug session I have identified that where memory increases considerably is on this line: https://github.com/yajra/pdo-via-oci8/blob/master/src/Pdo/Oci8/Statement.php#L592 (what make sense  but not to much - is taking around 150MB~200MB for 10.000 rows).

### Code snippet of problem

```php
<?php

use Yajra\Oci8\Connectors\OracleConnector;
use Yajra\Oci8\Oci8Connection;

/**
 * @return Oci8Connection
 * @throws \Exception
 */
private function getOracleConnection()
{
    $config = [
        'driver' => 'oracle',
        'host' => 'host',
        'database' => 'database',
        'port' => 'port',
        'username' => 'user',
        'password' => 'password',
        'charset' => 'charset',
        'schema' => 'schema',
        'options' => [
            \PDO::ATTR_PERSISTENT => true
        ],
    ];
    $connector = new OracleConnector();
    $connection = $connector->connect($config);

    $db = new Oci8Connection($connection, $database);

    return $db;
}

protected function loadSourceSystemData(): Collection
{
    $connection = $this->getOracleConnection();

    DB::disableQueryLog();
    $connection->disableQueryLog();

    $package_size = 10000;

    $return = new Collection();
    $offset = 0;

    while(true) {
        $records = $connection->query()
            ->from('ZVPCP003')
            ->take($package_size)
            ->offset($offset)
            ->get();

        if(empty($records)) break;

        $return = $return->merge($records);
        unset($records);

        gc_collect_cycles();
        $offset += $package_size;
    }

    return $return;
}
```

Update:I have collected some statistics about how memory is consuming for 10.000 entries:
```
Entries: 10000 | Memory: 124 MB  
Entries: 20000 | Memory: 241 MB  
Entries: 30000 | Memory: 357 MB  
Entries: 40000 | Memory: 474 MB  
Entries: 50000 | Memory: 590 MB  
Entries: 60000 | Memory: 707 MB  
Entries: 70000 | Memory: 825 MB  
Entries: 80000 | Memory: 941 MB  
Entries: 90000 | Memory: 1058 MB  
Entries: 100000 | Memory: 1174 MB  
Entries: 110000 | Memory: 1290 MB  
Entries: 120000 | Memory: 1407 MB  
Entries: 130000 | Memory: 1523 MB  
Entries: 140000 | Memory: 1644 MB  
Entries: 150000 | Memory: 1760 MB  
Entries: 160000 | Memory: 1876 MB  
Entries: 170000 | Memory: 1993 MB  
Entries: 180000 | Memory: 2109 MB  
Entries: 190000 | Memory: 2226 MB  
Entries: 200000 | Memory: 2342 MB  
Entries: 210000 | Memory: 2459 MB  
Entries: 220000 | Memory: 2575 MB  
Entries: 230000 | Memory: 2691 MB  
Entries: 240000 | Memory: 2808 MB  
Entries: 250000 | Memory: 2924 MB  
Entries: 260000 | Memory: 3041 MB  
Entries: 263152 | Memory: 3087 MB  
```
### System details

- Operating System: MacOS | Docker Debian Image
- PHP Version: 7.2.21
- Laravel Version: 5.8.34
- Laravel-OCI8 Version: v5.8.2

**Comment by sciracioglu** [comment]
can you try to use cursor?

https://community.oracle.com/thread/379275?start=0&tstart=0

**Comment by yajra** [comment]
@sciracioglu good point. And to add, since Laravel 6, we can now leverage LazyCollection which addresses the memory issues.

```php
$policies = DB::table('policies')->cursor();

foreach ($policies as $policy) {
    dump($policy);
}
```

**Comment by renanwilliam** [comment]
I have tried with cursor and behavior looks like the same - with a difference of 1MB less for each 10.000 records. Spending some time debugging it's look like a oci8 behavior, like it's don't clear the memory after each cursor interation.

Have made some discussions about in this topic on [Stackoverflow](https://stackoverflow.com/questions/58574628/why-select-table-with-200-000-records-is-using-too-much-memory-2gb) but I think that is not related with the package.
