### ISSUE TITLE
updateOrCreate updates whole table if model is found

### ISSUE THREAD

**Issue by awidschwendter** [yajra/laravel-oci8#544]
"name": "yajra/laravel-oci8",
"version": "v5.8.2",

when using the "Oraclemodel:updateOrCreate" method, the whole table is updated with the same values if a model is found.

**Comment by yajra** [comment]
Can you please provide some snippets on how to reproduce the issue? Thanks!

**Comment by awidschwendter** [comment]
Hi, meanwhile i don't  think its a bug in oci-8. the tables i experienced the issue have no primary key set. This seems to cause this unwanted behaviour.
