### ISSUE TITLE
cannot connect oracle 10g

### ISSUE THREAD

**Issue by Meshkat123** [yajra/laravel-oci8#545]
<------------------- Error -------------------->
Could not connect to the database. Please check your configuration. error:

<-------------------- Code ------------------>

'oracle' => [
        'driver'         => 'oracle',
        'tns'            => env('DB_TNS', ''),
        'host'           => env('DB_HOST', '192.168.01.44'),
        'port'           => env('DB_PORT', '1521'),
        'database'       => env('DB_DATABASE', 'orcl'),
        'username'       => env('DB_USERNAME', ''),
        'password'       => env('DB_PASSWORD', ''),
        'charset'        => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'         => env('DB_PREFIX', ''),
        'prefix_schema'  => env('DB_SCHEMA_PREFIX', ''),
        'edition'        => env('DB_EDITION', ''),
        'server_version' => env('DB_SERVER_VERSION', '11g'),
    ]
<-------------- Controller --------------------->

<?php

namespace App\Http\Controllers\store;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use DB;
class storeController extends Controller
{
    public function users(){
    	try {
    		DB::connection()->getPdo();
		} catch (\Exception $e) {
		    die("Could not connect to the database.  Please check your configuration. error:");
		}
		return 0;
    }
}

**Comment by yajra** [comment]
Try removing these on your config:

```
'edition' => env('DB_EDITION', ''),
'server_version' => env('DB_SERVER_VERSION', '11g'),
```
