### ISSUE TITLE
What about move "ext-oci8" to recommended or something like this

### ISSUE THREAD

**Issue by zorn-v** [yajra/laravel-oci8#546]
I have a project with OPTIONAL oracle support. Very LITTLE piece of code depends on oracle db and may not execute at all in dev/test env. But I need to provide `--ignore-platform-reqs` for `composer update` and other composer related commands because I dont need register on FUCKING oracle site to download FUCKING oracle instant client to compile FUCKING ext-oci8 which not need on that machines.

Thanks for understanding

**Comment by yajra** [comment]
I feel you there, I was hit by the same issue some time ago when I switch the DB :). 

Anyways, I can reconsider this request. It was added to avoid issues where the package is not working due to `ext-oci8` was missing. Please submit a PR on how you would want us to proceed with this. Thanks!

**Comment by zorn-v** [comment]
Something like https://github.com/yajra/laravel-oci8/pull/547

**Comment by Jon4t4n** [comment]
You can fake platform dependencies with Composer.

[https://getcomposer.org/doc/06-config.md#platform](https://getcomposer.org/doc/06-config.md#platform)

Add the following to the composer.json in your project:
```json
"config": {
    "platform": {
        "ext-oci8": "2.0"
    }
}
```

**Comment by zorn-v** [comment]
Thanks. How I forgot about this )
You can run `composer config platform.ext-oci8 2.0` BTW

**Comment by yajra** [comment]
@zorn-v do you still think we need https://github.com/yajra/laravel-oci8/pull/547 or the platform config is enough?

@Jon4t4n thanks for that info. I didn't know composer has something like that. :)

**Comment by zorn-v** [comment]
@yajra platform config is enough. 
More of then I was need it because I have `platform.php 7.2.5` (7.3 on dev machine but 7.2 on production without possible update) and `--ignore-platform-reqs` ignore that config section :wink: 
Now I dont need that flag and all is ok.

Maybe add that info in readme ?

**Comment by mstaack** [comment]
i think having it in the requirements is the exact use case for this option in the `composer.json` ;)
so we should keep it and close this for now @yajra 
any prs to the readme/setup etc are welcome

**Comment by zorn-v** [comment]
There is a problem with composer 2
It have a new platform-check feature that check platform reqs existing, and exit immediately if not, with message like
```
Composer detected issues in your platform:

Your Composer dependencies require the following PHP extensions to be installed: oci8
```
if you just run `./artisan` for example...

> The new platform-check feature means that Composer checks the runtime PHP version and available extensions to ensure they match the project dependencies. If a mismatch is found, the autoloader exits with error details to make sure problems are not overlooked. To avoid issues when deploying to production it is recommended to run composer check-platform-reqs --no-dev with the production PHP process as part of your build or deployment process.

**Comment by zorn-v** [comment]
For composer 2 workaround you can use
```
    "provide": {
        "ext-oci8": "2.0"
    }
```
in composer.json
