### ISSUE TITLE
Relationship eager loading issue in v6

### ISSUE THREAD

**Issue by mrminthu** [yajra/laravel-oci8#549]
Hi Yajra, 

My eloquent and relationship were working fine at v5.8. 
After I upgrade to Laravel v6 and oci8 v6, I get below wired error message. 

I have more than 1k records in both tables. That why I also tried with chunk method but unfortunately the same error message come out.

Please kindly suggest me.

Error Code    : 1722
Error Message : ORA-01722: invalid number
Position      : 41
Statement     : select * from "WEB_PROJECT" where "WEB_PROJECT_PIC"."PROJ_ID" in (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) 

My eloquent models are as below
---------------------------------

class Project extends Eloquent
{
   protected $table = 'WEB_PROJECT';

    public $timestamps = false;

    protected $primaryKey = 'proj_id';

    public $incrementing = false;

    protected $casts = [
        'date' => 'datetime:Y-m-d',
    ];

    public function projectPic()
    {
        return $this->hasMany(ProjectPIC::class, 'proj_id', 'proj_id');
    }
}

class ProjectPIC extends Eloquent
{
   protected $table = 'WEB_PROJECT_PIC';

   public $timestamps = false;

    protected $primaryKey = false;

    public $incrementing = false;

    public function project()
    {
       return $this->belongsTo(Project::class, 'proj_id', 'proj_id');
    }
}

**Comment by yajra** [comment]
Is the key `proj_id` numeric or string? If string, I think you need to set the `keyType` to string on your model.

```php
protected $keyType = 'string';
```

**Comment by mrminthu** [comment]
Thanks you so much. protected $keyType = 'string' solved my issue.
