### ISSUE TITLE
Can't reach https://yajrabox.com/docs/laravel-oci8

### ISSUE THREAD

**Issue by joseojedaf** [yajra/laravel-oci8#553]
Can't reach https://yajrabox.com/docs/laravel-oci8

**Comment by joseojedaf** [comment]
Is it temporarly down or have the docs moved to a different url?

**Comment by ultrablue** [comment]
Sometimes it takes Arjay awhile to put the smoke back in the motherboard or whatever it is he does to make it go again.

**Comment by yajra** [comment]
Sorry, the site has been down for a month or so now. Please use https://github.com/yajra/laravel-oci8-docs atm. Will try to bring it up on my first pay day for 2020. Thanks!

**Comment by yajra** [comment]
New server is up and running now. Thanks!
