### ISSUE TITLE
Can you help me, How to create a cursor from an array and pass it a cursor as an input parameter to a store procedure

### ISSUE THREAD

**Issue by joseojedaf** [yajra/laravel-oci8#554]
What is required is this arrangement $cursorEntrada to convert it into a valid cursor to pass it to an oracle store procedure as an input parameter

$cursorEntrada = [
    'MON_CONSULTAR' => '1',
    'COD_PAIS_RECIBIR' => '2',
    'COD_MONEDA_RECIBIR' => '3',
    'NUM_REFERENCIA' => '4',
    'DIR_BENEFICIARIO'  => '5',
    'CIUDAD_BENEFICIARIO'  => '6',
    'COD_POSTAL' => '7',
    'TIPO_ID_BENEFICIARIO' => '8',
    'NUM_ID_BENEFICIARIO' => '9',
    'COD_PAIS_ID_BENEFICIARIO' => '10',
    'FEC_NACIMIENTO' => '11',
    'OCUPACION_BENEFICIARIO' => '12',
    'COD_PAIS_NACIMIENTO_BEN' => '13',
    'NUM_TELEFONO'  => '14' 
];

- Operating System
- PHP Version 7.2

**Comment by yajra** [comment]
I think this recent PR is what you need. See https://github.com/yajra/pdo-via-oci8/pull/74.
