### ISSUE TITLE
Error Code : 942 Table or View not exist - Because of the auto-uppercase

### ISSUE THREAD

**Issue by alexaf2000** [yajra/laravel-oci8#557]
### Summary of problem or feature request

Hi, I'm having some troubles when I'm trying to get access to a table in a Oracle SQL.

I get the typical error Error:

Code : 942 Error Message : ORA-00942: Table or view not exist Position : 14 Statement : select * from "USUARI" Bindings : [] (SQL: select * from "USUARI")

The executed code is the next:
_$test = DB::connection('oracle')->table("Usuari")->get();_

And if I execute the query directly by using Oracle SQL Developer I'm getting the same problem, to get a correct result I must execute the query at this way:

'select * from "Usuari"'

If we compare the query executed by Laravel:

select * from "USUARI"

We can see how the problem is simple, the uppercases.

There is some way to solve this issue?

### Code snippet of problem

```php
$test = DB::connection('oracle')->table("Usuari")->get();
dd($test);
```

### System details

- Windows 10 - XAMPP
- PHP 7.2
- Laravel 5.8
- Laravel-OCI8 5.8

**Comment by yajra** [comment]
Try using raw expression?

```php
$test = DB::connection('oracle')->table(DB::raw("Usuari"))->get();
// or
$test = DB::connection('oracle')->table(DB::raw('"Usuari"'))->get();
```

**Comment by alexaf2000** [comment]
> Try using raw expression?
> 
> ```
> $test = DB::connection('oracle')->table(DB::raw("Usuari"))->get();
> // or
> $test = DB::connection('oracle')->table(DB::raw('"Usuari"'))->get();
> ```

**Well! The second one was the solution! Thank you!**

_But I think that is just a temporal solution and a bit lazy on the code. Maybe it's better begin thinking to add an option._

For a better improvement from this:
`
$Agent = DB::connection('oracle')->table(DB::raw('"Agents"'))->where(DB::raw('"Id"'), '=', $idUsuari)->first();
`

To this:
`
DB::connection('oracle')->table('Agents')->where('Id', '=', $idUsuari)->first();
`
