### ISSUE TITLE
[HELP] Config for using oracle wallet

### ISSUE THREAD

**Issue by ac1982** [yajra/laravel-oci8#568]
### Summary of problem or feature request

Would you please give an example for how to config for using oracle wallet?
Yes, your package works fine with username and password, but the latest oracle just send a wallet which have a digital certificate without username.

### System details

- Operating System : CENTOS 7.x
- PHP Version : ~7.4
- Laravel Version: ~7.0
- Laravel-OCI8 Version: ~7.0

**Comment by hitrov** [comment]
Here's what works for me.

1. First please make sure that you have installed the oci8 extension by this tutorial https://docs.oracle.com/en/cloud/paas/atp-cloud/atpdg/php-application.html#GUID-8DFB6ED5-D3C2-4C78-BE2F-EE89373D03F4 (don't forget about `TNS_ADMIN` env var)

2. Go to SQL Developer Web (from Tools tab of Autonomous DB in Oracle Cloud) and create simple example table with a few records. 

3. Make sure that you're able to fetch records from it https://www.php.net/manual/en/function.oci-pconnect.php just execute plain PHP script 

4. Here's what I changed in `.env` file
```
#DB_CONNECTION=mysql
#DB_HOST=127.0.0.1
#DB_PORT=3306
#DB_DATABASE=laravel
#DB_USERNAME=root
#DB_PASSWORD=

DB_CONNECTION=oracle
DB_PORT=1522
# explore tnsnames.ora file in Wallet directory
DB_TNS=db20200413xxxx_high
DB_USERNAME=ADMIN
DB_PASSWORD=***
```

5. Here's what I added to example controller `DB::connection()->getPdo();`
