### ISSUE TITLE
query building error, need quotes around table field's name

### ISSUE THREAD

**Issue by Amin-z** [yajra/laravel-oci8#57]
Hello, I am using this package with Laravel 5 and Oracle 11.

The thing is, when I use the ORM, OracleElequent, and try to insert, I get Invalid Identifier around the field name itself, example:

$user = new User();
$user->name = 'Amin';
$user->save();

The query produced, and sent to Oracle is:
"Insert into user(name) values('Amin');
And Oracle returns an error, invalid identifier NAME, meaning it wants 'name' instead of name.

Writing Raw queries works fine as long as I add the quotations myself, but Query Builder isn't easy to modify.

Can you please help ?

**Comment by Amin-z** [comment]
Actually I just tried it with Laravel 4, used "laravel-admin-template-master", connected to same Oracle server and got same error. I'm starting to think something is wrong on my side, PHP configurations or Oracle settings?
I'm using xampp v3.2.1, PHP 5.5 x86 ts, Windows 7 x64. 

Could use some help.

**Comment by yajra** [comment]
I am working on a Laravel 5 starter template and having no issue like this. So I assume that the error must be something on your configurations. Can you please attach here the error stack trace so we can further check.

**Comment by Amin-z** [comment]
Should I take a screen shot of this ?

Error Code : 904 Error Message : ORA-00904: "EMAIL": invalid identifier Position : 28 Statement : insert into wts_user (name, email) values (:autoparam0, :autoparam1) returning id into :autoparam2 Bindings : []


22. yajra\Pdo\Oci8\Exceptions\Oci8Exception
…\vendor\yajra\laravel-pdo-via-oci8\src\yajra\Pdo\Oci8\Statement.php153
21. yajra\Pdo\Oci8\Statement execute
…\vendor\yajra\laravel-oci8\src\yajra\Oci8\Query\Processors\OracleProcessor.php54
20. yajra\Oci8\Query\Processors\OracleProcessor processInsertGetId
…\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php1910
19. Illuminate\Database\Query\Builder insertGetId
<#unknown>0
18. call_user_func_array
…\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php972
17. Illuminate\Database\Eloquent\Builder __call
…\vendor\yajra\laravel-oci8\src\yajra\Oci8\Eloquent\OracleEloquent.php213
16. Illuminate\Database\Eloquent\Builder insertGetId
…\vendor\yajra\laravel-oci8\src\yajra\Oci8\Eloquent\OracleEloquent.php213
15. yajra\Oci8\Eloquent\OracleEloquent insertAndSetId
…\vendor\yajra\laravel-oci8\src\yajra\Oci8\Eloquent\OracleEloquent.php167
14. yajra\Oci8\Eloquent\OracleEloquent performInsert
…\bootstrap\compiled.php6856
13. Illuminate\Database\Eloquent\Model save
…\app\routes.php135
12. {closure}
<#unknown>0
11. call_user_func_array
…\bootstrap\compiled.php5394
10. Illuminate\Routing\Route run
…\bootstrap\compiled.php5061
9. Illuminate\Routing\Router dispatchToRoute
…\bootstrap\compiled.php5049
8. Illuminate\Routing\Router dispatch
…\bootstrap\compiled.php715
7. Illuminate\Foundation\Application dispatch
…\bootstrap\compiled.php696
6. Illuminate\Foundation\Application handle
…\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php34
5. Barryvdh\Debugbar\Middleware\Stack handle
…\bootstrap\compiled.php7821
4. Illuminate\Session\Middleware handle
…\bootstrap\compiled.php8428
3. Illuminate\Cookie\Queue handle
…\bootstrap\compiled.php8375
2. Illuminate\Cookie\Guard handle
…\bootstrap\compiled.php11038
1. Stack\StackedHttpKernel handle
…\bootstrap\compiled.php657
0. Illuminate\Foundation\Application run
…\public\index.php49

**Comment by Amin-z** [comment]
PHP Info

oci8
OCI8 Support 	enabled
OCI8 DTrace Support 	disabled
OCI8 Version 	2.0.8
Revision 	$Id: f04114d4d67cffea4cdc2ed3b7f0229c2caa5016 $
Oracle Run-time Client Library Version 	11.1.0.6.0
Oracle Compile-time Instant Client Version 	11.1

**Comment by yajra** [comment]
Does the table created via migration or it was already existing? I think the column names defined in your table DDL uses double quotes and thus the column name would be case sensitive. 

Check this thread: http://stackoverflow.com/questions/6027961/ora-00904-invalid-identifier

**Comment by Amin-z** [comment]
Tables already existed, but I just created another table with Navicat For Oracle, still same issue.

**Comment by Amin-z** [comment]
Even if I try to insert using Navicat, still requires the quotation around column names, any suggestions ? like contacting DB administrator, or playing with the code to add the quotes ?

**Comment by yajra** [comment]
Maybe you should contact your DBA and ask him why it is required to add quotes. I do not suggest adding quotes coz it will force you to always use raw query and Eloquent will not work as well.

**Comment by Amin-z** [comment]
Alright thanks mate :)

**Comment by yajra** [comment]
Your welcome. Please post here if you find the solution for future reference. Thanks!

**Comment by Amin-z** [comment]
Hi Yajra, finally figured out what was wrong, after my DBA took a look, it seemed that Oracles standard is to have column names in CAPS not small letter, i.e. NAME, EMAIL...etc. After changing tables fields all is working well, without the quotes around field name. Thanks a lot :dancers: 

Although, FYI, I tried CodeIgniter v2 (latest stable version), connected it to Oracles and it automatically encapsulates fields names with double quotations.

Anyways thanks again mate :)

**Comment by yajra** [comment]
Great! I didn't know that Oracle can set standard for columns to be all CAPS. Thanks for the heads up!
