### ISSUE TITLE
Oci8Exception (ORA-24408: could not generate unique server group name)

### ISSUE THREAD

**Issue by phyothiha** [yajra/laravel-oci8#574]
I have been struggling to connect my laravel app with oracle db for a week. First of all, I follow [this gist](https://gist.github.com/yajra/6a5de3086e062ab0ec258cb27e2cecd2) to make oci8 extension available on Mac. It works perfectly and install Laravel Oci8. After that, I make a dummy route to test db connection and Oci8Exception is thrown as well as in tinker. I check phpinfo and there is OCI8 support is enabled and loaded.

**Note: Everything is fine using with Laragon.**

web.php
```php
Route::get('/', function () {
    $db = \Illuminate\Support\Facades\DB::table('SOME.DB');

    dd($db);
});
```

.env

DB_CONNECTION=oracle
DB_HOST=**Private IP**
DB_PORT=1521
DB_DATABASE=xe
DB_SERVICE_NAME=foo
DB_USERNAME=user
DB_PASSWORD=pass

### System details

- Mac OS Catalina (10.15.4)
- PHP Version (7.3.14)
- Laravel Version (7.13.0)
- Laravel-OCI8 Version (^7.0)

**Comment by yajra** [comment]
Try changing your server/PC's hostname.

**Comment by phyothiha** [comment]
No Luck Sir

**Comment by phyothiha** [comment]
> 
> 
> Try changing your server/PC's hostname.

**Comment by phyothiha** [comment]
No Luck Sir

**Comment by yajra** [comment]
That's the fix I know that worked for me for the same issue. This is the command for mac:

```
sudo hostname yajra-mbpro.local
```

Also, you might need to restart for it to work.

**Comment by phyothiha** [comment]
![Screen Shot 2020-06-02 at 3 16 31 PM](https://user-images.githubusercontent.com/12383757/83499927-1df02e80-a4e4-11ea-9a34-3da32328ebba.png)

Still an error occur after restarting system and apachectl service.

**Comment by phyothiha** [comment]
@yajra Is there anyway to work around?

**Comment by phyothiha** [comment]
It's ok for now. I've just carefully follow your [gist](https://gist.github.com/yajra/6a5de3086e062ab0ec258cb27e2cecd2) again. Thanks for your effort @yajra Cheers!
