### ISSUE TITLE
Undefined index: hostname 

### ISSUE THREAD

**Issue by Coco-John** [yajra/laravel-oci8#578]
### Summary of problem or feature request

Hello,
I noticed a malfunction from the file "Oci8ServiceProvider.php", because the following error message appears randomly:
"Undefined index: **hostname**".

I added logs to determine where the problem was coming from, and it turns out that it comes from the register () method, at the following line:
```php
Connection :: resolverFor ('oracle', function ($connection, $database, $prefix, $config) {
```

Strangely, the ```$config``` is not updated with the **_./config/oracle.php_** file (which does the ```$this->mergeConfigFrom()``` a few lines above)
To fix that, I inserted the contents of the **_./config/oracle.php_** file into **_./config/database.php_** before deleting it.

Have you already encountered this bug?

Thanks 

### System details

- Operating System : CentOS release 6.9
- PHP Version : 7.3.15 / 7.4.3
- Laravel Version : >=6.1.0 && 6.18.23<=
- Laravel-OCI8 Version : ~6.0

**Comment by fabiogaspari** [comment]
try running config: cache. it worked for me

**Comment by appu-sm** [comment]
I too faced the same issue..
