### ISSUE TITLE
creating inactive session with oracle database, which is overloading the server

### ISSUE THREAD

**Issue by mukhtar9** [yajra/laravel-oci8#580]
### Summary of problem or feature request

my database is on a different server from apache server
with each request database, an active session is opened
but this active session is not closed and remains as inactive session in DB server
for example, my request count is 100 then an active session with the database is near to 100 and inactive sessions is 1000, and it grows with time span and overloads the database server

### System details

- Operating System
Ubantu 18
- PHP Version
7.2
- Laravel Version
7
- Laravel-OCI8 Version
oci8_12c instant client

**Comment by yajra** [comment]
Not sure but maybe try persistent configuration might help? 

```php
'options'   => [
        PDO::ATTR_PERSISTENT => true,
],
```
