### ISSUE TITLE
UUID Datatype | oci_bind_by_name(): Invalid variable used for bind

### ISSUE THREAD

**Issue by tsndp** [yajra/laravel-oci8#581]
### Summary of problem or feature request

Laravel UUID string is throwing error while inserting (seeder)

### Code snippet of problem
'uuid' => Str::uuid(),

Error:
oci_bind_by_name(): Invalid variable used for bind (SQL: insert into

Edit:
this is working 
'uuid' => "".Str::uuid(),
### System details

Windows 10- Operating System
7.4 - PHP Version
7.25 - Laravel Version
2.2 - Laravel-OCI8 Version

**Comment by yajra** [comment]
I think `Str::uuid()` is an object thus you need to cast it to string or use `Str::uuid()->toString()`.

**Comment by tsndp** [comment]
Thank you @yajra for the reply and awesome package!
