### ISSUE TITLE
ORA-12505: TNS:listener does not currently know of SID given in connect descriptor

### ISSUE THREAD

**Issue by dome21117** [yajra/laravel-oci8#588]
I have problem
laravel 8 and oracle 12C and php 7.4.8
ORA-12505: TNS:listener does not currently know of SID given in connect descriptor
service_name connect to laravel php
code
.env
DB_CONNECTION=oracle
DB_HOST=IP
DB_PORT=1521
DB_DATABASE=Service_name
DB_USERNAME=username
DB_PASSWORD=password

config/database .php

'oracle' => [
'driver' => 'oracle',
'host' => 'ip',
'port' => '1521',
'database' => ' ',
'service_name' => 'Service_name',
'username' => 'username',
'password' => 'password',
'charset' => '',
'prefix' => '',
    ],
],
help me please!!!!

**Comment by yajra** [comment]
Try removing `'service_name' => 'Service_name',`. 

Also, try connecting using SQL Developer first then copy the configuration used on it if it works.

**Comment by dome21117** [comment]
l have try remove 'service_name' => 'Service_name' 
config/database .php
  'oracle' => [
    'driver' => 'oracle',
    'host' => '172.18.0.18',
    'port' => '1521',
    'database' => 'HTDB01',
    'username' => 'QASYS',
    'password' => 'QASYS',
    'charset' => '',
    'prefix' => '',
        ],
.env The same

**Comment by dome21117** [comment]
I try connecting sql  Developer  is success

**Comment by dome21117** [comment]
Thank you is success
