### ISSUE TITLE
NLS_COMP = LINGUISTIC is a bad feature

### ISSUE THREAD

**Issue by leowangxp** [yajra/laravel-oci8#602]
### Summary of problem or feature request

when upgrate to 8.1，query is very slow.
NLS_COMP = LINGUISTIC 
In Oracle Doucments
To improve the performance, you can also define a linguistic index on the column for which you want linguistic comparisons.
But we can't create index for all fileds, so NLS_COMP = LINGUISTIC  is a bad Feature.

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-OCI8 Version

**Comment by yajra** [comment]
Yes, planning to revert that feature once I resolved the database presence verifier issue of the package as discussed on https://github.com/yajra/laravel-oci8/issues/601.

For now, please manually override the NLS_COMP on your AppServiceProvider as needed. Also, any recommendation for a better NLS_COMP settings?

**Comment by yajra** [comment]
Fixed on v8.1.2
