### ISSUE TITLE
Why not to include this project into Laravel Framework?

### ISSUE THREAD

**Issue by rgiaviti** [yajra/laravel-oci8#62]
Hi, I am wondering why not to include this excellent project into laravel core? Actually Laravel supports MySQL, Postgres, SQLite, and SQL Server. Oracle will be a great addition to laravel. Is it hard to include this project at laravel core?

I am using laravel-oci8 for 3 months with great success. It is stable and have a good performance. I don't know why not to include into laravel core.

Thanks!

**Comment by yajra** [comment]
Maybe it's not yet the right time. I think we need more proof/production projects for this to make it to the core of Laravel as I remember being mentioned by Taylor Otwell way back on some issues.

**Comment by ChaosPower** [comment]
+1

**Comment by sasanet** [comment]
Hello yajra,  i had already suggest a fix some times ago. I want to suggest another fix on Oci8Connection class.
The constructor of this class have a type PDO for the first argument, but in laravel framework this param may be of  tyoe PDO or Closure. It's possible to remove type hint?
This happen when i modify 'Illuminate\Database\Connectors\ConnectionFactory' to support oracle driver, you will see or try in 'createConnection' method.

Thanks
