### ISSUE TITLE
Getter for private attribute oci connection resource

### ISSUE THREAD

**Issue by ognjenVlad** [yajra/laravel-oci8#621]
### Create getter for oci connection resource

I want to use oci_set_call_timeout to set maximum query time. I cant make it work because there is no getter for oci connection resource which is a first parameter for oci_set_call_timeout. https://www.php.net/manual/en/function.oci-set-call-timout.php

### Code snippet of problem

```php
$db = \DB::connection('oracle');
oci_set_call_timeout($db->getPdo()->dbh, 2000);
```

### System details

- Operating System: centos
- PHP Version: 7.2.7
- Laravel Version: 5.8
- Laravel-OCI8 Version: 5.8.2

**Comment by yajra** [comment]
Agreed, maybe we can also add an api for this too? Something like:

```php
$db->getPdo()->setCallTimeout(2000);
```

Would you like to send a PR? The file to be updated is https://github.com/yajra/pdo-via-oci8/blob/master/src/Pdo/Oci8.php.

**Comment by ognjenVlad** [comment]
Thanks for quick response. 
It would be great to add an api for this, I will create PR hopefully today.
