### ISSUE TITLE
Eager loading with rowid hits the "ROWID output is not yet supported." exception

### ISSUE THREAD

**Issue by bobbypiper** [yajra/laravel-oci8#622]
### Summary of problem or feature request

using eager loading for a related model I hit the exception for `ROWID output is not yet supported.` - there is also no way to disable the `returnLobs` property.

Steps to reproduce: setup a relationship with a ROWID field and try eager loading it - the exception is thrown from `src/Pdo/Oci8/Statement.php:362`

### Code snippet of problem

```sql
select * from "TABLE" where "PART_CATALOG"."PART_NO" in ('190151', '191312', '191313'))
```
the above query is generated by using eloquent `with('part')`. 

Setting property `returnLobs = false` in `Pdo/Oci8/Statement.php` would resolve but I cannot see a way to set it currently

### System details

- Custom Docker image
- PHP Version: 7.4.13
- Laravel Version: 8.18.1
- Laravel-OCI8 Version: 8.0

**Comment by ZeoKnight** [comment]
For anyone else having this issue, as a stop gap I created a global scope to exclude ROWID column types from queries (where columns were not specified)
