### ISSUE TITLE
When is it compatible with php8?

### ISSUE THREAD

**Issue by kw-jeff** [yajra/laravel-oci8#624]
Hello.

I have a question...

When is it compatible with php8?

**Comment by yajra** [comment]
Still a WIP because I can't update to PHP8 yet. Maybe you can review PR https://github.com/yajra/laravel-oci8/pull/619 and let me know if it works.

**Comment by kw-jeff** [comment]
Oh! Good. I will be try it.

**Comment by OmarHossamEldin** [comment]
@yajra  i need to know as well is it okay with php 8 or not?
notice that im using windows not linux for the local network here in my work

**Comment by yajra** [comment]
@OmarHossamEldin there is a pending PR to support PHP8 but I need some user reviews / feedbacks before merging it. It would be helpful if you can test it. Thanks!

**Comment by OmarHossamEldin** [comment]
okay im trying rn

**Comment by OmarHossamEldin** [comment]
but it shows me this
![Capture](https://user-images.githubusercontent.com/62789045/105332880-c4a54e80-5bdd-11eb-8ada-0d29059aa1cc.PNG)

**Comment by OmarHossamEldin** [comment]
@yajra  just till me how to test it?

**Comment by yajra** [comment]
I think it should be something like:

```php
composer require yajra/laravel-oci8:dev-php8
```

**Comment by OmarHossamEldin** [comment]
ty gonna test it

**Comment by OmarHossamEldin** [comment]
it's working ty you saved the day @yajra  <3 <3
