### ISSUE TITLE
DB::rollback works?

### ISSUE THREAD

**Issue by laurenceHR** [yajra/laravel-oci8#63]
In previous version works normally, now when I updated the last version, I see un error when try DB::rollback();

**Comment by yajra** [comment]
Hi, can you please provide the error message returned or some snippets of your code? Will try to reproduce the error later. Thanks!

**Comment by yajra** [comment]
Just tried this out and it works well on my side.

```php
Route::get('rollback', function(){
	DB::beginTransaction();
	$user = \App\User::create([
		'name' => 'test',
		'email' => 'test@test.com',
		'password' => 'test@test.com',
		]);
	DB::rollBack();
	return \App\User::all();
});
```

**Comment by laurenceHR** [comment]
rollback() changes to rollBack() ??? why so semantics changes? u.u

**Comment by yajra** [comment]
No changes on `DB::rollBack();` it was like that as far as i know.
