### ISSUE TITLE
Question about pagination in Oracle

### ISSUE THREAD

**Issue by yaroslavmo** [yajra/laravel-oci8#632]
The way pagination is handled is very slow. 

For example, simple query:

```sql
SELECT "STATUS", "USER_NAME", "USER_TYPE" FROM "SCHEMA"."TABLE"
```

Results in:

```sql
SELECT t2.* FROM (SELECT ROWNUM AS "rn", t1.* FROM (SELECT "STATUS", "USER_NAME", "USER_TYPE" FROM "SCHEMA"."TABLE") t1) t2 WHERE t2."rn" BETWEEN 1 AND 100
```

Could you explain why [compileTableExpression](https://github.com/yajra/laravel-oci8/blob/43343e746334e67e5a468fc6fbe7a3067fa7f2a0/src/Oci8/Query/Grammars/OracleGrammar.php#L158) adds a subquery?

Can it just be?
```sql
WHERE ROWNUM <= 100
```

Thank you for the package.

### System details

- Operating System - Linux
- PHP Version - 7.3
- Laravel Version - 6
- Laravel-OCI8 Version - 6.x

**Comment by yaroslavmo** [comment]
Referring to this [thread](https://stackoverflow.com/questions/45687355/how-to-correct-pagination-in-oracle/45688396?noredirect=1#comment78410115_45688396). Do you think that [compileTableExpression](https://github.com/yajra/laravel-oci8/blob/43343e746334e67e5a468fc6fbe7a3067fa7f2a0/src/Oci8/Query/Grammars/OracleGrammar.php#L158) can be upgraded to use [OFFSET and ROWS ONLY](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6)?

> The following statement returns the next 5 employees with the lowest employee_id values:
> 
```SQL
SELECT employee_id, last_name
  FROM employees
  ORDER BY employee_id
  OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;
```
> 
> EMPLOYEE_ID LAST_NAME
> ----------- -------------------------
>         105 Austin
>         106 Pataballa
>         107 Lorentz
>         108 Greenberg
>         109 Faviet

**Comment by yajra** [comment]
> Can it just be?
> WHERE ROWNUM <= 100

Pagination was already updated on the latest version to something similar like this. 


> SELECT employee_id, last_name
  FROM employees
  ORDER BY employee_id
  OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;

This will not work on lower oracle versions. Some of my projects still uses 10g.

**Comment by yaroslavmo** [comment]
I see thank you for clarifying
