### ISSUE TITLE
ORA-02391: Exceeded Simultaneous SESSIONS_PER_USER Limit

### ISSUE THREAD

**Issue by johnwswar** [yajra/laravel-oci8#639]
Currently using Oracle 19c as the RDBMS, and instead of using the Laravel's Users table, the application has been modified and now connects as an Oracle proxy user.

In Oracle, for each proxy users, the maximum connection is set to 8. So when I connect to the application multiple times, I get the following error:

ORA-02391: Exceeded Simultaneous SESSIONS_PER_USER Limit

How should I resolve this issue?  Seems like it's not keeping a persistent connection, but in my configuration file, I have it set persistent to true.

Also, I want to disconnect a certain user and connect as another user after login.  I tried DB::reconnect('oracle'), but when I in the v$session, I see both users.  

Thanks you.

- RHEL 7.X
- PHP Version:  7.3.26
- Laravel Version:  7
- Laravel-OCI8 Version:  7.01

**Comment by aortegae** [comment]
Have you got persistent connections?
