### ISSUE TITLE
DB::Connection('Oracle') doesnt work unless the default is set to Oracle 

### ISSUE THREAD

**Issue by XenitXTD** [yajra/laravel-oci8#64]
Hey Guys

I finally got oracle connection working however i have an issue and dont know if its strictly related to this package or something i am doing wrong

my connection is as follows

'oracle' => array(
            'driver' => 'oracle',
            'host' => env('DB_HOST_ORACLE', ''),
            'port' => '1521',
            'database' => env('DB_DATABASE_ORACLE', 'base'),
            'username' => env('DB_USERNAME_ORACLE', ''),
            'password' => env('DB_PASSWORD_ORACLE', ''),
            'charset' => '',
            'prefix' => '',
        ),

now I have several Oracle databases so i would setup several connections similar to the above giving it unique names.

Note my default database is set to mysql 

Problem i have is when i connect using DB::connection('oracle') it doesnt connect and if i change the default to the oracle connection it works fine with the above connection... 

I know the connection works, But I cant call it explicitly for some reason

as the minute i do it like so DB::connection('oracle') i get the following error

ErrorException in Connector.php line 47:
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

but if i change the default database to oracle then it works perfectly fine?

can some advise as it would be pointless if i cannot have multiple database connections

**Comment by yajra** [comment]
Works well on my side.

```php
Route::get('connection', function()
{
	return $users = DB::connection('db2')->table('users')->select('*')->get();
});
```

On the other hand, double check your configurations and environment. The error SQLSTATE[HY000] [2002] appears to be on MySQL and not on Oracle.

**Comment by XenitXTD** [comment]
Hi Yajra, Thanks for the Feed back

It took several attempts but its working had issues with the oracle installation on windows and it got worse before it got better...

Eventually after doing a clean setup with oracle on windows with all the files require and reconfiguring the project everything is working fine again

**Comment by yajra** [comment]
@XenitXTD good to know you were able to fix this issue. BTW, I have a [homestead-oracle](https://github.com/yajra/homestead-oracle) project that I use for development. This might save you some trouble in setting up your Oracle dev environment while enjoying the perks of Laravel Homestead. :beers:
