### ISSUE TITLE
Unable to use the new version of laravel-ide-helper 2.9 model doc generator that uses Doctrine/DBAL 3

### ISSUE THREAD

**Issue by jwhulette** [yajra/laravel-oci8#641]
### Summary of problem or feature request
Unable to use the new version (2.9) of  [https://github.com/barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) model doc generator that uses Doctrine/DBAL 3

2.8 Did not throw an error.

### Code snippet of problem
The following error occurs
<details>
<summary>
Exception: An exception occurred while executing a query: An exception occurred in the driver: ORA-24415: Missing or null username.
</summary>
Trace:
#0 /var/www/vendor/doctrine/dbal/src/Connection.php(1728): Doctrine\DBAL\Driver\API\OCI\ExceptionConverter->convert(Object(Doctrine\DBAL\Exception\DriverException), Object(Doctrine\DBAL\Query))
#1 /var/www/vendor/doctrine/dbal/src/Connection.php(1667): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Exception\DriverException), Object(Doctrine\DBAL\Query))
#2 /var/www/vendor/doctrine/dbal/src/Connection.php(813): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Exception\DriverException), 'SELECT   c.*,\n ...', Array, Array)
#3 /var/www/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(170): Doctrine\DBAL\Connection->fetchAllAssociative('SELECT   c.*,\n ...')
#4 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(432): Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns('dashboard_pages', 'vtrak')
#5 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(270): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromTable(Object(Domain\Dashboard\Models\Dashboard))
#6 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(159): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs(Array, Array)
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#13 /var/www/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 /var/www/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\LaravelIdeHelper\Console\ModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\
Component\Console\Output\ConsoleOutput))
#17 /var/www/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}
Exception: An exception occurred while executing a query: An exception occurred in the driver: ORA-24415: Missing or null username.
Could not analyze class Domain\Dashboard\Models\DashboardCard.
</details>

### System details

- Operating System 
Oracle Linux 7
- PHP Version 
PHP 7.4.14 (cli) (built: Jan  7 2021 21:11:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
- Laravel Version
"laravel/framework": "^8.0",
- Laravel-OCI8 Version
"yajra/laravel-oci8": "^8.0"

**Comment by MajuTo** [comment]
Hi,
same issue for me.

System details

    Operating System
    Manjaro up to date

    PHP Version
    PHP 8.0.3 (cli) (built: Mar  4 2021 05:33:14) ( NTS )
    Copyright (c) The PHP Group
    Zend Engine v4.0.3, Copyright (c) Zend Technologies

    Laravel Version
    "laravel/framework": 8.35.1
    Laravel-OCI8 Version
    "yajra/laravel-oci8": 8.3

Didn't try with 2.8

**Comment by yajra** [comment]
Can't upgrade to PHP8 yet and might not be able to check this soon. Anyone interested in submitting a PR for a fix? Thanks!

**Comment by jwhulette** [comment]
I'm looking into this and if I find the issue I'll submit a PR.

**Comment by jwhulette** [comment]
This is just an FYI.
I've update to the latest ide-helper and now I get a new error:

Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement(): Argument #1 ($stmt) must be of type Doctrine\DBAL\Driver\ResultStatement, Yajra\Pdo\Oci8\Statement given, called in /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Conn
ection.php on line 1313

I'm looking into it.

**Comment by blackfyre** [comment]
Got the same issue on php 7.4
DB version is 19c

**Comment by jwhulette** [comment]
It appears Doctrine 3.0 is completely different and no longer is based on the PDO architecture. Support for Doctrine 3 would be a break change I believe. I'm going to see if I can get it working.

**Comment by jwhulette** [comment]
So per the Doctrine 3 release notes, **The PDO API is not longer the standard for DBAL APIs.**

I have found that this works. Just not sure how to determine v2 vs v3.
`
    /**
     * Get the Doctrine DBAL database connection instance.
     *
     * @return \Doctrine\DBAL\Connection
     */
    public function getDoctrineConnection()
    {
        if (is_null($this->doctrineConnection)) {
            $driver = $this->getDoctrineDriver();

            $pdoConnect = [
                'pdo' => $this->getPdo(),
                'dbname' => $this->getDatabaseName(),
                'driver' => method_exists($driver, 'getName') ? $driver->getName() : null,
                'serverVersion' => $this->getConfig('server_version'),
            ];

            $ociConnect = [
                'user'         => $this->config['username'],
                'password'      => $this->config['password'],
                'host'          => $this->config['host'],
                'port'          => $this->config['port'],
                'dbname'        => $this->getDatabaseName(),
                'servicename'   => $this->config['servicename'] ?? '',  //  Optional name by which clients can connect to the database instance. Will be used as Oracle's SID connection parameter if given and defaults to Doctrine's dbname connection parameter value.
                'service'       => $this->config['service'] ?? false, // (boolean):  Whether to use Oracle's SERVICE_NAME connection parameter in favour of SID when connecting. The value for this will be read from Doctrine's servicename if given, dbname otherwise.
                'pooled'        => $this->config['pooled'] ?? false, // (boolean): Whether to enable database resident connection pooling.
                'charset'       => $this->config['charset'],
                'instancename'  => $this->config['instancename'] ?? '', // Optional parameter, complete whether to add the INSTANCE_NAME parameter in the connection. It is generally used to connect to an Oracle RAC server to select the name of a particular instance.
                'connectstring' => $this->config['tns'] ?? '', // When using this option, you will still need to provide the user and password parameters, but the other parameters will no longer be used. Note that when using this parameter, the getHost and getPort methods from Doctrine\DBAL\Connection will no longer function as expected.
                'persistent'    =>  $this->config['persistent'] ?? false // (boolean): Whether to establish a persistent connection.
            ];

            $this->doctrineConnection = new DoctrineConnection(array_filter($ociConnect), $driver);
        }

        return $this->doctrineConnection;
    }
`

**Comment by yajra** [comment]
Created a PR for a possible fix but can only test it on DBAL 2.x and seems to work fine for me. Can anyone please review on PHP8? Thanks!

**Comment by yajra** [comment]
Tested and released the PR, was able to generate model helper too but have to use my own fork of the project for this to work. IDE Helper is a good package and will also use it too now :). 

I also tried to submit a PR but it was not accepted so I have to use my own Fork of IDE Helper. See https://github.com/yajra/laravel-ide-helper if it helps.

**Comment by jwhulette** [comment]
Thank you for fixing.

**Comment by MajuTo** [comment]
I tested on PHP8, seems to work.
Will try your package later, lowercase attribute should be better
