### ISSUE TITLE
Eloquent Relationships | Big Queries | Too much tokens | ORA-00936

### ISSUE THREAD

**Issue by tom-shelby** [yajra/laravel-oci8#644]
### Summary of problem or feature request

Hi, i'm messing around while doing some features inside a big project. These features involves Eloquent relations and we're using an Oracle DB.

The problem is simple :
In big queries, it seems that the query builder is doing messy things.

__Example:__
I've got three tables, DECLARATIONS, WITNESSES, and DECLARATIONS_WITNESSES (aka pivot) 

On the one hand, the `declarations` relation on the WITNESSES Model works. There's not so much declarations inside DB.
On the other hand, the `witnesses` relation on the DECLARATION Model is generating an `ORA-00936: missing expression`

Looking at the generated SQL, wev'e got this structure (i've just obfuscated IDs):
SQL:
select "ABS"."WITNESSES".*, "ABS"."DECLARATIONS_WITNESSES"."ID_DECLARATION" as "PIVOT_ID_DECLARATION", "ABS"."DECLARATIONS_WITNESSES"."ID_WITNESS" as "PIVOT_ID_WITNESS" from "ABS"."WITNESSES" inner join "ABS"."DECLARATIONS_WITNESSES" on "ABS"."WITNESSES"."ID_WITNESS" = "ABS"."DECLARATIONS_WITNESSES"."ID_WITNESS" where ("ABS"."DECLARATIONS_WITNESSES"."ID_DECLARATION" in (_a bunch of IDs_) or "ABS"."DECLARATIONS_WITNESSES"."ID_DECLARATION" in (_a bunch of IDs_) or or "ABS"."DECLARATIONS_WITNESSES"."ID_DECLARATION" in (_a bunch of IDs_) or or or "ABS"."DECLARATIONS_TIERS"."ID_DECLARATION" in (_a bunch of IDs...._)))

As you can see OR appears 6 times, and there's a `)` too many

### Code snippet of problem

Inside the DECLARATION Model

```php
public function witnesses()
{
    return $this->belongsToMany(Witness::class, "ABS.DECLARATIONS_WITNESSES", "id_declaration", "id_witness");
}
```

### System details

- Operating System
Windows 10
- PHP Version
7.3.12
- Laravel
^8.12
- Laravel-OCI8 Version
8

As i'm not a native english speaker, please be patient and tolerant 👍

**Comment by yajra** [comment]
Oracle only allows up to 1,000 values afaik when using `IN` query. As a work-around on this limitation, values were chunked by 1k and chained with OR|AND statements.

**Comment by tom-shelby** [comment]
> Oracle only allows up to 1,000 values afaik when using `IN` query. As a work-around on this limitation, values were chunked by 1k and chained with OR|AND statements.

Thanks for your answer, but it didn't help me to solve the problem 😅
Am I supposed to modify the relation with a chunking results workaround? 

Or may you be able to modify the workaround on this limitation to not repeat OR n+1 times on the n chunk and remove this parenthesis ? I don't know if your code is responsible of this

**Comment by yajra** [comment]
> Am I supposed to modify the relation with a chunking results workaround?

I guess Yes, there might an issue with the way the package chunk the queries (not sure). I only tested around 1k++ on real projects using `whereIn` query. This is where the chunking occurs: https://github.com/yajra/laravel-oci8/blob/8.x/src/Oci8/Query/OracleBuilder.php#L122

Maybe you can submit a PR for a possible fix if ever the package is the issue. Thanks!

**Comment by tom-shelby** [comment]
Hello,
As a user of this package, I would like to thank you for your contributions which saved me a lot of time just like Laravel does. Even though this bug makes me reconsider the future as i'm always working with large datasets 

I am not yet very comfortable with IT (1st year as a webdev in engineering school.), So finding the solution may take me a while, especially since I still have a bit of trouble understand the inner workings of Laravel. And obviously Eloquent is much more abstract than I thought! However I have looked for solutions to the problem mentioned above. Still as a user, I will be delighted to see your package integrate the functionality of Eloquent even on large requests and if you don't have the time, maybe we can cooperate to fix this if you have some time ?

So I found problem #73 ( also mentionned in #479 )and a user seems to have found a solution by replacing `whereIn` by `chunk` within the OracleGrammar class. Would that make it possible to build the query by correctly chaining the splits?

**Comment by tom-shelby** [comment]
I've found something

Inside resolveClause method of OracleGrammar class, i've tweaked something:

````php
private function resolveClause($column, $values, $type)
    {
        $chunks      = array_chunk($values, 1000);
        $whereClause = '';
        $i           = 0;
        $type        = $this->wrap($column) . ' '.$type.' ';

        // dd($column, $values, $type);
        $expression = $type;
        foreach ($chunks as $ch) {
            if ($i > 0) {
                // dd($chunks);
                $expression = ' or ' . $type . ' ';
            }
            $whereClause .= $expression . '('.implode(', ', $ch).')';
            $i++;
        }

        dd($whereClause);

        return '(' . $whereClause . ')';
    }
 ```
 This removes the unwanted 'OR' and may fix the problem. I'm doing further investigations to check if it works correctly
