### ISSUE TITLE
can i use lowercase for table's and column's name  in select statement?

### ISSUE THREAD

**Issue by achnnad** [yajra/laravel-oci8#645]
Illuminate\Database\QueryException
Error Code : 904 Error Message : ORA-00904: "ID_EVENT": invalid identifier Position : 32 Statement : select * from "DATA_BOOK" where "ID_EVENT" = :p0 Bindings : [2021043008321] (SQL: select * from "DATA_BOOK" where "ID_EVENT" = 2021043008321)

**Comment by yajra** [comment]
By lower, you mean "id_event" column? Use `DB::raw('"id_event"')` or `whereRaw('"id_event" = ?', $value)`.
