### ISSUE TITLE
ORA-12537: TNS:connection closed

### ISSUE THREAD

**Issue by sandysaini** [yajra/laravel-oci8#656]
Yajra\Pdo\Oci8\Exceptions\Oci8Exception
ORA-12537: TNS:connection closed

https://www.screencast.com/t/mMoMfA0ZA
![2021-05-10_16-28-55](https://user-images.githubusercontent.com/42863399/117649188-d884b880-b1ac-11eb-9ff4-b5f30e7a6e30.png)

**Comment by yajra** [comment]
As the error suggest, please make sure that your DB instance is running. Try connecting with SQL Developer too to verify it works manually.
