### ISSUE TITLE
Can I specify that some fields in the table be capitalized

### ISSUE THREAD

**Issue by gezilixu** [yajra/laravel-oci8#665]
When querying laravel, OCI will convert all fields to lowercase , The fields in my database table should be capitalized. Can I specify the corresponding fields to be capitalized

**Comment by yajra** [comment]
Do you mean like `$model->FIELD` uppercase attribute? I think this is possible by setting the PDO attribute case if I recall correctly. But the problem with this config is that it breaks the compatibility with Laravel's ORM and produces unexpected outputs.

**Comment by gezilixu** [comment]
Yes, it has been solved with other solutions, thanks
