### ISSUE TITLE
I get error when run migrations

### ISSUE THREAD

**Issue by marvelousvts** [yajra/laravel-oci8#669]
### Summary of problem or feature request

When I run `php artisan migrate` I get the following error:

`Migrating: 2017_01_15_000000_make_table_name_nullable_in_permissions_table

   ErrorException 

  Undefined index: user

  at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:81
     77▕     public function getDatabase(Connection $conn)
     78▕     {
     79▕         $params = $conn->getParams();
     80▕ 
  ➜  81▕         return $params['user'];
     82▕     }
     83▕ 
     84▕     /**
     85▕      * {@inheritdoc}

      +36 vendor frames 
  37  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()`

Any ideas how to resolve this?

### Code snippet of problem
`php artisan migrate`

### System details

- Operating System: Ubuntu
- PHP Version: 7.4.3
- Laravel Version: Laravel Framework 8.58.0
- Laravel-OCI8 Version: v8.4.1

**Comment by yajra** [comment]
Can you please provide your migration file? I think column modifications requires doctrine/dbal.

**Comment by marvelousvts** [comment]
Well, I removed voyager and it worked... I have no clue what caused this issue.

**Comment by yajra** [comment]
I'm not using voyager so may I not be able to help further atm. Thanks!
