### ISSUE TITLE
Support for Lumen

### ISSUE THREAD

**Issue by mattclements** [yajra/laravel-oci8#67]
Hey there,
Any plans to support Lumen?

`Oci8ServiceProvider.php` throws errors linked to `use Config;`

**Comment by caleywoods** [comment]
Looking to get this working as well.

**Comment by yajra** [comment]
Should be compatible with Lumen now. Kindly checkout and test. Thanks for reporting.

**Comment by mattclements** [comment]
Thanks @yajra thats awesome! All working :+1:

**Comment by mouradsm** [comment]
Hey there,
I'm very new in Laravel and Lumen. how can I use eloquent with oracle support in lumen with this package?

**Comment by caleywoods** [comment]
@mouradsm Follow the instructions on the main page to pull this into your project via composer then make sure you create a ```database.php``` file in the ```config/``` directory and have an entry in the connections array for your database.

I've created an example gist [here](https://gist.github.com/caleywoods/f7c3d3f66accb9dd021d)
