### ISSUE TITLE
Oracle autonomous database 19c

### ISSUE THREAD

**Issue by cadentic** [yajra/laravel-oci8#673]
### System details
oracle autonomous linux 7.9
oracle instant client 21.x
oracle autonomous database 19c 

- Operating System
- PHP Version 7.4
- Laravel Version 8.61
- Laravel-OCI8 Version 8.5

there is no error during php artisan migration but no pages are opening from the urls 
error: 
Yajra\Pdo\Oci8::connect
vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php:473 

how to fix it? what did I miss?

**Comment by yajra** [comment]
Please provide the error log.
