### ISSUE TITLE
Comparing value in where clause has data type CLOB

### ISSUE THREAD

**Issue by kailasb10** [yajra/laravel-oci8#677]
I've **"results_json"** column with a data type as longtext area in laravel migration & it will convert column the datatype to CLOB in Oracle.
When I tried to compare the value in the "results_json" column it's not working.
getting this error: **Error: ORA-00932: inconsistent datatypes: expected - got CLOB**

This the query I've executing:
`MeasurementData::where('m_id', $mId])->where('results_json', '!=', '[]')->whereNotNull('results_json')->orderBy('created_at', 'DESC')->take(1)->first();`

**Expected Result:**
     The query gives the last record where "results_json" column value should not equal to this string '[]' OR not null

**Actual Result:**
     **Error: ORA-00932: inconsistent datatypes: expected - got CLOB**

- Operating System: **Centos 7**
- PHP Version: **7.3.27**
- Laravel Version: **8.11.2**
- Laravel-OCI8 Version: **8.3.0**

**For Temporary Solution, I've used:** 
- **"result_json" != '[]'** => dbms_lob.compare(results_json, to_clob('[]')) != 0
- **"result_json" not null** => dbms_lob.getlength(results_json) != 0

**Comment by yajra** [comment]
I think your temporary solution is the correct solution. Oracle behavior is definitely unique compare to other RDBMS and thus some special syntax are needed when working with it. I often use raw sql for special cases, the downside is it will not work if you have plans to switch DB.
