### ISSUE TITLE
String values returned for type 'number' field

### ISSUE THREAD

**Issue by lalit-insnapsys** [yajra/laravel-oci8#682]
### Summary of problem or feature request
Hi @yajra ,
I have an '**action_id**' field in table which is of type '**number**'. But whenever I retreive the model of that table, I get type string value for '**action_id**'. E.g., I should get 5, but I'm getting "5".

### Code snippet of problem

**What is expected:**

![image](https://user-images.githubusercontent.com/84697534/136783181-2d3c2bcf-469d-4eab-b1d2-1f9f8e0e818a.png)

**What is received:**

![image](https://user-images.githubusercontent.com/84697534/136783500-0c9b20d1-c88b-44b9-99c4-c20454171151.png)

**Whereas in table, 'action_id' is type 'number'**

![image](https://user-images.githubusercontent.com/84697534/136783702-3cd2ca78-f3f0-4ee7-a16c-37fa62ec664b.png)

### System details

- Operating System => centos 7
- PHP Version => 7.3.27
- Laravel Version => 8.0
- Laravel-OCI8 Version => 8.3.0

**Comment by sciracioglu** [comment]
maybe you can use like this. its safety way for unused columns, and type casting

$query
->....
->get()
->map(function($item){
   return [
     'id' => (int) $item->id,
    'inventory_id' => (int) $item->inventory_id,
    'user_id' => (int) $item->user_id,
    'comment' => $item->comment,
    'completion' => $item->completion,
  ]
});

**Comment by yajra** [comment]
I think this is the expected behavior where almost everything is returned as string. Model ID is casted as int, thus you should also cast your attributes to int as needed. You can also use map as @sciracioglu suggested or use a `Laravel Resource` if you are returning an API response.
