### ISSUE TITLE
"ORA" errors - Friendly messages

### ISSUE THREAD

**Issue by DANIELFLEMES** [yajra/laravel-oci8#683]
Hi! How to write custom "ORA" error in laravel? 

I would like to show custom exception view/message in laravel.

- Operating System: Virtual Box, DebianDockerPHP
- PHP Version: 7.4.
- Laravel Version: 8
- Laravel-OCI8 Version

**Comment by sciracioglu** [comment]
try{
 //query
} catch (Oci8Exception $e){
Log::error($e->getMessage());
}
