### ISSUE TITLE
Call to undefined function Yajra\Pdo\oci_connect() 

### ISSUE THREAD

**Issue by DJAG95** [yajra/laravel-oci8#684]
### I have not been able to connect to my Oracle

I have tried:
- Typing the credentials directly into database.php.
- Creating a file inside config called Oracle.php and writing the credentials there, as the documentation says

### System details

- Windows 10
- PHP 7.4.19
- Laravel 8.7
- yajra/laravel-oci8:  8.5

### Error message

Call to undefined function Yajra\Pdo\oci_connect()

### Conection in database.php && Oracle.php

both connections are identical
```

return [
    'oracle' => [
        'driver'         => 'oracle',
        'tns'            => env('DB_TNS', ''),
        'host'           => env('ORACLE_HOST', ''),
        'port'           => env('ORACLE_PORT', '1521'),
        'database'       => env('ORACLE_DATABASE', ''),
        'service_name'   => env('ORACLE_SERVICE_NAME', ''),
        'username'       => env('ORACLE_USERNAME', ''),
        'password'       => env('ORACLE_PASSWORD', ''),
        'charset'        => env('ORACLE_CHARSET', 'AL32UTF8'),
        'prefix'         => env('ORACLE_PREFIX', ''),
        'prefix_schema'  => env('DB_SCHEMA_PREFIX', ''),
        'edition'        => env('DB_EDITION', 'ora$base'),
        'server_version' => env('DB_SERVER_VERSION', '11g'),
        'dynamic'        => [],
    ],
];
```

the variable tns is the only one that I don't have informed in .env, I have also tried to inform it and remove the line.

**Comment by Mohammed-Alama** [comment]
I think you did not install [Oci8](https://www.php.net/manual/en/book.oci8.php) for your PHP version check this [gist](https://gist.github.com/eSkiSo/781269c79b4dd740e90fcc059c1985ae)

**Comment by DJAG95** [comment]
> 
> 
> I think you did not install [Oci8](https://www.php.net/manual/en/book.oci8.php) for your PHP version check this [gist](https://gist.github.com/eSkiSo/781269c79b4dd740e90fcc059c1985ae)



I will follow the gist in full and let you know by editing this reply as soon as I finish it.

Thank you very much for your contribution, best regards

**Comment by Mohammed-Alama** [comment]
I hope my solution work with you if it's, can you close the issue

**Comment by DJAG95** [comment]
Good evening, sorry for the delay in answering, for my case I have been able to solve it by installing another version of OCI8, I was using the NTS and I needed the TS, I am very sorry for the inconvenience, thank you very much for helping me.
