### ISSUE TITLE
DB::getQueryLog() with laravel-oci8 on Lumen

### ISSUE THREAD

**Issue by caleywoods** [yajra/laravel-oci8#69]
How do we see queries in Lumen/Laravel which are executed using the oci8/oracle connection? Tried about everything I found online and couldn't get any of it to work.

**Comment by yajra** [comment]
You should enable DB::enableQueryLog() to get results on DB::getQueryLog(). It used to be enable on Laravel 4 but I think on Laravel 5 it was disabled by default.

**Comment by caleywoods** [comment]
I had to do:

    DB::enableQueryLog('oracle');
    DB::getQueryLog('oracle');

Within the code I was wanting to log the queries from. I thought that enabling the query log was an application runtime kind of thing that would always make it keep a log of queries but it doesn't look like it.

**Comment by yajra** [comment]
I suggest you use https://github.com/barryvdh/laravel-debugbar. This is what I use to debug my queries.

**Comment by caleywoods** [comment]
I'll install that and give it a go. I'll probably have to disable all the collectors except route and query. My lumen setup is only powering an API, we don't render any HTML pages on it.

**Comment by yajra** [comment]
oops.. I am using it on Laravel, not sure if it works on Lumen though.

**Comment by yajra** [comment]
Btw, why not try adding your own listener on the database for logging of queries? 

```php
DB::listen(function($sql, $bindings, $time)
{
    //
});
```

**Comment by alsofronie** [comment]
It seems ``DB::listen`` does not catch Eloquent operations, at least in unit testing. I can easily see the migrations, but nothing about my models being created/deleted. I am using Lumen 5.1 with ``factory()`` method. Maybe because of the ``factory`` ? The rows are present in my MySQL DB.
