### ISSUE TITLE
Misleading Documentation Yajra\Oci8\Oci8Connection::executeFunction() 

### ISSUE THREAD

**Issue by A-Tahemmout** [yajra/laravel-oci8#691]
**Wrong giving documentation or wrong witten function**

As mention in the executeFunction function documentation calling it should be like so
`DB::executeFunction('function_name(:binding_1,:binding_n)', [':binding_1' => 'hi', ':binding_n' => 'bye'], PDO::PARAM_LOB);`
The first parameter being the name of the function `$functionName`, this variable that goes to to the function createStatementFromFunction merge it with the bindings given and create
`function_name(:binding_1,:binding_n)(::binding_1,::binding_n)`

**First problem**
The Documentation tell to give the whole function name with the parameters and it should only be the function name

**Second problem**
The bindings arrays keys includes the ':' in the Documentation which generate '::' when calling `$bindings ? ':' . implode(', :', array_keys($bindings)) : '';` in the funtion createStatementFromFunction 
So the key binding must be without ':'

![image](https://user-images.githubusercontent.com/66123174/148767854-4a62dbb4-7f4b-4128-98eb-11005707c863.png)
![image](https://user-images.githubusercontent.com/66123174/148767926-48c04336-0ec4-459f-a894-448a614e40bd.png)

**Comment by yajra** [comment]
Thank you for spotting, would you be able to send a PR on docs and in the package?

Docs repo: https://github.com/yajra/laravel-oci8-docs/blob/master/function.md

**Comment by A-Tahemmout** [comment]
Sure thing

**Comment by yajra** [comment]
Fixed via https://github.com/yajra/laravel-oci8-docs/pull/3
