### ISSUE TITLE
!! Simple but drastic documentation typo

### ISSUE THREAD

**Issue by ChristianAdamski** [yajra/laravel-oci8#696]
Look at the project page:

'oracle' => [
    'driver'         => 'oracle',
    'tns'            => env('DB_TNS', ''),
    'host'           => env('DB_HOST', ''),
    'port'           => env('DB_PORT', '1521'),
    'database'       => env('DB_DATABASE', ''),
    'service_name'   => env('DB_SERVICENAME', ''),
    'username'       => env('DB_USERNAME', ''),
    'password'       => env('DB_PASSWORD', ''),

[...]

DB_PORT=1521
DB_SERVICE_NAME=orcl
DB_DATABASE=xe
DB_USERNAME=hr
DB_PASSWORD=hr``

The project page says "DB_SERVICE_NAME" but used is "DB_SERVICENAME"

**Comment by yajra** [comment]
Thanks for spotting the typo. I will rename the `DB_SERVICENAME` to `DB_SERVICE_NAME` on Laravel 9 and it will be a breaking change.

**Comment by ChristianAdamski** [comment]
Thank you!

**Comment by marteze** [comment]
Thank you! I was stuck a whole in this error and your reported issue helped me a lot!
