### ISSUE TITLE
Question - Oracle Eloquent Without Sequences

### ISSUE THREAD

**Issue by Teknoman117** [yajra/laravel-oci8#70]
I'm working on a laravel application where I have to interface with an existing Oracle database where I'm not allowed to change the schema, add sequences, etc.  (there is a local MySQL database that handles all of the application's data, this oracle database is part of another system).  Currently I'm manually running all of my queries using the transaction feature of the DB connection object, but I'd like to use Eloquent if i can.  

There is no primary sequence that the tables I need access to use, however there is a table column (patronid) which is unique to records in the table.  I'm able to fetch data using the eloquent examples in the wiki, but I'd also like to be able to update them as well.  If sequence is set to null, how are the records associated with the model updated?  So far I'm using a whereRaw statement to get the model from the database (these patron id's are retrieved using a function "getpatronid", which takes a string from a different id format).  

So my question is, in this scenario, is it even possible to use eloquent to update the records in the database?  I just wanted to check before experimenting, because this oracle database is production, there is no development mirror of it.  (bad, i know this, i'm not the one in control of these things and i take every opportunity to pester about it).  

I know this really isn't an issue, but I didn't know how else to contact you (or others who may know).

**Comment by Teknoman117** [comment]
I've set primary key to this patronid column in the model, just wanted to check before accidentally doing something really bad.

**Comment by Teknoman117** [comment]
So setting the primary key to patron id allows me to use find on the patronid values.  If i perform a whereRaw, is the column primary key is set to also used to identify the row when updating?

**Comment by yajra** [comment]
I think you can use Eloquent in your case. You just need to specify the `primaryKey=tableid` and `incrementing=false` since you're not using a sequence/auto increment function. For updating, `Model::find(1)` then `save()` would definitely work but for creating a new record, I have to verify it first but I think it should work as expected. You just need set the proper id value for your primary key.

**Comment by Teknoman117** [comment]
So this is my model definition

    <?php namespace App;
    use Illuminate\Database\Eloquent\Model;
    
    class PatronImage extends Model
    {
        // Connection to be used for this model
        protected $connection = '<omitted>';
        
        // Table the patron images are located in
        protected $table = '<omitted>';
        
        // define binary/blob fields
        protected $binaries = ['dbd_image'];
        
        protected $sequence = null;
        public $incrementing = false;
        
        // Database uses trigger to update timestamp
        public $timestamps = false;
    
        protected $primaryKey = 'patronid';
    }

Using php artisan tinker, I can get the patron using the eloquent query $patron = PatronImage::find(<student id>), but if i overwrite dbd_image with a new binary object loaded using fread, it throws some exception and the query is seems to have attempted to execute is 'update <omitted> set dbd_image = :autoparam0 where patronid = :autoparam1'.  As far as i understand, you can't update BLOBs this way.  The query i had to do previously was like transaction example on the wiki for blobs (returning into statements, followed by $lob->save(/* the content */).  Can i update blobs purely through eloquent?

**Comment by yajra** [comment]
You need to extend Oracle Eloquent if you want to save the blob directly using Eloquent. https://github.com/yajra/laravel-oci8/wiki/Oracle-Blob#updating-blob-directly-using-oracleeloquent.

Otherwise, if no blob is required, just extend the Model as usual.

**Comment by Teknoman117** [comment]
Okay, closer now.  I receive this exception when running save

>>> $patron->save()
PHP warning:  oci_execute(): ORA-01747: invalid user.table.column, table.column, or column specification in /home/sites/caticlick/vendor/yajra/laravel-pdo-via-oci8/src/yajra/Pdo/Oci8/Statement.php on line 141
yajra\Pdo\Oci8\Exceptions\Oci8Exception with message 'Error Code    : 1747
Error Message : ORA-01747: invalid user.table.column, table.column, or column specification
Position      : 32
Statement     : update diebold.patronimages set , dbd_image = EMPTY_BLOB() where patronid = :autoparam0 returning dbd_image, patronid into :autoparam1, :autoparam2
Bindings      : []

It appears there is a stray comma after set in the sql statement.  Dunno whats causing it.

**Comment by yajra** [comment]
Seems like a bug, did you update only the blob field? Can you please try updating other fields that are not blob? Im travelling atm and will not be able to check the codes. Thanks!

**Comment by Teknoman117** [comment]
Yup.  If i update more than one field it works correctly (or if I hide all but the binary field it works as well)

**Comment by yajra** [comment]
Then it is indeed a bug. Will work on it as soon as i can. Thanks for confirming the error.

**Comment by yajra** [comment]
Inserting/updating only blob field should be fixed on v2.3.1. Kindly verify and test. Thanks!
