### ISSUE TITLE
mplemented the "setClientIdentifier" in the model

### ISSUE THREAD

**Issue by maxdevis** [yajra/laravel-oci8#703]
hi,
how  implemented the "setClientIdentifier" in the model ?

br
Max

**Comment by yajra** [comment]
Haven't tried yet but I think you can do this:

```php
$user = User::first();
$pdo = $user->getConnection()->getPdo();
$pdo->setClientIdentifier($user->name)
```

**Comment by maxdevis** [comment]
thank you for the answer, i will try to implement it in a basic model

br
max
