### ISSUE TITLE
Call to undefined method Yajra\Pdo\Oci8::setClientIdentifier()

### ISSUE THREAD

**Issue by maxdevis** [yajra/laravel-oci8#704]
hi, i test setClientIdentifier() on mi model i put:

$pdo = $model->getConnection()->getPdo();
        $pdo->setClientIdentifier(Auth::id());

but :setClientIdentifier() is undefined

any help?

br
Max

- Operating System windows 10
- PHP Version 8.1
- Laravel Version 8.x
- Laravel-OCI8 Version 8

**Comment by yajra** [comment]
It was added on https://github.com/yajra/pdo-via-oci8/blob/2.0/CHANGELOG.md#v240---2022-02-09 and v3, were you able to update to latest version?
