### ISSUE TITLE
Showing OCI Error?

### ISSUE THREAD

**Issue by caleywoods** [yajra/laravel-oci8#71]
I have a try/catch on a delete call on an eloquent method. The particular record I'm trying to delete would violate an integrity constraint. I can catch the Exception object but there is no information contained within it to allow me to give the user a proper error message.

**Comment by yajra** [comment]
You should be able to catch the error using basic try catch like below:

```php
try {
	User::first()->delete();
} catch (Exception $e) {
	echo "<pre>{$e->getMessage()}</pre>";
}
```
```php
Error Code    : 2292
Error Message : ORA-02292: integrity constraint (SCHEMA.SALES_USER_ID_FOREIGN) violated - child record found
Position      : 0
Statement     : delete from users where id = :autoparam0
Bindings      : [10000]
 (SQL: delete from users where id = 10000)
```

**Comment by caleywoods** [comment]
Thank you I was able to use ```getCode()``` to do a check on if it's an integrity constraint and send  back a somewhat helpful message.
