### ISSUE TITLE
Error when using withCount()

### ISSUE THREAD

**Issue by Bosphoramus** [yajra/laravel-oci8#713]
### Summary of problem or feature request

Hi! i have a relationship between Oracle/MySql, the relationship is working perfectly and returning the collection of related models, but when using the withCount() function from Laravel i get the following error: 

```
Error Message : ORA-00911: invalid character
Position      : 48
Statement     : select "V_HM_TEST".*, (select count(*) from `test_app_local`.`commissions` where `V_HM_TEST`.`emp_code` = `commissions`.`foreman_id` and `commissions`.`deleted_at` is null) as "COMMISSIONS_COUNT" from "V_HM_TEST"Bindings      : [] (SQL: select "V_HM_TEST".*, (select count(*) from `test_app_local`.`commissions` where `V_HM_TEST`.`emp_code` = `commissions`.`foreman_id` and `commissions`.`deleted_at` is null) as "COMMISSIONS_COUNT" from "V_HM_TEST")'
```

I know that mixing Laravel relationship methods between database connection is probably not advised, but its working fine for me. As i said it returns the collection of related models properly, now i just need the count of related models, using this method, if it worked would be perfect. Maybe im doing something wrong on the relationship method params or something else.

### Code snippet of problem

```php
// Relationship method on Employee model

    public function commissions()
    {
        return $this->hasMany(Commission::class, 'foreman_id', 'emp_code');
    }

// Relationship method on Commission model

    public function foreman()
    {
        return $this->belongsTo(Worker::class, 'foreman_id', 'emp_code');
    }
```

I have specified the connection on both classes, 

```php
// Connection property on Employee model

    protected $connection = 'oracle';

// Connection property on Commission model

    protected $connection = 'mysql';
```

### System details

- Operating System
- PHP Version 7.4
- Laravel Version 8
- Laravel-OCI8 Version 8

**Comment by yajra** [comment]
I think this is not possible afaik since they are different connections. withCount perform a sub-query which is then not possible due to diff rdbms connection.
