### ISSUE TITLE
Querybuilder's joinSub method is naming subquery using the AS directive. 

### ISSUE THREAD

**Issue by grainone** [yajra/laravel-oci8#718]
### Summary of problem or feature request

When using the querybuilder joinSub method the generated SQL is using the AS directive to name the subquery. This is not correct Oracle SQL. 

### Code snippet of problem
Here Person, SectionAssign and SectionGeneralBase are all models. The column method is a helper that retrieves the full column name from the model.
```php
$instructor = new Person();
$assignment = new SectionAssign();
$section = new SectionGeneralBase();

$pidm = $instructor->where(column('bannerid','Person'),$queryBannerId)->first()->pidm;
$assignments = $assignment->where(column('pidm','SectionAssign'),$pidm);     
        
$finalQuery = $section->whereIn(column('term_code','SectionGeneralBase'), $allowedterms)
                      ->joinSub($assignments, "A", function($join)
                                                    {    
                                                        $join->on(column('term_code','SectionGeneralBase'), '=', column('term_code','SectionAssign'))
                                                             ->on(column('crn','SectionGeneralBase'), '=', column('crn','SectionAssign'));

                                                    }
                                );

dd($finalQuery->toSql());
```
This is what the builder is generating:
```sql
select
    *
from
    "SSBSECT"
    inner join (
        select
            *
        from
            "SIRASGN"
        where
            "SIRASGN_PIDM" = ?
    ) as "A" on "SSBSECT_TERM_CODE" = "SIRASGN_TERM_CODE"
    and "SSBSECT_CRN" = "SIRASGN_CRN"
where
    "SSBSECT_TERM_CODE" in (?, ?)
```
To which Oracle responds with 'ORA-00905: missing keyword'.

The correct Oracle SQL should be:
```sql
select
    *
from
    "SSBSECT"
    inner join (
        select
            *
        from
            "SIRASGN"
        where
            "SIRASGN_PIDM" = ?
    )  "A" on "SSBSECT_TERM_CODE" = "SIRASGN_TERM_CODE"
    and "SSBSECT_CRN" = "SIRASGN_CRN"
where
    "SSBSECT_TERM_CODE" in (?, ?)
```
### System details

- Operating System: RHEL7
- PHP Version: 7.4.3
- Laravel Version: 8.42.1
- Laravel-OCI8 Version: 8.4.0

**Comment by yajra** [comment]
Seems to be working fine for me but tested on Laravel 9.

```php
Route::get('test', function () {
    return User::query()
               ->select('users.name', 'u.email')
               ->whereIn('users.id', [1, 2, 3])
               ->joinSub(
                   User::query(),
                   'u',
                   function (JoinClause $join) {
                       $join->on('users.id', '=', 'u.id');
                   }
               )
               ->toSql();
});
```

**OUTPUT**

Note I have **AH_** prefix on my tables. Was also able to get the json response.

```php
select "AH_USERS"."NAME", "AH_U"."EMAIL" from "AH_USERS" inner join (select * from "AH_USERS") "AH_U" on "AH_USERS"."ID" = "AH_U"."ID" where "AH_USERS"."ID" in (?, ?, ?)
```

**Comment by yajra** [comment]
Based on https://github.com/yajra/laravel-oci8/pull/551/files, joinSub was added since 6.x. 

If still an issue, please provide a sample script to replicate. Thanks!

**Comment by grainone** [comment]
Interesting. My models are using Awobaz\Compoships\Compoships trait because my database is full of compound keys.

Using the route script you provided and the User model in your test folder I get the correct result. However if I just add the trait to the model it returns a query with the as.

So with a model that looks like this:
```php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @property int id
 * @property string name
 * @property string email
 */
class User extends Model
{
    use \Awobaz\Compoships\Compoships;
    
    protected $guarded = [];
}
```

**Comment by yajra** [comment]
@grainone I think the issue is on that package. I suspect that there is a raw query used there that forces `AS` in sql. Common package issues when working with Oracle. This issue should be raised there instead. Thanks!
