### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by rgiaviti** [yajra/laravel-oci8#72]
With 5.1 Laravel out in a few days, I have to wonder if the library already supports the new version of Laravel. I am starting a new project and I want to start with Laravel 5.1 and Oracle is my database, so I need this library.

Thanks!

**Comment by yajra** [comment]
@rgiaviti the last time I checked (a week or two ago), the package worked with Laravel 5.1 as is. No modification/updates required on the package.

**Comment by yajra** [comment]
I'm currently playing with Laravel 5.1 and the package indeed works!
