### ISSUE TITLE
Why "max object name length is 30 chars"?

### ISSUE THREAD

**Issue by jsamaniegog** [yajra/laravel-oci8#720]
Why does this method limit the name to 30 characters? I had to modify the value for the migrations to work because there was a conflict when matching the name of the table.
```
/**
     * Create an object name that limits to 30 chars.
     *
     * @param  string  $prefix
     * @param  string  $table
     * @param  string  $col
     * @param  string  $type
     * @return string
     */
    private function createObjectName($prefix, $table, $col, $type)
    {
        // max object name length is 30 chars
        return substr($prefix.$table.'_'.$col.'_'.$type, 0, 30);
    }
```

- PHP Version: 8.0
- Laravel Version: v8.83.2
- Laravel-OCI8 Version: v8.6.2

Thank you.

**Comment by yajra** [comment]
Per [SO Post](https://stackoverflow.com/questions/756558/what-is-the-maximum-length-of-a-table-name-in-oracle#:~:text=In%20Oracle%2012.2%20and%20above,name%20length%20is%2030%20bytes.)

In [Oracle 12.2](http://docs.oracle.com/database/122/REFRN/ALL_OBJECTS.htm#REFRN20146) and above the maximum object name length is 128 bytes.
In [Oracle 12.1](https://docs.oracle.com/database/121/SQLRF/sql_elements008.htm#SQLRF00223) and below the maximum object name length is 30 bytes.

We are still using 10g on some projects so we are limited to 30. But I guess we can improve it now and make the length configurable. Accepting a PR if you can implement. Thanks!

**Comment by jsamaniegog** [comment]
The real problem is that the length of $prefix + $table is 30.
the solution could be to put $type as a prefix, regardless of making that length configurable.

What do you think about it?
