### ISSUE TITLE
error when post data

### ISSUE THREAD

**Issue by rsoenar** [yajra/laravel-oci8#726]
Error Code    : 942\r\nError Message : ORA-00942: table or view does not exist\r\nPosition      : 10\r\nStatement     : insert into \"DBADMIT\".\"TMKEDBHDWSFWSC\" (\"I_TCKT\", \"I_ID_KEDBHDWSFW\", \"C_KEDB_RESSTART\", \"I_ENTRY\", \"D_ENTRY\") values (:p0, :p1, :p2, :p3, :p4) returning \"I_ID_KEDBHDWSFWSC\" into :p5\r\nBindings      : [202207200002,1150,1,1407620,2022-03-08,0]\r\n"

**Comment by gustavobretas** [comment]
[rsoenar](https://github.com/rsoenar), what precisely would be your question? Don't get me wrong, but, the error shows "table or view does not exist", which is quite revealant about the error you got. Would you like to clarify more details?
