### ISSUE TITLE
Undefined constant "Yajra\Pdo\OCI_DEFAULT" found 

### ISSUE THREAD

**Issue by arirah** [yajra/laravel-oci8#727]
### Summary of problem or feature request
I am getting this error, Please help
 

### Code snippet of problem
 

```php
 $sessionMode = array_key_exists('session_mode', $options) ? $options['session_mode'] : OCI_DEFAULT;


```
 
### System details

 

- Operating System : LINUX 
- PHP Version : 8.1
- Laravel Version : 8
- Laravel-OCI8 Version : 8.

**Comment by yajra** [comment]
Make sure that `oci8` extension is installed correctly. Try running `php -m | grep oci8` and phpinfo in the browser to see if the extension is loaded.

**Comment by kurniawanekoyulianto** [comment]
I have same problem like that, anyone can help me?
I use Windows 10, PHP version 8.1, Laravel v 9.x, Oci8

**Comment by Makeroot911** [comment]
I have same problem, I use Mac OS Monterey, Php version 8.0 , Laravel 9.x , Oci 8, InstantClient v11
![image](https://user-images.githubusercontent.com/61171264/194402157-42eacda0-5cf8-47bf-9b34-c39b480b9f9b.png)
![Screen Shot 2022-10-07 at 02 30 52](https://user-images.githubusercontent.com/61171264/194402440-2806af26-1ef7-4fa7-b54c-62383899ac9f.png)

**Comment by yajra** [comment]
@Makeroot911 make sure you have ORACLE_HOME and LD_LIBRARY_PATH configured.

```sh
# OCI8 Instantclient
export ORACLE_HOME=/usr/local/oracle
export LD_LIBRARY_PATH=/usr/local/oracle
export OCI_LIB_DIR=/usr/local/oracle
export OCI_INC_DIR=/usr/local/oracle/sdk/include
```

**Comment by jwhoami** [comment]
> @Makeroot911 make sure you have ORACLE_HOME and LD_LIBRARY_PATH configured.
> 
> ```shell
> # OCI8 Instantclient
> export ORACLE_HOME=/usr/local/oracle
> export LD_LIBRARY_PATH=/usr/local/oracle
> export OCI_LIB_DIR=/usr/local/oracle
> export OCI_INC_DIR=/usr/local/oracle/sdk/include
> ```

I know these are env variables, but when using your package with laravel, where should I put these lines?
Thanks

**Comment by gabrielcorradinis** [comment]
> Solved? I have the same problem.
> 
> If I run migrations it works, but a simple all() function doesn't.

Hello Jonas, you are using the project on Windows, right? Move the project to linux (can be on WSL) and use Docker, then install the dependencies with Makefile.
