### ISSUE TITLE
Undefined constant "Yajra\Pdo\OCI_DEFAULT"

### ISSUE THREAD

**Issue by julianov** [yajra/laravel-oci8#734]
### Summary of problem or feature request

      Error 

      Undefined constant "Yajra\Pdo\OCI_DEFAULT"

       at vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php:138

Why the constant can be undefined? 

private function connect(string $dsn, string $username, string $password, array $options, string $charset)
    137▕     {
  ➜ 138▕         $sessionMode = array_key_exists('session_mode', $options) ? $options['session_mode'] : OCI_DEFAULT;
    139▕ 
    140▕         if (array_key_exists(PDO::ATTR_PERSISTENT, $options) && $options[PDO::ATTR_PERSISTENT]) {
    141▕             $this->dbh = @oci_pconnect($username, $password, $dsn, $charset, $sessionMode);
    142▕         } else {

### System details

- openSUSE Leap 15
- PHP8
- Laravel 9

**Comment by yajra** [comment]
Setup issue, make sure you have the oci8 extension installed properly. See similar issues for reference:

https://github.com/yajra/laravel-oci8/issues?q=is%3Aissue+OCI_DEFAULT+

**Comment by RJYOMAN485** [comment]
This errors shows on production. I think it never works on production. Pleas fix the issue

**Comment by jesusferm** [comment]
I have the same problem

PHP 8.2
Laravel 9
Laravel-OCI8 Version ^9.0
Fedora 37 x86_64

i have installed oci8
