### ISSUE TITLE
Error on Create when try it out of the book

### ISSUE THREAD

**Issue by Calcio** [yajra/laravel-oci8#74]
When I try to use Model::Create I got the error:
Error Code : 904
Error Message : ORA-00904: "ID": invalid identifier
Position : 109
Statement : insert into gcc_bancos (id_banco, cod_banco, banco) values (:autoparam0, :autoparam1, :autoparam2) returning id into :autoparam3
Bindings : []

My table don't have the id field. Instead of it I have "id_banco" field to my id. I try many workarouds but I receive the same error.

Laravel 5.1

Thanks

**Comment by yajra** [comment]
On your model I think you need to specify the `$primaryKey='id_banco'` and `$incrementing=false' since your not using the Laravel table structure approach. This also applies to other database aside from oracle.

```php
class Model extends Eloquent
{
   protected $primaryKey = 'id_banco';
   protected $incrementing = false;
}
```

**Comment by Calcio** [comment]
Thaks so much Yajra. 
Could you help me again once? How can I create a Nextval() Oracle increment ?

**Comment by yajra** [comment]
you can use the oracle sequence class. see docs here https://github.com/yajra/laravel-oci8/wiki/Oracle-Sequence.

**Comment by Calcio** [comment]
Thaks again. I'll try it.
