### ISSUE TITLE
Undefined constant "Yajra\Pdo\OCI_DEFAULT" running without php -S localhost:8000 -t public but xampp

### ISSUE THREAD

**Issue by dedisupriadi1612** [yajra/laravel-oci8#741]
i running lumen 9 without php -S localhost:8000 -t public i found error **this Undefined constant "Yajra\Pdo\OCI_DEFAULT"**, running in xampp
but i run with php -S localhost:8000 -t public it's work , can you help me to solved running in xampp ?

- Operating System Windows
- PHP Version 8
- Lumen 9 
- Laravel-OCI8 Version ^9.0

**Comment by jesusferm** [comment]
I have the same problem
- PHP 8.2
- Laravel 9
- Laravel-OCI8 Version ^9.0
- Fedora 37 x86_64

i have installed oci8

**Comment by m4gn3to** [comment]
Hi. 

I have the same behaviour.

If I run nginx then I face this error but if I run "php -S localhost:8000 -r public" I don't.

$php -v
PHP 8.0.27 (cli) (built: Jan 13 2023 10:38:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.27, Copyright (c), by Zend Technologies

$php -m | grep oci
oci8

Laravel 9.48.0

**Comment by jesusferm** [comment]
I reinstalled oci from pecl and update path in file /etc/php.ini and xampp php.ini (i use xampp)

- now working

https://blog.linuxitos.com/post/instalar-instantclient-de-oracle-y-fedora-36
