### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by AlienwareTG** [yajra/laravel-oci8#744]
php 8.2.0
laravel 9.19

Getting this error

**Comment by yajra** [comment]
Thanks for reporting, will check and give PHP 8.2 a try.

**Comment by yajra** [comment]
PHP 8.2 tests are passing via #745 

Can you please add some snippets to reproduce the issue?

**Comment by aurawindsurfing** [comment]
Thanks for the fix!
