### ISSUE TITLE
oci_connect(): ORA-12504: TNS:listener was not given the SID in CONNECT_DATA

### ISSUE THREAD

**Issue by marcosantoniocaro** [yajra/laravel-oci8#75]
If you are using SERVICE_NAME based Oracle TNS connections:
Getting errors like: oci_connect(): ORA-12504: TNS:listener was not given the SID in CONNECT_DATA
In order to configure the service name add: 'service_name' => env('SERVICE_NAME',''),
leaving DB_DATABASE empty.
    'connections' => [
        'oracle' => [
            'driver'    => 'oracle',
            'host'      => env('DB_HOST', ''),
            'port'      => env('DB_PORT','1521'),
            'database'  => env('DB_DATABASE', ''),
            'service_name' => env('SERVICE_NAME',''),
            'username'  => env('DB_USERNAME', ''),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
     ]
]
The .env should looks like:
DB_CONNECTION=oracle
DB_HOST=edb01-scan
DB_PORT=1521
DB_DATABASE=
SERVICE_NAME=<service_name>
DB_USERNAME=<user>
DB_PASSWORD=<password>
DB_CHARSET=utf8

**Comment by yajra** [comment]
Yes, this is correct. If you're DB uses service name, then your config must be like that. I think i have accidentally removed it on documentation so I re-added it on [Wiki Installation](https://github.com/yajra/laravel-oci8/wiki/Installation). Thanks!
