### ISSUE TITLE
problem with Arabic language 

### ISSUE THREAD

**Issue by hussien269** [yajra/laravel-oci8#754]
@yajra 
i have problem with laravel and oracle in arabic language not in connection

**Comment by hussien269** [comment]
and i set AL32UTF8 in database.php but the result is
ÊäÔÄ ÎÈíË Ýí ÇáÚÙã æ ÇáÛÖÇÑíÝ ÇáãÝÕáíÉ ááÃØÑÇÝ

**Comment by yajra** [comment]
Afaik, encoding should be set upon the creation of the database. Setting it in the config level doesn't seem to work if I recall correctly.

Unfortunately, I haven't tried working with other languages yet so I may not be able to help much with this.
