### ISSUE TITLE
change function in migration not working

### ISSUE THREAD

**Issue by devvmaaster** [yajra/laravel-oci8#769]
### change function in migration not working

In a migration i'll try to change an existing table column.
I always get the same error from DBAL:
"Undefined index: user" in function getDatabase(Connection $con)
located in AbstractOracleDriver.php in line 81

### Code snippet of problem

```php
...
Schema::table('PROJECTS_BENEFITS_SOLUTIONS', function (Blueprint $table) {
    $table->boolean('EFFORT_SOLUTION_M')->default(false)->change();
});
...
```

### System details

- Operating System: Windows
- PHP Version: 7.4
- Laravel Version: 8.83.27
- Laravel-OCI8 Version: 8.6.3

**Comment by yajra** [comment]
I think `change()` requires `doctrine/dbal` library. Did you install it already?

**Comment by devvmaaster** [comment]
Hi @yajra 
thanks for your answer.
I have DBAL installed in version 2.13.9
This error comes from a called DBAL function "getParams()"
I've tried to set the "user" parameter in the .env and also in the config/database.php and config/oracle.php, but without success :-(

**Comment by yajra** [comment]
I just tried on fresh Laravel 8 with `"doctrine/dbal": "^3.6"` and seems to work well. Can you update your dbal version and test?
