### ISSUE TITLE
Custom Connection String?

### ISSUE THREAD

**Issue by derdida** [yajra/laravel-oci8#77]
Can ill use a custom connection string?

I am unable to connect to Oracle, always getting the following error:

Unsupported driver [pdo-via-oci8]

But when ill use:

$conn = oci_connect('user', 'pass', '(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = xxx.com)(PORT = 1521))(CONNECT_DATA = (SID = my_SID)(GLOBAL_DBNAME = global_db_name)))');

Everthing works fine.

Is it possible to set this specific connection string with your extension?

**Comment by yajra** [comment]
YES, just use the `tns` attribute. I think something like below should work. 

```php
'oracle'     => [
            'driver'   => 'oracle',
            'tns'     => '......',
        ],
```

**Comment by derdida** [comment]
Thank you so much, works fine!
