### ISSUE TITLE
Inite loop on OracleBlueprint createIndexName 

### ISSUE THREAD

**Issue by edcaron** [yajra/laravel-oci8#781]
### Summary of problem or feature request

Using the migrations from laravel, When creating an index on a table with lots of underscore character and big length, the execution gets stuck.
Debugged the code and found out that the function `createIndexName` on the class `OracleBlueprint` tries to reduce the string to 30 chars, but respecting the rule of at least 2 chars after the underscore character but then when there are lots of underscores, summing up all the splits it it passes 30 chars, an then there is the inifite loop.

### Code snippet of problem

```php
Schema::create(
            'servidor_lotacao_distr_ch', function (Blueprint $table) {
                $table->id();
                $table->unsignedBigInteger('categoria_ser_lot_distr_ch_id')->index();
            }
        );
```

### System details

- Operating System: Ubuntu 22
- PHP Version: 8.1
- Laravel Version: v9.43
- Laravel-OCI8 Version: v9.1.0

**Comment by yajra** [comment]
Depending on your Oracle version, you can use a more prominent index/object name. See PR https://github.com/yajra/laravel-oci8/pull/777
