### ISSUE TITLE
Version 6 not working on php 8

### ISSUE THREAD

**Issue by absiddiqueLive** [yajra/laravel-oci8#790]
### Summary of problem or feature request

PHP8 support issue

### Code snippet of problem

```php
Declaration of Yajra\Pdo\Oci8::query($statement, $fetchMode = null, $modeArg = null, $ctorArgs = null) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)
```

### System details

- Operating System: Ubuntu 22.04
- PHP Version: 8
- Laravel Version: 6
- Laravel-OCI8 Version: 6

**Comment by yajra** [comment]
Try using https://github.com/yajra/pdo-via-oci8 v3. However, not sure if it works on Laravel 6. Tested on 9 & 10 only.

**Comment by yajra** [comment]
Feel free to send a pull request as needed. Thanks!
