### ISSUE TITLE
Undefined Constant "Yajra\Pdo\OCI_DEFAULT"

### ISSUE THREAD

**Issue by yasar-salim** [yajra/laravel-oci8#799]
### System details

- Operating System: ubuntu 22.02
- PHP Version: 8.1.2
- Laravel Version: 10.12
- Laravel-OCI8 Version: 10

**Comment by beto-pu** [comment]
Same problem here, haven't tried to use it outside controller. 

System details

    Operating System: Debian 11
    PHP Version: 8.2.0
    Laravel Version: 10
    Laravel-OCI8 Version: 10

**Comment by yajra** [comment]
This is a common issue and it all boils down to an OCI8 extension installation/setup error. The solution varies depending on OS and versions.

Some items to check:

- LD library path
- ORACLE_HOME path
- Try `ldconfig`
- 2 php.ini for fpm & cli, make oci8.so is enabled on both config

**Comment by Charlink3** [comment]
I have the same issue, I installed yajra and run DB by locally , but have the issue, someone have a solution?
Thanks

**Comment by luiz-andrade** [comment]
Hello. I had the same problem and I solved it by installing this lib:

`apt-get install -y libaio1`

**Comment by yasar-salim** [comment]
reinstalled the oci and it worked
