### ISSUE TITLE
Error: ORA-12505: TNS:listener does not currently know of SID given in connect descriptor

### ISSUE THREAD

**Issue by smrita-garg** [yajra/laravel-oci8#80]
I am getting an error while connecting to schemas through sql developer as ORA-12505
TNS:listener does not currently know of SID given in connect descriptor

When I am trying tnsping xe through command prompt . its working for me .please help

**Comment by yajra** [comment]
Please see these same issue as ref:
https://github.com/yajra/laravel-oci8/issues/75
https://github.com/yajra/laravel-oci8/issues/66
https://github.com/yajra/laravel-oci8/issues/49

**Comment by smrita-garg** [comment]
Thanks for the response.. !!

**Comment by dome21117** [comment]
I have problem  
laravel 8 and oracle 12C and php 7.4.8
ORA-12505: TNS:listener does not currently know of SID given in connect descriptor 
service_name  connect to laravel php 
code 
.env
DB_CONNECTION=oracle
DB_HOST=IP
DB_PORT=1521
DB_DATABASE=Service_name
DB_USERNAME=username
DB_PASSWORD=password

config/database .php

    'oracle' => [
    'driver' => 'oracle',
    'host' => 'ip',
    'port' => '1521',
    'database' => ' ',
    'service_name' => 'Service_name',
    'username' => 'username',
    'password' => 'password',
    'charset' => '',
    'prefix' => '',
        ],
    ],

help me please!!!!
