### ISSUE TITLE
Method Yajra\\Oci8\\Query\\Grammars\\OracleGrammar::setConnection does not exist

### ISSUE THREAD

**Issue by tiendathb94** [yajra/laravel-oci8#802]
### System details

- Operating System
- PHP Version ^8.1
- Laravel Version ^10.8
- Laravel-OCI8 Version ^10

**Comment by flavio-alves-roboyo** [comment]
Same issue here.

- Ubuntu 22.04.3 LTS
- PHP Version 8.2.8
- Laravel Version 10.11.0
- Laravel-OCI8 Version 10.3.2

**Comment by yajra** [comment]
Can you provide snippets to reproduce the issue? Per checking, the `setConnection($connection)` method exists in the base Grammar class.

**Comment by damiensu** [comment]
It seems that there's no `setConnection()` method  in the base Grammar class before `illuminate/database` 10.12.0
https://github.com/illuminate/database/blob/v10.12.0/Grammar.php
Please upgrade your laravel version.
https://github.com/illuminate/database/blob/v10.13.0/Grammar.php

**Comment by yajra** [comment]
@damiensu sorry, I might have missed something. But it's there at https://github.com/illuminate/database/blob/v10.13.0/Grammar.php#L287
