### ISSUE TITLE
oci_connect(): ORA-12637: Packet receive failed

### ISSUE THREAD

**Issue by luiz-andrade** [yajra/laravel-oci8#805]
### I'm getting the error: oci_connect(): ORA-12637: Packet receive failed
Using version 11g works normally only on versions 19 and 21 that have the error

### Code snippet of problem

```
oci_connect(): ORA-12637: Packet receive failed
/var/www/html/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php#155
```

### System details

- Operating System: Linux Mint 21.2
- PHP Version: 8.1.22
- Laravel Version: 10.14
- Laravel-OCI8 Version: 10.3.1

**Comment by luiz-andrade** [comment]
I've been having this problem for days and today after posting this question here I found the solution.

you must add DISABLE_OOB=ON in the sqlnet.ora file in the path: /opt/oracle/instantclient/network/admin/sqlnet.ora

I'm using docker so I did:
`RUN echo "DISABLE_OOB=ON" > /opt/oracle/instantclient/network/admin/sqlnet.ora`

**Comment by yajra** [comment]
First time I have seen this error. Thanks for sharing your solution.
