### ISSUE TITLE
Routing in laravel with yajra datatables

### ISSUE THREAD

**Issue by Raman16** [yajra/laravel-oci8#82]
Hi Yajra,its a great effort on datatables ,thanks for it..but please let me know as i am new to laravle and dtables that we are calling controller as below to get output
Route::controller('/', 'Admin\UserController', [
    'getList'  => 'user.data',
    'getIndex' => 'users',   -->works fine

Is n;t it possible to call using'
Route::get('/', 'Admin\ProductController@getList'); and please let me know if there any naming conventions for writing functions names in controller .i.e getList [works fine]but if index [not work]

Thanks in advance

**Comment by yajra** [comment]
Please post the issue on datatables repo @ https://github.com/yajra/laravel-datatables/issues. 
Anyways, there is no naming conventions. You just basically need two routes for it to work. One for displaying the view and 2nd route for processing datatables ajax response. Thanks!
