### ISSUE TITLE
DRCP Connection Pooling

### ISSUE THREAD

**Issue by ahmedbnhussain** [yajra/laravel-oci8#828]
### Summary of problem or feature request

Reading through [this](https://www.php.net/manual/en/oci8.connection.php) I can't find a way to specify the `SERVER=POOLED`. I looked at the `setTNS` function and I think it's not an option at the moment. am I missing something? 

```
$config['tns'] = "(DESCRIPTION = (ADDRESS = (PROTOCOL = {$config['protocol']})(HOST = {$config['host']})(PORT = {$config['port']})) (CONNECT_DATA =({$config['service']})))";
```

What I understood, is that I must add `SERVER=POOLED ` in the `CONNECT_DATA`, so I get something like this:

```
(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp) (HOST=myhost.dom.com) (PORT=1521))(CONNECT_DATA=(SERVICE_NAME=sales) (SERVER=POOLED)))
```

### System details

- Ubuntu 22.04
- PHP 8.3
- Laravel 10
- Laravel-OCI8 10.3

**Comment by ahmedbnhussain** [comment]
I just found out that I can set the `DB_TNS` in the `.env`.

**Comment by yajra** [comment]
Yes, you can use raw TNS to connect. Are you using a persistent connection with SERVER=POOLED? I just read the link and seems like it's nice to have this implemented like maybe on another config key. How was the performance?
