### ISSUE TITLE
Undefined type 'Yajra\Oci8\Oci8ServiceProvider'.

### ISSUE THREAD

**Issue by DanielRuizMawesi** [yajra/laravel-oci8#829]
### Summary of problem or feature request

When I try to use Oci8 in my laravel 10 application error appears because Yajra only have Datatables not Oci8

### Code snippet of problem
![image](https://github.com/yajra/laravel-oci8/assets/84457803/cf42ed84-bd66-481d-8fb0-02351855cf87)

composer.json
![image](https://github.com/yajra/laravel-oci8/assets/84457803/d713ac30-f142-4e0f-a887-79d51b8442e9)

### System details

- Operating System linux
- PHP Version 8.2.1
- Laravel Version 10
- Laravel-OCI8 Version 10.4.3

**Comment by yajra** [comment]
I just tested and installed fine:

![image](https://github.com/yajra/laravel-oci8/assets/2687997/3801289c-0a91-44be-8d28-49e5a5ffa5a4)

**Comment by DanielRuizMawesi** [comment]
> I just tested and installed fine:
> 
> ![image](https://private-user-images.githubusercontent.com/2687997/306961206-3801289c-0a91-44be-8d28-49e5a5ffa5a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDg0NDIsIm5iZiI6MTcwODYwODE0MiwicGF0aCI6Ii8yNjg3OTk3LzMwNjk2MTIwNi0zODAxMjg5Yy0wYTkxLTQ0YmUtOGQyOC00OWU1YTVmZmE1YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTMyMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA5NmVlZTUxNTIxMDY3ZWNkZjA2ZTdkNzI0OTljZWZjNGNhMjc3OThkZTFlNTk4N2YzZGQ5NWZlMmNhZjI2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ttR5alIlrHoR4h3lo2MbtrO4-BNZff35VM3nAZO--Xc)

The installation was successfully but when you try to use Oci8 of that library is not Showing Oci8

**Comment by yajra** [comment]
> Undefined constant "Yajra\Pdo\OCI_DEFAULT"

This is a common issue that pertains to the OCI8 extension not being installed correctly. Please make sure you have the php oci8 extension installed properly. Installation may vary depending on your environment.
