### ISSUE TITLE
"OracleProcessor->saveLob" A little suggestion.

### ISSUE THREAD

**Issue by sasanet** [yajra/laravel-oci8#83]
In yajra\Oci8\Query\Processors\OracleProcessor 
The method saveLob have : 
		$query->getConnection()->getPdo()->beginTransaction();
and 
                $query->getConnection()->getPdo()->commit().

This raise an managed exception if you create a transaction with more query.
I think that this lines must be removed to resolve issue.

**Comment by sasanet** [comment]
Please this is an example : 


DB::transaction(function()
{

                    $a  =   new Type1();
                    
                    $a->prop  = 1;
                    
                    $a->save();
                    
                    
                    $b =   new Type2();
                    
                    $b->blob_item  = ........;
                    $b->prop2        = 2;

                    $b->save();
}

**Comment by yajra** [comment]
Ooops.. sorry @sasanet, overlooked this one. Will add this on my todo list this week and let you know what I may find. Thanks!

**Comment by sasanet** [comment]
ok, no problem.

**Comment by yajra** [comment]
@sasanet, I am reviewing this request and I think that it would took more changes for this to be implemented. Currently, saving of blob requires a transaction and wrapping it inside another transaction would definitely raise an exception. I would say that this is a limitation of the package atm when using a blob.

Anyways, lets keep this issue open until we find a better solution to this. Regards!

P.S. If you can find/have some solutions in mind, I would gladly accept a PR. Thanks!

**Comment by yajra** [comment]
@sasanet, sorry the delay on this. Issue should be fixed on v2.4.3. Kindly check and verify. Thanks!

**Comment by sasanet** [comment]
It's already so much what you did when you create laravel-oci. thank you very much.
