### ISSUE TITLE
 Method Yajra\Oci8\Schema\Grammars\OracleGrammar::compileColumns does not exist.

### ISSUE THREAD

**Issue by jirapetr** [yajra/laravel-oci8#831]
### Summary of problem or feature request

Whan I want generate filement
php artisan make:filament-resource Customer --generate

### Code snippet of problem

 php artisan make:filament-resource EnumPrivilege --generate

   BadMethodCallException 

  Method Yajra\Oci8\Schema\Grammars\OracleGrammar::compileColumns does not exist.

  at ..\vendor\laravel\framework\src\Illuminate\Macroable\Traits\Macroable.php:112
    108▕      */
    109▕     public function __call($method, $parameters)
    110▕     {
    111▕         if (! static::hasMacro($method)) {
  ➜ 112▕             throw new BadMethodCallException(sprintf(
    113▕                 'Method %s::%s does not exist.', static::class, $method
    114▕             ));
    115▕         }
    116▕

  1   ..vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php:364
      Illuminate\Database\Grammar::__call("compileColumns")

  2   ..\vendor\filament\forms\src\Commands\Concerns\CanGenerateForms.php:23
      Illuminate\Database\Schema\Builder::getColumns("enum_privileges")

### System details

WIN 10
PHP 8.2
- Laravel Version 10
- Laravel-OCI8 Version: 10

**Comment by yajra** [comment]
Bumped into this while upgrading to Laravel 11. A new feature added via https://github.com/laravel/framework/pull/48357. Tagged for enhancement, thanks!

**Comment by yajra** [comment]
fixed on v10.5.0 🚀 Thanks!
