### ISSUE TITLE
OCI_SUCCESS_WITH_INFO: ORA-28002: the password will expire within 13 days

### ISSUE THREAD

**Issue by nmalcolm** [yajra/laravel-oci8#839]
### Summary of problem or feature request

I get this exception which causes a 500 error on my web application. This shouldn't happen since it's only informational.

```
Yajra\Pdo\Oci8\Exceptions\Oci8Exception: oci_pconnect(): OCI_SUCCESS_WITH_INFO: ORA-28002: the password will expire within 13 days
```

### Code snippet of problem

-

### System details

- Laravel-OCI8 Version: 10.5.1

**Comment by yajra** [comment]
fixed via https://github.com/yajra/pdo-via-oci8/pull/138, please update and confirm. Thanks!
