### ISSUE TITLE
Plain PHP able to resolve via LDAP this library, not so much.

### ISSUE THREAD

**Issue by Zamerick** [yajra/laravel-oci8#84]
When creating a plain PHP OCI8 connection, if it fails to find the SID in the tnsname.ora file it is still able to resolve the SID via LDAP. Currently, this library does not do that(not by default anyway) and just fails. 

Is there a work around for this, or is it something that needs to be tweaked in the underlying classes?

**Comment by yajra** [comment]
hmm.. I am not familiar with PHP OCI8 with LDAP. Anyways, you can use your own connection string by setting tns manually. On database config, set `datatabase['tns'] = 'CONN_STRING'`

**Comment by Zamerick** [comment]
Just to make sure I'm follow you, this connection string would be the same arguments that I pass to a plain php oci8 connection?

**Comment by yajra** [comment]
Yes, the same connection string using plain php connection. Btw, can you paste your connection string if possible? Kinda curious how LDAP connection is. Thanks!

**Comment by Zamerick** [comment]
I don't do anything special, i just pass the username, password and the name of the database to the oci_connect() function like so:

$conn = oci_connect('username', 'password', 'dbname');

**Comment by Zamerick** [comment]
Digging through your OracleConnector class and it looks like you actually build your own tnsnames entry through the setTNS function. Whats the reasoning behind doing it that way rather than just taking the db name from the connection settings in laravel's database.php?

**Comment by Zamerick** [comment]
Ended up changing the OracleConnector class to return just the database name rather than the whole TNS string.

**Comment by yajra** [comment]
@Zamerick, I think tns/dsn was use because there are cases where we need multiple connections/hosts in a single DB instance. And I think it was more flexible to use that approach. If you just want to return the database then I think you can also use the config like below.

```php
'oracle' => [
	'driver'   => 'oracle',
	'tns'      => 'sid',
	'host'     => 'localhost',
	'username' => 'username',
	'password' => 'password',
],
```

**Comment by Zamerick** [comment]
adding a 'tns' index did work, though you still have to specify 'prefix' and 'database' indexes or it breaks. (Only mentioning it for anyone else that might run into this)
