### ISSUE TITLE
Laravel 11 support is on the road?

### ISSUE THREAD

**Issue by abrahampe** [yajra/laravel-oci8#840]
I am starting a new project and would like to use it, we will use last version of Laravel. 

Thanks for the nice project

**Comment by robertogallea** [comment]
Master branch is already compatible with L11

**Comment by jfccapali** [comment]
well I get that message
  Problem 1
    - Root composer.json requires yajra/laravel-oci8 11 (exact version match: 11, 11.0, 11.0.0 or 11.0.0.0), found yajra/laravel-oci8[dev-fix-ci-unique-index, dev-master, dev-analysis-0gN4Lm, dev-patch-ai, dev-phpstan, 0.1.0, ..., 0.3.0, 1.0.0, ..., 1.15.x-dev, v2.0.0.beta, ..., 2.4.x-dev, v3.0.0, ..., v3.1.3, v4.0.0-RC1, ..., v4.2.6, v5.1.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0, ..., 9.x-dev, v10.0.0, ..., 10.x-dev, 11.x-dev (alias of dev-master)] but it does not match the constraint

**Comment by abrahampe** [comment]
@jfccapali I believe you cannot set exact version (11) in composer.json, you need to put an asterisk (*) instead of the version. When the release happen you replace with exact version (^11.0)

**Comment by robertogallea** [comment]
You should require`dev-master` instead of ^11.0. It was not released yet.

**Comment by yajra** [comment]
v11.0.0 tagged 🚀, thanks!
