### ISSUE TITLE
[11.x] Error Code : 942 Error Message : ORA-00942, Sessions table

### ISSUE THREAD

**Issue by antunes18** [yajra/laravel-oci8#845]
### Summary of problem or feature request

After the installation and configs of laravel-oci8, getting an err when acessing index.php. I do not have a sessions table on my company oracle db pl/sql created, is it really necessary?

### Code snippet of problem
`Error Code : 942 Error Message : ORA-00942: table or view does not existis at Position : 29 Statement : select * from (select * from "SESSIONS" where "ID" = :p0) where rownum = 1 Bindings : [7KuBlHrqmPEhnd3wTfhTyF4TxLLC3cLOlqxvP73X]`

`select * from (select * from "SESSIONS" where "ID" = 7KuBlHrqmPEhnd3wTfhTyF4TxLLC3cLOlqxvP73X) where rownum = 1`

![image](https://github.com/yajra/laravel-oci8/assets/40566429/3a7788cc-ad56-4d92-b8bc-df49c062649b)

My `config/app.php`
```
    'providers' => [
        Yajra\Oci8\Oci8ServiceProvider::class,
    ],
```

My `config/oracle.php`

```
<?php

return [
    'oracle' => [
        'driver' => 'oracle',
        'tns' => env('DB_TNS', ''),
        'host' => env('DB_HOST', ''),
        'port' => env('DB_PORT', '1521'),
        'database' => env('DB_DATABASE', ''),
        'service_name' => env('DB_SERVICE_NAME', ''),
        'username' => env('DB_USERNAME', ''),
        'password' => env('DB_PASSWORD', ''),
        'charset' => env('DB_CHARSET', 'AL32UTF8'),
        'prefix' => env('DB_PREFIX', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
        'edition' => env('DB_EDITION', 'ora$base'),
        'server_version' => env('DB_SERVER_VERSION', '11g'),
        'load_balance' => env('DB_LOAD_BALANCE', 'yes'),
        'max_name_len' => env('ORA_MAX_NAME_LEN', 30),
        'dynamic' => [],
    ],
];
```

### System details
- Operating System = Windows NT M16 10.0 build 22621 (Windows 11) AMD64
- PHP Version =8.2.12
- Laravel Version = 11
- Laravel-OCI8 Version = 11.x

**Comment by yajra** [comment]
If the session driver is `database`, then yes. Check your ENV as I think Laravel defaults to DB for session and cache store which I'm also trying to fix via https://github.com/yajra/laravel-oci8/pull/844
