### ISSUE TITLE
ORA-01830

### ISSUE THREAD

**Issue by sciracioglu** [yajra/laravel-oci8#85]
Hi yajra

here is my model
```php
protected     $dates      = [
		'created_at',
		'updated_at',
		'tarih1',
		'tarih2'
	];
	protected     $dateFormat = "d/m/Y H:i:s";
```
when i insert then ORA-01830 error 

how can i fix this

**Comment by yajra** [comment]
@sciracioglu, by default, the driver will set session NLS_DATE_FORMAT to `YYYY-MM-DD HH24:MI:SS`. I think the issue was raised because you override the `dateFormat` on your model and thus not matching the session date format. Quick solution would be removing the dateFormat attribute.

```php
// set oracle session variables
            $sessionVars = [
                'NLS_TIME_FORMAT'         => 'HH24:MI:SS',
                'NLS_DATE_FORMAT'         => 'YYYY-MM-DD HH24:MI:SS',
                'NLS_TIMESTAMP_FORMAT'    => 'YYYY-MM-DD HH24:MI:SS',
                'NLS_TIMESTAMP_TZ_FORMAT' => 'YYYY-MM-DD HH24:MI:SS TZH:TZM',
                'NLS_NUMERIC_CHARACTERS'  => '.,',
            ];
```

**Comment by yajra** [comment]
You can optionally override the session date format by using `DB::setDateFormat('d/m/Y')` but I think this should be done before loading your models.

**Comment by yajra** [comment]
@sciracioglu matching the sessions date format with your input should fix this issue. Just play with the settings I provided above to match your need. Thanks!
