### ISSUE TITLE
Error LogicException This database driver does not support modifying columns

### ISSUE THREAD

**Issue by diovanemonteiro** [yajra/laravel-oci8#852]
### Summary of problem or feature request

The change method Modifying Columns in migration error  LogicException  This database driver does not support modifying columns

### Code snippet of problem

 Creating migration table ............................................................................................................ 52.73ms DONE

   INFO  Running migrations.  

  0001_01_01_000000_create_users_table ................................................................................................. 1.80ms DONE
  0001_01_01_000001_create_cache_table ................................................................................................. 2.14ms DONE
  0001_01_01_000002_create_jobs_table .................................................................................................. 1.64ms DONE
  2023_09_11_142343_create_generos_table .............................................................................................. 45.09ms DONE
  2023_09_11_145752_create_escolaridades_table ........................................................................................ 45.99ms DONE
  2023_09_11_162726_create_tipos_moradia_table ........................................................................................ 53.07ms DONE
  2023_09_11_163518_create_formas_remuneracao_table ................................................................................... 40.06ms DONE
  2023_09_11_165321_create_programas_sociais_table .................................................................................... 42.94ms DONE
  2023_09_11_170444_create_estados_civil_table ........................................................................................ 47.75ms DONE
  2023_09_11_171239_create_tipos_deficiencia_table .................................................................................... 44.83ms DONE
  2023_09_11_171833_create_faixas_salariais_table ..................................................................................... 57.83ms DONE
  2023_09_11_173745_create_unidades_federativas_table ................................................................................. 18.00ms DONE
  2023_09_11_190217_create_inscricoes_table ........................................................................................... 38.06ms DONE
  2023_09_12_125600_create_candidatos_table ........................................................................................... 61.21ms DONE
  2023_09_12_125622_create_candidatos_documentos_table ................................................................................ 54.16ms DONE
  2023_09_12_125746_create_candidatos_contatos_table .................................................................................. 59.36ms DONE
  2023_09_12_130200_create_componentes_familia_table .................................................................................. 60.06ms DONE
  2023_09_12_132011_create_candidatos_dados_adicionais_table ......................................................................... 144.26ms DONE
  2023_09_13_134036_create_candidatos_enderecos_table ................................................................................. 64.33ms DONE
  2023_09_17_145928_change_table_candidatos_outras_informacoes_modify_collumn_tempo_moradia_municipio ................................. 10.21ms FAIL

   LogicException 

  This database driver does not support modifying columns.

  at vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/Grammar.php:96
     92▕      * @throws \RuntimeException
     93▕      */
     94▕     public function compileChange(Blueprint $blueprint, Fluent $command, Connection $connection)
     95▕     {
  ➜  96▕         throw new LogicException('This database driver does not support modifying columns.');
     97▕     }
     98▕ 
     99▕     /**
    100▕      * Compile a fulltext index key command.

      +5 vendor frames 

  6   database/migrations/2023_09_17_145928_change_table_candidatos_outras_informacoes_modify_collumn_tempo_moradia_municipio.php:14
      Illuminate\Support\Facades\Facade::__callStatic()
      +38 vendor frames 

  45  artisan:13
      Illuminate\Foundation\Application::handleCommand()

### System details

- Linux Mint
- PHP 8.3.7
- Laravel 11.7.0
- Laravel-OCI8 11.2.3

**Comment by yajra** [comment]
Thanks for reporting, I think this was due to `dbal` being removed in Laravel 11. Will try to add support on this as soon as I can.
