### ISSUE TITLE
Oci_new_cursor() requires resource.

### ISSUE THREAD

**Issue by Zamerick** [yajra/laravel-oci8#86]
I'm trying to access a stored procedure that takes in a varchar and returns 2 refcursors. In plain PHP, this requires the use of oci_new_cursor() which takes a connection resource as a param. The example in the wiki, $pdo = DB::getPdo(), returns an object.

Is there a method of accessing the resource inside the object, or some other work around to enable the use of oci_new_cursor?

**Comment by yajra** [comment]
Try using bindParam with type PDO::PARAM_STMT.

See file `yajra\Pdo\Oci8\Statement.php` for details.

**Comment by Zamerick** [comment]
I should really get more coffee before submitting issues... this was exactly my problem. I wasn't paying attention and was trying to cast my cursor to an int. Thanks
