### ISSUE TITLE
Upgrading laravel/framework v11.15.0 fails migration containing table update (ORA-01430)

### ISSUE THREAD

**Issue by timoteo7** [yajra/laravel-oci8#864]
### Summary of problem or feature request
when I updated the 
`laravel/framework` `(v11.14.0 => v11.15.0)` 
a migration containing a table update (adding a string and date column for example),
the failure occurs:
`ORA-01430: column being added already exists in table`
(I'm not sure if this only happens with Oracle DB, I haven't tested it on other databases)

but downgrading solves the problem:
`php composer update laravel/framework:11.14.0`

### Code snippet of problem
```php
        Schema::table('users', function (Blueprint $table) {
            $table->string('string_test')->nullable();
            $table->date('date_test')->nullable();
        });
```

### System details

- Operating System : `Linux 6.5.0-41-generic`
- PHP Version : `PHP 8.3.8 (cli)`
- Laravel Version : `11.15.0`
- Laravel-OCI8 Version : `v11.3.0`

**Comment by hafezdivandari** [comment]
The overridden [`compileAdd`](https://github.com/yajra/laravel-oci8/blob/4aa04694a91a360184d2f8c3be83e0704d020052/src/Oci8/Schema/Grammars/OracleGrammar.php#L270) and [`compileChange`](https://github.com/yajra/laravel-oci8/blob/4aa04694a91a360184d2f8c3be83e0704d020052/src/Oci8/Schema/Grammars/OracleGrammar.php#L919) methods of the `\Yajra\Oci8\Schema\Grammars\OracleGrammar` should change, just like PR laravel/framework#51373.

You may check the changes on [`MySqlGrammar`](https://github.com/laravel/framework/pull/51373/files#diff-56c5c7428a9c212202ed1ff8087231537cb51af4e53de282d6c7b0675ba57e46R293-R296) as an example.

```php
public function compileAdd(Blueprint $blueprint, Fluent $command)
{
    if (laravel version >= 11.15) {
        // add single column
    } else {
        // previous code (add all columns at once)
    }
}
```
