### ISSUE TITLE
Problem with sequence with long table name

### ISSUE THREAD

**Issue by jocelimjr2000** [yajra/laravel-oci8#869]
### Summary of problem or feature request

I have two tables (CHKLST2_ACTION_PLANS_CUSTOM_FIELDS and CHKLST2_ACTION_PLANS_CUSTOM_FIELDS_OPTIONS). When creating the table CHKLST2_ACTION_PLANS_CUSTOM_FIELDS the sequence CHKLST2_ACTION_PLANS_CUSTOM_FI is created, however, when creating the table CHKLST2_ACTION_PLANS_CUSTOM_FIELDS_OPTIONS, it tries to create the sequence with the same name. How can I customize the sequence name?

### Code snippet of problem

```php
Schema::create('ACTION_PLANS_CUSTOM_FIELDS', function (Blueprint $table) {
            $table->id('ID');
            $table->unsignedBigInteger('ACTION_PLAN_ID');
            $table->unsignedBigInteger('FIELD_ID');
            $table->string('FIELD_NAME', 4000)->nullable();
            $table->unsignedBigInteger('FIELD_TYPE')->nullable();
            $table->string('FIELD_BOOL', 4000)->nullable();
            $table->string('FIELD_TEXT', 4000)->nullable();
            $table->date('FIELD_DATE')->nullable();
            $table->unsignedBigInteger('SYNC_ID')->nullable();
});

Schema::create('ACTION_PLANS_CUSTOM_FIELDS_OPTIONS', function (Blueprint $table) {
            $table->id('ID');
            $table->unsignedBigInteger('CUSTOM_FIELD_ID');
            $table->unsignedBigInteger('ACTION_PLAN_ID');
            $table->string('OPTION_NAME', 4000)->nullable();
            $table->unsignedBigInteger('SYNC_ID')->nullable();
});
```

### System details

- Operating System Docker
- PHP Version 8.2
- Laravel Version 11
- Laravel-OCI8 Version 11

**Comment by yajra** [comment]
By default, the package limits the DB object name to 30 chars. If you are using a latest version of oracle, you can increase it by setting this in your config:

```
'max_name_len'   => env('ORA_MAX_NAME_LEN', 30),
```
