### ISSUE TITLE
Configurable Index and Objects names

### ISSUE THREAD

**Issue by vyolla** [yajra/laravel-oci8#87]
Shoud be great if we could configure the name of the objects and idexes,
In my case, all primary keys must be like this "XPK_APP_USER" for table APP_USER

**Comment by yajra** [comment]
I think this is already built-in with Laravel. You can specify the index name too by passing the name as argument like `->index('my_index')`.

**Comment by yajra** [comment]
Object and indexes name are already configurable on Laravel's built-in function. You may have to dig in the API though because I think it's not well documented.
