### ISSUE TITLE
Solution for Integration with Oracle 

### ISSUE THREAD

**Issue by DaltonCastro** [yajra/laravel-oci8#88]
Hy,
I spent a few hours trying to find the best solution for connecting to Oracle.

After upgrading the "yajra/laravel-oci8: ~ 2.0" on the composer and set up your config / database.php file like this (don't forget to set your default connection at the beginning of file):

        'oracle' => array (
            'driver' => 'oracle'
            'host' => 'your-dns'
            'username' => 'username'
            'password' => 'password'
            'charset' => 'charset'
            'prefix' => '',
            'port' => '1521',
            'service_name' => 'service_name'
            'server' => 'pooled'
            'database' => 'name_of_schema'
        )

After performing this, go to the ConnectionFactory.php class and add these two classes:

use yajra \ oci8 \ Connectors \ OracleConnector;
use yajra \ oci8 \ Oci8Connection;

After this, we inserted a condition in the both switch structure, in the methods:

public function createConnector(array $config){
..
    case 'oracle':
            return new OracleConnector;
..
}

protected function createConnection($driver, PDO $connection, $database, $prefix = '', array $config = []){
...
    case 'oracle':
            return new Oci8Connection ($connection, $database, $prefix, $config);
....
}

Without these adjustments Laravel will not find Oracle driver to make the connection.

I hope it helps!
Cheers.

**Comment by yajra** [comment]
Thanks for the suggestions. However, I think the solution you're proposing is a bit of a hack because you are editing the core file of Laravel. When you update your version, then your code will break for sure.

On the other hand, just register the service provider `yajra\Oci8\Oci8ServiceProvider::class` and Laravel should be able to connect and find the oracle driver. Does the provider not working for you?

**Comment by DaltonCastro** [comment]
You're right, It will break my code indeed.

I did just like you said and put it inside the service provider and it really works!

Thanks for your reply!

**Comment by yajra** [comment]
You're welcome! ^_^
