### ISSUE TITLE
@gabrieloliverio, setting a custom sequence is not yet fully functional. ATM, I think you need to set the id manually by getting the next value of the sequence. See https://github.com/yajra/laravel-oci8/wiki/Oracle-Sequence.

### ISSUE THREAD

**Issue by Sudheert7** [yajra/laravel-oci8#883]
````    
See https://github.com/yajra/laravel-oci8/wiki/Oracle-Sequence.
````````````

Link is redirecting to git repository, please update link.          

_Originally posted by @yajra in https://github.com/yajra/laravel-oci8/issues/155#issuecomment-195651543_

**Comment by yajra** [comment]
See https://yajrabox.com/docs/laravel-oci8/11.0/sequence, thanks!
