### ISSUE TITLE
The after method doesn't work, the column is added at the end

### ISSUE THREAD

**Issue by jsamaniegog** [yajra/laravel-oci8#887]
### Summary of problem or feature request

The after method doesn't work, the column is added at the end.

### Code snippet of problem

```
  Schema::table('users', function (Blueprint $table) {
      $table->string('new_column')->after('email')->nullable();
  });
```
### System details

- Operating System: Linux
- PHP Version: 8.2.8
- Laravel Version: 10
- Laravel-OCI8 Version: 10.6.0

**Comment by ErDiabIo** [comment]
Hi @jsamaniegog 

You can't change the order of column in oracle, this becouse there is no "AFTER" Clause in the alter table add column.

More info here [https://stackoverflow.com/questions/8922638/alter-table-after-keyword-in-oracle/8922722#8922722](url)

**Comment by jsamaniegog** [comment]
Thank you @ErDiabIo i didn't know that.
