### ISSUE TITLE
[v11.6.1] Randomly Error: ORA-00907: missing right parenthesis

### ISSUE THREAD

**Issue by nathanaelytj** [yajra/laravel-oci8#891]
### Summary of problem or feature request

After upgrading to v11.6.1 the log suddenly reporting some strange issues:

Error Code    : 907
Error Message : ORA-00907: missing right parenthesis
Position      : 158
Statement     : select from (select "ORAFIN"."R_JOB"., row_number() over (order by "ID_JOB" asc) as rn from (select * from "ORAFIN"."R_JOB" order by "ID_JOB" asc) "ORAFIN"."R_JOB") "ORAFIN"."R_JOB" where rn between 1 and 1000
Bindings      : []

This doesn't happen in v11.6.0 so downgrading solved the issue for now.

### Code snippet of problem

This bug randomly happen to any Laravel Model.
Attached is sinppet of the trace:

`
{
    "class": "Illuminate\\Database\\QueryException",
    "message": "Error Code    : 907\nError Message : ORA-00907: missing right parenthesis\nPosition      : 158\nStatement     : select * from (select \"ORAFIN\".\"R_JOB\".*, row_number() over (order by \"ID_JOB\" asc) as rn from (select * from \"ORAFIN\".\"R_JOB\" order by \"ID_JOB\" asc) \"ORAFIN\".\"R_JOB\") \"ORAFIN\".\"R_JOB\" where rn between 1 and 1000\nBindings      : []\n (Connection: kettle, SQL: select * from (select \"ORAFIN\".\"R_JOB\".*, row_number() over (order by \"ID_JOB\" asc) as rn from (select * from \"ORAFIN\".\"R_JOB\" order by \"ID_JOB\" asc) \"ORAFIN\".\"R_JOB\") \"ORAFIN\".\"R_JOB\" where rn between 1 and 1000)",
    "code": 907,
    "file": "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825",
    "trace": [
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Connection.php:779",
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Connection.php:398",
        "/var/www/vhosts/localhost/vendor/yajra/laravel-oci8/src/Oci8/Query/OracleBuilder.php:159",
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3073",
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3661",
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3072",
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:759",
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:741",
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php:172",
        "/var/www/vhosts/localhost/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php:124",
`

### System details

- Operating System: Ubuntu 24.04 LTS
- PHP Version: 8.3
- Laravel Version: 11
- Laravel-OCI8 Version: 11.6.1

**Comment by yajra** [comment]
Fixed via https://github.com/yajra/laravel-oci8/releases/tag/v11.6.2, thanks for reporting.
