### ISSUE TITLE
Blob Update: Not updating correctly

### ISSUE THREAD

**Issue by wremon** [yajra/laravel-oci8#9]
Using the sample blob field update provided on the laravel-oci page I came up with this code:

<pre lang="php"><code>
DB::table( 'metas' )
    ->where( 'object_id' , '=', $postId )
    ->where( 'meta_name', '=', $name )
    ->updateLob(
        array( 'meta_name'      => $name, ),
        array( 'meta_value'     => $value )
    );
</code></pre>

But when this code executes it do this. example:
- Old Blob Value:
  "Laravel"
- And then update the field with this string:
  "PHP"
- New Blob Value:
  "PHPavel"

I think it only replace a substring of the blob field depending on the length of the new value.

Thanks,

**Comment by luiz-andrade** [comment]
Boa tarde. Em: meta_name é o nome do campo do banco ?
```
->updateLob(
    array('meta_name' => $name),
    array('meta_value'=> $value),
```
