### ISSUE TITLE
ORA-00936

### ISSUE THREAD

**Issue by JavoByte** [yajra/laravel-oci8#90]
When I try to use the `whereHas` function with my model, it works fine on MySQL, but with Oracle, *ORA-00936* shows up.

My code is:

```
$executives = User::where('role', 'executive');
if(...){
    $executives->whereHas('manager', function($q) use($management_id) {
        $q->where('management_id', $management_id);
    });
}
```

And this produces the following error:
```
[2015-10-05 10:31:14] production.ERROR: exception 'yajra\Pdo\Oci8\Exceptions\Oci8Exception' with message 'Error Code    : 936
Error Message : ORA-00936: missing expression
Position      : 126
Statement     : select count(*) as aggregate from users where users.deleted_at is null and role = :autoparam0 and (select count(*) from users as self_c36fc6119c4fd9ce0a696c5fd6ded1f0 where self_c36fc6119c4fd9ce0a696c5fd6ded1f0.id = users.manager_id and management_id = :autoparam1 and users.deleted_at is null) >= 1
Bindings      : [executive,3]
```

Is this an issue or am I missing something?

**Comment by yajra** [comment]
Can try executing the generated SQL manually on SQLDeveloper/tools you are using? The generated query seems fine except for `self_c36fc6119c4fd9ce0a696c5fd6ded1f0`. As far as I know, oracle only allows an object name up to 30 chars.

**Comment by ChaosPower** [comment]
[https://docs.oracle.com/database/121/SQLRF/sql_elements008.htm#SQLRF51130](SQLRF51130)

**Comment by yajra** [comment]
Limiting the object name to max of 30 chars should fix the issue. See suggested link above of @ChaosPower. Thanks!
