### ISSUE TITLE
Oracle reserved words

### ISSUE THREAD

**Issue by arzola** [yajra/laravel-oci8#93]
Hi i am tried to use your awesome adapter but i have a trouble

In my company we were using column names with oracle reserved words (namespace,group,item)and for example my migration script looks like this.

```php
Schema::create('system_parameters', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('namespace', 100);
            $table->string('group', 50);
            $table->string('item', 150);
            $table->text('value')->nullable();
            $table->index(['namespace', 'group', 'item'], 'item_index');
        });
```

Where can i wrap column names with quotes to avoid this issue on select statements and the table creation?

*I am tried a workaround like this. (works nice to create the database tables but fails when the laravel try to perform a select*

```php
 Schema::create('system_parameters', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('"NAMESPACE"', 100);
            $table->string('"GROUP"', 50);
            $table->string('"ITEM"', 150);
            $table->text('"VALUE"')->nullable();
            $table->index(['"NAMESPACE"', '"GROUP"', '"ITEM"'], 'item_index');
        });
```

**Comment by yajra** [comment]
@arzola unfortunately, I also uses the same work around like you did and the same trick goes on my queries where I specifically added `"` on reserved words. Don't have any idea yet how to fix it.

**Comment by yajra** [comment]
@arzola, I just pushed a development version to support columns with reserved words when building a query. Can you give [`4.*`](https://github.com/yajra/laravel-oci8/tree/4.0) a shot if you time to check? Will try to do the same thing for Schema builder. Thanks!

**Comment by yajra** [comment]
Schema grammar quoting of reserved words implemented too on `4.0` branch.

**Comment by arzola** [comment]
Sure let me test, thanks a lot

**Comment by yajra** [comment]
Great. Btw, if installation of 4.0 branch fails. Try adding this on your composer.json file:
```json
  "minimum-stability": "dev",
  "prefer-stable": true
```

And use `yajra\laravel-oci8: 4.*`. Thanks!

**Comment by yajra** [comment]
Forgot to mention, I changed namespace from `yajra` to `Yajra` on v4.x. Please see [4.0 branch](https://github.com/yajra/laravel-oci8/tree/4.0) for the changes on installation. Thanks!
