### ISSUE TITLE
ORA-01843: not valid month

### ISSUE THREAD

**Issue by jljunior3** [yajra/laravel-oci8#94]
Hi, 
I'm using ORM doctrine and SoftDelete feature.
But it is returned a date error in the updateas shown below.

How can I  set another date format ?

DriverException in AbstractOracleDriver.php line 76:
An exception occurred while executing 'UPDATE cadastros SET deletedAt = ? WHERE id = ?' with params ["2015-10-20 11:43:59", 3]:

ORA-01843: não é um mês válido
![capturar](https://cloud.githubusercontent.com/assets/13906859/10606285/a79a2af2-7710-11e5-84bb-86dac494c8f7.PNG)

**Comment by yajra** [comment]
hi @jljunior3,

Try using https://github.com/yajra/laravel-oci8/wiki/Date-Formatting. However, not sure if this works on ORM Doctrine. I haven't use it yet.

```php
DB::setDateFormat('MM/DD/YYYY');
```

**Comment by yajra** [comment]
Setting the date session format on Oracle to match your date input should fix the issue. Closing issue. Thanks!
