### ISSUE TITLE
How to use laravel-oci8 with illuminate.

### ISSUE THREAD

**Issue by AviRns** [yajra/laravel-oci8#97]
Hi,
i am very new to php framework.
recently started to work with Slim framework. learnt Slim with Illuminate Eloquont Database to connect to mysql.

need to connect to oracle for my new project.

Please help me.
Give me a sample of code that connect to oracle.

**Comment by AviRns** [comment]
my composer.json file is as below.

{
    "autoload": {
        "psr-4": {
            "Codecourse\\": "app\\Codecourse"
        }
    },
    "require": {
        "slim/slim": "~2.6",
        "slim/views": "0.1.*",
        "twig/twig": "~1.0",
        "phpmailer/phpmailer": "~5.2",
        "hassankhan/config": "0.8.*",
        "illuminate/database": "~5.0",
        "alexgarrett/violin": "2.*",
        "ircmaxell/random-lib": "~1.1",
        "yajra/laravel-oci8": "~2.0"
    }
}

**Comment by AviRns** [comment]
i am learning from a video series of alexgarrett.

**Comment by yajra** [comment]
@AviRns, I haven't personally tried to use the package outside Laravel but this wiki may help give you some hint. https://github.com/yajra/laravel-oci8/wiki/Stand-alone-Usage

**Comment by AviRns** [comment]
@yajra, 
Its Working!!!!

Thank you Yajra so much for your kind help.
its working like charm.
