### ISSUE TITLE
1.15.0 update to  2.4.3

### ISSUE THREAD

**Issue by Tugsbayar** [yajra/laravel-oci8#98]
After I  updated my project, following error occurred. 
Undefined property: yajra\Oci8\Query\OracleBuilder::$useWritePdo
How to solve this problem?
thank you,

**Comment by yajra** [comment]
@Tugsbayar, is it possible to provide a sample snippet to reproduce the error?

**Comment by Tugsbayar** [comment]
In my code:
$sObj = DB::table('table_dd')->where('id',$Id)->first(); // error occured here.
---
ErrorException (E_NOTICE)
HELP
Undefined property: yajra\Oci8\Query\OracleBuilder::$useWritePdo

return $this->connection->select($this->toSql(), $this->getBindings(), ! $this->useWritePdo);

**Comment by yajra** [comment]
I just tested your code and works well for me. Maybe you have some unique setup that I don't have?

```php
Route::get('test', function() {
    return (array) DB::table('users')->where('id',1)->first(); // error occured here.
});
```

**Comment by ChaosPower** [comment]
@Tugsbayar closing issues with one month no updates.
