### ISSUE TITLE
Not Getting Data from Related Model using Eloquent

### ISSUE THREAD

**Issue by AviRns** [yajra/laravel-oci8#99]
Hi,
I have model user and a related model pay_master one to one.

i have defined is as followes in User.php:

public function paymasters()
	{
		return $this->hasOne('Codecourse\User\UserPaymaster','pm_tkt_no');
	}

now i am querying the paymaster with:
echo $this->user->paymasters()->where('pm_tkt_no', $value)->count();

for valid pay_master pm_tkt_no also it is returning 0.
it should return 1 instead.

Please help.

Thank you.

**Comment by yajra** [comment]
@AviRns, I think your code is fine. Are you sure that there is a related data on `UserPaymaster` model? Maybe you should use something like debugbar and verify if the generated query is correct?

**Comment by AviRns** [comment]
@yajra 
Thanks for reply,
i found out that i wanted to validate the user in my paymaster model before i have populated the key in user table. Thats why is was not working.

Now i have included the `Paymaster` table in seperate model and now i can use it.

Thanks for all your help and oracle support for laravel.
